- src/main/frontend/commands.cljs
- src/main/frontend/components/block.cljs
- src/main/frontend/components/datetime.cljs
- src/main/frontend/components/editor.cljs
- src/main/frontend/components/sidebar.cljs
- src/main/frontend/handler.cljs
- src/main/frontend/handler/editor.cljs
- src/main/frontend/handler/file.cljs
- src/main/frontend/handler/repo.cljs
- src/main/frontend/state.cljs
- Code cleanup
- Append `?`/`!` suffix for state getters/setters
> Minor refactoring of state.cljs

- src/main/frontend/db.cljs
- src/main/frontend/fs.cljs
- src/main/frontend/handler/page.cljs
> fix: rename the file when renaming page

- src/main/frontend/commands.cljs
- src/main/frontend/components/editor.cljs
- src/main/frontend/format/block.cljs
- src/main/frontend/handler.cljs
- src/main/frontend/handler/editor.cljs
- src/main/frontend/handler/page.cljs
- src/main/frontend/state.cljs
- src/main/frontend/util.cljs
Add a `:org-mode/insert-file-links` option to configuration.
Resolved #672
> feat: support org mode file links

- resources/css/common.css
Fix for better global variables names and added support for the Firefox scrollbar.
> Fix: Scrollbar: Better global variable names and added support for Firefox

- src/main/frontend/components/diff.cljs
- src/main/frontend/core.cljs
- src/main/frontend/handler.cljs
- src/main/frontend/handler/git.cljs
- src/main/frontend/handler/repo.cljs
- src/main/frontend/helper.cljs
- src/main/frontend/state.cljs
Refresh token automatically when getting the token and the token expires.
PS: need the server to update at the same time.
> fix(token):  refresh token automatically

- resources/css/datepicker.css
This fix will add support for global variable for the dark theme.
You can squash merge, but don't delete the branch yet, the white theme needs more thought.
> Fix: Support global variables for calendar

- deps.edn
- shadow-cljs.edn
- src/main/frontend/core.cljs
- src/main/frontend/log.cljs
fixed: https://github.com/logseq/logseq/issues/679
> feat: add unified log lib

- src/main/frontend/extensions/code.cljs
> fix: slow loading when a page has a lot of code blocks

- src/main/frontend/handler/repo.cljs
> fix: avoid empty commits && simplify git push checks

- src/main/frontend/components/diff.cljs
- src/main/frontend/git.cljs
- src/main/frontend/handler/repo.cljs
It is the same as `git/get-diffs`.
> chore: remove git/get-local-diffs

- src/main/frontend/db.cljs
- src/main/frontend/fs.cljs
- src/main/frontend/handler/dnd.cljs
- src/main/frontend/handler/repo.cljs
- src/main/frontend/state.cljs
Related to #786 
It has not been completely finished, but I'm afraid further changes will conflict with the `feat/chrome-native-fs` branch, so it would be better to merge the partial refactor.
> Refactor handler/repo.cljs

- src/main/frontend/components/journal.cljs
This should fix #408, but is untested because I don't know how to build the publishing zip file.
> Do not show intro on published sites

- src/main/frontend/components/diff.cljs
> fix: try to fix entire file content deleted after unusual sync behavior

- src/main/frontend/components/repo.cljs
- src/main/frontend/config.cljs
- src/main/frontend/handler/repo.cljs
This should partially fix the "large number of empty commits" problem.
> fix: only periodically push/pull the current repo

- resources/css/common.css
- src/main/frontend/components/block.cljs
- src/main/frontend/components/right_sidebar.cljs
- src/main/frontend/tools/html_export.cljs
> fix: slide style

- src/main/frontend/components/block.cljs
- src/main/frontend/db.cljs
- src/main/frontend/extensions/sci.cljs
Also, display the result if custom query failed
> fix: show custom view error

- src/main/frontend/fs.cljs
- src/main/frontend/handler/file.cljs
> fix: native fs writing concurrency

- src/main/frontend/components/editor.cljs
- src/main/frontend/state.cljs
related #840
Fixes #840 
Fixes #864
> try to fix scroll position when switch editing mode

- src/main/frontend/components/editor.cljs
- src/main/frontend/db.cljs
- src/main/frontend/handler.cljs
- src/main/frontend/handler/editor.cljs
- src/main/frontend/handler/web/nfs.cljs
- src/main/frontend/state.cljs
> fix(editor): cursor jump to the start when idle

- src/main/frontend/components/repo.cljs
- src/main/frontend/config.cljs
- src/main/frontend/fs.cljs
- src/main/frontend/handler.cljs
- src/main/frontend/handler/draw.cljs
- src/main/frontend/handler/editor.cljs
- src/main/frontend/handler/file.cljs
- src/main/frontend/handler/page.cljs
- src/main/frontend/handler/repo.cljs
- src/main/frontend/handler/web/nfs.cljs
- src/main/frontend/idb.cljs
- src/main/frontend/state.cljs
Idb file handles should be cleared when unlinking a local directory.
> fix(native-fs): today journal not created automaticaly

- src/main/frontend/components/editor.cljs
> chore: don't handle key down if ctrl/meta pressed

- src/main/frontend/components/editor.cljs
- src/main/frontend/handler/editor/keyboards.cljs
> fix(editor): ESC doesn't work after auto-save

- src/main/frontend/handler/git.cljs
- src/main/frontend/handler/repo.cljs
This might fix https://github.com/logseq/logseq/issues/919.
> fix: git add today's journal even if it exists

- src/main/frontend/fs.cljs
- src/main/frontend/handler/page.cljs
> fix(editor): rename page will promotes file has been modified

- Dockerfile
- README.md
Takes care of the prerequisites
> Add docker based development environment

- resources/css/common.css
- src/main/frontend/components/block.cljs
- src/main/frontend/components/block.css
- src/main/frontend/handler/editor.cljs
Resolved #975.
Also, I made some css tweaks and `alt+left` can be working as `back` when not in a block page.
> fix: clicking on some links not working anymore

- src/main/frontend/handler/editor.cljs
> fix(editor): use markdown images and links

- deps.edn
- src/main/frontend/components/settings.cljs
- src/main/frontend/handler/config.cljs
- src/main/frontend/handler/repo.cljs
> fix: preserve config.file order when updating

- src/main/frontend/components/block.cljs
- src/main/frontend/db.cljs
- src/main/frontend/db/model.cljs
Discussion thread: https://discuss.logseq.com/t/improve-implementation-of-aliases/81/4
> feat: add alias redirects

- src/main/frontend/db.cljs
- src/main/frontend/handler.cljs
- src/main/frontend/handler/repo.cljs
- src/main/frontend/handler/user.cljs
Persist in-memory db and file-db to IndexedDB in one transaction.
> fix: make db persistence atomic

- src/main/frontend/components/search.cljs
- src/main/frontend/search.cljs
Resolves https://github.com/logseq/logseq/issues/937.
> Fix text highlight for fuzzy search

- src/main/frontend/components/block.cljs
- src/main/frontend/components/reference.cljs
- src/main/frontend/components/svg.cljs
- src/main/frontend/filtering.cljs
- src/main/frontend/handler/block.cljs
- src/main/frontend/handler/page.cljs
- src/main/frontend/util.cljs
Clicking a reference will include it and Shift+Click will exclude it. Click it again and it'll be removed from the filter.
Preview:
> feat: Filter

- src/main/frontend/format/mldoc.cljs
- src/main/frontend/handler/editor.cljs
- src/main/frontend/text.cljs
- src/test/frontend/text_test.cljs
> fix(editor): unstable properties when updating or creating a block

- src/main/frontend/components/content.cljs
- src/main/frontend/handler/editor.cljs
- src/main/frontend/text.cljs
- src/test/frontend/text_test.cljs
> fix(editor): put content after properties for any block without title

- src/main/frontend/components/editor.cljs
- src/main/frontend/components/widgets.cljs
- src/main/frontend/handler/editor.cljs
> feat(editor): support paste an image in block

- src/main/frontend/components/widgets.cljs
> fix:  Notification text is unreadable

- src/main/frontend/handler/editor.cljs
> fix(editor): pressing enter right after the first bullet of a page will append ##

- src/main/frontend/handler/editor.cljs
> fix(editor): Scheduled command not working when creating a new block

- src/main/frontend/components/block.cljs
- src/main/frontend/components/block.css
- src/main/frontend/dicts.cljs
> fix: case of untitled block ref #1094

- package.json
- src/main/frontend/components/block.cljs
- yarn.lock
> enhance: add image metadata support

- src/main/frontend/extensions/code.cljs
> Update to code.cljs

- src/main/frontend/components/header.cljs
- src/main/frontend/publishing.cljs
- src/main/frontend/publishing/html.cljs
- src/main/frontend/security.cljs
- src/main/frontend/util.cljs
> fix: Database isn't escaped when dumped in the published HTML file

- src/main/frontend/components/block.cljs
- src/main/frontend/components/page.cljs
- src/main/frontend/components/right_sidebar.cljs
> fix: block parents not rendered correctly

- resources/css/common.css
- src/main/frontend/components/page.cljs
- src/main/frontend/components/page.css
- src/main/frontend/db/utils.cljs
- src/main/frontend/fs/watcher_handler.cljs
> fix(editor): page blocks duplicated when multiple same page name files

- docs/Build LogSeq Desktop for windows on Ubuntu.md
Adding the How to Build LogSeq Destkop app for windows on a Ubuntu Machine
> Create Build LogSeq Desktop for windows on Ubuntu.md

- src/main/frontend/components/editor.cljs
- src/main/frontend/components/journal.cljs
- src/main/frontend/components/page.cljs
- src/main/frontend/components/sidebar.cljs
- src/main/frontend/handler/editor.cljs
- src/main/frontend/handler/route.cljs
- src/main/frontend/keyboards.cljs
- src/main/frontend/mixins.cljs
- src/main/frontend/state.cljs
> Custom shortcuts

- src/electron/electron/core.cljs
> Fix desktop shortcuts on Win32

- src/main/frontend/components/sidebar.cljs
- src/main/frontend/components/theme.cljs
- src/main/frontend/handler/route.cljs
> fix(ui): Page title show null 

- src/main/frontend/handler/file.cljs
- src/main/frontend/handler/page.cljs
> fix(desktop): Desktop client cannot delete files #1346

- src/electron/electron/handler.cljs
- src/main/frontend/fs.cljs
- src/main/frontend/fs/nfs.cljs
- src/main/frontend/fs/node.cljs
- src/main/frontend/fs/watcher_handler.cljs
- src/main/frontend/handler/file.cljs
> fix: don't overwrite disk file

- .github/workflows/build-desktop-release.yml
- resources/forge.config.js
- resources/package.json
Add AppImage format for Linux desktop build.
> chore(electron): add appimage format for linux

- src/main/frontend/commands.cljs
- src/main/frontend/components/block.cljs
- src/main/frontend/components/block.css
CSS Credits to @Piotr#6529 
<Pinned to activate
> Adding Pinned Notes command and CSS

- src/main/frontend/handler/page.cljs
page search and insert is broken in raw edit mode as in #1474, this pr shall fix this issue
> fix: get-page-ref-text shall return in file edit mode

- src/main/frontend/components/export.cljs
- src/main/frontend/components/page.cljs
- src/main/frontend/db/model.cljs
- src/main/frontend/handler/export.cljs
> feat: support exporting single page to markdown

- src/main/frontend/commands.cljs
- src/main/frontend/components/block.cljs
- src/main/frontend/state.cljs
Needs to enable inline html support first.
https://github.com/logseq/mldoc/issues/34
> feat: markdown underline command

- src/main/frontend/handler/editor.cljs
> fix(org): asset link of org mode #1449

- src/main/frontend/handler/export.cljs
if the count of exporting files >= 30
then pre-compute the whole graph's page&block refs
else collect refs by querying DB for per page
> enhance(export): pre-compute whole graph's page&block refs

- src/main/frontend/dicts.cljs
Found some more small things -- 3 character fix.
> Fix small typos

- src/main/frontend/handler/editor.cljs
- src/main/frontend/util.cljc
- fix up down cross-boundary cursor position bug
- dealing with in selection arrow key press action
> fix: some arrow key handling issues

- src/main/frontend/components/header.cljs
- src/main/frontend/components/header.css
- src/main/frontend/components/journal.cljs
- src/main/frontend/components/right_sidebar.cljs
- src/main/frontend/components/sidebar.cljs
- src/main/frontend/components/sidebar.css
- src/main/frontend/ui.cljs
> feat: new layout for sidebar

- resources/css/common.css
- src/main/frontend/components/header.css
- src/main/frontend/components/journal.cljs
- src/main/frontend/components/page.cljs
- src/main/frontend/components/right_sidebar.cljs
- src/main/frontend/components/sidebar.cljs
- src/main/frontend/components/sidebar.css
- src/main/frontend/components/theme.css
- src/main/frontend/format/block.cljs
- src/main/frontend/handler/graph.cljs
- src/main/frontend/state.cljs
- src/main/frontend/util.cljc
also, a sticky right topbar
https://www.loom.com/share/13fc04dead084c15bba3d74a7f7d839a
> enhance: scrollbar no longer limits to the main content

- src/main/frontend/handler/events.cljs
- src/main/frontend/ui.cljs
encrypt dialog `cancel` action not work.
> fix(ui): dialog can't close

- libs/package.json
- libs/src/LSPlugin.d.ts
- libs/src/LSPlugin.user.ts
- libs/yarn.lock
@xyhp915 Please help review.
- use `csstypes` to enhance style-related api
> enhance: types for lsp

- CODEBASE_OVERVIEW.MD
- README.md
Some areas that I don't fully understand may need careful review:
- encryption
- how LogSeq use DataScript
- application state
> Add a codebase overview page

- src/main/frontend/components/export.cljs
- src/main/frontend/dicts.cljs
- src/main/frontend/format/adoc.cljs
- src/main/frontend/format/mldoc.cljs
- src/main/frontend/format/protocol.cljs
- src/main/frontend/handler/export.cljs
related to https://github.com/logseq/mldoc/pull/60
> feat: export page as opml

- src/main/frontend/components/block.css
> fix: incorrect marker indent of order list item

- src/main/frontend/components/editor.cljs
- src/main/frontend/components/search.cljs
- src/main/frontend/handler/ui.cljs
- src/main/frontend/ui.css
this shall fix the autocomplete scroll issue on keypress
> fix: autocompelete arrow key scroll issue

- src/main/frontend/handler/events.cljs
- src/main/frontend/ui.cljs
this shall fix the enter key not working for "Grant".
> feat: add a default enter action for modal

- src/main/frontend/format/adoc.cljs
- src/main/frontend/format/mldoc.cljs
- src/main/frontend/format/protocol.cljs
- src/main/frontend/handler/export.cljs
see also https://github.com/logseq/mldoc/pull/62
> feat(export): replace embed & block-refs in opml

- src/main/frontend/components/block.cljs
- src/main/frontend/components/sidebar.cljs
- src/main/frontend/components/sidebar.css
- src/main/frontend/components/svg.cljs
- src/main/frontend/components/widgets.cljs
- fix: remove Brave browser from browser suggestion page
- fixed: a react unique key error
- fix: do not need to wrap a scroll container with another scroll container
> some minor issues

- src/main/frontend/components/block.cljs
users may want to hide pdf preview using custom css
> feat: add a pdf-preview class name

- src/main/frontend/components/external.cljs
- src/main/frontend/format/block.cljs
- src/main/frontend/format/mldoc.cljs
- src/main/frontend/handler/editor.cljs
- src/main/frontend/handler/external.cljs
see also: https://github.com/logseq/mldoc/pull/65
> feat(opml): support opml import

- src/main/frontend/handler/editor.cljs
- src/main/frontend/modules/shortcut/config.cljs
- src/main/frontend/modules/shortcut/dict.cljs
on top of #2186, add toggle open `t o` for collapse all and expand all shortcut.
> feat: add toggle open

- src/main/frontend/modules/outliner/core.cljs
> fix: another left-id conflict case

- src/main/frontend/components/block.cljs
- src/main/frontend/components/block.css
issue ref: https://twitter.com/CatoMinor3/status/1404860903825285121
> fix(editor): weird behavior when toggling edit mode for long text.

- src/main/frontend/components/block.cljs
- src/main/frontend/handler/editor.cljs
- src/main/frontend/modules/shortcut/config.cljs
- src/main/frontend/modules/shortcut/core.cljs
- src/main/frontend/modules/shortcut/data_helper.cljs
- src/main/logseq/api.cljs
corresponding to discord request:
> feat: add a shortcut for escape editing

- src/main/frontend/commands.cljs
- src/main/frontend/components/block.cljs
- src/main/frontend/format/block.cljs
- src/main/frontend/format/mldoc.cljs
- src/main/frontend/handler/editor.cljs
- src/main/frontend/modules/file/core.cljs
- src/main/frontend/modules/outliner/core.cljs
see also: https://github.com/logseq/mldoc/pull/66
> feat: support `- ##` like heading

- src/main/frontend/components/block.cljs
> feat: preview block reference with its children

- src/main/frontend/handler/editor.cljs
> fix: copy a heading and sub bullets (replaces tabs and dashes by #)

- src/main/frontend/db/model.cljs
> enhance: unlinked ref search page alias as well

- src/main/frontend/components/onboarding.cljs
- src/main/frontend/components/shortcut.cljs
- src/main/frontend/modules/shortcut/config.cljs
- src/main/frontend/modules/shortcut/core.cljs
- src/main/frontend/modules/shortcut/data_helper.cljs
- templates/config.edn
> feat: customize shortcut ux

- src/main/frontend/handler/export.cljs
related to https://github.com/logseq/mldoc/pull/68
> fix: update exported md format

- src/main/frontend/components/settings.cljs
Previously, when you opened up the Settings modal (hotkeys: `t` + `s`), you got this error:
This PR replaces `:selected` in the various inputs with the recommended `:default-value`. 
This refactor should not change any behavior whatsoever.
> Fix React warning by updating :selected -> :value <select/> syntax

- src/main/frontend/extensions/code.cljs
fix for https://github.com/logseq/logseq/issues/2321
> fix: error when editing config.edn

- src/main/frontend/handler/editor.cljs
> enhance: collape take account of block body

- src/main/frontend/db.cljs
- src/main/frontend/db_schema.cljs
- src/main/frontend/handler/events.cljs
- :ast-version < db-schema/ast-version
- :ast-version is nil
> enhance: add notification for ast-version

- src/main/frontend/components/onboarding.cljs
Not working when using app/local instance
> fix: Links to privacy-policy/terms not working

- src/main/frontend/components/block.cljs
related pr: https://github.com/logseq/mldoc/pull/76
> fix: open file externally with relative paths

- src/main/frontend/modules/shortcut/config.cljs
Common wording and minor changes
> Minor updates to keyboard shortcut wording

- src/main/frontend/ui.cljs
> fix: clear data-active-keystroke when blur

- src/main/frontend/components/export.cljs
- src/main/frontend/format.cljs
- src/main/frontend/format/adoc.cljs
- src/main/frontend/format/mldoc.cljs
- src/main/frontend/format/protocol.cljs
- src/main/frontend/handler/export.cljs
source:
result html(open export.html in chrome):
GIF:
see also : https://github.com/logseq/mldoc/pull/80
> feat: block-level html export

- package.json
- src/main/frontend/components/block.cljs
- src/main/frontend/util.cljc
- yarn.lock
see also https://github.com/logseq/mldoc/pull/81
> fix: orgmode id-link

- src/main/frontend/components/export.cljs
- src/main/frontend/format/mldoc.cljs
- src/main/frontend/handler/editor.cljs
- src/main/frontend/handler/export.cljs
- src/main/frontend/util.cljc
- remove [[]]
- remove emphasis
see also https://github.com/logseq/mldoc/pull/83
> feat: support remove options when export

- src/main/frontend/components/content.cljs
- src/main/frontend/handler/editor.cljs
1. rename block-level "Export" to "Copy as"
2. blocks selection copy use options in "Copy as"
> feat: blocks copy with options

- package.json
- src/main/frontend/commands.cljs
- src/main/frontend/components/block.cljs
- src/main/frontend/ui.cljs
- yarn.lock
Add `/Embed Twitter` command
Fix https://discuss.logseq.com/t/the-ability-to-embed-tweets/1121
See demo:
<video src="https://user-images.githubusercontent.com/584378/127636427-46e5ccb7-5dd6-4a42-8052-ebb3387337d3.mp4"></video>
> feat: add embed twitter command

- src/main/frontend/components/block.cljs
- src/main/frontend/components/page.cljs
- src/main/frontend/date.cljs
- src/main/frontend/extensions/pdf/assets.cljs
- src/main/frontend/extensions/pdf/pdf.css
- src/main/frontend/handler/page.cljs
For example, `![Book Title](file:///Users/tiensonqin/Desktop/1.pdf)`
should be opened by the pdf viewer and allows highlights.
> feat: support PDFs outside assets

- src/main/frontend/handler/page.cljs
> fix: rename page case only

- src/main/frontend/commands.cljs
- src/main/frontend/components/block.cljs
address issue https://github.com/logseq/logseq/issues/2547
> fix: <Center command

- src/main/frontend/components/settings.css
- src/main/frontend/ui.css
Indicate when buttons or dropdowns are hovered over
PS aria-checked always seems to be "false" for toggles
> feat: Button & toggle interactivity on hover

- src/main/frontend/extensions/pdf/assets.cljs
reported from https://discord.com/channels/725182569297215569/802530020605820949/876610210058342410
> improve(pdf): make local asset file as relative path for hls page related properties

- src/main/frontend/extensions/zotero.cljs
- src/main/frontend/extensions/zotero/setting.cljs
Add Zotero setting profiles. Multiple profile settings would allow users 
1. to config different base directories for different devices
2. or using different user/group profile settings
> feat: zotero setting profile

- src/main/frontend/components/block.cljs
- src/main/frontend/date.cljs
- src/main/frontend/handler/editor.cljs
- src/main/frontend/util/clock.cljs
- src/main/frontend/util/drawer.cljs
I still couldn't figure out how to split the pull requests. The first three commits is for drawer improvement, and the last one is for clock system. If you have any questions, feel free to write me. 
Clock demo:
> More compatible with Orgmode

- src/main/frontend/extensions/calc.cljc
- src/main/grammar/calc.bnf
- src/test/frontend/extensions/calc_test.cljc
Allows the calculator to do understand percentages like
```
500 * 50%
```
> feat(calc): Understand percentages

- src/main/frontend/handler/editor.cljs
- src/main/frontend/util/drawer.cljs
- src/main/frontend/util/property.cljs
> fix duplicated clock-in log / Remove empty properties drawer

- src/main/frontend/components/block.cljs
- src/main/frontend/components/block.css
- src/main/frontend/handler/editor.cljs
- src/main/frontend/handler/extract.cljs
- src/main/frontend/handler/page.cljs
- src/main/frontend/text.cljs
> Fix(org): org-styled link embedded-page rendering

- src/main/frontend/components/editor.cljs
- src/main/frontend/components/search.cljs
Some modals (for example "Search for page") were really small, so I adjusted the style to be more similar to the other modals.
Take a look:
https://user-images.githubusercontent.com/23294184/133821507-0bf95825-e60f-4924-a3b7-28c6eaf6fd93.mp4
> Animated editor modals and improved style consistency

- resources/css/common.css
- src/main/frontend/extensions/srs.cljs
- src/main/frontend/handler.cljs
- src/main/frontend/ui.cljs
Before:
After:
Note — a few of the changes are the result of my auto-formatter. I've separated these out into a commit so it's easier to read the real changes.
> Button styles for spaced repetition cards

- src/electron/electron/core.cljs
This PR fix the issue that in some locations (in my case, Taiwan), some YouTube videos cannot be played without setting a `referer` on the HTTP requests. I would like to open this PR since it may also happen in other places of the world!
Details of my debugging journey can be found [here on Discord](https://discord.com/channels/725182569297215569/735747000649252894/888446597531320382).
To test it, you can use [video 1](https://www.youtube.com/watch?v=XCs7FacjHQY) or [video 2](https://www.youtube.com/watch?v=aJOTlE1K90k).
About the solution, I use Electron's [`webRequest.onBeforeSendHeaders()`](https://www.electronjs.org/docs/api/web-request#webrequestonbeforesendheadersfilter-listener) API to intercept requests and modify the headers. Also this is my first time writing ClojureScript, so …
> fix(electron): Some YouTube videos cannot be played without referer

- src/main/frontend/exif.js
- src/main/frontend/selection.js
- src/main/frontend/utils.js
I notice these js files use lots of 'var' to define variables. It's not a good way. So, I use const/let to replace them.  Please take a look.
> use let/const to replace var

- src/main/frontend/components/editor.cljs
- src/main/frontend/components/svg.cljs
- src/main/frontend/ui.css
> fix(ui): correct position of slash command tip docs

- src/main/frontend/extensions/pdf/pdf.css
- src/main/frontend/util.cljc
- src/main/frontend/utils.js
Mentioned here:
https://discord.com/channels/725182569297215569/735747000649252894/894089877136736257
> fix(pdf): support the raw path under win32 that included backslash

- src/main/frontend/extensions/pdf/assets.cljs
> fix(pdf): support sub assets for pdf files #3024

- src/main/frontend/components/block.cljs
reported: https://discord.com/channels/725182569297215569/735747000649252894/904483818327662602
> fix(ui): preview image broken within right sidebar occasionally.

- src/main/frontend/ui.cljs
- src/main/frontend/ui.css
> fix: notification wrapper blocks user from interacting with the main area

- src/main/frontend/components/page.cljs
- src/main/frontend/components/page.css
- src/main/frontend/components/sidebar.css
- src/main/frontend/components/svg.css
> improve(ux): more interacted area for insert-block-plus button

- resources/css/common.css
- src/main/frontend/components/page.cljs
- src/main/frontend/components/sidebar.cljs
- src/main/frontend/components/sidebar.css
- adds emoji identifiers according to page properties
- add hover styles for nav-content-item
- move `+ New page` to bottom of sidebar
> Emoji page identifiers + sidebar tweaks

- src/main/frontend/handler/page.cljs
> fix rename-page produces extra wrong pages

- src/main/frontend/components/block.cljs
- src/main/frontend/handler/page.cljs
- src/main/frontend/handler/recent.cljs
> fix: update recent-pages when renaming pages

- src/main/frontend/util.cljc
> fix: complete page-reference clear block content

- src/main/frontend/components/plugins.cljs
- src/main/frontend/handler/page.cljs
> enhance(editor): load slash commands items dynamically.

- src/main/frontend/components/page.cljs
> fix: illegal regex

- src/main/frontend/components/right_sidebar.cljs
- src/main/frontend/components/right_sidebar.css
mentioned: 
https://discord.com/channels/806040386614853642/840125562970439690/908401568703971328
> fix(ui): height of right sidebar items container

- src/main/frontend/components/sidebar.cljs
- when user has `default home` set, show **Home** in left sidebar instead of **Journals**
- extract function for rendering a sidebar item
> add home to sidebar

- src/main/frontend/components/block.cljs
- src/main/frontend/components/search.cljs
- yarn.lock
per discussion in https://github.com/logseq/logseq/pull/3061?notification_referrer_id=NT_kwDOAAjqurEyNjM5Njc2NjA3OjU4NDM3OA#pullrequestreview-803444031, we add back `:haschild`, but also add `data-block-ref` and `data-page-ref` to search items
> feat: add some attributes for plugin authors

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
- pull_request_template.md
- mv `pull_request_template.md` to `.github`
- minnor grammar fix
> chore: relocate PR template, with grammar correction

- src/main/frontend/components/plugins.cljs
- src/main/frontend/components/plugins.css
> enhance(marketplace): add category filter for plugins

- src/electron/electron/git.cljs
> fix(git): auto commit not work on win32

- src/main/frontend/components/block.cljs
related to https://github.com/logseq/mldoc/pull/110
> add embed-data link-type

- e2e-tests/basic.spec.ts
- e2e-tests/utils.ts
- Minor refactor, add utility functions
- add test cases for autocompletion and autopair
> test(e2e): add test cases for auto-completion

- src/main/frontend/components/block.cljs
> fix: avoid cyclical refs and deep refs

- src/main/frontend/components/header.cljs
- src/main/frontend/components/header.css
- src/main/frontend/dicts.cljs
> enhance: style alert for "a new version has been downloaded"

- src/main/frontend/components/block.cljs
- src/main/frontend/handler/editor.cljs
- src/main/frontend/handler/route.cljs
> redirect-to-page!: Add target-page to 'Recent' list

- src/main/frontend/components/settings.cljs
> fix: invalid setting toggle handler fn

- src/main/frontend/components/repo.cljs
- src/main/frontend/dicts.cljs
- src/main/frontend/handler.cljs
- src/main/frontend/ui.cljs
> Cleanup repo dropdown

- src/main/frontend/handler/page.cljs
- src/main/frontend/modules/shortcut/config.cljs
https://user-images.githubusercontent.com/6979755/144958862-9916e7dd-59dd-4fd9-b393-6cfefb249c1f.mov
> feat: add "add to favorites" to command palette

- src/main/frontend/handler/editor.cljs
> feat: keep indent after copy block refs

- src/main/frontend/handler/editor.cljs
I just found out that the https://github.com/logseq/logseq/pull/3372 does not handle complex nesting cases well, but the previous PR has been Merged, so I open this new one.
> fix: fixed copy block refs in complex nesting cases

- src/main/frontend/components/sidebar.css
> fix(ui): overlay editor of left sidebar when narrow screen

- src/main/frontend/components/header.css
- src/main/frontend/components/sidebar.css
> fix(ui): top padding of left sidebar for ios mobile

- src/main/frontend/components/block.cljs
fix https://github.com/logseq/logseq/issues/3383
> fix(drawer): display user-defined drawer

- src/main/frontend/components/theme.css
- src/main/frontend/handler/plugin.cljs
> fix(ui): preboot logo color on dark mode

- src/main/frontend/ui.css
> fix(ui): position of modal for narrow screen #3447

- src/main/frontend/handler/editor.cljs
Mentioned here:
https://discord.com/channels/806040386614853642/841675547523678218/920168233573707807
> fix(api): insert as first child when current node is first child

- externs.js
- package.json
- src/main/frontend/components/page.cljs
- src/main/frontend/components/sidebar.cljs
- src/main/frontend/extensions/graph.cljs
- src/main/frontend/extensions/graph.css
- src/main/frontend/extensions/graph/pixi.cljs
https://www.loom.com/share/7567e69efa8440cf986c871463586ed3
> Graph view enhancements

- .github/workflows/build-desktop-release.yml
- Typo
- Keep the title the same as the beta release channel
> fix(ci): typo in title, add missing checksum

- src/main/frontend/components/sidebar.css
> fix(mobile): height of left sidebar from native ios platform

- src/main/frontend/fs.cljs
Mentioned: 
https://discord.com/channels/806040386614853642/806040658082791424/920530395299196968
> fix: encrypt content by special file types when write file

- src/main/frontend/extensions/pdf/pdf.css
- src/main/frontend/ui.css
> Enhance/polish UI for narrow screen

- src/main/frontend/components/block.cljs
> fix(editor): logbook should not be editable

- cypress.json
- resources/package.json
> Add missing license field to package.json

- src/main/frontend/components/header.css
- src/main/frontend/components/sidebar.cljs
- src/main/frontend/state.cljs
> enhance(ui): make consistent ux for headbar of native ios on wide screen device (iPad)

- src/main/frontend/mobile/camera.cljs
Add spaces around the photo link
> enhance(mobile): take care of spaces around photo link

- package.json
> fix(build): wrong excalidraw version

- src/main/frontend/handler/mobile/swipe.cljs
Now swipe supports to open/close right sidebar on large tablet.
> enhance(mobile): enable swipe to open/close right sidebar on large screen

- android/app/build.gradle
- resources/package.json
- scripts/bump-version.sh
- src/main/frontend/version.cljs
- Add a script to bump version
- ~~for now, Android version is not touched~~
- bump version 0.5.5, preparing for release
**EDIT:**
Add android app version bump
> bump version 0.5.5, add bump-version script

- public/index.html
Switching apps or rotating screen will cause the layout zooming-in/out on iOS, this PR sets the scale to 1 to fix it.
> enhance(ios): don't allow zoom-in/out

- src/electron/electron/window.cljs
> fix(desktop): ctrl+click on a journal page-title will open a browser tab 

- src/main/frontend/components/sidebar.css
> improve(ui): transition left sidebar when toggling #2947

- src/main/frontend/config.cljs
- src/main/frontend/fs/capacitor_fs.cljs
> fix(ios): toggling settings persists

- src/main/frontend/config.cljs
> revert part of last merge

- .github/workflows/build-docker.yml
- .github/workflows/build.yml
- Dockerfile
- README.md
- Remove Docker-based development environment
- Add build workflow for docker web app image
- Remove Clojure version check in CI
Close #3601
> build(docker): add docker build

- src/main/frontend/handler/mobile/swipe.cljs
> enhance(mobile): clear edit when opening left sidebar on narrow screens

- docs/Docker Web App Guide.md
> docs: add guide for docker webapp

- src/main/frontend/config.cljs
- src/main/frontend/fs/capacitor_fs.cljs
more elegant to process path encoding/decoding on iOS
> use js/encodeURI and js/decodeURI to process path on iOS

- src/electron/electron/core.cljs
- src/electron/electron/fs_watcher.cljs
- src/electron/electron/handler.cljs
- src/electron/electron/state.cljs
- src/electron/electron/utils.cljs
- src/electron/electron/window.cljs
- src/main/electron/listener.cljs
- src/main/frontend/components/repo.cljs
- src/main/frontend/components/search.cljs
- src/main/frontend/db.cljs
This should fix search blanks in multiple windows.
Also, the changes in other windows should be much faster now because there's no need to listen for file watchers first.
https://www.loom.com/share/5b0f57e04b34492180cf07dd6fe2ddf8
> Sync db between multiple windows

- src/main/frontend/components/sidebar.cljs
https://www.loom.com/share/5c898789417341189a74dd0f68bf87e7
> enhance(mobile): don't close left-sidebar when clicking favorites/recent nav

- android/app/build.gradle
- resources/package.json
- src/main/frontend/version.cljs
> chore: bump version 0.5.6

- src/main/frontend/components/block.cljs
- src/main/frontend/components/editor.cljs
- src/main/frontend/handler/image.cljs
Demo: https://1drv.ms/v/s!AqqglbcuVBVHheYlKkK_HnyK3dX7lA
> fix(iOS): image display error

- src/main/frontend/handler/file.cljs
Demo: https://www.loom.com/share/e2b1cb3e4bca45ceb70fb0ab0faf9de3
> fix(iOS): css customization support

- src/main/frontend/extensions/code.css
> fix(editor): calc result offset in code editor

- src/main/frontend/extensions/graph.cljs
> Fix: missing do-sexp in graph on-click-handler

- src/main/frontend/components/header.css
> fix(ui): position of new updates tip

- src/electron/electron/fs_watcher.cljs
> fix(electron): avoid notifying destroyed window

- src/main/frontend/extensions/code.cljs
- templates/config.edn
- Add new codemirror options
- add corresponding options to config template
- rm unused config option
- add `:meta/version`, allowing for future migration support
> Feature: add codemirror options

- e2e-tests/basic.with-diacritics.spec.ts
- e2e-tests/utils.ts
- src/main/frontend/components/block.cljs
- src/main/frontend/components/page.cljs
- src/main/frontend/db/model.cljs
- src/main/frontend/format/block.cljs
- src/main/frontend/handler/extract.cljs
- src/main/frontend/handler/page.cljs
- src/main/frontend/search/db.cljs
- src/main/frontend/util.cljc
- src/main/frontend/util/page_property.cljs
**Normalization Support Progress**
**E2E tests**
**To resolve**
* rename namespace from subpage
* page search
**Resources**
- Test graph: [normalization_test.zip](https://github.com/logseq/logseq/files/7780208/normalization_test.zip)
- Steps to test: Re-index, enter page `normalize`, click one of the page refs, edit content
> enhance: apply normalization to the whole app

- src/main/frontend/components/header.css
- src/main/frontend/components/sidebar.cljs
- src/main/frontend/ui.cljs
close https://github.com/logseq/logseq/issues/3675
- iPhone 6/7/8
- iPhone 13
> fix(iPhone): remove extra top padding on landscape mode

- android/app/build.gradle
- resources/package.json
- src/main/frontend/extensions/code.cljs
- src/main/frontend/version.cljs
> Bump version 0.5.8

- resources/css/common.css
- src/main/frontend/components/search.cljs
> fix(ui): missing padding in mark element

- package.json
- resources/package.json
See-also: https://github.com/Marak/colors.js/issues/285
> fix(deps): bad colors.js

- src/main/frontend/components/settings.cljs
Related  #3818
- use warning, and this kind of notification should be a warning
- the warning will not disappear automatically
- wording
> enhance(ui): warning when journals date format chagne

- src/main/frontend/components/editor.cljs
- src/main/frontend/components/search.cljs
- src/main/frontend/components/sidebar.cljs
- src/main/frontend/handler/editor.cljs
- src/main/frontend/search.cljs
- src/main/frontend/util.cljc
> enhance: use search normalization

- package.json
- src/main/frontend/handler/editor.cljs
- src/main/frontend/util.cljc
- src/main/frontend/util/cursor.cljs
- src/test/frontend/util_test.cljs
> fix(editor): backspace for emoji char

- .github/workflows/pr-labeler.yml
- src/main/frontend/modules/shortcut/data_helper.cljs
Revert #3170 (partially)
Fixes #3574
> fix(settings): ctrl and cmd misuse in settings

- .github/workflows/build.yml
- README.md
- src/electron/electron/configs.cljs
- src/electron/electron/core.cljs
- src/electron/electron/fs_watcher.cljs
- src/electron/electron/git.cljs
- src/electron/electron/handler.cljs
- src/electron/electron/plugin.cljs
- src/electron/electron/updater.cljs
- src/electron/electron/utils.cljs
- src/electron/electron/window.cljs
- src/main/frontend/handler/extract.cljs
- src/main/frontend/ui/date_picker.cljs
- src/main/frontend/util/clock.cljs
- src/main/frontend/util/list.cljs
- src/main/frontend/util/page_property.cljs
- src/main/frontend/util/persist_var.cljs
- src/main/frontend/util/property.cljs
- src/main/frontend/util/thingatpt.cljs
- src/main/logseq/api.cljs
- src/test/frontend/db/query_dsl_test.cljs
- src/test/frontend/format/block_test.cljs
- src/test/frontend/handler/export_test.cljs
- src/test/frontend/handler/extract_test.cljs
- src/test/frontend/modules/outliner/core_test.cljs
- src/test/frontend/modules/outliner/ds_test.cljs
- src/test/frontend/react.cljc
- src/test/frontend/react_test.cljs
- src/workspaces/workspaces/cards.cljs
This PR fixes the first ~100 clj-kondo lint errors. I thought it'd be good to open a small PR so I can get familiar with our code review process. I wasn't sure whom to ask for review so I used github's suggested reviewers. Linter caught a couple small errors I noted in comments. For QA, I only used desktop version. I can try other versions if that's desired. I also updated documentation to avoid other devs from stumbling on node 17 issues. Discussed this some with @cnrpman
> Test/add clj kondo - Part 1

- src/main/frontend/components/file.cljs
Use CodeMirror editor to edit markup files as well.
This pull request:
Current:
Can not edit!
Known Issue: 
Will pop up a saving confirmation dialog when losing focus.
> enhance(editor): allow edit markup files with code editor

- src/electron/electron/core.cljs
- src/electron/electron/exceptions.cljs
- src/electron/electron/window.cljs
> enhance(electron): support uncaught exceptions handler for main process

- e2e-tests/page-refs.spec.ts
> [WIP]test(e2e): fix CI page ref check with no content display

- src/main/frontend/mobile/core.cljs
Some users report data loss if close logseq immediately after edit, the PR addresses this issue.
> enhance(iOS): save data when switching to other app

- e2e-tests/fixtures.ts
- e2e-tests/utils.ts
- won't require a fresh install
- fix left sidebar condition
> test(e2e): allow test with newly opened graph

- src/main/frontend/components/editor.cljs
Demo:
https://www.loom.com/share/0ef2c69b86d7496f89117173b8c14f61
> enhance: ac window moves with text

- gulpfile.js
> Revert "dev: fix gulp-watch cpu usage"

- e2e-tests/page-refs.spec.ts
- package.json
- src/main/frontend/components/block.cljs
- src/main/frontend/components/editor.cljs
- src/main/frontend/components/search.cljs
- src/main/frontend/config.cljs
- src/main/frontend/handler/extract.cljs
- src/main/frontend/handler/file.cljs
- src/main/frontend/handler/page.cljs
- src/main/frontend/handler/web/nfs.cljs
- src/main/frontend/search.cljs
- src/main/frontend/search/db.cljs
- src/main/frontend/util.cljc
- yarn.lock
Fix #2726
**New Dependency**
* [remove-accents](https://www.npmjs.com/package/remove-accents) to make searching accents & diacritics insensitive
> Enhance search normalization

- android/app/build.gradle
- resources/package.json
- src/main/frontend/version.cljs
Prepare for the v0.5.9 release.🚀
> chore: bump version 0.5.9

- android/app/build.gradle
- scripts/bump-version.sh
> Fix: should bump android version code

- src/main/frontend/handler/ui.cljs
> fix: custom js not work

- src/main/frontend/util.cljc
- src/main/frontend/utils.js
- Rewrite Javascript code by ClojureScript.
- Remove unnecessary codes
Javascript code only works in development mode.
> fix(iOS): make status bar style change in release mode

- e2e-tests/code-editing.spec.ts
- e2e-tests/page-refs.spec.ts
- src/main/frontend/components/block.cljs
- src/main/frontend/components/onboarding.cljs
- src/main/frontend/components/sidebar.cljs
- src/main/frontend/handler/editor.cljs
- src/main/frontend/util.cljc
https://www.loom.com/share/a8638967c606429d8dc56a395ffbe4bf
> Feature: shift click to select multiple blocks

- src/main/logseq/api.cljs
Mentioned: https://discord.com/channels/806040386614853642/841675547523678218/934343600542724106
> improve(plugin): api of `get_block` with shallow children uuid results

- .github/ISSUE_TEMPLATE/bug_report.yaml
- disable required check for platforms
> chore: update  issue template

- .github/ISSUE_TEMPLATE/bug_report.yaml
I noticed these while filing a bug. This is a follow up to https://github.com/logseq/logseq/pull/4057 . Since this is minor, I tried pushing this on master but I don't have permission to do that
> Fix grammar and typos in issue template

- package.json
- src/electron/electron/core.cljs
> enhance(ui): setup default context menu with right click

- .github/pr-labeler.yml
> chore(dev): add more pr labeler rules

- src/main/frontend/handler/extract.cljs
> fix(properties): disable blank alias

- package.json
- resources/package.json
- static/yarn.lock
- yarn.lock
Fixes #4235
also removes duplicated entry: "remove-accents"
> Fix: deps of electron-context-menu

- src/main/frontend/extensions/calc.cljc
- src/main/frontend/extensions/code.cljs
- src/main/frontend/extensions/code.css
> fix: calc result overlaps with input text when the latter is very long

- src/main/frontend/components/sidebar.cljs
- src/main/frontend/extensions/srs.cljs
- src/main/frontend/handler/events.cljs
- src/main/frontend/modules/shortcut/before.cljs
- src/main/frontend/modules/shortcut/config.cljs
- src/main/frontend/modules/shortcut/core.cljs
- src/main/frontend/state.cljs
> fix: srs cards shortcuts not working

- src/main/frontend/components/page.css
> fix(ui): checkbox floats above button

- src/main/frontend/components/content.cljs
- src/main/frontend/db/model.cljs
- src/main/frontend/extensions/srs.cljs
https://www.loom.com/share/1e222e80d73547a39ca08e47a3713edd
> fix: srs cards can't be edited during preview or in /cards queries

- package.json
- resources/package.json
- src/electron/electron/context_menu.cljs
- src/electron/electron/core.cljs
- src/electron/electron/window.cljs
- yarn.lock
Fix #4274
Fix #4271 
- replace electron-context-menu
- fix bug caused by register context-menu twice
> fix(electron): rewrite electron-context-menu

- src/electron/electron/context_menu.cljs
- do not show context-menu when there's no item
- add select all
- refine separator position
- gray out disabled items
> enhance(ui): refine electron context-menu

- src/main/frontend/config.cljs
- src/main/frontend/fs/capacitor_fs.cljs
- src/main/frontend/handler/file.cljs
- src/main/frontend/handler/web/nfs.cljs
- src/test/frontend/fs/capacitor_fs_test.cljs
As described in title.
Fixes #4283
> fix(android): app crashes

- .clj-kondo/config.edn
- deps.edn
- docs/dev-practices.md
- docs/develop-logseq.md
- src/main/frontend/db/model.cljs
- src/main/frontend/handler/export.cljs
- src/test/frontend/handler/export_test.cljs
Fixes #4211. Also add a testing library to help with focusing tests and improved develop docs based on my experience with Jakob. I linked him to the doc and he was running tests and building the release when I just wanted him to setup for development
> Fix: Change export to not depend on printing

- src/main/frontend/modules/shortcut/config.cljs
> fix(ui): exit edit mode when prompt

- e2e-tests/sidebar.spec.ts
- e2e-tests/utils.ts
~~Fix #4320~~
~~Introduced in ee9b52248ef57c5fb8f62b55a834cecef26e2786~~
**EDIT**: this is the e2e test case for #4322
> test(e2e) for #4320: recent list is not updated

- shadow-cljs.edn
see also: https://shadow-cljs.github.io/docs/UsersGuide.html#_output_settings
> fix: sourcemap cannot load when developing

- src/main/frontend/components/datetime.cljs
- src/main/frontend/handler/editor.cljs
fix https://github.com/logseq/logseq/issues/3783
> fix: set timestamp to another editing block

- src/main/frontend/util.cljc
fix https://github.com/logseq/logseq/issues/4406
> enhance: add zh-Hans-CN check in zh-CN-supported command

- src/main/frontend/handler/editor.cljs
fix https://github.com/logseq/logseq/issues/3806
> fix wrong block marker toggle if its reference is in editing

- src/main/frontend/components/editor.cljs
- src/main/frontend/components/editor.css
Demo: https://www.loom.com/share/cdaf463638de46d2a77aa0d3c0ef7e1a
Close https://github.com/logseq/logseq/issues/4293
> Feat: be able to collapse keyboard on mobile

- src/main/frontend/fs/capacitor_fs.cljs
Fix https://github.com/logseq/logseq/issues/4417
> fix(mobile): unable to load and render excalidraw file

- src/main/frontend/components/shortcut.cljs
close https://github.com/logseq/logseq/issues/4395
> fix italic syntax typo in help

- ios/App/App.xcodeproj/project.pbxproj
- ios/App/App/DownloadiCloudFiles.m
- ios/App/App/FileContainer.swift
- ios/App/App/FsWatcher.m
- ios/App/App/FsWatcher.swift
- src/main/frontend/fs.cljs
- src/main/frontend/fs/capacitor_fs.cljs
- src/main/frontend/handler/file.cljs
- src/main/frontend/handler/web/nfs.cljs
- src/main/frontend/mobile/util.cljs
- add a polling-based recursive file watcher
**EDIT**: add todo
> feat(ios): add polling based file watcher

- src/main/frontend/db/rules.cljs
As mentioned in the last PR https://github.com/logseq/logseq/pull/4424
> doc: comments for child query optimization

- src/main/frontend/components/page.cljs
- src/main/frontend/components/page.css
Demo: https://www.loom.com/share/1a5b48ac16d44c9b934f5149f2117904
> feat(mobile): add collapse/uncollaspe all blocks functionality

- src/main/frontend/db/model.cljs
fix https://github.com/logseq/logseq/issues/3704
> enhance: ignore logbook and default properties in unlinked reference

- src/main/logseq/api.cljs
> fix(api): return value of move block #4409

- .clj-kondo/config.edn
- .github/workflows/build.yml
- scripts/lint_rules.clj
- src/main/frontend/db/query_custom.cljs
- src/main/frontend/db/query_dsl.cljs
- src/main/frontend/db/query_react.cljs
- src/main/frontend/db/rules.cljc
- src/main/frontend/extensions/srs.cljs
- src/test/frontend/db/query_dsl_test.cljs
This PR fixes bugs #4498 , #4497 and #4500 that were introduced in #4441 . This PR also adds linting for datalog rules and finishes making all react-queries to display explicit errors like #4434
> Fix: dsl query bugs

- package.json
- shadow-cljs.edn
Use `yarn electron-watch` for correct sourcemap path while dev.
> fix(dev): sourcemap path in electron while dev

- android/app/src/main/java/com/logseq/app/FsWatcher.java
- android/app/src/main/java/com/logseq/app/MainActivity.java
- src/main/frontend/fs/capacitor_fs.cljs
- src/main/frontend/mobile/core.cljs
- src/main/frontend/mobile/util.cljs
> feat(android): add fs watcher plugin

- src/electron/electron/fs_watcher.cljs
- src/electron/electron/handler.cljs
Fix #4507
Introduced in  #4374
> fix(electron): unwatch dir when needed

- src/main/frontend/handler/editor.cljs
> fix(editor): error whilte cycling todos

- src/main/frontend/components/editor.cljs
- src/main/frontend/components/editor.css
Stretch the toolbar to full width.
Also refactor two functions.
> fix(tablet): toolbar width

- src/main/frontend/extensions/code.cljs
Fix #4565
When mouse clicked with selection, on-blur handler is called twice.
> fix(code): avoid calling saving handler too often

- src/main/frontend/handler/dnd.cljs
> fix: block disappears when drag to another block

- src/main/frontend/components/block.cljs
- src/main/frontend/db/query_dsl.cljs
- src/main/frontend/util/datalog.cljc
- src/test/frontend/db/query_dsl_test.cljs
- src/test/frontend/util/datalog_test.cljs
This fixes two nested boolean query bugs including #4510. There's also some query-dsl cleanup to remove unused string result code
> Fix nested boolean query bugs

- android/app/src/main/java/com/logseq/app/FsWatcher.java
- ios/App/App/FsWatcher.swift
- src/main/frontend/fs/watcher_handler.cljs
> fix(mobile): ignore bak and recycle in fs watcher

- .github/workflows/build-android.yml
- .github/workflows/build-desktop-release.yml
Fix #4614
requires secret SENTRY AUTH TOKEN (added).
> fix(ci): add sentry sourcemaps

- src/main/frontend/handler/page.cljs
Fix https://github.com/logseq/logseq/issues/4666
> fix(editor): error while toggling fav in journals

- libs/yarn.lock
> fix: update lockfile

- .github/workflows/build-desktop-release.yml
Fix #4563
Ref:
https://github.com/desktop/dugite/blob/ad8b11fb12ee109f45a62670385424d465dc63e9/script/config.js#L17-L23
> fix(build): dugite arch under macOS arm64

- src/main/frontend/components/block.cljs
Some elements in the block are rendered additionally, which I will point out with comments.
> chore: reduce extra rendering

- src/main/frontend/components/plugins.cljs
- src/main/frontend/components/plugins.css
- src/main/frontend/dicts.cljc
> enhance(ux): filter of marketplace plugins list

- src/main/frontend/db/model.cljs
Affects: only master branch
Introduced In: #4750
> fix(editor): cannot create journal

- .gitignore
- e2e-tests/editor.spec.ts
- e2e-tests/utils.ts
- src/main/frontend/components/block.cljs
- src/main/frontend/db/model.cljs
Fix #4814, e2e test added too.
> fix: Disappearing children

- src/main/frontend/publishing/html.cljs
Related #4796
Fix the following error:
> fix(publishing): order of scripts

- src/main/frontend/handler/editor.cljs
When the last block is empty and `reuse-last-block?` is non-nil, don't create a new block but use the last block to insert contents.
Use case 1:
When receiving shared data from other apps and inserting them into today's empty journal, it's better to insert the data into the first empty block instead of creating a new block to save it but keeping the first one empty.
> enhance: add an `reuse-last-block?` paras key to `api-insert-new-block`

- src/main/frontend/components/onboarding/setups.cljs
Thanks to @logseqramses for catching these
> Fix a few onboarding logseq capitalizations

- resources/package.json
- src/electron/electron/file_sync_rsapi.cljs
- src/electron/electron/handler.cljs
- src/main/frontend/config.cljs
- src/main/frontend/fs/sync.cljs
- src/main/frontend/handler/user.cljs
- update rsapi version
- goog-define FILE-SYNC-PROD?, LOGIN-URL, API-DOMAIN
> feat(sync): support dev&prod env

- src/main/frontend/components/plugins_settings.cljs
> fix(plugin): sometimes settings GUI of plugin not work when entry from app settings pane

- src/main/frontend/components/block.cljs
- src/main/frontend/util.cljc
fix https://github.com/logseq/logseq/issues/4916
> fix playing video goes into editing mode on iOS

- ios/App/Podfile
- package.json
- src/main/frontend/utils.js
- yarn.lock
close https://github.com/logseq/logseq/issues/4918
> fix copy to clipboard failure on iOS

- src/main/frontend/components/settings.cljs
> style(settings): line-space of general/journals

- src/main/frontend/components/page.cljs
> enhance(editor): accept enter in dummy block

- android/app/build.gradle
- resources/package.json
- src/main/frontend/version.cljs
Prepare for the 0.6.6 release.
> chore: bump version 0.6.6

- templates/config.edn
Basically the title. Improving PR #913 by adding the new configuration in the default config.edn.
Future improvement: put this in the settings panel.
> Add start-of-week config to default config.edn

- src/main/frontend/config.cljs
close https://github.com/logseq/logseq/issues/4960
> add more audio files support

- src/main/frontend/extensions/srs.cljs
- Use the same UI in both preview and review mode
- Simplify button UI structure, fix misaligned button in preview mode
- Revert tippy-style button, use the former button with shortcut key style
- Simple opacity change when button-key pressed (not an animation, but to inform user which button is pressed)
> enhance(card): refine card ui

- src/main/frontend/config.cljs
- src/main/frontend/dicts.cljc
- src/main/frontend/fs/sync.cljs
when toggle sync on, need to check current graph belongs to the current login user first.
> fix(sync): check current graph belongs to current logged-in user

- android/app/src/main/java/com/logseq/app/MainActivity.java
- ios/App/App/AppDelegate.swift
Delay 3 seconds to notify Logseq app from share sheet after cold launch.
Delay 5 seconds.
> enhance: receive share content after cold launch

- resources/css/common.css
- src/main/frontend/components/sidebar.cljs
- src/main/frontend/components/sidebar.css
- src/main/frontend/fs/watcher_handler.cljs
- src/main/frontend/handler/repo.cljs
- src/main/frontend/handler/web/nfs.cljs
- src/main/frontend/modules/outliner/datascript.cljc
- src/main/frontend/state.cljs
- src/main/frontend/ui.cljs
https://www.loom.com/share/6fca4583c32d4f38a1febbbe414d455f
> Enhance: parsing progress bar

- libs/src/LSPlugin.ts
- src/main/logseq/api.cljs
> feat: expose start-of-week to plugins

- src/main/frontend/components/command_palette.css
- src/main/frontend/components/search.cljs
search modal resizing causes a jump when the keyboard shows.
> fix: search modal jumps on mobile

- src/main/frontend/handler/editor.cljs
- src/main/frontend/util/list.cljs
- src/main/frontend/util/thingatpt.cljs
- src/test/frontend/util/list_test.cljs
Previous bug:
https://www.loom.com/share/9d70f79027df49bc85f48780c6f3e75d
> fix: ordered list numbers

- src/main/frontend/handler/editor.cljs
How to reproduce:
1. `git checkout master`
2. copy some blocks
3. paste anywhere
4. copy something from external apps, for example, your browser
5. paste the text
6. notice that logseq still paste the blocks copied in step 2
> fix: Cmd-v sometimes pastes wrong content

- src/main/frontend/extensions/code.cljs
This causes strange navigation problems randomly.
> fix(code): do not accept tab in codemirror

- e2e-tests/editor.spec.ts
- e2e-tests/utils.ts
- src/main/electron/listener.cljs
- src/main/frontend/components/block.cljs
- src/main/frontend/components/page.cljs
- src/main/frontend/components/settings.cljs
- src/main/frontend/db.cljs
- src/main/frontend/db/model.cljs
- src/main/frontend/extensions/zotero/handler.cljs
- src/main/frontend/handler/editor.cljs
- src/main/frontend/handler/events.cljs
- src/main/frontend/handler/external.cljs
- src/main/frontend/handler/page.cljs
- src/main/frontend/modules/instrumentation/sentry.cljs
- src/main/frontend/modules/outliner/datascript.cljc
> Fix new pages from bracketing text is broken

- src/main/frontend/handler/route.cljs
> fix: page crash when navigating to home if default home is a custom page

- src/main/frontend/components/block.cljs
close https://github.com/logseq/logseq/issues/4930
> fix scroll lags on iOS images

- android/app/build.gradle
- resources/package.json
- src/main/frontend/version.cljs
> chore: bump version 0.6.7

- ios/App/App.xcodeproj/project.pbxproj
- ios/App/App/FileSync/Extensions.swift
- ios/App/App/FileSync/FileSync.m
- ios/App/App/FileSync/FileSync.swift
- ios/App/App/FileSync/Payload.swift
- ios/App/App/FileSync/SyncClient.swift
- ios/App/App/FsWatcher.swift
- ios/App/Podfile
- src/main/frontend/components/header.cljs
- src/main/frontend/fs/sync.cljs
- src/main/frontend/handler/events.cljs
- src/main/frontend/handler/user.cljs
- src/main/frontend/mobile/core.cljs
- src/main/frontend/mobile/util.cljs
- data encryption will be in another PR
> Feat: enable file sync for iOS platform

- src/main/frontend/extensions/latex.cljs
Related plugin https://github.com/xyhp915/logseq-extensions-plus
> fix(ux): initial renderer not working for Katex extension hooks

- src/main/frontend/config.cljs
support username+email when signin&signup (dev env)
> enhance: update login url

- src/main/frontend/handler/user.cljs
auth-callback, auth-refresh-token api return application/json now
> fix(login): auth-callback&auth-refresh-token return json type resp

- src/main/frontend/fs/sync.cljs
- go-loop websocket ping to keep ws alive
- remove ::remote->local=>local->remote state
- remove ::remote->local=>local->remote-full-sync state
- remote ::remote->local-full-sync=>local->remote-full-sync state
- when starting sync, first trigger remote->local, then local->remote-full-sync
> enhance(sync): ws ping, update sync init process

- src/main/frontend/handler/repo.cljs
fix https://github.com/logseq/logseq/issues/5143
> fix hidden files removing failure on mobile

- src/main/frontend/fs/sync.cljs
- src/main/frontend/handler/events.cljs
- src/main/frontend/state.cljs
- auto start sync when switching graphs
- add state ::starting
> enhance(sync): auto start sync when switching graphs

- src/main/frontend/ui.cljs
It fixes #5278.
None that I know of.
> fix: render preview page on-hover

- package.json
> fix(publishing): use release build for publishing js

- android/app/build.gradle
- ios/App/App.xcodeproj/project.pbxproj
- resources/package.json
- src/main/frontend/version.cljs
> Chore/bump version 0.6.10

- src/main/frontend/components/plugins.cljs
> fix(plugin): page crash when checking plugin updates with some network issues

- src/main/frontend/components/plugins.cljs
- src/main/frontend/ui.cljs
> fix: save mode when switching themes

- src/main/frontend/components/block.cljs
- src/main/frontend/components/theme.css
> Revert "style: optimize block alignment"

- docs/contributing-to-translations.md
- src/main/frontend/dicts.cljc
- src/main/frontend/modules/shortcut/dicts.cljc
Languages Portuguese (Brazilian) and Italian are 100% translated.
Checked when running ```bb lang:list```, ```bb lang:missing pt-BR``` and ```bb lang:missing it```
> Fully translated in Portuguese (BR) and Italian

- src/main/frontend/components/header.cljs
Fix e2e CI
`when` is lazy in evaluation, wrap the two elements in a seq.
> fix(ui): left menu style

- src/main/frontend/dicts.cljc
Including dummy note and tutorial. See seperate pull requests for those.
> Updated Norwegian translation

- src/electron/electron/core.cljs
- macOS has a default App menu
- Windows has no `about` role
> fix(electron): use different app menu for macos and others

- deps/graph-parser/src/logseq/graph_parser/block.cljc
> fix(graph-parser): avoid parsing illegal id

- src/main/frontend/extensions/pdf/assets.cljs
> fix(pdf): highlight refs lose association with related pdf

- src/electron/electron/core.cljs
> fix(electron): register accelerator for mod+n

- src/main/frontend/extensions/code.css
> enhance(ui): extra white space of code block from top

- templates/config.edn
- bullet indentation
- scheduled and deadline default query
#5675
> 5675 fix: Add missing config

- src/main/frontend/extensions/excalidraw.cljs
> Making excalidraw follow the theme of logseq. (basic 'dark 'light' theming)

- deps/graph-parser/src/logseq/graph_parser/util.cljs
- src/main/frontend/extensions/pdf/assets.cljs
> fix: trim spaces when sanitizing page name

- ios/App/App.xcodeproj/project.pbxproj
- ios/App/App/FileContainer.swift
> ensure iOS local storage container id

- android/app/src/main/java/com/logseq/app/FsWatcher.java
Fix #5668
Fix #5665
- defer deletion notification
- checks file status when receive a deletion notification
> fix(android): handle quick deletion then creating

- src/main/frontend/components/block.cljs
- src/main/frontend/util/text.cljs
> fix bilibili embed issues

- src/main/frontend/util/marker.cljs
> fix(editor): wrong cycle todo when heading symbol on the same line

- src/main/frontend/components/search.cljs
> Fix: Close modal before opening more results

- deps/db/src/logseq/db/default.cljs
- deps/graph-parser/src/logseq/graph_parser/test/docs_graph_helper.cljs
Address https://github.com/logseq/logseq/issues/5871
> enhance: built-in canceled page

- src/main/frontend/extensions/code.css
> fix calc output position

- tldraw/apps/tldraw-logseq/src/components/ZoomMenu/ZoomMenu.tsx
fixes an issue with previous PR
> fix(whiteboards): zoom text not updating

- src/main/frontend/extensions/html_parser.cljs
- should keep space between tags
- should avoid raw data-url
> fix(editor): bad format copy from html

- src/main/frontend/extensions/html_parser.cljs
- handle `<br />`
- partially handle `<code>[any nested elements]</code>`
- avoid adding `data-` attributes to hiccup
> fix(editor): more support for html convertion

- src/main/frontend/components/plugins.cljs
**Disable this feature on pagebar.**
> fix(ui): remove plugin ui items manager from pagebar

- src/main/frontend/components/editor.cljs
- fix missing i18n term
- reorder items when found along a hierarchy
- order alphabetically when term lengths are equal
Fix #5927
> fix(editor): reorder items in page search auto-complete

- src/main/frontend/handler/page.cljs
> fix(editor): new-page auto-completion under non-en environment

- src/main/frontend/extensions/srs.cljs
> fix flashcards not working

- src/main/frontend/mobile/mobile_bar.cljs
- src/main/frontend/state.cljs
Fix https://github.com/logseq/logseq/issues/5969
> only update toolbar when keyboard re-displays

- e2e-tests/flashcards.spec.ts
- src/main/frontend/handler.cljs
See-also: #5957 
This test should fail before the bug is fixed.
> test(e2e): add simple flashcards check

- resources/js/preload.js
Not sure why the existing behavior works, but this issue should fix https://github.com/pengx17/logseq-publish/issues/36
cc @QWxleA
> fix: export as html issue

- src/electron/electron/core.cljs
- src/main/frontend/extensions/pdf/assets.cljs
> fix(assets): missing asset resource when file name with specific url encoded chars

- tldraw/apps/tldraw-logseq/src/styles.css
This PR is simple and just improves the css for the action bar which I noticed while working on context bar.
> enhance(whiteboards):update action bar css

- resources/package.json
> fix(build): codesign error

- android/app/build.gradle
- ios/App/App.xcodeproj/project.pbxproj
- resources/package.json
- src/main/frontend/version.cljs
Minor upgrade, to fix macOS codesign error.
Pending Fixes:
> chore: bump version 0.7.8

- resources/css/common.css
> fix(ui): inline code style

- src/main/frontend/modules/shortcut/config.cljs
- src/main/frontend/modules/shortcut/dicts.cljc
Added this command as I found it useful and I imagine anyone who needs to apply workarounds or QA will as well. I didn't give it a keybinding as I don't think it needs a top level keybinding and it is easy to access with `Cmd-shift-P re-`
> Enhance: Add command to re-index graph

- src/main/frontend/extensions/pdf/_viewer.css
- src/main/frontend/extensions/pdf/highlights.cljs
> fix(pdf): missing cmaps resources 

- src/main/frontend/components/block.cljs
> Fix #5856: Wrong order of switching images in maximize mode

- android/app/build.gradle
- ios/App/App.xcodeproj/project.pbxproj
- resources/package.json
- src/main/frontend/version.cljs
> chore(release): bump version 0.7.9

- src/main/frontend/extensions/pdf/utils.cljs
mentioned here: 
https://discord.com/channels/806040386614853642/840125562970439690/1001867676664221737
> improve(pdf): friendly breakline for multiple language highlights text

- src/main/frontend/handler/editor.cljs
This was part of https://github.com/logseq/logseq/pull/6270 but I split it off because it's not super related.
I put these in as a matter of clarifying the code a bit since it took me a good while to figure them out more precisely.
Of note, the one that says 
> When you type two spaces after a command character (may always just be handled by the above instead?)
I could never get this branch of code to fire; it may be completely covered by the two cases above it.
> Add comments to editor keyup-handler cases

- src/electron/electron/search.cljs
> fix(electron): handle corrupted search db

- src/main/frontend/components/block.cljs
Fix #6284
Introduced in #6193
This bug does not affect the beta release.
> fix(ref): block embedded error

- android/app/build.gradle
- ios/App/App.xcodeproj/project.pbxproj
- resources/package.json
- src/main/frontend/version.cljs
> chore: bump version 0.8.0

- src/electron/electron/utils.cljs
- src/main/frontend/handler/plugin.cljs
> fix(plugin): initial plugin core with fatal argument of empty logseq dot root

- .github/workflows/build-android.yml
- .github/workflows/build-desktop-release.yml
- enable-file-sync flag for Android
- check against invalid builds
- avoid signing if repo is forked
- do not overwrite existing release
> refactor(ci): add checks for ci release

- src/main/frontend/components/onboarding.cljs
> fix incorrect feature request URL

- e2e-tests/editor.spec.ts
- e2e-tests/fixtures.ts
- e2e-tests/types.ts
- e2e-tests/utils.ts
- src/main/frontend/components/editor.cljs
- src/main/frontend/handler/editor.cljs
Will fix #6266. First, adding e2e tests.
> Fix moving cursor outside brackets

- android/app/build.gradle
- ios/App/App.xcodeproj/project.pbxproj
- resources/package.json
- src/main/frontend/version.cljs
> chore: bump version 0.8.1

- src/main/frontend/components/repo.cljs
- src/main/frontend/handler.cljs
- src/main/frontend/handler/events.cljs
- src/main/frontend/handler/file.cljs
- src/main/frontend/handler/repo.cljs
Fix #5001 
Fix #3861 
Related #6382
- Fix the journal title format bug
- Remove debug print introduced recently(which prints massive logs when re-indexing)
- Minor i18n fixes
> Fix wrong journal title format while parsing

- resources/js/preload.js
- src/main/frontend/util.cljc
- src/main/frontend/utils.js
Under windows, 
URL will return a `file://` for incoming windows paths.
> fix(fs): wrong url for windows

- src/main/frontend/components/search.cljs
> fix: shift-click on recently searched page

- src/main/frontend/components/block.cljs
Small enhancement requested by https://discuss.logseq.com/t/hide-icon-property-like-title/8738. Seemed reasonable. Gave this property functionality a name (var) to reduce the chance of it being buggy as described in https://quire.io/w/Logseq-_team_dedicated_to_sport_of_knowledge/1242/Move_hardcoded_properties_to_named_vars
> enhance: Hide icon page property

- templates/config.edn
As noted by a user in https://discuss.logseq.com/t/official-comprehensive-list-of-config-edn-options/4935/7?u=cldwalker, we didn't have this config option documented
> Chore: Document dwim config introduced in #2975

- docs/develop-logseq-on-windows.md
Remove outdated description about gulp
---
Close #6476
> docs: Add guide to speed up build process on Windows

- src/main/frontend/components/sidebar.cljs
> fix: Re-enabling Journals options does not work when default home page is filled out

- .github/workflows/build-desktop-release.yml
The corresponding secrets are already added to repo.
> fix(build): codesign on windows

- .github/workflows/e2e.yml
- e2e-tests/accessibility.spec.ts
- e2e-tests/editor.spec.ts
- e2e-tests/fixtures.ts
- e2e-tests/page-search.spec.ts
- e2e-tests/utils.ts
E2E test changing towards codebase would trigger 10 times of E2E testing in parallel (using matrix mechanism)
Help exposing E2E stability issues.
Fix some minor E2E stability issues.
p.s. Github Action is free for open source projects.
> test(e2e): github action workflow for E2E tests

- android/app/build.gradle
- ios/App/App.xcodeproj/project.pbxproj
- resources/package.json
- src/main/frontend/version.cljs
Prepare for the v0.8.3 release.
> chore: bump version 0.8.3

- src/main/frontend/handler/web/nfs.cljs
This fixes ios first-start bug.
> fix: aways clean all load state when nfs open

- src/main/frontend/components/sidebar.cljs
- src/main/frontend/components/sidebar.css
> improve(ui): nested scroll container for left sidebar dynamic modules

- public/index.html
- src/main/frontend/handler.cljs
- src/main/frontend/handler/web/nfs.cljs
- src/main/frontend/idbkv.js
This is very tricky. "restore repo" is hanging forever! So "db-restoring!" state is never cleared. All following operations are unpredictable.
See-also: https://developer.apple.com/forums/thread/681201
> fix(ios): handle ios indexedDB preload

- src/main/logseq/api.cljs
> fix(api): returns of raw datascript query

- src/main/frontend/components/file_sync.cljs
- src/main/frontend/handler/events.cljs
Demo:
https://www.loom.com/share/0fb51162ee8448609fdd2c96e701d882
> fix: sync allows to pick a non-empty folder to sync with remote

- android/app/build.gradle
- ios/App/App.xcodeproj/project.pbxproj
- resources/package.json
- src/main/frontend/version.cljs
This is the preparation for v0.8.5 release.
- ~~[ ] https://github.com/logseq/logseq/pull/6531~~
> Release 0.8.5

- src/main/frontend/util/persist_var.cljs
Introduced in https://github.com/logseq/logseq/pull/6613
https://github.com/logseq/logseq/blob/59e7d092b180c9407299030f192dd31d25658b4d/src/main/frontend/fs/sync.cljs#L2742-L2751
> fix: persist var init promise

- src/main/frontend/components/file_sync.cljs
- src/main/frontend/components/header.cljs
- src/main/frontend/components/plugins.cljs
- src/main/frontend/components/shortcut.cljs
- src/main/frontend/extensions/latex.cljs
- src/main/frontend/ui.cljs
- Avoid react dev warnings about missing keys or duplicated key
- Fix latex extension error when rendering null element
> Fix react dev warnings

- src/main/frontend/components/sidebar.css
> fix(ui): mobile left sidebar overflow hidden

- src/main/frontend/handler/file.cljs
- src/main/frontend/handler/repo_config.cljs
- src/main/frontend/state.cljs
- templates/config.edn
> fix: config cleared if passed content is nil

- src/main/frontend/components/encryption.cljs
Demo: https://www.loom.com/share/ab33813ab83346718633a855dffdbffa
> enhance: add "Show password"

- src/main/frontend/components/plugins_settings.cljs
A regression in https://github.com/logseq/logseq/pull/6659
> fix: plugin settings not loading

- .gitignore
- capacitor.config.ts
- gulpfile.js
- package.json
- yarn.lock
These commands just supported binding with local IP for dev server.
```shell
yarn ios:dev
yarn android:dev
```
> Enhance/one command for ios & android dev

- resources/css/common.css
This reverts commit 5bc0537954925ac9c17b5282e49788239f870656.
> Revert "chore: increase the max width of main container"

- src/main/frontend/components/right_sidebar.cljs
- src/main/frontend/components/sidebar.cljs
- Disable css transitions on key down to increase the resizing speed of the right sidebar when using arrow keys
- Remove the outline from the main container
> Fix: Minor UI issues

- package.json
- src/main/frontend/encrypt.cljs
- src/main/frontend/fs.cljs
- src/main/frontend/fs/capacitor_fs.cljs
- yarn.lock
- capacitor v4 compat fix
- android native encryption support
> Fix: capacitor v4 compat 

- src/main/frontend/components/query_table.cljs
- src/main/frontend/db/query_dsl.cljs
- src/test/frontend/db/query_dsl_test.cljs
Fixes sort-by filter as reported by @logseqramses. Also fixes #5643 by adding sort-by page support which AFAIK didn't work with page results previously
> Fix sort-by filter for simple queries

- android/app/src/main/assets/capacitor.plugins.json
- package.json
- src/electron/electron/file_sync_rsapi.cljs
- src/main/frontend/fs/sync.cljs
- yarn.lock
> Fix: include graph UUID in capacitor call

- .gitignore
- deps.edn
- deps/graph-parser/src/logseq/graph_parser/extract.cljc
- src/js/.gitignore
- src/main/frontend/components/sidebar.cljs
- src/main/frontend/components/whiteboard.cljs
- src/main/frontend/extensions/tldraw.cljs
- src/main/frontend/handler/paste.cljs
- src/main/frontend/modules/shortcut/config.cljs
- src/main/frontend/modules/shortcut/dicts.cljc
- tldraw/apps/tldraw-logseq/build.mjs
Added `g w` to get to whiteboards quickly and addressed some minor things I saw while reviewing #5341. See commits for explanations
> Whiteboards shortcut and minor fixes

- src/main/frontend/components/query_table.cljs
- src/main/frontend/util/clock.cljs
> Fix total clock-time calculation in query table

- android/app/build.gradle
- ios/App/App.xcodeproj/project.pbxproj
- resources/package.json
- src/electron/electron/handler.cljs
- src/main/frontend/version.cljs
> Chore: bump version 0.8.8

- src/electron/electron/file_sync_rsapi.cljs
This PR disables file-sync on Windows 7/8 temporarily.
Fix #6756
Fix #6727 
Fix #6698
Fix #5362
> fix(build): windows7 compatibility

- src/main/frontend/components/command_palette.css
- src/main/frontend/components/settings.cljs
- src/main/frontend/dicts.cljc
- src/main/frontend/ui.cljs
- Add icon support to button component
- Add login/logout prompt to alpha features on settings
- Fix icon sizing  issue on command palette
> Enhance: Activation settings

- resources/css/common.css
- src/main/frontend/components/content.cljs
- src/main/frontend/components/content.css
- src/main/frontend/components/header.css
- src/main/frontend/components/page.cljs
- src/main/frontend/components/reference.cljs
- src/main/frontend/components/right_sidebar.cljs
- src/main/frontend/components/right_sidebar.css
- src/main/frontend/components/scheduled_deadlines.cljs
- src/main/frontend/components/sidebar.cljs
- src/main/frontend/components/sidebar.css
> Style tweaks

- tldraw/apps/tldraw-logseq/src/components/ContextMenu/ContextMenu.tsx
- tldraw/packages/core/package.json
- tldraw/packages/core/src/lib/TLApp/TLApp.ts
- tldraw/packages/core/src/utils/BoundsUtils.ts
- tldraw/yarn.lock
https://user-images.githubusercontent.com/584378/194841855-61757172-2bac-4ebe-87f5-46d3eb756c0f.mp4
> feat(whiteboard): pack shapes into rect action

- tldraw/apps/tldraw-logseq/src/components/ContextMenu/ContextMenu.tsx
- tldraw/apps/tldraw-logseq/src/styles.css
> Feat: Add icons to context menu

- src/main/frontend/components/header.cljs
> Fix #6965 caused by button unable to handle href

- deps/graph-parser/src/logseq/graph_parser/property.cljs
- deps/graph-parser/src/logseq/graph_parser/text.cljs
- deps/graph-parser/test/logseq/graph_parser/text_test.cljs
- deps/graph-parser/test/logseq/graph_parser_test.cljs
- src/test/frontend/db/name_sanity_test.cljs
Fixes #6970 as well as a number of built-in properties that were incorrectly parsing refs
> Fix: For incorrect ref parsing for built in props

- resources/js/preload.js
- src/electron/electron/window.cljs
https://user-images.githubusercontent.com/1779837/195501611-3bf76325-a12d-43a4-9306-6ac3f42e343b.mp4
> fix(electron): can't open zotero protocol links via external app

- ios/App/App/AppDelegate.swift
- ios/App/App/FileContainer.swift
- ios/App/App/FolderPicker.swift
- ios/App/App/FsWatcher.swift
- ios/App/App/Utils.swift
- package.json
- src/main/frontend/components/file_sync.cljs
- src/main/frontend/mobile/core.cljs
- yarn.lock
- Update `@logseq/capacitor-file-sync`
- support for file upload/download progress on Android
- reduce notification frequency on iOS
Related:
- https://github.com/logseq/capacitor-file-sync/commit/162ae4f42c14fa74dded3d5f29297dfc83485c2d
- https://github.com/logseq/file-sync/commit/48062186211d259d3b32ee26cedbc58123068b90
> enhance(android): add sync progress

- src/main/frontend/handler/paste.cljs
- tldraw/apps/tldraw-logseq/package.json
- tldraw/apps/tldraw-logseq/src/hooks/usePaste.ts
- tldraw/apps/tldraw-logseq/src/lib/preview-manager.tsx
- tldraw/apps/tldraw-logseq/src/lib/shapes/LogseqPortalShape.tsx
- tldraw/packages/core/src/lib/TLApp/TLApp.ts
- tldraw/packages/core/src/utils/BoundsUtils.ts
- tldraw/packages/react/src/hooks/useDebounced.ts
- tldraw/yarn.lock
> fix(whiteboards): some pasting issues

- src/main/frontend/dicts.cljc
- "页面图谱：" -> "页面图谱"
- graph -> 图谱
> I18n: enhance zh-CN translation

- android/app/build.gradle
- ios/App/App.xcodeproj/project.pbxproj
- resources/package.json
- src/main/frontend/version.cljs
> Bump to 0.8.9

- src/main/frontend/fs/watcher_handler.cljs
> Fix: Not showing all content when editing a long page (pdf)

- src/main/frontend/handler/assets.cljs
- src/main/frontend/handler/editor.cljs
related https://github.com/logseq/logseq/issues/7043
> fix(windows): remove encoding assets protocol path temporarily

- src/main/frontend/components/header.css
- src/main/frontend/mobile/util.cljs
> fix(ui): headerbar position on iPhone14x

- resources/css/common.css
Add color & bg vars like other blocks have - blockquote, inline code, etc...
> fix: add missed mark css vars

- src/main/frontend/components/block.css
- tldraw/apps/tldraw-logseq/src/lib/shapes/LogseqPortalShape.tsx
- tldraw/apps/tldraw-logseq/src/styles.css
> Fix: Whiteboard color issues

- src/main/frontend/components/encryption.cljs
- src/main/frontend/components/file_sync.cljs
- src/main/frontend/components/header.cljs
- src/main/frontend/components/settings.cljs
- src/main/frontend/core.cljs
- src/main/frontend/fs/sync.cljs
- src/main/frontend/handler/events.cljs
- src/main/frontend/handler/file_sync.cljs
1. make sure there's no sync reentrancy
2. there's no need to restore pwd after user input the password
> fix: sync crashes

- .gitignore
- resources/css/common.css
- src/main/frontend/components/right_sidebar.cljs
- src/main/frontend/components/search.css
> Small style fixes

- .github/workflows/build-android.yml
- .github/workflows/build-desktop-release.yml
> fix(build): android file sync prod env

- templates/config.edn
Current wording is both wrong from the grammar perspective and misleading.
> Correct wording of a comment in `config.edn`

- android/app/capacitor.build.gradle
- android/app/src/main/assets/capacitor.plugins.json
- android/app/src/main/res/values/colors.xml
- android/app/src/main/res/values/styles.xml
- android/capacitor.settings.gradle
- ios/App/Podfile
- package.json
- src/main/frontend/handler.cljs
- src/main/frontend/state.cljs
- src/main/frontend/util.cljc
- yarn.lock
> Fix: android nav bar and status bar color

- deps/db/bb.edn
- deps/db/src/logseq/db/rules.cljc
- src/main/frontend/db/model.cljs
- src/test/frontend/db/model_test.cljs
Also remove 2 unused rules and made the alias rule reusable so it could possibly be pulled in for other work like #7248
> Dev: Fix and add model tests

- README.md
This PR add a small section at the end of the README with some instructions on how to contribute by opening a PR and a link to the `good first issues`.
I recently worked on a small PR and I found that the process on how to contribute wasn't clear at least to me 😅, so I thought that I could create another small PR with a link also to the official github documentation on how to contribute from a fork.
I'm not sure if you'll find this useful, if this is not case, please excuse me and just delete/close this PR.
Thanks :)
> Add a section on how to contribute by opening a PR

- src/main/frontend/components/block.cljs
- src/main/frontend/components/file_sync.cljs
- src/main/frontend/fs.cljs
- src/main/frontend/fs/capacitor_fs.cljs
- src/main/frontend/fs/sync.cljs
- src/main/frontend/handler.cljs
- src/main/frontend/handler/block.cljs
- src/main/frontend/handler/events.cljs
- src/main/frontend/handler/file.cljs
- src/main/frontend/handler/file_sync.cljs
- src/main/frontend/handler/page.cljs
- src/main/frontend/idb.cljs
- src/main/frontend/mobile/core.cljs
- src/main/frontend/mobile/util.cljs
- src/main/frontend/state.cljs
> WIP: fix(sync): apply path-normalize on read/write filepath

- src/main/frontend/extensions/code.cljs
- src/main/frontend/handler/editor.cljs
- src/main/frontend/state.cljs
close #7015
close #7378
close #5735
> fix: ``` surroundings in code block disappear

- .github/workflows/build-ios.yml
- package.json
- yarn.lock
Related https://github.com/logseq/capacitor-file-sync/commit/402bfb0232cf338187b7d20417300081ac4bbc48
> fix(ios): apply path normalize for file-sync

- src/main/frontend/fs/sync.cljs
- src/main/frontend/handler/events.cljs
- src/main/frontend/handler/page.cljs
- src/main/frontend/util/fs.cljs
Reusing the notification for reserved characters detected upon Logseq Sync uploading
> feat: notify users to update filename format

- src/main/frontend/ui.cljs
> enhance(ui): add class options for icon ui component

- android/app/build.gradle
- ios/App/App.xcodeproj/project.pbxproj
- resources/package.json
- scripts/build-ios.sh
- src/main/frontend/version.cljs
> chore: bump to 0.8.12

- src/main/frontend/components/sidebar.cljs
- src/main/frontend/extensions/pdf/highlights.cljs
- src/main/frontend/ui.cljs
- tldraw/apps/tldraw-logseq/src/lib/shapes/LineShape.tsx
- tldraw/apps/tldraw-logseq/src/lib/shapes/PencilShape.tsx
- tldraw/apps/tldraw-logseq/src/styles.css
- tldraw/packages/core/src/types/types.ts
> Enhance: Minor UI issues

- src/main/frontend/fs/sync.cljs
IRemoteControlAPI contains API functions provided for outside of the sync process
> enhance(sync): add IRemoteControlAPI

- src/main/electron/listener.cljs
- templates/config.edn
- rename config keys
- add keys to config template
See-also #7431
> enhance(editor): rename quick-capture config keys

- src/main/frontend/components/editor.cljs
- src/main/frontend/fs.cljs
- src/main/frontend/fs/capacitor_fs.cljs
- src/main/frontend/fs/sync.cljs
- src/main/frontend/handler.cljs
- src/main/frontend/handler/events.cljs
- src/main/frontend/handler/file.cljs
- src/main/frontend/handler/repo.cljs
- src/main/frontend/modules/instrumentation/sentry.cljs
- src/main/frontend/modules/outliner/core.cljs
Also removed the posthog->sentry integration.
> fix: use sentry to capture errors instead of posthog

- src/main/frontend/fs/sync.cljs
- remove stop-sync-chan, stop-sync-mult, private-stop-sync-chan
- simplify the sync stop process
> enhance(sync): remove sync-stop-chan and simplify the stop process

- src/main/frontend/handler/events.cljs
Close #7226
Close #7100
When hiding keypad:
> fix(ios): ipad toolbar position when hiding keyboard

- resources/css/common.css
> fix(ui): use default font family for headings

- src/main/frontend/dicts.cljc
"à moins que vous n'ouvriez" au subjonctif présent.
> French typo on first warning after opening

- .github/workflows/build-ios-release.yml
- .github/workflows/build.yml
- .github/workflows/graph-parser.yml
Updates actions version as well
> ci: save ios build artifacts

- .github/ISSUE_TEMPLATE/bug_report.yaml
- src/main/frontend/components/header.cljs
> enhance(ux): add bug report url

- src/main/frontend/components/encryption.cljs
- src/main/frontend/components/page.cljs
- src/main/frontend/mobile/index.css
- src/main/frontend/mobile/mobile_bar.cljs
- UI warnings fixes for mobile and desktop platform
- Refactor `calendar` button of mobile toolbar
> Fix: ios UI warnings

- resources/css/common.css
> enhance(ui): adaptive font size for tags

- .github/ISSUE_TEMPLATE/bug_report.yaml
- capacitor.config.ts
- src/main/frontend/components/header.cljs
- Append platform UA on native mobile platforms
- Filter URL characters
> fix: bug report url on native mobile

- .github/workflows/build.yml
- .github/workflows/e2e.yml
- e2e-tests/editor.spec.ts
- e2e-tests/page-search.spec.ts
- e2e-tests/sidebar.spec.ts
- e2e-tests/utils.ts
* Recover E2E test for alias
* Improve E2E robustness
> E2E - Recover alias test

- src/main/frontend/state.cljs
> fix(conf): global config should failback to repo config

- src/main/frontend/extensions/pdf/highlights.cljs
> fix(pdf): wrong default page number when first open

- android/app/build.gradle
- ios/App/App.xcodeproj/project.pbxproj
- resources/package.json
- scripts/get-pkg-version.js
- src/main/frontend/version.cljs
Ref: https://semver.org/#spec-item-9
CC @tiensonqin @logseq-cldwalker
> Bump version 0.8.13, switch to prerelease style

- src/main/frontend/components/hierarchy.cljs
> fix(editor): missing hierarchy in parent page

- src/main/frontend/components/page.cljs
- src/main/frontend/components/page.css
- Make pagination a reusable component
- Add "First" / "Last" button to pagination
- Add "Icon" column
> refactor(ui): use pagination component for All pages

- src/main/frontend/modules/shortcut/config.cljs
BREAKING CHANGE: use mod+g c for git commit
> refactor!(shortcut): use mod+g c for git commit

- src/main/frontend/components/block.cljs
> fix: open inline block refs by default when zoom in a block

- src/main/frontend/fs/sync.cljs
- src/test/frontend/fs/sync_test.cljs
steps to reproduce:
1. keep 2 devices synced
2. close one of these 2 logseq apps
3. delete multiple pages in 'all-pages' on the other app, and wait sync
4. re-open the previously closed app
5. you will find the deleted pages are uploading in the re-opened app
6. then the other app received pages deleted before
> fix(sync): delete multi files and sync-back from other devices

- src/main/frontend/handler/events.cljs
- src/main/frontend/handler/user.cljs
- src/main/frontend/modules/instrumentation/sentry.cljs
Development errors are collected too to help identity errors earlier
> fix: use tags for filter and add user id to the scope

- src/main/frontend/modules/instrumentation/posthog.cljs
@andelf same change in 662a8a9
> fix(dev): do not use posthog when dev

- tldraw/apps/tldraw-logseq/src/components/ContextBar/contextBarActionFactory.tsx
- tldraw/apps/tldraw-logseq/src/components/Tooltip/Tooltip.tsx
- tldraw/apps/tldraw-logseq/src/components/inputs/ToggleInput.tsx
- tldraw/apps/tldraw-logseq/src/lib/shapes/BoxShape.tsx
- tldraw/apps/tldraw-logseq/src/lib/shapes/EllipseShape.tsx
- tldraw/apps/tldraw-logseq/src/lib/shapes/LineShape.tsx
- tldraw/apps/tldraw-logseq/src/lib/shapes/PolygonShape.tsx
- tldraw/apps/tldraw-logseq/src/styles.css
*Reverted the work that was related to arrow bounds, so we can merge this asap.
> Fix: Minor UI fixes

- src/main/frontend/components/block.cljs
- src/main/frontend/components/right_sidebar.cljs
- src/main/frontend/db/model.cljs
- src/main/frontend/db/react.cljs
- src/main/frontend/db/utils.cljs
- src/main/frontend/handler/editor.cljs
- src/test/frontend/db/model_test.cljs
Block with an id `1000000000` doesn't exist in the database.
Related to #7597.
> fix: db/entity with interger id is not nil with non-exist block

- tldraw/apps/tldraw-logseq/src/components/ContextMenu/ContextMenu.tsx
- tldraw/packages/core/src/lib/TLApi/TLApi.ts
- tldraw/packages/core/src/lib/TLApp/TLApp.ts
> fix: group/ungroup shortcuts

- src/main/frontend/components/settings.cljs
- src/main/frontend/components/whiteboard.cljs
- src/main/frontend/handler/events.cljs
- src/main/frontend/handler/user.cljs
- src/main/frontend/state.cljs
> release: open whiteboards for beta users

- .github/ISSUE_TEMPLATE/bug_report.yaml
Borrow the practice from https://github.com/apache/incubator-kvrocks/issues/new?assignees=&labels=bug&template=bug-report.yml
> github: Add two questions to bug template

- resources/css/common.css
- src/main/frontend/components/command_palette.css
- src/main/frontend/components/search.css
- src/main/frontend/handler/events.cljs
- src/main/frontend/ui.css
> fix(ui): modal style for mobile

- src/main/frontend/components/block.cljs
- src/main/frontend/db/model.cljs
> fix: block Reference only return the first level of data

- src/main/frontend/handler/editor.cljs
> fix(editor): move caret for the block right-boundary in the journals list page

- deps/graph-parser/deps.edn
- deps/graph-parser/src/logseq/graph_parser/util.cljs
- src/electron/electron/search.cljs
- src/main/frontend/util.cljc
The origin version distinct-by has O(n^2) cost
> enhance: replace util/distinct-by

- src/main/frontend/components/right_sidebar.cljs
Just make the right sidebar working on iPad
> improve(ui): right sidebar visibility based on response layout

- src/main/frontend/util.cljc
These fns‘ results shouldn't change, so memoize them
> enhance: memoize electron?, mobile?, etc

- src/main/frontend/components/block.cljs
- src/main/frontend/components/block.css
- src/main/frontend/mobile/footer.cljs
> improve(ui): polishments for mobile

- src/main/frontend/handler/editor.cljs
- src/main/frontend/modules/shortcut/config.cljs
- src/main/frontend/modules/shortcut/dicts.cljc
- src/main/frontend/state.cljs
https://www.loom.com/share/5646b85dacdf418ba30e148d2b7951b1
> feat: mod+a to select parent up to the whole page

- android/app/build.gradle
- ios/App/App.xcodeproj/project.pbxproj
- resources/package.json
- src/main/frontend/version.cljs
> chore(release): bump version 0.8.15

- .github/stale-issues.yml
- .github/workflows/stale-issues.yml
Looks like I created the initial PR for a branch on the repo. Now I don't have permission to edit or force push master into the branch :sweat_smile:. Please force push master and merge when possible.
---
For more information, see:
- https://github.com/marketplace/actions/close-stale-issues
- https://github.com/actions/stale/blob/master/action.yml
- https://github.com/actions/stale
<br></br>
- run every day at 00:00 UTC
- limit number of operations per run to: 100
- days before marking the issue stale: 180
- days before closing the issue after marking it: 20
- label added to stale issues: `:status/automatic-stale`
- label added to closed stale issues: `:status/automatic-closing`
- exempt issue labels: `:status/hold`, `:status/WIP`, `:type/enhancement`
<br></br>
there is a separate task to …
> Feat: close stale issues action

- .github/workflows/stale-issues.yml
Somehow, an older version of the config was merged into master. This should be updated to allow the awaiting response task to run and fix the print statements.
> fix(stale-issues.yml): add awaiting-respose step

- src/main/frontend/extensions/code.cljs
> fix: save code block resets cursor position

- docs/issue-labels.md
- **view table:** https://github.com/Bad3r/logseq-dev/blob/enhance/triage-labels/docs/issue-labels.md
<br></br> 
I am in the process of updating docs to improve onboarding of new contributors. This will also include documenting Logseq triage process. 
The first step of documenting the triage process is reviewing the list of current labels and adding a description for each one if it's missing. 
Instead of changing the labels in the repository; this file will be created to discuss and showcase planned changes. After team approval. The changes will be applied to the repo.  
Please review the list. I attempted to add a description for each label based on my understanding.  
- Which labels should be removed, if any?  
- Which labels should be added, if any?  
- which descriptions should be …
> enhance(dev): document labels and their descriptions

- src/main/frontend/config.cljs
- src/main/frontend/handler/user.cljs
add fn `login-with-username-password-e2e` for e2e test
> enhance: add login fn for e2e test

- src/main/frontend/components/block.cljs
> improve(ui): remove warning of macro renderer slot for mobile

- src/electron/electron/core.cljs
Fix https://github.com/logseq/logseq/issues/7384
> fix: capture open-url failure

- .github/workflows/stale-issues.yml
Temporarily remove the print functions until I find a fix
> fix(dev): remove print steps from stale action

- src/main/frontend/db/query_custom.cljs
- src/test/frontend/db/query_custom_test.cljs
> Enhance: Allow :rules and built in rules to be used together

- docs/dev-practices.md
update to match `$ bb dev:lint`
```cljs
(defn lint
"Run all lint tasks
- clj-kondo lint
- carve lint for unused vars
- lint for vars that are too large
- lint invalid translation entries"
[]
(doseq [cmd ["clojure -M:clj-kondo --parallel --lint src --cache false"
"bb lint:carve"
"bb lint:large-vars"
"bb lang:invalid-translations"
"bb lint:ns-docstrings"]]
(println cmd)
(shell cmd)))
```
this update is a pre-req to adding docs for data validation with Malli from https://github.com/logseq/logseq/blob/dev/malli-schema%2526kondo-config/
```sh
bb dev:gen-malli-kondo-config
```
Note that it will also need to be added to `build.yaml`  https://github.com/logseq/logseq/blob/dev/malli-schema%26kondo-config/.github/workflows/build.yml
I can submit a PR to that branch once this one is merged
CC: …
> docs(dev): update linting to match bb dev:lint

- src/main/frontend/extensions/pdf/assets.cljs
- src/main/frontend/extensions/pdf/utils.cljs
- src/test/frontend/extensions/pdf/assets_test.cljs
> enhance(pdf): make the weblink pdf filename to be human-readable for the annotations page

- src/main/frontend/mobile/mobile_bar.cljs
> fix(mobile): not showing hide keyboard button

- package.json
- resources/package.json
- static/yarn.lock
- yarn.lock
See-also: https://github.com/logseq/file-sync/commit/86ead1bc5ab19e9199a5816e4e0d12597eb5006d
Tested on my Android 13 device.
> fix(sync): update deps, fix expired token issue

- src/main/frontend/dicts.cljc
- templates/config.edn
> fix: Clarify the option to prefer pasting a file rather than text

- bb.edn
- deps.edn
- src/main/frontend/schema/handler/common_config.cljc
> Fix: :commands in config schema - fixes #8403

- src/main/frontend/core.cljs
- src/main/frontend/fs/sync.cljs
`md/stop!` do `(clj-kondo/save! {})` which overwrite `.clj-kondo/metosin/malli-types/config.edn` with `{}`
> fix(dev): md/stop! will rewrite malli-kondo config.edn with {}

- package.json
- resources/package.json
- static/yarn.lock
- yarn.lock
- rm s3 dependency, use s3-presign
- add http2 optimizations
- handle `NODE_TLS_REJECT_UNAUTHORIZED`
- update deps
> Update rsapi, allowing ignore certs

- package.json
- resources/package.json
- static/yarn.lock
- yarn.lock
> fix(sync): revert age upgrade

- src/test/frontend/db/name_sanity_test.cljs
> test: some more page name test cases

- src/main/frontend/dicts.cljc
> fix: Chinese (Simplified) translation

- e2e-tests/fixtures.ts
- src/main/frontend/db/query_react.cljs
- src/test/frontend/db/query_react_test.cljs
Closes #4156
Fix #8349
Fix #5166
> fix(query): cache special value as resolved value

- deps/graph-parser/src/logseq/graph_parser/util.cljs
- deps/graph-parser/test/logseq/graph_parser/util_test.cljs
- src/main/frontend/components/block.cljs
This is my attempt at a fix for #8271 
I do not know the concrete implications of changing assets to file in the url (hence the draft pr). I also couldn't find any documentations about the 2 protocols. 
If anyone knows more about this, please comment since I am stuck here
NOTE: This PR allows fragment URIs to render and play but they don't yet seek to the specified times because Chromium hasn't implemented it yet
> feat: support Media Fragment URIs with audio

- e2e-tests/headings.spec.ts
Following up on https://github.com/logseq/logseq/pull/8327 to test the behavior.
> Chore: Add heading tests

- src/main/frontend/extensions/pdf/assets.cljs
- src/main/frontend/extensions/pdf/highlights.cljs
- src/main/frontend/extensions/srs.cljs
This can results in data-loss in dev environment due to malli validation has been enabled.
> fix: safe-parse-float/int received nil parameter

- src/main/frontend/mobile/index.css
- src/main/frontend/mobile/mobile_bar.cljs
- use dom id to denote submenu
- fix css not functioning
> fix(mobile): timestamp submenu of toolbar

- android/app/build.gradle
- ios/App/App.xcodeproj/project.pbxproj
- resources/package.json
- src/main/frontend/version.cljs
> chore: bump version 0.8.17

- src/main/frontend/mobile/intent.cljs
> fix(mobile): do not use newer regex flags

- src/main/frontend/components/file.cljs
- src/main/frontend/handler/file.cljs
- src/main/frontend/state.cljs
Also, all configs should be clojure maps.
> fix: don't store broken config in DB

- src/electron/electron/git.cljs
- src/electron/electron/handler.cljs
- src/main/frontend/components/commit.cljs
> enhance(electron): show git status when commit

- src/electron/electron/server.cljs
- fix https://github.com/logseq/logseq/issues/8335
> fix(http-server): bad logger stream for windows

- src/electron/electron/context_menu.cljs
> fix(copy): cannot copy blank string

- resources/package.json
- src/electron/electron/server.cljs
- static/yarn.lock
> improve(apis): support CORS for http server

- src/main/frontend/components/block.cljs
Disable image resize on small screens.
> fix(android): disable image resize on android

- src/main/frontend/components/file.cljs
Fixes editing global config.edn from Settings. Probably related to #8578
> Fix: Edit global config.edn

- .github/workflows/build-android.yml
- .github/workflows/build-desktop-release.yml
- .github/workflows/build-docker.yml
- .github/workflows/build-ios.yml
- .github/workflows/build-stage.yml
- .github/workflows/build.yml
- .github/workflows/db.yml
- .github/workflows/e2e.yml
- .github/workflows/graph-parser.yml
- docs/develop-logseq-on-windows.md
> ci: update actions and build deps

- .gitignore
- .lsp/config.edn
add :ns-inner-blocks-indentation config to keep the current style of :require
> dev: add lsp config

- src/electron/electron/utils.cljs
- src/main/frontend/components/page_menu.cljs
- src/main/frontend/handler/page.cljs
- src/main/frontend/modules/shortcut/config.cljs
- src/main/frontend/modules/shortcut/dicts.cljc
- src/main/frontend/util/page.cljs
Closes #5704 
I don't quite understand how i18n is handled for shortcuts, so I might be missing an entry somewhere for this new shortcut.
> Shortcut for copying a page url

- android/app/build.gradle
- ios/App/App.xcodeproj/project.pbxproj
- resources/package.json
- src/main/frontend/version.cljs
> chore(release): bump version 0.8.18

- src/main/frontend/components/right_sidebar.cljs
> fix: shrink on-click range of sidebar-item

- README.md
just a quick PR to add the missing links to Logseq Hub and awesome-logseq.
> docs: Add Hub & Awesome-logseq to README

- e2e-tests/fixtures.ts
- package.json
- yarn.lock
fix: https://github.com/logseq/logseq/pull/8263#issuecomment-1406350694
> dev: upgrade playwright to 1.31.0

- src/main/frontend/ui.cljs
- src/main/frontend/ui.css
https://user-images.githubusercontent.com/1779837/224521723-eb7f87ac-8d8b-4459-a5fb-6bac7fedf809.mp4
https://user-images.githubusercontent.com/1779837/224521771-01641c4d-569d-463c-b8a7-3c2a9203216a.mp4
> enhance(ux): optimize active state of the auto-complete component for mouse interaction

- src/main/frontend/components/block.cljs
> fix(editor): wrong cookie render

- src/main/frontend/components/page.cljs
fix for https://github.com/logseq/logseq/issues/8793
> unwrap hierarhy and unlinked page blocks

- e2e-tests/page-search.spec.ts
- e2e-tests/whiteboards.spec.ts
- src/main/frontend/components/settings.cljs
- src/main/frontend/components/sidebar.cljs
- src/main/frontend/components/whiteboard.cljs
- src/main/frontend/dicts.cljc
- src/main/frontend/handler/events.cljs
- src/main/frontend/handler/user.cljs
- src/main/frontend/handler/whiteboard.cljs
- src/main/frontend/state.cljs
This PR also toggles on whiteboards by default.
> Release whiteboard to everyone

- src/main/frontend/fs/sync.cljs
`<get-remote-txid` is more lightweight. 
And these original usages of `<get-remote-graph` only need remote-txid values.
> enhance(sync): replace <get-remote-graph by <get-remote-txid

- android/app/build.gradle
- ios/App/App.xcodeproj/project.pbxproj
- resources/package.json
- src/main/frontend/version.cljs
> chore(release): bump version 0.9.0

- src/main/frontend/components/page_menu.cljs
- src/main/frontend/handler/page.cljs
- src/main/frontend/util/page.cljs
> fix(fs): open dir with default app

- android/app/build.gradle
- ios/App/App.xcodeproj/project.pbxproj
- resources/package.json
- src/main/frontend/version.cljs
This will be an emergency bug-fix release.
> chore: release 0.9.1

- src/main/frontend/components/header.cljs
- src/main/frontend/components/plugins.cljs
- src/main/frontend/components/plugins.css
- src/main/frontend/components/right_sidebar.cljs
- src/main/frontend/handler/ui.cljs
https://user-images.githubusercontent.com/1779837/228718800-19639815-9913-4b71-be98-0b77b48a7d59.mp4
https://user-images.githubusercontent.com/1779837/228718981-1b89b9a0-ffef-45a0-ae80-ffabd2d88257.mp4
> Enhance(UI): dynamic layout of the plugin UI items from the app toolbar

- src/main/frontend/pubsub.cljc
add the missing :get-remote-all-files-failed event schema
> fix(sync): add missing sync event schema

- src/main/electron/listener.cljs
- src/main/frontend/db/model.cljs
- tldraw/apps/tldraw-logseq/src/styles.css
- tldraw/packages/core/src/lib/tools/TLSelectTool/states/PointingMinimapState.ts
- tldraw/packages/react/src/components/BacklinksCountContainer/BacklinksCountContainer.tsx
- tldraw/packages/react/src/hooks/useCanvasEvents.ts
- Stop keyboard propagation on backlinks (resolves https://github.com/logseq/logseq/issues/8923)
- Don't remove orphaned whiteboards (resolves https://github.com/logseq/logseq/issues/8957)
- Check if clientX exists on event (should eliminate some sentry errors)
- Fix whiteboards block url handler (see https://discord.com/channels/725182569297215569/1001746361303187466/1091013741283389561 to reproduce this)
- Disable breadcrumb wrapping on portal header
> Fix (Whiteboard): Various issues

- src/main/frontend/components/block.cljs
- src/main/frontend/components/whiteboard.cljs
- src/main/frontend/db.cljs
- src/main/frontend/db/model.cljs
- src/main/frontend/db/query_dsl.cljs
- src/main/logseq/api.cljs
> fix: disable reactive queries in api

- src/main/frontend/mobile/index.css
> fix(ui): incorrect position of mobile bar

- docs/contributing-to-translations.md
- Update table with progress
- Add command to improve workflow
- Minor improvements
> Improve contributing-to-translations doc

- deps/db/src/logseq/db/rules.cljc
> fix: query searching for two or more properties is extremely slow

- .gitignore
> chore: remove duplicated item

- resources/package.json
- static/yarn.lock
> chore(deps): update rsapi, refine certs check

- android/app/build.gradle
- ios/App/App.xcodeproj/project.pbxproj
- resources/package.json
- src/main/frontend/fs/sync.cljs
- src/main/frontend/util/fs.cljs
- src/main/frontend/version.cljs
- static/yarn.lock
> Chore: bump version 0.9.3

- src/main/frontend/extensions/pdf/assets.cljs
- src/main/frontend/fs.cljs
> fix(fs): image renaming op when resizing pdf hl area

- src/main/frontend/components/block.cljs
- src/main/frontend/components/journal.cljs
- src/main/frontend/components/query.cljs
- src/main/frontend/components/scheduled_deadlines.cljs
- src/main/frontend/db/react.cljs
- src/main/frontend/db_mixins.cljs
- src/main/frontend/ui.cljs
Close #9132
Also, enable lazy loading on mobile
> fix: lazy loading shakes

- src/main/frontend/components/block.cljs
> Fix: no collapse control on collapsed query block for mobile

- android/app/build.gradle
- ios/App/App.xcodeproj/project.pbxproj
- resources/package.json
- src/main/frontend/version.cljs
This will be an emergency bug fix release mainly for mobile platforms.
Pending fix: #9214
> chore(release): bump version 0.9.4

- src/main/frontend/components/container.cljs
- src/main/frontend/components/find_in_page.cljs
Resolves https://github.com/logseq/logseq/issues/9217
Also see https://discord.com/channels/725182569297215569/775936939638652948/1099055069485355088
> Fix: Search in page position

- src/main/frontend/components/plugins.cljs
https://user-images.githubusercontent.com/1779837/233938292-a1c933f7-b0a8-46ae-a28b-c97adc382588.mp4
> enhance(ux): keep the item position from the installed plugins list when toggling enable/disable button

- deps/common/src/logseq/common/path.cljs
- deps/common/test/logseq/common/path_test.cljs
- deps/graph-parser/src/logseq/graph_parser/util.cljs
- src/main/frontend/components/block.cljs
> fix(editor): handle protocol urls including email ones

- .clj-kondo/config.edn
- src/main/frontend/components/content.cljs
- src/main/frontend/components/query.cljs
- src/main/frontend/components/query_table.cljs
- src/main/frontend/extensions/pdf/assets.cljs
- src/main/frontend/extensions/srs.cljs
- src/main/frontend/fs/watcher_handler.cljs
- src/main/frontend/handler/dnd.cljs
- src/main/frontend/handler/editor.cljs
- src/main/frontend/handler/editor/property.cljs
- src/main/logseq/api.cljs
This PR addresses a tech debt item noticed at https://github.com/logseq/logseq/pull/9235#discussion_r1180621066. https://github.com/logseq/logseq/pull/9235 needs to be merged before this PR. This was a mechanical refactor as I didn't touch any logic of the moved fns
> Chore: Organize property related fns for the editor

- src/main/frontend/modules/outliner/core.cljs
- src/test/frontend/modules/outliner/core_test.cljs
This PR fixes #8627, #7720 and #8282 by removing page aliases and tags when a user deletes them. There is also another bug fix where a page's `:block/properties-text-values` weren't being updated when properties changed. I also added a test for orphaned page refs since there weren't any for it
> Fix: Page tags and aliases should be deleted when deleted by user

- src/main/frontend/components/datetime.cljs
> fix: adjust repeater ui

- src/main/frontend/handler/editor.cljs
- tldraw/apps/tldraw-logseq/src/components/inputs/SelectInput.tsx
-  Prevent delete selection on edit mode (resolves #9337)
- Stop event propagation on select component (resolves #9326)
> Fix (Whiteboards): Keyboard shortcuts

- src/main/frontend/handler/export/text.cljs
see also: https://github.com/logseq/logseq/issues/8971#issuecomment-1539587342
> fix(export): export table err when empty table-header

- src/main/frontend/util/text.cljs
To reprodue:
- create a graph with name `f%2@1`
> fix(fs): handle graph name with percent symbol on mobile

- e2e-tests/basic.spec.ts
- e2e-tests/fixtures.ts
- src/main/frontend/modules/outliner/core.cljs
- src/main/frontend/modules/outliner/datascript.cljc
- src/main/logseq/api.cljs
Reproduce:
https://github.com/logseq/logseq/assets/479169/8570f0ba-f667-4008-a846-4bfbff5483f2
> fix: can't insert template

- src/main/frontend/dicts.cljc
Hi,
I've added small pending translations for pt-BR
> chore: added missing translations for pt-BR

- src/main/logseq/api.cljs
- src/main/logseq/api/block.cljs
- src/test/frontend/fs_test.cljs
- src/test/frontend/handler/plugin_config_test.cljs
- src/test/frontend/test/helper.cljs
- src/test/frontend/test/node_helper.cljs
- src/test/logseq/api_test.cljs
> fix: api get current block

- src/main/frontend/components/block.cljs
- src/main/frontend/components/block.css
- src/main/frontend/handler/editor.cljs
> Fix: ordered list minor style tweaks

- src/main/frontend/components/block.css
> Fix/mobile UI tweaks

- src/main/frontend/handler/export/opml.cljs
add title when page opml exporting, for blocks exporting, title = "untitled"
> enhance(export): add title when page opml-export

- src/main/frontend/dicts/it.cljc
Fixed Italian translation error. "Svilupppa" to "Sviluppa"
> FIX: Update it.cljc - Italian translation error 

- android/app/src/main/java/com/logseq/app/FsWatcher.java
- src/main/frontend/fs/sync.cljs
> fix(android): apply url decode before fs watcher notifies

- package.json
- yarn.lock
> Revert "chore(deps): bump posthog-js from 1.10.2 to 1.57.2"

- src/main/frontend/extensions/pdf/core.cljs
> Fix: resizing of pdf area highlight

- src/main/frontend/components/block.cljs
- aim to fix https://github.com/pengx17/logseq-plugin-bullet-threading/issues/17
> enhance(ui): add more semantic class to the order-list block element

- ios/App/App/FsWatcher.swift
Cherry-pick from #9238
- iOS rel path has a`/private` prefix
- Logseq didn't use the `/private` prefix
> fix(ios): watcher rel path handling

- src/main/frontend/handler/code.cljs
https://github.com/logseq/logseq/assets/1779837/a0a591fa-3ac2-4da2-b427-cbb08ee69bc0
Mentioned https://discord.com/channels/806040386614853642/841675547523678218/1115109877044494368
> fix(editor): incorrect behavior for the code editor of file page

- src/main/frontend/components/block.cljs
- src/main/frontend/util/property.cljs
- src/test/frontend/util/property_test.cljs
Fixes hidden editable block properties showing up when a user property is present e.g. https://github.com/logseq/logseq/issues/9489#issuecomment-1590974141. Also tested visible properties since the logic is getting complicated. To QA, try:
```
|New tables style| with CRIMSON accent|
| woo | hoo |
logseq.table.version:: 2
logseq.color:: crimson
woot:: yeehaw
```
> Fix: Hidden editable block properties showing up when user properties present

- src/main/frontend/components/settings.cljs
> fix(ui): position of tooltip icon in setting ui

- src/main/frontend/components/repo.cljs
- src/main/frontend/components/select.cljs
- src/main/frontend/util/text.cljs
Fix #9683
Fix usage of `get-graph-name-from-path`
> fix(ui): revise graph name dropdown

- src/main/frontend/components/page.cljs
- src/main/frontend/handler/editor.cljs
Resolves https://github.com/logseq/logseq/issues/9781
Resolves https://github.com/logseq/logseq/issues/9783
Please read the mentioned issues to reproduce.
> Fix (Whiteboard): Blur on empty title and select all on shape labels

- src/main/frontend/handler/plugin.cljs
fix https://github.com/logseq/marketplace/pull/420#issuecomment-1630194028
> fix(plugin): hook fenced code renderer for multiple providers

- docs/docker-web-app-guide.md
This is a security issue reported by Erno Kuusela.
> Add note about unsafe exposed port for dockker commands

- src/main/frontend/handler.cljs
- src/main/frontend/ui.cljs
fix: dev warnings from react about missing keys
Fix #9872
> fix(ui): close context menu when page navs

- src/main/frontend/handler/file_sync.cljs
- src/main/frontend/util/fs.cljs
Bug: Page history on Android is not working. It complains about cannot open the directory.
> fix(sync): page history on mobile platforms

- src/main/frontend/components/file.cljs
> fix(fs): editing global config on windows

- src/main/frontend/components/svg.cljs
- src/main/frontend/extensions/zotero.cljs
- src/main/frontend/extensions/zotero.css
- src/main/frontend/ui.cljs
> enhance(zotero): polish UI details of the zotero search component

- src/main/frontend/extensions/pdf/core.cljs
Close #10033
Help Wanted:
- How to set a callback for the modal's close button? (in order to cancel opening pdf)
> enhance(pdf): pdf password support

- src/main/frontend/components/container.css
- src/main/frontend/components/right_sidebar.cljs
- src/main/frontend/components/right_sidebar.css
Resolves #10066
Should also resolve https://discord.com/channels/725182569297215569/802530020605820949/1142308014251049081
> Fix: Disable sidebar pane content scrolling

- src/main/frontend/components/block.cljs
- src/main/frontend/components/query_table.cljs
- src/main/logseq/api/block.cljs
> Enhance/plugin APIs x

- src/main/frontend/extensions/pdf/core.cljs
> fix(pdf): incorrect path of pdfjs cmaps resources

- .github/workflows/build.yml
- deps/shui/src/logseq/shui/context.cljs
- docs/develop-logseq-on-mobile.md
- scripts/src/logseq/tasks/lang.clj
- src/main/frontend/common.css
- src/main/frontend/components/conversion.cljs
- src/main/frontend/fs/capacitor_fs.cljs
- src/main/frontend/handler/page.cljs
- src/main/frontend/util/keycode.cljs
- typos.toml
1. upgrade typos in workflow to 1.16.8
2. fix existing typos
3. automatically format some cljs files
> ci: upgrade typos to 1.16.8

- package.json
- yarn.lock
> fix(ios): crash caused by capacitor saved call

- src/main/frontend/extensions/excalidraw.cljs
Resolves https://github.com/logseq/logseq/issues/7323
Resolves https://github.com/logseq/logseq/issues/3543
Resolves https://github.com/logseq/logseq/issues/7048
Resolves https://github.com/logseq/logseq/issues/5221
Resolves https://github.com/logseq/logseq/issues/3340
Resolves https://github.com/logseq/logseq/issues/9980
Please check the mentioned issues to QA.
> Fix (draw): Focus container on click

- src/main/frontend/config.cljs
- src/main/frontend/fs/sync.cljs
- src/resources/dicts/en.edn
- src/resources/dicts/zh-cn.edn
test these 2 urls (GET method):
- s3: https://logseq-connectivity-testing-prod.s3.us-east-1.amazonaws.com/logseq-connectivity-testing
- API: https://api.logseq.com/logseq/version
this s3 obj is public & cache-control=no-cache
> enhance(sync): add connectivity-testing

- src/main/frontend/fs/sync.cljs
- src/main/frontend/handler/file_sync.cljs
- src/main/frontend/handler/user.cljs
1. dont clear-tokens when refresh-token failed
2. log invalid json when failing to parse api json body. Usually, it's returned by a firewall (e.g. a XML)
3. handle exceptions carefully in frontend.fs.sync
4. update avoid reentrancy related code
> Enhance(sync): serveral enhancements in sync

- docs/Build LogSeq Desktop for windows on Ubuntu.md
- docs/accessibility.md
- docs/contributing-to-translations.md
- src/resources/tutorials/tutorial-fr.md
> fix(docs): typos

- src/main/frontend/fs/sync.cljs
> fix(sync): missing cross-origin handling for conn check

- src/electron/electron/handler.cljs
- src/electron/electron/window.cljs
- src/main/frontend/components/theme.cljs
Reverts logseq/logseq#10049
See-also #10162
CC @sprocketc
> Revert "Enhance (UX): Electron loading"

- src/main/frontend/fs/sync.cljs
- src/main/frontend/handler/user.cljs
> fix(sync): avoid check connectivity for non-sync graph

- src/main/frontend/components/block.cljs
> fix: bilibili autoplay

- src/main/frontend/ui.cljs
- reproduced plugin: https://github.com/logseq/logseq-plugin-samples/blob/master/logseq-a-translator/index.ts#L13
- related PR: https://github.com/logseq/logseq/pull/10113
> fix(plugin): incorrect mouse point payload for the plugin hook of the editor input selection

- src/main/frontend/config.cljs
> fix(mobile): incorrect asset resource path for custom css

- src/main/frontend/extensions/pdf/core.cljs
To resolve #10235.
This is just a preliminary fix by debouncing the heavy call and make it less frequently called (4s should be already enough safe while 100ms is too frequent from my point of view).
To further address the problem, I think we can:
1. Separate the storage of current page number and highlights. So frequent changes in page number during scrolling won't trigger repeated saving of highlights.
2. Optimize performance of the serialization of highlights data. The file writing is async and won't hang the application; while the serialization seems happened on the render thread of Electron.
I'm not familiar with Clojure so please correct me if I did something wrong ;)
> fix(pdf): too frequent highlights saving

- src/main/frontend/components/editor.cljs
https://github.com/logseq/logseq/assets/1779837/4de8e190-1c57-43df-9bc5-bd8175592312
https://github.com/logseq/logseq/assets/1779837/b5b1e40d-c99f-4b92-8338-095e43bf7d5c
> fix(ui): incorrect auto-complete modal position for overflow editor content input

- externs.js
- src/electron/electron/utils.js
Related API call for the production bundle:
> fix(apis): incorrect api call for the electron production bundle

- src/main/frontend/modules/shortcut/config.cljs
Resolves https://github.com/logseq/logseq/issues/10176#issuecomment-1751549748
> Fix: Close window while editing

- src/main/frontend/extensions/pdf/assets.cljs
- src/main/frontend/extensions/pdf/core.cljs
https://github.com/logseq/logseq/assets/1779837/69fc382e-38fe-4db0-b014-3c7dfd503e0c
> fix(pdf): missing the initial ref highlight block sometimes

- src/electron/electron/search.cljs
fix #10267
bypass error, or else app won't start
> fix(electron): bypass corrupted sqlite search index

- .github/workflows/build-stage.yml
See-also: https://github.com/logseq/logseq/discussions/10340#discussioncomment-7344370
> ci: deploy web app when release

- src/main/frontend/extensions/srs.cljs
- src/main/frontend/util/block_content.cljs
- src/main/frontend/util/property.cljs
https://github.com/logseq/logseq/issues/9380
**Fix demo**
> fix: issue-9380 - #card should only be appended to the title

- src/main/frontend/components/search.cljs
- src/main/frontend/date.cljs
- src/main/frontend/modules/file/core.cljs
> Fix journal name judgement

- package.json
- resources/package.json
- static/yarn.lock
- yarn.lock
- Close #10413 
- Lock node-abi
> chore(deps): upgrade electron v26

- package.json
- resources/package.json
- static/yarn.lock
- yarn.lock
- Close #10436
- Related https://github.com/electron/electron/issues/39515
> fix(linux): downgrade electron to v25

- package.json
- resources/package.json
- static/yarn.lock
- yarn.lock
- Refine Network access
- Use global tokio runtime for JNI(Android)
> chore(deps): update rsapi

- android/app/src/main/AndroidManifest.xml
- Fix #10406
- Reorder xml, avoid IDE warning
Ref: https://stackoverflow.com/questions/31032042/android-get-restarted-once-it-is-connected-or-disconnected-to-bluetooth-device
> fix(android): activity restart when bluetooth kbd connected

- android/app/build.gradle
- resources/forge.config.js
- resources/package.json
- src/main/frontend/version.cljs
This will be a minor bug-fix release.
- #10404 
Changes Since Latest tag: 0.9.19
- feat(pdf): add toggle option for the feature of auto opening the highlight context menu from new text selection [#10390](https://github.com/logseq/logseq/pull/10390)
- Fix android back button closing order [#10345](https://github.com/logseq/logseq/pull/10345)
- Fix: drag and drop of assets, not being about to save assets sometimes [#10351](https://github.com/logseq/logseq/pull/10351)
- Enhance / shortcuts [#10290](https://github.com/logseq/logseq/pull/10290)
- enhance(ux): disable keymap settings for the mobile [#10380](https://github.com/logseq/logseq/pull/10380)
- Update Norwegian translations [#10361](https://github.com/logseq/logseq/pull/10361)
> chore(release): bump version 0.9.20

- resources/package.json
- static/yarn.lock
See-also: https://discuss.logseq.com/t/sync-privacy-and-tencent-servers/22885
> chore(deps): upgrade rsapi, rm doh

- src/main/frontend/ui.cljs
> fix: send parameters to ui/button :button-props

- src/main/frontend/fs/watcher_handler.cljs
- src/main/frontend/state.cljs
- src/main/frontend/util.cljc
- dedupe contents to sync-to-file channel
- batch-set-block-property! for set-missing-block-ids!
> Fix: too many same page sync-to-file

- src/main/frontend/config.cljs
- src/main/frontend/fs/memory_fs.cljs
See-also: https://github.com/isomorphic-git/lightning-fs/blob/9eb71923ed02a2f23d81194feb9e99ef713f5f1b/index.d.ts#L272
> fix(fs): impl mkdir-recur! for memory-fs

- src/main/frontend/components/cmdk.cljs
To reproduce:
1. create a new page "Foo"
2. add `alias:: [[A]]` to page Foo
3. cmd+k to search A 
Notice that A doesn't redirect to its source page "Foo".
QA:
1. Enter to redirect to the source page
2. Shift + Enter to open the source page in the right sidebar.
> fix: redirect to alias if possible

- deps/common/src/logseq/common/path.cljs
- deps/common/test/logseq/common/path_test.cljs
- resources/js/preload.js
- src/electron/electron/core.cljs
- src/electron/electron/handler.cljs
- src/electron/electron/utils.cljs
- src/main/frontend/components/block.cljs
- src/main/frontend/components/page_menu.cljs
- src/main/frontend/handler/assets.cljs
- src/main/frontend/handler/editor.cljs
- src/main/frontend/handler/page.cljs
- Close #10491
- Close #10003
- Close #8985
- Close #9349
- Close #9135
See-also: https://github.com/electron/electron/issues/38540
> Fix fs path handling: open file in folder, open backup folder, Windows UNC path support

- deps/publishing/src/logseq/publishing.cljs
- scripts/src/logseq/tasks/dev/publishing.cljs
- src/main/frontend/components/settings.cljs
- src/main/frontend/publishing.cljs
This option allows our publish-spa CLI and github action to set the color accent
> enhance: Add color option to publishing app

- src/main/frontend/handler/editor.cljs
- src/main/frontend/search.cljs
> fix: increase the default search length

- src/main/frontend/colors.cljs
> fix(ui): incorrect node edges color for the global graph view #10578

- src/main/frontend/common.css
- src/main/frontend/components/container.css
- fix: https://github.com/logseq/logseq/issues/10572
> fix(ui): incorrect background color for the left sidebar on mobile

- e2e-tests/page-search.spec.ts
- src/main/frontend/components/cmdk.cljs
- src/main/frontend/handler/recent.cljs
- Fix #10615
- Fix e2e test fail
> Fix: Do not add block UUID to recent

- deps/shui/src/logseq/shui/button/v2.cljs
- deps/shui/src/logseq/shui/shortcut/v1.cljs
- resources/css/shui.css
- src/main/frontend/components/cmdk.cljs
- src/main/frontend/components/shortcut.cljs
- src/main/frontend/modules/shortcut/data_helper.cljs
- Fixes https://github.com/logseq/logseq/issues/10583 
- simplify the implementation of shui/shortcut
> fix: cross-platform shotcuts

- src/main/frontend/components/cmdk.cljs
- src/main/frontend/db/model.cljs
> feat: add whiteboards to search filters

- src/main/frontend/colors.cljs
- src/main/frontend/components/settings.cljs
- src/main/frontend/components/settings.css
- src/main/frontend/components/shortcut.cljs
> fix(ui): theme color related issues

- deps/common/src/logseq/common/graph.cljs
- src/main/frontend/components/cmdk.cljs
- src/main/frontend/fs/watcher_handler.cljs
- Fixes #10609
- Fixes #10610
- Fixes #10611
- Fixes #10614
> fix more new search issues

- src/main/frontend/components/cmdk.cljs
- src/main/frontend/handler/editor.cljs
- src/main/frontend/util.cljc
> fix(ui): incorrect IME composition detection

- src/main/frontend/components/cmdk.cljs
Close #10658
Bug: :current-page search is not implemented.
> fix(cmdk): missing current-page search impl

- src/main/frontend/state.cljs
- src/main/frontend/util.cljc
> fix(android): sync navbar and actionbar color when theme change

- src/resources/dicts/zh-cn.edn
- src/resources/dicts/zh-hant.edn
Add missing zh-cn/zh-hant translations
> Add missing zh translations

- src/main/frontend/components/cmdk.cljs
> fix: add back full page content search

- .github/workflows/build-desktop-release.yml
- resources/forge.config.js
- resources/package.json
- static/yarn.lock
- Use asar for resource packaging (reduce file count)
- Add Windows .zip release for portable App
> Enhance: Release .zip build for windows

- src/resources/dicts/fr.edn
> enhance: Update French translations

- src/electron/electron/handler.cljs
- src/main/frontend/extensions/pdf/windows.cljs
> fix(pdf): set up initial listeners for the pdf viewer inside system window

- resources/forge.config.js
- resources/package.json
- static/yarn.lock
> fix: do not use asar

- android/app/build.gradle
- ios/App/App.xcodeproj/project.pbxproj
- resources/forge.config.js
- resources/package.json
- src/main/frontend/version.cljs
This is a bug-fix release to address #10744
> chore(release): bump version 0.10.3

- e2e-tests/basic.spec.ts
Fix e2e tests, which blocks nightly release.
> fix(e2e): do not use css to test selection

- src/main/logseq/api.cljs
- related https://github.com/logseq/logseq/issues/10743
> fix(api): missing git sdk

- deps/graph-parser/src/logseq/graph_parser.cljs
- deps/graph-parser/src/logseq/graph_parser/block.cljs
- src/main/frontend/components/imports.cljs
- src/main/frontend/handler/repo.cljs
Tracker https://linear.app/logseq/issue/LOG-2977/basic-file-based-graph-import
> Import from graph folder to db graph

- src/main/frontend/ui.css
> fix(ui): incorrect position for the filter modal on ios platform

- e2e-tests/basic.spec.ts
- e2e-tests/page-rename.spec.ts
- src/main/frontend/config.cljs
- Close #10792
- Fix some wrong usage in e2e tests
> fix(mobile): accept video as shared content

- src/main/frontend/components/query_table.cljs
> fix(query): cannot toggle updated-at and created-at

- docs/develop-logseq.md
@tiensonqin Some grammar fixes and typos. Also using GitHub builtin Tip markdown syntax:
> [!TIP]
> Tip body
> enhance: pipeline worker doc

- android/app/src/main/java/com/logseq/app/FsWatcher.java
Related
- Fix #10827
- Fix #10828
- Fix #10404
- ~~[ ] Guard against illegal android path~~
> fix(android/watcher): wrong relpath calculation

- .github/workflows/build-android.yml
See-also: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240107.1
> fix(ci): android build tools path

- tldraw/demo/package.json
- tldraw/yarn.lock
> chore: upgrade @swc/core (adds 16k pages support)

- android/app/build.gradle
- ios/App/App.xcodeproj/project.pbxproj
- resources/forge.config.js
- resources/package.json
- src/main/frontend/version.cljs
- #10536
- https://github.com/logseq/logseq/pull/10782
> chore(release): bump version 0.10.4

- android/app/build.gradle
- ios/App/App.xcodeproj/project.pbxproj
- resources/forge.config.js
- resources/package.json
- src/main/frontend/version.cljs
- Fix App Crash for https://github.com/logseq/logseq/issues/10868
> chore(release): bump version 0.10.5

- package.json
- yarn.lock
> chore(build): rm postcss version lock

- src/main/frontend/search/db.cljs
See-also: #10771
This PR is not a solution to the original bug, but a trade-off between accuracy and usability, with minimal modification.
For a random graph with 2000+ pages:
- Before: 60s+
- After: 8.4s
> fix(mobile): cold start performance of block search

- src/main/frontend/components/block.cljs
- src/main/frontend/extensions/video/youtube.cljs
> enhance(editor): support time offset of youtube links

- src/main/frontend/components/page.cljs
> fix(editor): wrong new page link handling in graph view

- src/main/frontend/components/page.cljs
- src/main/frontend/extensions/graph/pixi.cljs
- src/main/frontend/ui.cljs
- src/main/frontend/ui.css
This PR also adds a toggle for force simulation.
Related to #10755
> Enhance: trigger on-change for slider when mouse up instead of input value change

- android/app/build.gradle
- resources/forge.config.js
- resources/package.json
- src/main/frontend/version.cljs
- Fix outdent-then-delete removing incorrect block [#10790](https://github.com/logseq/logseq/pull/10790)
- fix: publishing app not building [#10911](https://github.com/logseq/logseq/pull/10911)
- fix: Simplify fn translations in light of #10868 [#10881](https://github.com/logseq/logseq/pull/10881)
- fix(android): sync crash caused by wrong logging [#10922](https://github.com/logseq/logseq/pull/10922)
- fix(mobile): cold start performance of block search [#10924](https://github.com/logseq/logseq/pull/10924)
- fix(mobile): commit composing text before cycle todo [#10921](https://github.com/logseq/logseq/pull/10921)
- Add ability to change graph forces via UI [#10755](https://github.com/logseq/logseq/pull/10755)
- Add toggle to stop/start force simulation …
> chore: Release 0.10.6

- packages/ui/src/vars-classic.css
- resources/css/shui.css
- src/main/frontend/components/cmdk.css
- src/main/frontend/components/container.cljs
- src/main/frontend/components/page.css
> Enhance(UI): accent color related details

- src/main/frontend/components/container.cljs
Fix #10979
Introduced in: https://github.com/logseq/logseq/pull/10986
> fix(config): wrong `:command/toggle-favorite` handling

- android/app/build.gradle
- resources/forge.config.js
- resources/package.json
- src/main/frontend/version.cljs
- https://github.com/logseq/logseq/pull/11030
- feature: new keybinding for "toggle expand/collapse this block" [#10980](https://github.com/logseq/logseq/pull/10980)
- Fix typo in mldoc package name [#10995](https://github.com/logseq/logseq/pull/10995)
- fix: add .heic to media type [#11017](https://github.com/logseq/logseq/pull/11017)
- fix(bug): Main scrollbar jumps #5961 (process once only) [#10037](https://github.com/logseq/logseq/pull/10037)
- fix(config): wrong `:command/toggle-favorite` handling [#10998](https://github.com/logseq/logseq/pull/10998)
- fix(ui): shorter heading for pwd input box [#11016](https://github.com/logseq/logseq/pull/11016)
- enhance: add partial Persian translation [#10938](https://github.com/logseq/logseq/pull/10938)
- Enhance: Android share/open asset file …
> chore(release): bump version 0.10.7

- src/main/frontend/ui.cljs
> fix(ux): support herf prop for the classical ui button component

- deps/graph-parser/src/logseq/graph_parser/exporter.cljs
- src/main/frontend/components/block.cljs
- src/main/frontend/config.cljs
- src/main/frontend/extensions/pdf/assets.cljs
- src/main/frontend/extensions/pdf/toolbar.cljs
- src/main/frontend/extensions/tldraw.cljs
- src/main/frontend/handler/assets.cljs
- src/main/frontend/handler/editor.cljs
- src/main/frontend/handler/ui.cljs
- src/main/logseq/sdk/assets.cljs
- move make-asset-url to assets-handler
- handle assets for db-based graph in add-style-if-exists!
> Fix(db) css asset loading

- .github/workflows/build-desktop-release.yml
- resources/forge.config.js
- resources/package.json
- static/yarn.lock
Fixes macOS release build.
Success build: https://github.com/logseq/logseq/actions/runs/8448687702
Related: https://github.com/logseq/electron-forge-maker-appimage/commit/4bf4d4eb5925f72945841bd2fa7148322bc44189
> Fix: macOS release build

- .github/workflows/build-desktop-release.yml
See-also: https://github.com/logseq/logseq/actions/runs/8533609313
> ci: self-hosted runner for codesign

- .github/stale-issues.yml
- .github/workflows/stale-issues.yml
- CONTRIBUTING.md
- src/main/frontend/components/container.cljs
- src/main/frontend/components/onboarding.cljs
> fix: feature request dead link

- .github/workflows/build-desktop-release.yml
Split artifacts, minimize download/upload
> ci(build): refine windows sign

- src/main/frontend/common.css
Cherry-pick feat/db branch.
Close #11123
> fix(ui): missing default colors for mark tag

- src/electron/electron/window.cljs
> fix(macos): windows restore at current workspace

- deps/shui/src/logseq/shui/list_item/v1.cljs
- src/main/frontend/components/cmdk.cljs
> enhance(ux): better highlights page name for the search result items

- deps/common/src/logseq/common/graph.cljs
> fix(sync): cannot delete some nested files

- e2e-tests/fixtures.ts
- e2e-tests/logseq-api.spec.ts
- e2e-tests/plugins.spec.ts
- e2e-tests/utils.ts
- package.json
- resources/package.json
- static/yarn.lock
- yarn.lock
> Update Electron 28

- src/main/frontend/mobile/util.cljs
> fix(ios): add new ipad resolutions

- src/resources/dicts/ko.edn
- ## Pull Request - Update Korean translation
- ### Details
- #### Add Korean translation
:command-palette/toggle                     "명령어 검색"  
:go/search-in-page                               "현재 페이지에서 블록 검색"  
- #### Fix Korean translation
fixes the typo from "디오" to "이동".  
- ### Files Changed
- `ko.edn` 
> Update Korean translation

- tldraw/apps/tldraw-logseq/build.mjs
> Revert "fix tsup domain"

- src/main/frontend/components/user/login.cljs
- src/main/frontend/handler/events.cljs
**mentioned**: https://github.com/logseq/docs/issues/124
> fix(mobile): invalid keyboard input for the `create account` pane form

- src/main/frontend/util.cljc
I wanted to push a fix for this in the past, so I decided to take a shot. You can read more about this case [here](https://github.com/logseq/logseq/issues/9006#issuecomment-1494313541).
`copy-image-to-clipboard` is also used by the PDF extension, so this might resolve some additional issues.
Resolves #9006
Resolves #11405
> fix: copying non-png images from the image overlay toolbar

- deps/db/src/logseq/db/frontend/class.cljs
- deps/db/src/logseq/db/frontend/property.cljs
- deps/db/src/logseq/db/frontend/schema.cljs
- scripts/src/logseq/tasks/lang.clj
- src/main/frontend/commands.cljs
- src/main/frontend/components/block.cljs
- src/main/frontend/components/block.css
- src/main/frontend/components/container.cljs
- src/main/frontend/components/icon.cljs
- src/main/frontend/components/property/value.cljs
- src/main/frontend/components/query.cljs
- src/main/frontend/components/query/builder.cljs
- src/main/frontend/components/query/view.cljs
- src/main/frontend/components/query_table.cljs
- src/main/frontend/components/views.cljs
- src/main/frontend/handler.cljs
- src/main/frontend/handler/db_based/recent.cljs
- src/main/frontend/publishing.cljs
- src/main/frontend/worker/db/migrate.cljs
- src/resources/dicts/en.edn
- src/test/frontend/db/db_based_model_test.cljs
> refactor: query result with the new table view

- deps/db/src/logseq/db.cljs
- deps/db/src/logseq/db/frontend/property.cljs
- deps/db/src/logseq/db/frontend/schema.cljs
- src/main/frontend/components/objects.cljs
- src/main/frontend/components/views.cljs
- src/main/frontend/db/async.cljs
- src/main/frontend/worker/db/migrate.cljs
> Feature: tag multiple views

- deps/db/src/logseq/db.cljs
- deps/db/src/logseq/db/sqlite/common_db.cljs
- deps/db/src/logseq/db/sqlite/create_graph.cljs
- deps/db/src/logseq/db/sqlite/util.cljs
- src/main/frontend/components/block.cljs
- src/main/frontend/components/export.cljs
- src/main/frontend/handler/events.cljs
- src/main/frontend/handler/export.cljs
- src/main/frontend/worker/db/migrate.cljs
To test, go to "Export graph" and set up a folder to store the db backup.
Notice: exporting assets is not supported yet.
> feat: create a db backup every hour

- deps/db/src/logseq/db/frontend/property.cljs
- deps/db/src/logseq/db/frontend/schema.cljs
- deps/outliner/src/logseq/outliner/property.cljs
- src/main/frontend/commands.cljs
- src/main/frontend/common.css
- src/main/frontend/components/block.cljs
- src/main/frontend/components/property/value.cljs
- src/main/frontend/extensions/code.cljs
- src/main/frontend/extensions/latex.cljs
- src/main/frontend/handler/code.cljs
- src/main/frontend/handler/editor.cljs
- src/main/frontend/worker/db/migrate.cljs
- src/main/frontend/worker/rtc/db_listener.cljs
> feat: code/quote/math block

- deps/db/src/logseq/db.cljs
- deps/db/src/logseq/db/frontend/entity_plus.cljc
- deps/shui/src/logseq/shui/table/core.cljc
- deps/shui/src/logseq/shui/table/impl.cljc
- src/main/frontend/components/all_pages.cljs
- src/main/frontend/components/views.cljs
1. cache :block/title calculation
2. sort rows if only sorting changed
3. use string/includes? instead of fuzzy search
> perf: table search

- src/main/frontend/common/missionary_util.clj
- src/main/frontend/common/missionary_util.cljs
- src/main/frontend/db/rtc/debug_ui.cljs
- src/main/frontend/worker/crypt.cljs
- src/main/frontend/worker/db_worker.cljs
- src/main/frontend/worker/device.cljs
- src/main/frontend/worker/rtc/client_op.cljs
- src/main/frontend/worker/rtc/const.cljs
- src/main/frontend/worker/rtc/core.cljs
- src/main/frontend/worker/rtc/crypt.cljs
- src/main/frontend/worker/rtc/full_upload_download_graph.cljs
- src/main/frontend/worker/rtc/ws_util.cljs
This PR is a part of the RTC encryption implementation.
- each rtc-graph has aes key, used for encrypting block-attrs
- each device has rsa public&private key pair, used for transferring graph aes-keys
this pr can be merged directly, it won't affect any features in the db-branch
> feat: crypt keys management

- externs.js
- src/main/frontend/components/block.cljs
- src/main/frontend/components/block.css
- src/main/frontend/components/property/value.cljs
- src/main/frontend/handler/editor.cljs
- src/main/frontend/ui.cljs
https://github.com/user-attachments/assets/7baaa6c1-7f75-4108-a10f-424c42085c57
> Enhance(ux): resize image

- resources/package.json
- static/yarn.lock
> chore(deps): upgrade electron stuff

- src/main/frontend/components/block.cljs
> frontend/block code: set ClojureScript as a Clojure language

- .clj-kondo/config.edn
- src/main/frontend/components/profiler.cljs
- src/main/frontend/components/right_sidebar.cljs
- src/main/frontend/handler/profiler.cljs
> feat: add profiler(dev) rightside-tab

- deps/db/src/logseq/db/frontend/class.cljs
- deps/db/src/logseq/db/frontend/property.cljs
- deps/db/src/logseq/db/frontend/schema.cljs
- deps/db/src/logseq/db/sqlite/create_graph.cljs
- deps/graph-parser/src/logseq/graph_parser/block.cljs
- deps/graph-parser/src/logseq/graph_parser/db.cljs
- deps/outliner/src/logseq/outliner/core.cljs
- deps/outliner/src/logseq/outliner/pipeline.cljs
- src/main/frontend/commands.cljs
- src/main/frontend/components/block.cljs
- src/main/frontend/components/editor.cljs
- src/main/frontend/components/property/value.cljs
- src/main/frontend/components/views.cljs
- src/main/frontend/db/model.cljs
- src/main/frontend/handler/common/page.cljs
- src/main/frontend/handler/editor.cljs
- src/main/frontend/search.cljs
- src/main/frontend/worker/db/migrate.cljs
- src/main/frontend/worker/pipeline.cljs
- src/test/frontend/modules/outliner/core_test.cljs
This PR brings back text templates and applies templates on tags automatically.
Demo:
https://www.loom.com/share/f9c1841c13484f1c949a46d93aca6177
> feat: text template && auto-apply templates on tags

- .clj-kondo/config.edn
- deps/graph-parser/src/logseq/graph_parser.cljs
- src/main/electron/listener.cljs
- src/main/frontend/components/block.cljs
- src/main/frontend/components/file.cljs
- src/main/frontend/components/file_based/hierarchy.cljs
- src/main/frontend/components/file_sync.cljs
- src/main/frontend/components/query/builder.cljs
- src/main/frontend/db.cljs
- src/main/frontend/db/async.cljs
- src/main/frontend/db/file_based/model.cljs
- src/main/frontend/db/model.cljs
- src/main/frontend/db/query_custom.cljs
- src/main/frontend/db/query_dsl.cljs
- src/main/frontend/db/react.cljs
- src/main/frontend/fs/diff_merge.cljs
- src/main/frontend/fs/watcher_handler.cljs
- src/main/frontend/handler/editor.cljs
- src/main/frontend/handler/file_based/editor.cljs
- src/main/frontend/handler/file_based/file.cljs
- src/main/frontend/handler/file_based/page.cljs
- src/main/frontend/handler/file_based/page_property.cljs
- src/main/frontend/handler/file_based/repo.cljs
- src/main/frontend/handler/file_based/reset_file.cljs
- src/main/frontend/handler/repo.cljs
- src/main/logseq/api.cljs
- src/test/frontend/components/file_based/query_table_test.cljs
- src/test/frontend/db/file_based/model_test.cljs
- src/test/frontend/db/model_test.cljs
- src/test/frontend/db/query_dsl_test.cljs
Also removed some unused fns and frontend.db mappings. I did some QA of file graphs
> Refactor: mv file graph model fns to their own ns

- src/main/frontend/components/property/value.cljs
fixes https://test.logseq.com/#/page/683f58a0-6545-4b75-953d-875fda33dab5
> fix: node property value dropdown doesn't allow choosing existing values

- .clj-kondo/config.edn
- deps/graph-parser/src/logseq/graph_parser/test/docs_graph_helper.cljs
- deps/graph-parser/test/logseq/graph_parser/cli_test.cljs
- deps/graph-parser/test/logseq/graph_parser/exporter_test.cljs
- deps/graph-parser/test/logseq/graph_parser/mldoc_test.cljs
- src/test/frontend/handler/repo_test.cljs
Hadn't been updated in over a year
> chore: bump docs graph being tested

- clj-e2e/deps.edn
- clj-e2e/test/logseq/e2e/plugins_basic_test.clj
- deps/db/src/logseq/db/frontend/db_ident.cljc
- libs/src/LSPlugin.ts
- src/main/logseq/api.cljs
- src/main/logseq/api/block.cljs
- src/main/logseq/sdk/utils.cljs
related: https://github.com/logseq/db-test/issues/294
> enhance(plugins): block property related apis

- deps/db/src/logseq/db.cljs
- deps/db/src/logseq/db/frontend/class.cljs
- deps/db/src/logseq/db/frontend/db.cljs
- deps/db/src/logseq/db/frontend/malli_schema.cljs
- deps/db/src/logseq/db/frontend/property.cljs
- deps/db/src/logseq/db/frontend/schema.cljs
- deps/db/src/logseq/db/sqlite/build.cljs
- deps/db/src/logseq/db/sqlite/export.cljs
- deps/db/test/logseq/db/sqlite/export_test.cljs
- deps/graph-parser/test/logseq/graph_parser/exporter_test.cljs
- deps/outliner/src/logseq/outliner/property.cljs
- deps/outliner/src/logseq/outliner/validate.cljs
- deps/outliner/test/logseq/outliner/property_test.cljs
- deps/outliner/test/logseq/outliner/validate_test.cljs
- scripts/src/logseq/tasks/db_graph/create_graph_with_schema_org.cljs
- src/main/frontend/components/property/value.cljs
- src/main/frontend/worker/db/migrate.cljs
- src/test/frontend/db/query_dsl_test.cljs
- src/test/frontend/worker/handler/page/db_based/page_test.cljs
> enhance: extends support multiple tags

- src/main/frontend/components/page.cljs
- src/main/frontend/components/page.css
- src/main/frontend/handler/common/page.cljs
- src/main/frontend/handler/editor.cljs
- src/main/frontend/state.cljs
https://github.com/user-attachments/assets/e46b790a-c7ff-4ff4-9f1e-2a9eceaae525
https://github.com/user-attachments/assets/9182eab3-d61a-4666-8e76-fac7420dec4b
> enhance(ux): blocks selection with up/down key

- clj-e2e/test/logseq/e2e/outliner_basic_test.clj
- deps/outliner/src/logseq/outliner/core.cljs
fixes https://github.com/logseq/db-test/issues/361
> fix: indentation after an embeded node

- src/main/frontend/components/svg.cljs
- src/main/frontend/extensions/pdf/core.cljs
- src/main/frontend/extensions/pdf/toolbar.cljs
- src/main/frontend/extensions/pdf/utils.cljs
enhance: enhance PDF reading experience.
> enhance: enhance PDF reading experience.

- scripts/install-linux.sh
- Fix broken installation with --user option
- Fix desktop icon link when in --user mode
- Add uninstall command (only installation, not user's data)
- Closes #12148
> fix: Fix install-linux.sh and add uninstall option
