src/main/frontend/components/file_sync.cljs, src/main/frontend/handler/file_sync.cljs
This can result in app crash when clicking the icon multiple times.
=> fix: clicking sync icon restarts the file sync

src/main/frontend/components/file_sync.cljs, src/main/frontend/fs/sync.cljs, src/main/frontend/handler/events.cljs, src/main/frontend/handler/file_sync.cljs
Also, don't show `password is required` when starting the sync.
=> fix: disable creating remote graph when sync is not started yet

src/main/frontend/components/query_table.cljs, src/main/frontend/date.cljs, src/main/frontend/format/block.cljs, src/test/frontend/format/block_test.cljs
Fixes #6363 
The approach is to normalize the special formats such as 50% to 0.5 and then sort them with existing functionality. This allows interoperability ex. percentages with integers.
There are probably many more possible formats but I couldn't find a list of formats to support.
=> fix: Date sorting is nonsensical #6363 

src/main/frontend/components/sidebar.css
Increase the width of the closed sidebar instead of setting a negative left position
on the resizer.
Resolves https://github.com/logseq/logseq/issues/6770
=> Fix: Resizer position

tldraw/apps/tldraw-logseq/src/hooks/usePaste.ts
When we drag and drop a selected area, we should probably use the `text/plain` data type by default. `tryCreateShapeFromIframeString` would automatically create an iframe if we drag a link (or a youtube video), and it would also filter out unneeded info. The downside is that some of the information that is only available on `text/html` might be useful (e.g. anchor elements).
[2022-09-19 12-10-40.webm](https://user-images.githubusercontent.com/10744960/190992397-bed36fc7-0db6-44ba-9ef9-78ea78ca1447.webm)
=> Prefer text type on dnd

src/main/frontend/dicts.cljc
"Refresh detects and processes files modified on your disk and diverged from the actual Logseq page content. Continue?" to
"Refresh detects and processes files modified on your disk that have diverged from the current Logseq page content. Continue?"
=> issue #6782- changed message typo 

.github/workflows/db.yml, .github/workflows/graph-parser.yml, deps/db/bb.edn, deps/db/src/logseq/db.cljs, deps/db/src/logseq/db/default.cljs, deps/db/src/logseq/db/schema.cljs, deps/graph-parser/bb.edn, deps/graph-parser/src/logseq/graph_parser.cljs, deps/graph-parser/src/logseq/graph_parser/block.cljs, deps/graph-parser/src/logseq/graph_parser/config.cljs, deps/graph-parser/src/logseq/graph_parser/extract.cljc, deps/graph-parser/src/logseq/graph_parser/log.cljs, deps/graph-parser/src/logseq/graph_parser/mldoc.cljc, deps/graph-parser/src/logseq/graph_parser/property.cljs, deps/graph-parser/src/logseq/graph_parser/text.cljs, deps/graph-parser/src/logseq/graph_parser/utf8.cljs, deps/graph-parser/src/logseq/graph_parser/util/block_ref.cljs, deps/graph-parser/src/logseq/graph_parser/util/page_ref.cljs, docs/dev-practices.md
As part of [this task](https://quire.io/w/Logseq-_team_dedicated_to_sport_of_knowledge/164/Document_namespaces?sublist=Cycle_13_End_2022-09-16&view=board), this adds [a linter for documenting namespaces](https://github.com/logseq/bb-tasks/blob/main/src/logseq/bb_tasks/lint/ns_docstrings.clj) to our deps/ . If this linter seems reasonable, I'd like to add this to the logseq frontend next. For the frontend, we could ignore namespaces like components as it wouldn't be that helpful to just repeat a namespace e.g. for `frontend.components.onboarding` - "Onboarding fns"
=> Dev: Add linter to deps to document namespaces 

src/electron/electron/core.cljs, src/electron/electron/window.cljs
On https://github.com/logseq/logseq/pull/6617 we introduced a way to persist the zoom level when we navigate.
It also makes sense to persist the zoom level when we close the app, and restore it when we reopen logseq.
Resolves https://github.com/logseq/logseq/issues/6719
**Notes for reviewers**
- There are two `on window close` event handlers, one for the main and one for non-main windows. We persist the zoom level on main. I am not sure if there is a reason to add this to the other handler as well. Ideally, we would like to hook on something like [zoom-changed](https://www.electronjs.org/docs/latest/api/web-contents#event-zoom-changed), but this is triggered exclusively when we use the mouse wheel.
- I tried using `did-finish-load`, `dom-ready` and some other related events to restore the …
=> Fix: Persist zoom level on app close

shadow-cljs.edn
CC @kanru 
The current Flatpak build didn't set `ENABLE_FILE_SYNC_PRODUCTION` as `true`.
So the App will use file-sync development environment as default.
This PR set production environment as default. eliminate the need of setting `ENABLE_FILE_SYNC_PRODUCTION`
Changes for Developers:
When doing local development on file-sync, you might need to set 
`ENABLE_FILE_SYNC_PRODUCTION=false`
=> chore(build): file-sync production env as default

deps/db/src/logseq/db/schema.cljs, deps/graph-parser/src/logseq/graph_parser/block.cljs, deps/graph-parser/src/logseq/graph_parser/test/docs_graph_helper.cljs, src/main/frontend/commands.cljs, src/main/frontend/components/block.cljs, src/main/frontend/components/content.cljs, src/main/frontend/components/editor.cljs, src/main/frontend/db/model.cljs, src/main/frontend/dicts.cljc, src/main/frontend/handler/editor.cljs, src/main/frontend/handler/events.cljs, src/main/frontend/handler/export.cljs, src/main/frontend/mobile/action_bar.cljs, src/main/frontend/modules/file/core.cljs, src/main/frontend/ui.css
This PR unifies the UX to set and clear headings for Markdown and Org modes.
For org mode, a heading block will have a `:heading` property whose value ranges from 1 to 6 (h1 ~ h6).
Demo: https://www.loom.com/share/ae5a8cbb5c2c43979b9be518f687c433
=> refactor: unify heading UX for both markdown and org mode

src/main/frontend/components/content.cljs
I think that with Flashcards disabled the user shouldn't see the option to convert a block to a card. This PR hides this menu item when flashcards are disabled in settings.
=> Fix: Don't show 'Make a flashcard' menu item with flashcards disabled

src/main/frontend/components/file_sync.cljs, src/main/frontend/fs/sync.cljs, src/main/frontend/handler/events.cljs, src/main/frontend/state.cljs
This can avoid running multiple downloads/uploads at the same time.
=> fix: cancel previous requests when sync needs to download/upload

src/main/frontend/handler/editor.cljs
Introduced in ClojureScript upgrade. parse-long fails when `nil` passed.
=> fix(android): key code nil sometimes

src/main/frontend/util.cljc
While activating/deactivating/editing a block, we are calling `util/scroll-editor-cursor` which calculates and sets the `scrollTop` of  `#main-content-container`. The problem is that we might be editing a block within the sidebar. To fix this, we can pass the editing element ref to `app-scroll-container-node` and check if `#main-content-container` is a parent element using [closest](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest). If not, the scrolling parent should be the `.sidebar-item-list`.
**To consistently reproduce the issue, you need to edit a bock at the bottom of the right sidebar and have a long scrollable  page loaded on the main container.**
Resolves https://github.com/logseq/logseq/issues/6470
=> Fix: Container scrolling on sidebar editing

src/electron/electron/file_sync_rsapi.cljs
Reverts logseq/logseq#6868
After checking all the dependencies and DLLs.
This might be a regression in the Rust compiler or Github Actions Runner.
Somehow vcruntime140 is not static-linked to libs.
Revert this. The original bug will be fixed by updating rsapi.
=> Revert "fix(build): windows7 compatibility"

resources/package.json
Fix https://github.com/logseq/logseq/issues/6756
Fix https://github.com/logseq/logseq/issues/6727
Fix https://github.com/logseq/logseq/issues/6698
Fix https://github.com/logseq/logseq/issues/5362
=> fix(windows): update rsapi, use static link

ios/App/App/Info.plist
Previously, the voice recorder would silently stop recording the moment that the phone locked.
Apple's documentation doesn't directly say this, but it looks like a prerequisite for recording background audio is enabling background audio playback: https://developer.apple.com/documentation/xcode/configuring-background-execution-modes
Fixes #6407 
cc @cnrpman
=> iOS: Continue recording audio when phone sleeps (Fixes #6407)

src/main/frontend/mobile/record.cljs
Fix #6871
ref: https://github.com/tchvu3/capacitor-voice-recorder/blob/master/android/src/main/java/com/tchvu3/capacitorvoicerecorder/VoiceRecorder.java
=> fix(mobile): use .m4a for mobile audio record

deps/graph-parser/src/logseq/graph_parser/extract.cljc, deps/graph-parser/src/logseq/graph_parser/util.cljs, deps/graph-parser/test/logseq/graph_parser_test.cljs, src/main/frontend/handler/common/file.cljs, src/main/frontend/handler/events.cljs, src/main/frontend/handler/file.cljs, src/main/frontend/handler/repo.cljs, src/main/frontend/modules/file/core.cljs, src/main/frontend/modules/outliner/file.cljs, src/main/frontend/ui.cljs
This PR fixed the issue that re-index can be stuck if there're multiple whiteboard pages that have the same UUID.
Some changes:
1. re-index will continue even if some files fail to parse or load to db.
2. all the errors will be notified when re-index is finished
3. for each error, users can either click the file path to fix it themselves, or click the `Fix` button to replace the UUID.
Demo: https://www.loom.com/share/148330aac0864c279707293a3a9d9baf
=> Fix: stuck re-index when there're multiple whiteboards have the same UUID

src/main/frontend/components/plugins_settings.cljs
https://user-images.githubusercontent.com/1779837/194833854-cf815ceb-bafe-4aef-b45a-df90d7f94f04.mp4
https://user-images.githubusercontent.com/1779837/194833894-410d00a2-78e0-4769-a867-a5f9b66326ba.mp4
=> fix(plugin): enter to break line not work for textarea settings item

src/main/frontend/components/block.cljs, src/main/frontend/handler/whiteboard.cljs, src/main/frontend/modules/shortcut/before.cljs, tldraw/apps/tldraw-logseq/src/hooks/usePaste.ts
=> fix(whiteboard): dnd missing uuid issue

deps/graph-parser/src/logseq/graph_parser/property.cljs, src/main/frontend/util/marker.cljs
Fixes #6902. Can see that the removed task properties weren't used in https://github.com/logseq/logseq/commit/b63aa2c03c7bf576c59d687b5370d7c89fabb730
=> Fix: Remove hidden task properties that weren't used 

src/main/frontend/fs/sync.cljs
1. avoid writing txid=nil to graphs-txid.edn
2. allow to sync-start when txid=nil
=> fix(sync): allow to sync-start when txid=nil(in graphs-txid.edn)

src/main/frontend/fs.cljs, src/main/frontend/fs/capacitor_fs.cljs, src/main/frontend/fs/sync.cljs, src/main/frontend/handler/events.cljs, src/main/frontend/handler/file_sync.cljs
Previously, the local file will not be added to local history if there was any conflict when syncing with the server, which can result in data-loss.
=> fix: add local conflicted versions on mobile

src/main/frontend/extensions/excalidraw.cljs
Grid mode status not correctly shown because of a small typo of `grid-mode`.
https://user-images.githubusercontent.com/28241963/195325910-fbdd1d51-e2aa-4258-8b76-7da8e50f5a52.mp4
https://user-images.githubusercontent.com/28241963/195325881-cecf5c9a-06dc-4642-b67d-ff1428d02c4d.mp4
=> fix(excalidraw): grid mode status not correctly shown

src/main/frontend/handler/editor.cljs
Resolves https://github.com/logseq/logseq/issues/6697
As stated on the original issue
> This doesn't happen on macOS (probably related to built-in event throttling differences). The frontend.state/editing? predicate returns false after 4-5 consequent events, because (gdom/getElement id) of get-input fails. Adding a custom 50ms throttle to the event seems to fix this, but I am not sure if that's the best approach.
I think trying to solve this by throttling the event is not great, and might lead to unexpected results. The root problem is that `state/editing?`should return `true`, but the dom element can't be selected yet. If `(state/get-edit-input-id)` is set but the element does not exist, we are on a transitioning state, so we simply do nothing. Calling `select-first-last` (which calls …
=> Fix: Up/down arrow navigation

shadow-cljs.edn, src/main/frontend/extensions/hickory.cljc, src/main/frontend/extensions/html_parser.cljs, src/main/frontend/handler/paste.cljs, src/test/frontend/extensions/zotero/extractor_test.cljs, src/test/frontend/handler/paste_test.cljs
This PR was to fix the pasting issue of writeboard (addressed in #7002 )
Now the paste issue fix is removed.
This PR now
1. **Enables test on `frontend.handler.paste`** which was blocked by the dependency on `hickory`, and provides some trivial tests in `src/test/frontend.handler.paste_test`
2. Recovers `src/test/frontend.extensions.zotero.extractor-test` which was also blocked previously.
=> test: enable Node-test on namespaces with dependency on hickory

src/main/frontend/components/command_palette.cljs, src/main/frontend/ui.cljs
This fixes the alignment of the shortcuts on our command palette. I also increased the opacity of namespace to make it readable.
=> Fix: shortcut alignment on command palette

deps/graph-parser/src/logseq/graph_parser/property.cljs, deps/graph-parser/test/logseq/graph_parser_test.cljs
Fixes bugs seen in #6753. This is consistent with https://github.com/logseq/logseq/commit/066496089fdd2f1c749909d2e552d780ce5cd416. Eventually we may want to share validation logic between property names and page names
=> Fix: Disallow tags as property names

.clj-kondo/config.edn, deps.edn, deps/db/deps.edn, deps/graph-parser/.clj-kondo/config.edn, deps/graph-parser/deps.edn, deps/graph-parser/test/logseq/graph_parser/nbb_test_runner.cljs, src/main/frontend/components/editor.cljs, src/main/frontend/components/shortcut.cljs, src/main/frontend/rum.cljs, src/main/frontend/util.cljc, src/main/frontend/util/persist_var.cljs
- Bump clj-kondo as it has added a couple new linters and fixed some bugs.
- Bump hickory to use the [original version](https://github.com/clj-commons/hickory/commits/master) as it now has a deps.edn (which was our only reason for the fork) and also includes a dependency bump to patch a security vulnerability with jsoup
=> Dev: bump clj-kondo and hickory

src/main/frontend/components/block.cljs
Introduced [here](https://github.com/logseq/logseq/commit/aed9527f5a7520cb744181cc522bb7d3d6ffeac2#diff-39e448dcea9d6d637136848eddca673106911b12f656627ab14923fb3fa72322R622)
Resolves  
> Another thing I noticed was that nothing was happening when I clicked on the edit block option. I am guessing this should take me to the block text in Logseq. Am I missing something? Other buttons like Zen mode etc are working fine.
on https://github.com/logseq/logseq/issues/7034
The edit button doesn't work because `block-uuid` is `nil`
=> Fix: block-uuid on page-reference

src/main/frontend/db/utils.cljs, src/main/frontend/handler/whiteboard.cljs, src/main/frontend/modules/outliner/file.cljs
This PR adds timestamps for whiteboard blocks too (pages are supported already). Timestamps could enable some really interesting usages, e.g., reviewing the blocks created on the same day, which blocks have been modified recently, etc.
=> fix: add timestamps for whiteboard blocks

src/main/frontend/components/query_table.cljs, src/test/frontend/components/query_table_test.cljs
Added support for locale sensitive sorting for query tables. E.g, in Chinese, "圆圈" should be placed after "意志" according to pinyin order.
I'm not too familiar with Clojure and ClojureScript, can you help revise? Hope I implemented it right.
=> feat: support locale sensitive string comparisons for table sorting

src/main/frontend/components/page.css
I figure out that the `<span>` of title has height 0 when it has no content while editing the title.
Reference: https://stackoverflow.com/questions/8692041/minimum-height-for-div-or-span-with-empty-element
https://user-images.githubusercontent.com/28241963/198179783-df0a38ad-8394-49cb-aae7-d9f321d7dedd.mp4
https://user-images.githubusercontent.com/28241963/198179815-8c4262d2-4b7b-4ad3-a09a-1a9ec222a136.mp4
=> fix(page): title has height 0 when length of editing title is 0

deps/graph-parser/src/logseq/graph_parser/block.cljs, deps/graph-parser/test/logseq/graph_parser_test.cljs
Fixes #6034, #6618 and  #6930 . Looks like behavior was introduced [awhile ago](https://github.com/logseq/logseq/commit/986bb201c7430f84e1cbadb535a865bae1f0fafd#diff-5caa002eb84518fbfaa4afa600ecd7fc3fb59a485193f826aff2efa46cc54d97)
=> Fix: File links creating garbage pages

src/main/frontend/components/block.cljs
Fix issues on the whiteboard shape refs in block's ref panel.
=> fix: several issues on clicking the whiteboard shape ref

deps/graph-parser/src/logseq/graph_parser/extract.cljc, src/main/frontend/components/whiteboard.css, src/main/frontend/handler/whiteboard.cljs, src/main/frontend/modules/outliner/file.cljs, src/main/frontend/modules/shortcut/before.cljs, src/main/frontend/state.cljs, tldraw/apps/tldraw-logseq/src/app.tsx, tldraw/apps/tldraw-logseq/src/lib/shapes/LogseqPortalShape.tsx, tldraw/apps/tldraw-logseq/src/lib/tools/LogseqPortalTool/states/CreatingState.tsx, tldraw/packages/core/src/lib/TLApp/TLApp.ts, tldraw/packages/react/src/hooks/useSetup.ts
It seems block collapsing state of the first root block of a portal shape will not work due to `frontend.components.block/root-block?`. I am not sure what is the best way to fix that 🤔
=> fix(whiteboard): some more ux issues

src/main/frontend/components/content.cljs, src/main/frontend/components/page.cljs, tldraw/apps/tldraw-logseq/src/lib/shapes/LogseqPortalShape.tsx, tldraw/apps/tldraw-logseq/src/styles.css
=> Fix: Whiteboards portal issues

src/main/frontend/components/page.cljs, src/main/frontend/components/reference.cljs
More consistency in page bottom reference blocks (tagged, linked, unlinked) classnames (same as https://github.com/logseq/logseq/blob/master/src/main/frontend/components/hierarchy.cljs#L43 has).
=> Page bottom refs blocks

tldraw/apps/tldraw-logseq/src/lib/shapes/ImageShape.tsx, tldraw/apps/tldraw-logseq/src/lib/shapes/YouTubeShape.tsx
Turns out it is pretty easy to get a youtube video's thumbnail image. See https://gist.github.com/iredun/a9681c46d3d74e03fb35d9ebf198b83d
=> feat: show youtube thumb images in preview

src/main/frontend/security.cljs
Since we allow custom protocols on markdown links, it makes sense to also allow them on HTML and Hiccup.
We can find a better way to handle both later (related discussion here https://github.com/logseq/logseq/pull/6967)
We can test this by creating a hiccup link with a custom protocol 
`[:a {:href "skype://"} "skype link"]`
Resolves https://github.com/logseq/logseq/issues/7206
=> Fix: Allow custom protocols

src/main/frontend/fs/sync.cljs
dynamodb range key has limit < 1024 bytes, for us, it is user-uuid/graph-uuid/encrypted-file-path
=> enhance(sync): filter pages whose page-name is too long

deps/graph-parser/src/logseq/graph_parser/extract.cljc, deps/graph-parser/src/logseq/graph_parser/util.cljs, src/electron/electron/core.cljs, src/electron/electron/utils.cljs, src/electron/electron/window.cljs, src/main/frontend/components/block.cljs, src/main/frontend/components/file_sync.cljs, src/main/frontend/config.cljs, src/main/frontend/fs/sync.cljs, src/main/frontend/handler/events.cljs, src/main/frontend/handler/file_sync.cljs, src/main/frontend/handler/paste.cljs, src/main/frontend/mobile/intent.cljs, src/main/frontend/util.cljc, src/main/frontend/util/fs.cljs
This PR will notify users to switch to the new filename format when there're file paths that have some reserved chars.
It also skips downloading those files and notifies users to update the filename format on other devices.
This PR fixed two issues:
1. Sync stops because there're filenames with reserved chars.
2. `js/decodeURIComponent` is not safe to use, for example, `(js/decodeURIComponent "% 20")` will throws a `URI malformed` error.
=> Fix sync stops when there's filenames with reserved chars

src/main/frontend/config.cljs, src/main/frontend/handler/common/file.cljs, src/main/frontend/handler/conversion.cljs, src/main/frontend/util.cljc, src/test/frontend/db/name_sanity_test.cljs
Fix #7188 #7259
Why remove the check?
The "manually set title property" might be introduced by unconscious behavior of users, like renaming the filename with reserved characters. 
We should force rename to avoid any possibility of breaking  cross platform file sync 
Close #7204 
macOS's FSEvent doesn't fire `add` when renaming files between capitalization
=> fix: page names are URIencoded on Android pad / iPad devices

src/main/frontend/components/file_sync.cljs, src/main/frontend/components/repo.cljs, src/main/frontend/fs/sync.cljs, src/main/frontend/handler/events.cljs, src/main/frontend/handler/file_sync.cljs, src/main/frontend/handler/repo.cljs, src/main/frontend/state.cljs
Fix:
1. unlink a graph can unlink others.
2. remove a remote graph doesn't remove it from the graph list sometimes.
=> fix: unlink wrong graphs

src/main/frontend/components/page_menu.cljs, src/main/frontend/state.cljs, tldraw/apps/tldraw-logseq/src/hooks/usePaste.ts
- fix: pasting texts into portal shapes not working. This is due to a regression in a5e01895c. Supporting `get-current-page` for whiteboard route breaks https://github.com/logseq/logseq/blob/b09fe61e86a64580faa9c6fb3a90cb54cf2f63db/src/main/frontend/handler/paste.cljs#L118-L150
- fix: pasting image assets are not correctly handled. Also, dropping multiple assets will also pack them into a rect.
https://user-images.githubusercontent.com/584378/200510135-dbd97aec-6790-42fc-9f49-e66d33770d9c.mp4
=> fix(whiteboard): pasting text in block portal shapes

e2e-tests/page-rename.spec.ts, e2e-tests/whiteboards.spec.ts, src/main/frontend/handler/page.cljs
Closes #6907. 
Fixed by checking wether the renamed page is the homepage and then setting it to the new page name.
Added a e2e-test for this usecase. This caused the whiteboard e2e-test to become flaky on my machine. The fix was to draw the whiteboard rectangle 5 pixel from the origin. I couldn't find any other way to fix it, as I don't think my changes should've interfered with the whiteboard
=> fix: Renaming the homepage makes it no longer the homepage

src/main/frontend/extensions/zotero/setting.cljs
The update to config via `set-config` has some latency to be listen by `sub-config`, which causes race condition. (The latency may be introduced by the global config PR)
The race condition triggered a legacy bug in the zotero implementation.
The solution is adding timeout between `set-config` and `sub-config`
Fix #6861 
Fix #7092 
Fix #7103
=> fix: race condition on creating zotero profile

src/main/frontend/components/block.cljs
I have a plugin where I would like to render a custom component on top of block references that would typically be invalid. An example:
Notice how the top block reference is custom - it's a uuid followed by a `:` and another id. Allowing this to render as invalid will make it easier for me to create a mutation observer in my plugin that watches for this component and renders the desired content instead.
The screenshot above is with the changes introduced in this PR. Without this PR, this is what renders instead:
Notice how that top block reference is now just missing, with no HTML content to watch for.
=> Always render the invalid block ref regardless of contents

src/main/frontend/fs/capacitor_fs.cljs, src/main/frontend/handler/events.cljs
Re-index needed.
This fixed two bugs:
1. unsaved changes will be overwritten when restarting the app.
2. full sync instead of incremental sync
=> fix: force /private part on iOS

src/main/frontend/components/sidebar.cljs
Displayed filenames should be URL-decoded on mobile platforms, instead of something like %XX%XX....%XX.md
=> fix(mobile): show url-decoded filenames when re-indexing

src/main/frontend/components/sidebar.cljs
decodeURIComponent crashes under some conditions:
`decodeURIComponent('%E0%A4%A')`
=> fix(mobile): use safe uri decode fn

src/main/frontend/components/block.cljs, src/main/frontend/fs.cljs
**Before the fix, URLencoded href (the `%20` in path) is not accepted, though the asset exists in the decoded form (`../assets/IMG_9072 2.PNG`)**
`**00:28** [[quick capture]]: ![IMG_9072%202](../assets/IMG_9072%202.PNG)`
(Image doesn't show)
`**00:28** [[quick capture]]: ![IMG_9072%202](../assets/IMG_9072 2.PNG)`
(Image shows up)
**After the fix, URLencoded href (the `%20` in path) is also accepted**
`**00:28** [[quick capture]]: ![IMG_9072%202](../assets/IMG_9072%202.PNG)`
(Image shows up)
=> fix: href asset is not loaded on Electron

docs/develop-logseq.md
**Disclaimer:**
This is my first PR to Logseq so please forgive me if I've misunderstood something about the repo that makes this PR incorrect.
**Summary**:
The changes to the docs in this PR now direct users to the static/ directory for released files instead of resources/ for browser development.
**Details:**
When I look at the `release` script in `package.json` I can see that it runs `gulp:build` script first. `gulp:build` in turn runs `gulp build`. Following the command into `gulpfile.js` I can see that the build script runs:
```
exports.build = gulp.series(common.clean, common.syncResourceFile, common.syncAssetFiles, css.buildCSS)
```
Each of the functions that are used in `gulp.series` output files to `outputPath = path.join(__dirname, 'static')`. This is the static directory and …
=> Small fix in documentation for browser development.

.gitignore, deps.edn, src/bench/frontend/benchmark_test_runner.cljs, src/bench/frontend/macros.cljc, src/main/frontend/modules/file/core.cljs, src/main/frontend/modules/file/uprint.cljs
Prints fast with newlines
clojure -M:test:bench
```
Testing frontend.benchmark-test-runner
[], (with-out-str (pprint/pprint onboarding)), 10 runs, 2950 msecs 
[], (with-out-str (fipp/pprint onboarding)), 10 runs, 2447 msecs 
[], (up/ugly-pr-str onboarding), 10 runs, 94 msecs 
[], (pr-str onboarding), 10 runs, 82 msecs
```
=> replace whiteboard printing with ugly print #7168

e2e-tests/basic.spec.ts, src/main/frontend/components/datetime.cljs
fixes  #6985 
Datepicker now opens on the previously specified day if editing a task
Also added a e2e-test for this
=> fix: Scheduled date picker always points to today, regardless of a previous date

tldraw/apps/tldraw-logseq/build.mjs
This fixes a build error on Windows(PowerShell).
```console
> yarn
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
$ yarn tldraw:build
yarn run v1.22.19
$ cd tldraw && yarn
[1/4] Resolving packages...
success Already up-to-date.
$ yarn build
$ cd apps/tldraw-logseq && yarn build
[1/4] Resolving packages...
success Already up-to-date.
$ zx build.mjs
$ tsup
tsup : The term 'tsup' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ tsup
+ ~~~~
+ CategoryInfo          : ObjectNotFound: (tsup:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```
=> fix(build): use npx to run tsup

src/main/frontend/components/theme.cljs, src/main/frontend/handler/plugin.cljs, src/main/frontend/ui.cljs, yarn.lock
From #5434.
In `apply-custom-theme-effect!`, the previous code used `url` to detect if the user was using a custom theme, which would cause problems (do not execute selectTheme) because the default themes did not have `url`.
https://github.com/logseq/logseq/blob/a939767aaf5720ec68c1ca00cc589dd85718995f/src/main/frontend/components/plugins.cljs#L47
This problem will occur when the user has set only one theme (e.g. set a custom light theme but uses the default dark theme). So I change the code to use `name` to detect if the user has set a custom theme (see more details in code comments).
This PR also updates the caniuse-lite.
=> fix: use name to detect default theme

src/main/frontend/fs/watcher_handler.cljs
Error: Path contains invalid characters: C:\Users\xxxx\Works\mynotes\logseq\bak\C:\Users\xxxx\.logseq\config\config****
=> fix: error while backup global config under windows

e2e-tests/sanitization.spec.ts, src/main/frontend/security.cljs
dompurify remove `is` attribute from generated html from hiccup. I Add extra option into `sanitization-options` to allow `is` attribute.
=> fix: issue #7366 render custom html element as hiccup not working

src/main/frontend/components/header.cljs, src/main/frontend/components/header.css
Double click handling was limited to `.cp__header`.
A `drag-region` class was added to allow toggling the maximized state on multiple regions.
I also moved the drag related rules under this class.
Resolves https://github.com/logseq/logseq/issues/7380
=> Fix: Title bar drag region

src/main/frontend/handler/plugin.cljs, src/main/frontend/state.cljs
This change will allow theme plugins to show in the list under _Settings > Plugin Settings_ if they register settings schema using `logseq.useSettingsSchema(settings)` same as how non-theme plugins do.
This will enable theme designers to give users customization options within the theme design guidelines like accent color, hide/unhide elements, etc. 
I have shared context and additional info in a feature request at [discuss](https://discuss.logseq.com/t/theme-plugin-settings/12280). Discord [conversation](https://discord.com/channels/725182569297215569/752845138148982877/1039251172156002324) related to this.
Thanks!
=> feat: show theme plugin settings under "Plugin Settings"

src/main/frontend/components/page.cljs
**Summary**:
Fixes #5976 - Fixes shift+click on items in "all pages" launching a new browser window.
**Details**:
Because the items in `all pages` are `<a>` tags, their default behaviour (when doing a shift+click) is to open a new browser window. I've added `preventDefault` to these tags to stop that from happening.
=> Fixes shift+click on "all pages" launching a new browser window

src/main/logseq/api.cljs
Took us only about 4 hours to figure out, but we found the fix :tada: 
We found that the only other usage of the custom-uuid argument 
in assets / `ensure-ref-block!` already passes a uuid, 
so we chose to convert in the calling api. 
Closes #7283
=> fix #7283: customUUID not converted to UUID type

src/main/frontend/handler/paste.cljs
The html content is escaped from the start of the text, instead of the inner content inside of `whiteboard-tldr` tags after a recent change
=> fix: copying whiteboard shapes into outliner

src/main/logseq/api.cljs
Logseq api should throw an error if there is an invalid block-uuid string.
Also, make sure UUIDs are converted already when passing to cljs.
Related to #7375.
=> Enhance/api block UUID

src/main/frontend/extensions/html_parser.cljs
Avoid adding redundant space around a `<code>` element.
Comparing the following two blocks:
=> fix(editor): do not wrap space when pasting <code>

e2e-tests/editor.spec.ts, src/main/frontend/commands.cljs, src/main/frontend/components/editor.cljs, src/main/frontend/handler/editor.cljs, src/test/frontend/handler/editor_test.cljs
Fix #7305
- move `#` handler from keyup to `:did-update` (for Android platform)
- Typing `/` after `#blah` page search no longer triggers inline command popup (Now it will keep searching/creating namespace pages)
- Minor style fix of  search block auto-complete - `((|))`
=> Refactor: page search hashtag

src/main/frontend/handler/common/file.cljs, src/main/frontend/handler/repo.cljs
=> fix: notify users if page name already exists when parsing files

src/main/frontend/handler/conversion.cljs, src/test/frontend/db/name_sanity_test.cljs
New rule:
Don't rename file with custom `title::`property, unless it contains reserved characters
=> fix: filename format revert manual title check

src/main/electron/listener.cljs
Ref: https://github.com/logseq/logseq/pull/7427
With the new changes from the above PR, user is redirected to the page where the quick capture item is inserted. This can be jarring. Hence offer the option to disable the redirect in `config.edn` using the following:
```
:quick-capture-options {
:redirect-page false
}
```
=> Allow using config.edn to change if page redirect happens when inserting quick-capture

ios/App/App/Info.plist
Ref: https://developer.apple.com/documentation/bundleresources/information_property_list/itsappusesnonexemptencryption
Ref: https://stackoverflow.com/questions/35841117/missing-compliance-status-in-testflight
=> chore(ios): config keys of non-exmpect encryption

src/main/frontend/config.cljs, src/main/frontend/util.cljc
Closes #7435, #7416, #7295, #7271, #7264, #7211, #7077.
Till version 0.8.8 it was possible to upload files in any format. After this version, some changes were made (not sure if this was intended) that only accept a subset of file formats. 
This PR enables the following formats (replace `:` with `.`)
`:json :org :md :yml :dat :asciidoc :rst :txt :markdown :adoc :html :js :ts :edn :clj :ml :rb :ex :erl :java :php :c :css
:excalidraw :tldr :sh :zip :msg :xltx :eml :odt`
=> Fix: Cannot upload assets with certain formats. 

src/main/frontend/components/block.cljs
Fix: cannot open assets(PDF) with non-ASCII filenames on iOS.
Or else conversion to URL fails.
https://github.com/ionic-team/capacitor-plugins/blob/473dbe5159258c4e8ea5c9bbbd9542f864da55c0/share/ios/Plugin/SharePlugin.swift#L20-L37
=> fix(mobile): missing urlencode when sharing asset url

src/main/frontend/extensions/pdf/toolbar.cljs
When scrolling the page number input box:
=> fix(pdf): missing min max value of page number

tldraw/apps/tldraw-logseq/src/components/ZoomMenu/ZoomMenu.tsx, tldraw/packages/react/src/components/Canvas/Canvas.tsx
fixes LOG-1962
Steps to reproduce:
Zoom buttons keep focus, Steps to reproduce: click Reset Zoom, click on whiteboard once, press Space. Zoom changes.
https://discord.com/channels/725182569297215569/1006913306822459484/1045340931655745557
Issue caused by the following line:
https://github.com/radix-ui/primitives/blob/main/packages/react/dropdown-menu/src/DropdownMenu.tsx#L186-L191
=> fix: zoom menu trigger should not gain focus on close LOG-1962

tldraw/apps/tldraw-logseq/src/components/BlockLink/BlockLink.tsx, tldraw/apps/tldraw-logseq/src/components/QuickLinks/QuickLinks.tsx, tldraw/apps/tldraw-logseq/src/components/inputs/ShapeLinksInput.tsx, tldraw/packages/core/src/lib/TLSettings.ts
Optimize block link reference display on whiteboard shape
For block links (the links under the shape and the links in the context menu)
- when the link refers to a portal and the portal is a block, do not show the block content
- otherwise, show the link content (max 20 characters)
=> fix: optimize block link reference display in whiteboard

tldraw/packages/react/src/components/Canvas/Canvas.tsx
The original bug is to fix an issue that if blocks are too close to each other, the links underneath are hard to be clicked.
The fix makes sure that the hovered or selected shape will have higher order so that the hovering state will not be transferred
https://user-images.githubusercontent.com/584378/204176772-13ae8382-f0a8-47cd-a3a3-215bf2620b73.mp4
=> fix: hovered or selected shape should have higher zindex

tldraw/apps/tldraw-logseq/src/components/ContextBar/ContextBar.tsx, tldraw/packages/react/src/index.ts
fixes https://linear.app/logseq/issue/LOG-1961/decrease-object-action-bar-distance-when-below-portal
=> fix: decrease Object Action Bar distance when below portal

android/app/src/main/java/com/logseq/app/FsWatcher.java
- Polling-based fs watcher
- Fewer bugs compared to the current implementation
- Supports all Android API level
- Multilevel directory support
- Avoid notifying too soon after file op
Close #7072
Close #7106
=> refactor(android): rewrite fs watcher

src/main/frontend/handler/editor.cljs, src/main/frontend/modules/outliner/core.cljs, src/test/frontend/modules/outliner/core_test.cljs
This PR fixed:
Can't paste nested blocks into an empty block, to reproduce it, check #7500 
It also improves the paste UX, if the target block is empty and it has children, pasting nested blocks will create blocks above it.
close #7500
=> fix: can't paste nested blocks into an empty block

tldraw/packages/react/src/components/Canvas/Canvas.tsx
Reverts logseq/logseq#7491
The introduces another regression described in https://github.com/logseq/logseq/pull/7491#issuecomment-1329438197, which is even harder to fix for now.
=> Revert "fix: hovered or selected shape should have higher zindex" 

src/main/frontend/fs/sync.cljs
Taking a photo and going back to the app will result in the `resume` state, `idle` doesn't handle it previously and returns `nil` so that local->remote ops can't be triggered anymore.
=> fix: sync stopped working after taking a photo

src/main/frontend/handler/editor.cljs, src/main/frontend/mobile/camera.cljs
- fix: When clicking then not picking any image, an empty image link still gets created
- fix: use safe path join for image asset path
=> fix(mobile): refactor mobile camera toolbar command

src/main/frontend/handler/events.cljs, src/main/frontend/state.cljs
User's groups will be stored in local storage.
How to test?
1. Login if you haven't 
2. Disable Wifi
3. Restart logseq 
The sync icon should still be there.
=> fix: sync icon disappear with unstable network

.gitignore, e2e-tests/page-search.spec.ts, e2e-tests/utils.ts, src/electron/electron/search.cljs, src/main/frontend/search/db.cljs
- Fix: Wrong handled `distinct-by` at block search
- Feat: Page content search index now contains title (addressing #7510)
- E2E tests:
- CJK search test
- ~Recover alias test~
=> Page content search fine-tuning

shadow-cljs.edn, src/dev-cljs/shadow/hooks.clj, src/main/frontend/components/settings.cljs, src/main/frontend/config.cljs, src/main/frontend/modules/instrumentation/sentry.cljs
- implemented using shadow-cljs build hooks
- hover on VERSION text to acquire the revision string
- report to sentry.io
=> Enhance: add git revision to sentry report

e2e-tests/whiteboards.spec.ts
Since e2e tracing is re-enabled now. We can enable the whiteboard tests again and see what is the error cause if any of them failed.
I manually retriggered the whiteboard test runs, but none of them failed 😅
=> e2e: reenable whiteboard e2e

tldraw/apps/tldraw-logseq/src/components/ZoomMenu/ZoomMenu.tsx, tldraw/apps/tldraw-logseq/src/hooks/useQuickAdd.ts, tldraw/apps/tldraw-logseq/src/lib/shapes/LogseqPortalShape.tsx, tldraw/apps/tldraw-logseq/src/lib/tools/LogseqPortalTool/states/CreatingState.tsx, tldraw/apps/tldraw-logseq/src/styles.css, tldraw/packages/core/src/lib/TLApi/TLApi.ts, tldraw/packages/core/src/lib/TLViewport.ts
Apply a transition animation for canvas camera-related actions. The implementation refers to the new beta.tldraw.com.
Also moves the canvas to zoom in to the quick search after creating a portal shape. 
Note the FPS on the simulator is not that smooth because of rendering performance. We still need to improve this.
https://user-images.githubusercontent.com/584378/205478765-c352dec4-f276-45c0-98c1-23750934ba28.mp4
https://user-images.githubusercontent.com/584378/205478585-aecd4a8f-f4f2-4009-8e45-52d967717cd2.mp4
=> feat: animate canvas camera movement

src/main/frontend/modules/shortcut/config.cljs
In general, we should avoid using single char as shortcut, the only exception is for whiteboard actions.
=> Deprecate: use g c to git commit instead of `c`

src/main/frontend/components/onboarding.cljs, src/main/frontend/components/right_sidebar.cljs, src/main/frontend/components/shortcut.cljs, src/main/frontend/modules/shortcut/data_helper.cljs, src/main/frontend/util.cljc, src/test/frontend/util_test.cljs
1. As proposed in [here](https://discuss.logseq.com/t/new-user-frustrated-with-learning-shortcuts/12909?u=ramses), the `keyboard shortcut` button in the right sidebar will open the shortcut panel in place:
* <img width="1065" alt="image" src="https://user-images.githubusercontent.com/9862022/205127371-04800095-de1b-4220-a8c2-7be1224e26e9.png">
2. Reduce lagging of opening shortcut view
* Before, likely blocked by 1 sec 
* <img width="1375" alt="image" src="https://user-images.githubusercontent.com/9862022/205127820-f6e3d8ad-e67b-4664-8102-f2f53808aaca.png">
* After, by caching, cut time consumption by 80% to ~200ms
* <img width="1260" alt="image" src="https://user-images.githubusercontent.com/9862022/205270192-62d0717e-5ae0-4e9d-8fdf-d8c62648e3a6.png">
* Add function `util/memorize-last` …
=> feat: open right side bar helping page shortcut settings on right side

.github/ISSUE_TEMPLATE/bug_report.yaml
When I created a new issue for logseq, I noticed that there is a typo **MacOS** in the hint of `Desktop or Mobile Platform Information`. The name with correct case should be **macOS**.
=> fix(typo): wrong case of macOS

src/main/frontend/components/block.cljs
Before version 0.8.2, linked references were grouped by parent, which was really important to me and kept me from upgrading to the latest version. 
As can be seen from the following, if there is no group, multiple parents are redundant, and the order of children sometimes is chaotic.
**Basic usage**, write multiple same link below a block (TODO, OKR etc)
**Without group**: redundant parents and wrong children order
**With group**
I check the code difference between v0.8.1 and v0.8.2, it really takes a long time for me to locate the bug. So I only revert some part of code, which might not be the best solution, but it does point out the essential code snippet.
Really hope this could be fixed or be an option in settings, thanks 🙏
=> fix: group linked references by parent

src/main/frontend/handler/paste.cljs
fixes #7268
Fixed by testing whether text is selected while pasting and formatting accordingly
The code is kinda ugly, but I don't know of a nicer way
=> fix: Link can't be pasted on selected text in block content

bb.edn, scripts/src/logseq/tasks/malli.clj, src/main/frontend/handler/file.cljs, src/main/frontend/handler/global_config.cljs, src/main/frontend/schema/handler/common_config.cljc, src/main/frontend/schema/handler/global_config.cljc, src/main/frontend/state.cljs, src/test/frontend/handler/global_config_test.cljs
This adds validation to global config to improve the user experience when editing global config and to prevent invalid config data that can cause unexpected failures like https://github.com/logseq/logseq/issues/7392.  Validation works whether the global config is edited inside or outside of Logseq. If this validation works fairly well for global config, it would be pretty easy to also add it to the repo config.edn
=> Enhance: Validate global config

src/main/frontend/commands.cljs, src/main/frontend/components/datetime.cljs, src/main/frontend/components/editor.cljs, src/main/frontend/handler/editor.cljs, src/main/frontend/handler/page.cljs, src/main/frontend/util.cljc
=> fix: remove spaces around CJK characters when auto-complete pages

src/main/frontend/components/header.cljs, src/main/frontend/components/settings.cljs
There are some translated keys in i18n file, but logseq does not replace the origin hard-coded text in the code with the i18n key. After replacing them, everything looks good to me.
Note: Screenshots are taken under language Chinese(Simpified)
By the way, I also found that there are some hard-coded text in settings, I would like to translate them.
=> chore: replace hard-coded text with existing i18n key

src/main/frontend/handler/events.cljs
Otherwise, sync can still work and download files from the server, which could lead to unexpected results.
=> fix: stop file sync when re-index

e2e-tests/whiteboards.spec.ts, tldraw/apps/tldraw-logseq/package.json, tldraw/apps/tldraw-logseq/src/components/ActionBar/ActionBar.tsx, tldraw/apps/tldraw-logseq/src/components/Button/Button.tsx, tldraw/apps/tldraw-logseq/src/components/ContextBar/contextBarActionFactory.tsx, tldraw/apps/tldraw-logseq/src/components/ContextMenu/ContextMenu.tsx, tldraw/apps/tldraw-logseq/src/components/GeometryTools/GeometryTools.tsx, tldraw/apps/tldraw-logseq/src/components/PrimaryTools/PrimaryTools.tsx, tldraw/apps/tldraw-logseq/src/components/ToolButton/ToolButton.tsx, tldraw/apps/tldraw-logseq/src/components/Tooltip/Tooltip.tsx, tldraw/apps/tldraw-logseq/src/components/Tooltip/index.ts, tldraw/apps/tldraw-logseq/src/components/inputs/ColorInput.tsx, tldraw/apps/tldraw-logseq/src/components/inputs/SelectInput.tsx, tldraw/apps/tldraw-logseq/src/components/inputs/ShapeLinksInput.tsx, tldraw/apps/tldraw-logseq/src/components/inputs/ToggleGroupInput.tsx, tldraw/apps/tldraw-logseq/src/components/inputs/ToggleInput.tsx, tldraw/apps/tldraw-logseq/src/lib/tools/BoxTool.tsx, tldraw/apps/tldraw-logseq/src/lib/tools/EraseTool.tsx, tldraw/apps/tldraw-logseq/src/lib/tools/HighlighterTool.tsx, tldraw/apps/tldraw-logseq/src/lib/tools/LineTool.tsx, tldraw/apps/tldraw-logseq/src/lib/tools/LogseqPortalTool/LogseqPortalTool.tsx, tldraw/apps/tldraw-logseq/src/lib/tools/PencilTool.tsx, tldraw/apps/tldraw-logseq/src/lib/tools/TextTool.tsx, tldraw/apps/tldraw-logseq/src/styles.css, tldraw/demo/src/App.jsx, tldraw/packages/core/src/lib/tools/TLMoveTool/TLMoveTool.ts, tldraw/packages/core/src/lib/tools/TLSelectTool/TLSelectTool.tsx, tldraw/yarn.lock
Merged with https://github.com/logseq/logseq/pull/7641, because it is going to affect the implementation of this enhancement.
[Screencast from 2022-12-09 12-44-06.webm](https://user-images.githubusercontent.com/10744960/206685043-ecba2157-3785-4af8-a78d-91c96e8c9a8d.webm)
=> Feat: Use tooltips instead of titles on whiteboard buttons

tldraw/apps/tldraw-logseq/src/components/ToolButton/ToolButton.tsx
When there are no shortcuts for a tool button, we need to render just the tooltip which is a string.
=> Fix: Tooltip without shortcuts

src/main/frontend/handler/global_config.cljs
The default global config.edn will trigger this notification because the `parsed-body` is nil.
=> fix: allows empty config.edn

src/main/frontend/components/header.cljs, src/main/frontend/state.cljs
There are cases that right-swiping from the left edge will not work well on mobile (eg. on iPad with stage manager on). The proposed fix is to always show the hamburger button.
=> feat: always show hamburger button for mobile

src/main/frontend/components/block.cljs, src/main/frontend/fs/watcher_handler.cljs, src/main/frontend/handler/common/file.cljs
To reproduce:
1. Create a page `odroid-c2` with the content:
```
alias:: Board/ODROID-C2
title:: odroid-c2
```
2. Rename `odroid-c2` to `ODROID-C2`
3. Cmd+R to refresh the app
An error similar to `Page already exists` will be notified.
=> fix: remove orphaned files/blocks from db when comparing db && disk

src/main/frontend/components/page.cljs
```
Warning: Received `false` for a non-boolean attribute `indeterminate`.
```
=> fix(dev): indeterminate warning

src/main/frontend/extensions/pdf/highlights.cljs
1. Stop event propagation so that context menu will not be hidden when it is clicked. #7661 
2. Ensure that context menu is shown when text is selected. #7663 
close #7661
=> fixes for PDF context menu

deps/graph-parser/src/logseq/graph_parser/property.cljs, docs/dev-practices.md, src/main/frontend/components/block.cljs, src/main/frontend/components/query_table.cljs, src/main/frontend/date.cljs, src/main/frontend/db/react.cljs, src/main/frontend/format/block.cljs, src/main/frontend/util.cljc, src/test/frontend/components/query_table_test.cljs, src/test/frontend/format/block_test.cljs
The query performance was degraded by date normalization
TODO after merge: update document
TODO in future: use LRU cache to speed up sort with nlp-date parsing
=> fix: improve query performance

src/main/frontend/handler/editor.cljs
=> fix: copy block-ref instantly after input text lost block content

src/main/frontend/handler/web/nfs.cljs
The reason is that reload-dir! returns a promise, but should block waiting graph-added-chan to determine whether the parsing is finished
=> fix: stop sync when re-index

package.json
I like to have a dev version of logseq on my system alongside a regular build. I have been building it so far using the full command:
```sh
$ clojure -M:cljs release app electron --config-merge "{:closure-defines {frontend.config/DEV-RELEASE true}}"
```
Since `cljs:dev-release-app` already exist; It would be nice to add `cljs:dev-release-electron` as well
```sh
$ yarn cljs:dev-release-electron
```
=> enhance(dev): add `cljs:dev-release-electron`

src/main/frontend/components/plugins.cljs
fixes #7401  
Added padding at the bottom. As a side effect there is now more whitespace at the bottom. IMO this matches with the title whitespace and looks balanced.
=> fix: overflow of installed plugin settings dialog

src/main/frontend/modules/outliner/file.cljs
The performance gain is minor though.
=> fix: no need to convert blocks to tree for whiteboards

src/main/frontend/extensions/code.cljs
Fixes #7460 
The bug: 
After fix:
From my understanding, the issue is that  `block/content` of every codeblock updates (the main and referenced/embed block included) but the codemirror view updates only for the block that is being edited. 
This solution might be the best solution and I could be missing something trivial, if that's the case please let me know. 
cc @andelf
=> Update code edit for the codeblocks that are opened in main area and sidebar, as embeds.

README.md
- Fixed a minor typo `you we'll` --> `you'll`
- Capitalized the `H` in `GitHub` to follow the official brand naming
=> fix(typo): minor changes in README.md

resources/package.json, src/electron/electron/configs.cljs, src/electron/electron/core.cljs, src/electron/electron/handler.cljs, src/electron/electron/utils.cljs, src/main/frontend/components/plugins.cljs, src/main/frontend/components/settings.cljs, src/main/frontend/ui.cljs, static/yarn.lock
- Add Proxy support for Logseq Sync
- Use system proxy when possible
=> Enhance: Refine proxy support; Add proxy support to Logseq Sync

tldraw/packages/core/src/lib/TLApi/TLApi.ts, tldraw/packages/core/src/lib/TLApp/TLApp.ts, tldraw/packages/core/src/lib/TLPage/TLPage.ts
- fix pasting offset when the selected item contains a group shape
- fix an issue when pasting a group with an invalid shape id,
- fix performance issue of `getShapeById`
=> fix: some issues on pasting group shape

tldraw/packages/react/src/hooks/useCanvasEvents.ts
Looks like if we call event.preventDefault of the touchend event, the callout magnifier will not show any longer and makes sure user can draw quickly on the canvas.
=> fix: pencil issue when drawing quickly

src/main/frontend/db/model.cljs
=> fix: linked References Filter Empty

src/main/frontend/db/model.cljs, src/test/fixtures/broken-outliner-data-with-cycle.edn, src/test/frontend/db/model_test.cljs
`get-block-children-ids` may forever loop when some outliner data construct a cycle: parent-block's parent is its child-block
=> enhance: validate outliner data when get-block-children-ids

deps/graph-parser/.carve/ignore, deps/graph-parser/src/logseq/graph_parser/property.cljs, src/main/frontend/handler/page.cljs
Fix #7127 
The code seemed not to take into account the fact that the user can select the `org` mode, and that in that mode the delimiters for a property are a semicolon at the beginning and one at the end (if I'm not misunderstood).
So in order to add this case but not to break old code, I opted for the creation of a small function `colons-org` defined right below `colons` and by propagating the info about the `format` we can then choose the right property delimiter depending on the format.
Here a video of the flow, now fixed:
[Uploading Screencast from 2022-11-17 12-17-25.webm…]()
=> Fix format property reference when org mode

src/main/frontend/handler/route.cljs, src/test/frontend/handler/route_test.cljs
When coming from search, page links were capitalized but most everywhere else page links were lower case. This fix consistently enforces lower case and thus provides consistency to page identity in urls. With this consistency, web apps no longer encourage weird scenarios e.g. https://docs.logseq.com/#/page/Logseq%20Sync leading to https://docs.logseq.com/#/page/logseq%20sync/block/functionality when you click on a block
=> Fix: Provide consistent page links for web and publishing

.github/ISSUE_TEMPLATE/bug_report.yaml
Changed the wording on the checkbox. The previous wording looked wrong and it sounded like an action will be taken by checking the box.
=> fix: update confirm-search wording

src/main/frontend/dicts.cljc
Change the wording from `Check page history` to `view page history`. This is more inline with similar tools and feels more natural.
=> enhancement: change page/version-history wording

.github/stale-issues.yml
This GitHub Action is designed to close stale issues in a repository. An issue is considered stale if it hasn't received any new activity (e.g. comments, reactions, etc.) for a specified number of days. The Action will first apply a label to the issue to mark it as stale and then, after a specified number of days, it will close the issue if there has been no new activity. The Action can also be configured to exempt certain issues from being closed, for example if they have certain labels or if they are marked as a work in progress. The Action can be run on a schedule (e.g. daily), or it can be manually triggered using the workflow_dispatch event.
Here's a breakdown of the main configuration options for the Action:
- days-before-issue-stale: The number of days of inactivity that must pass …
=> feat: Add close-stale-issues-action

src/main/frontend/components/search.cljs
I found that the `More` button in searching results only exists in electron app but the function works also well in web app.
=> feature: Display full search result in the web app

package.json, resources/package.json, src/electron/electron/file_sync_rsapi.cljs, static/yarn.lock, yarn.lock
Follow up of #8146
- Changes: use NFC normalization before encryption, after decryption,
=> fix(rsapi): add fname unicode normalization

src/main/frontend/components/content.cljs
The right-click menu on bullets is not yet internationalized.
'open-in-sidebar', 'copy-block-ref' and 'copy-block-emebed' have already been translated in dicts.cljc and applied to the keyboard shortcuts in the help.
Therefore, I have also applied this translation to the right-click menu.
=> enhancement: add several internationalizations to the right-click menu

src/main/frontend/fs/sync.cljs
aws apigateway websocket idle timeout is 10min.
https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html#apigateway-execution-service-websocket-limits-table
=> enhance(sync): reduce ws ping messages

e2e-tests/page-rename.spec.ts, src/main/frontend/handler/editor.cljs, src/main/frontend/state.cljs
`mod+a` is now registered as a global shortcut.
Releated #7803
Bug1:
- when editing page title, `mod+a` will ignore current editing status and select page blocks
Bug2:
- when viewing "Unlinked References", `mod+a` will cause error:
=> WIP: fix(test): removal of select-all shortcut

src/main/frontend/components/command_palette.cljs, src/main/frontend/components/search.cljs
As the title.
Before:
After:
Edit:
=> style(search): center content in search items

src/main/frontend/mobile/mobile_bar.cljs
Per discord discussion: https://discord.com/channels/725182569297215569/802530020605820949/1053042117917810788
This rotates the undo/redo button icons to make more sense for their purpose (they're using icons meant for "rotate clockwise"/"rotate counterclockwise"), by adding the "rotate-180" class to those icons in the mobile bar.
Noting in case it helps other devs later: I got the mobile by to show up by modifying mobile-bar like so temporarily:
```
(rum/defc mobile-bar < rum/reactive
[]
(when (and (state/sub :editor/editing?)
;;  (or (state/sub :mobile/show-toolbar?)
;;      (mobile-util/native-ipad?))
)
```
Before (left: undo; right: redo):
After:
(I also removed unused "true" argument on undo/redo buttons)
=> enhance: Rotate undo/redo button icons

src/main/frontend/components/page.css, src/main/frontend/components/sidebar.css
Currently in Logseq when you press Ctrl-A (or Meta-A on macOS), the whole page is selected. This behavior is useless and nobody would expect this.
This PR enhances Ctrl+A to be more intuitive:
1. ~~When in the selection mode, all blocks are selected.~~ Removed due to bugs.
2. When in the editing mode, all text in the block is selected.
3. Global Ctrl+A does nothing.
=> ehhancement: Prevent Ctrl+A from selecting the whole document

src/main/frontend/components/content.cljs
Mentioned: https://discuss.logseq.com/t/fundamental-need-keyboard-and-menu-shortcut-to-delete-block/13832/1
https://user-images.githubusercontent.com/1779837/210298219-697d06ca-8884-471e-8d0d-b830b65824a8.mp4
=> improve(ux): add delete option for blocks context menu

src/main/logseq/api.cljs
Some enhancements for api/insert_block :
1. remove `isPageBlock` 
There's no need for it because block's id is UUID and page name is not.
2. create a new page if it doesn't exist, otherwise, users have to create a page first and invoke this method then to add content, which is tedious.
=> enhance(api): no need to pass `isPageBlock` for api/insert_block

docs/dev-practices.md
This adds a short note to dev-practices.md, that I believe accurately reflects the current situation about auto-formatting code (and will hopefully help others like me avoid spending a bunch of time looking into this).
=> enhance(docs): Add note about auto-formatting in `dev-practices.md`

docs/dev-practices.md
the link https://cljdoc.org/d/cljfmt/ will always load the most up to date documentation of cljfmt.  It should be used instead of a specific version number
=> fix: do not link to a specific cljfmt version docs

src/main/frontend/components/block.cljs
Tried to fix it and finally worked it out , seems it works well.
I figure out that hovering on page ref in page-preview does not show another page-preview if `{:preview? true}` was passed to `page-blocks-cp` like the following code.
https://github.com/logseq/logseq/blob/f5e37091dd0e1d23fa52acf7b368899b85a33f24/src/main/frontend/components/block.cljs#L664
https://user-images.githubusercontent.com/28241963/210232438-57b04ac3-65e0-49ce-a4bb-190ecef14235.mp4
https://user-images.githubusercontent.com/28241963/210232444-d607d7c6-d48f-467f-9101-0486be05e417.mp4
=> Chore: Document components related to hide page-preview itself when hovered hierarchy ref in the preview

e2e-tests/utils.ts
This bug was found when I want to perform a **single** e2e test instead of all.
If we test just a single e2e test in debug mode(both debug and non-debug mode fails, debug mode is just used to 
demonstrate how I found where the bug occurs), the test will be failed and we will be breaked at this line.
```typescript
await page.waitForSelector('strong:has-text("Choose a folder")', { state: 'visible', timeout: 5000 })
```
Here is screen recording.
https://user-images.githubusercontent.com/28241963/210493245-9b2d7087-d7cf-4362-a9dc-a36117834aa7.mp4
I have also found that the test dir is loaded by these codes so that simply clicking on `Add new graph` will automatically load the test graph.
https://github.com/logseq/logseq/blob/86b5c9dc770e5769eeb10bb98d2757e780ac6379/e2e-tests/utils.ts#L148-L161 …
=> fix(e2e-test): should not wait for selector when there is no onboarding button

src/main/frontend/handler/editor.cljs
- Fixed #6853
https://user-images.githubusercontent.com/1779837/210231498-b41063f2-1c88-4bf9-bc5a-e4fb7fe4d599.mp4
=> fix(ios): wrong behavior when backspace with line-head text selection

e2e-tests/plugins.spec.ts
Will enable it once it's stable.
=> fix: disable plugins e2e tests temporally

libs/src/LSPlugin.ts, src/electron/electron/search.cljs, src/main/frontend/components/search.cljs, src/main/frontend/handler/search.cljs, src/main/frontend/search.cljs
Fix a error that would cause outdated FTS search cache (happens when Logseq is closed and edit file content directly)
Fix a type error in SearchServiceAPI
Breaking change: ask users to re-index to eliminate all `outdated cache` warning
=> fix: some search service plugin API typo

deps.edn
I updated emacs cider to 1.6.0, and it suggests me to upgrade cider-nrepl
=> dev: update cider-nrepl to 0.29.0

.clj-kondo/config.edn, src/main/frontend/fs/sync.cljs, src/main/frontend/pubs.cljc, src/main/frontend/pubsub.cljc, src/main/frontend/util.cljc
put all events mult/pub/chan in this namespace.
use macro `def-mult-or-pub` to define a event-ch+ mult/pub pair with malli-schema validation and doc-string. 
merge malli-schema into doc-string, so we can view their malli-schema in emacs cider-doc (don't know other editor's plugin).
```
frontend.pubs/app-wake-up-from-sleep-mult
app wake up from sleep event
Malli-schema:
[:map [:last-activated-at :int] [:now :int]]
frontend.pubs/app-wake-up-from-sleep-mult is defined in 
/Users/rcmerci/src/logseq/src/main/frontend/pubs.cljc.
```
one use case is `pubs/app-wake-up-from-sleep-mult` and `pubs/app-wake-up-from-sleep-ch`.
`frontend.util/<app-wake-up-from-sleep-loop` offers events, and fn(sync ns) tap this mult to receive events, then trigger a remote->local sync when app awakes from sleep.
=> feat: add frontend.pubsub ns

deps/graph-parser/.carve/ignore, deps/graph-parser/src/logseq/graph_parser/text.cljs, src/electron/electron/handler.cljs, src/main/frontend/handler/file_sync.cljs
- Fix #8292
- Now Electron's `readdir` only returns files, the same as capacitor
Solved: ~~After fixing this, some fs access warnings come out at Electron main part. It seems there're still other fs bugs.~~
=> fix(fs): wrong graph name from graph-parser; readdir should not return directories

src/main/frontend/components/bug_report.cljs
Introduced in #8317
CC @situ2001
=> fix(ui): error calling set-step! in bug-report

src/main/frontend/handler/user.cljs
if users can't redirect from the browser back to the app,
the workaround is calling
frontend.handler.user.login_callback(\<code\>) to finish login progress
=> feat: export login-callback fn

src/main/frontend/components/query_table.cljs
This fixes #8334 which was introduced by #8301 . There is a related issue I need to make for page properties with page ref and non-page ref content that would be an improvement over recent versions
=> Fix: Page properties not being visible in the query table

e2e-tests/editor.spec.ts, src/main/frontend/handler/editor.cljs
close #7615
Based on my basic understanding of undo-redo of logseq that undo-redo is based on the order of tx, my solution to this issue is `save-current-block!` before every indent/outdent so that logseq can generate the correct order of tx.
I also added an e2e test to ensure the fix is working.
=> fix(editor): incorrect undo/redo sequence of indent/outdent

src/electron/electron/handler.cljs
fixes #7573
Examples:
The Error messages are not very pretty but functional enough for the user to figure out the problem IMO.
=> fix: Add error notification if graph can't be opened

src/main/frontend/components/block.cljs
closes https://github.com/logseq/logseq/issues/7054
--
The call to `security/sanitize-html` was previously being called on a Clojurescript map (`{:html &gamma; ...}`), but in reality the `:html` should be called first to extract the `&gamma;` from the map, then it can be sanitized!
Super small diff to fix a super annoying and long-standing bug!
=> Fix: rendering of inline symbols #7054

src/main/frontend/components/search.cljs, src/main/frontend/state.cljs
Fix small bug that was introduced in #7805 -
https://sentry.io/organizations/logseq/issues/3857043471/?project=5311485&query=is%3Aunresolved&referrer=issue-stream. Also added a malli schema for the offending fn so future stacktraces lead to the buggy UI component. To QA this, Cmd-k and then click on the command palette icon (furthest right)
=> Fix search tippy component failing

src/main/frontend/components/block.cljs
Fixes the issue described in #2398 by allowing tables to widen when the user switches to wide mode.
=> fix tables not widening in wide mode (#2398)

src/main/frontend/components/block.cljs
- refactor: use macro->text instead of str concat
Related to https://github.com/logseq/logseq/pull/8164/commits/344103e56ed4b571b1c4f34cb5c346bf907ff52f in PR https://github.com/logseq/logseq/pull/8164
- fix(macro->text): remove redundant brackets
The macro name and argument are enclosed by {{}} rather than {{{}}} 
=> fix: remove extra braces for some incorrect macro usages

src/main/frontend/components/editor.cljs
When switching pages with modals open, `.editor-wrapper` might be a `null`.
=> fix(ui): null while query .editor-wrapper

e2e-tests/fixtures.ts
E2E tracing is fully functioning. Introduce a per-file toggle `traceAll()` in `fixtures.ts`
With the toggle invoked in a E2E test file, the tracing file will be dumped in the CI artifacts (if test failed)
To open dumped trace file: ` npx playwright show-trace <blablabla.dump>`
Be care: dump file is relatively big (1MB per sec.)
=> test(e2e): fix E2E tracing file dump

Dockerfile
Addresses Clojure Docker images breaking change: [groups.google.com/g/clojure](https://groups.google.com/g/clojure/c/eNLvJMEchM8)
> Wes Morgan July 25th 2022:
> Upstream has recently announced that even the old
> openjdk:8 and openjdk:11 images are being deprecated and
> will no longer receive updates (security and otherwise).
>
=> chore(webapp): migrate 🐋 builder image from openjdk to temurin

src/main/frontend/schema/handler/common_config.cljc
=> Fix: Allow keywords for macros in config.edn

src/main/frontend/extensions/code.cljs
stop propagation and preventDefault of event on wrapper element of CodeMirror editor
1. Create a code block.
2. Click on or select some codes on the block.
3. Press `Cmd+[` to indent the code or `Cmd+]` to outdent the code.
4. If the web browser can go back or forward to other pages, it will do that.
https://user-images.githubusercontent.com/28241963/213966830-01c1f73b-ae85-4182-ad5c-61e91cb8c1c0.mp4
https://user-images.githubusercontent.com/28241963/213966891-3c53bb51-de6f-46cf-9852-00bbd7e244a7.mp4
=> fix: CodeMirror indenting shortcuts cause page routing

tldraw/apps/tldraw-logseq/src/hooks/usePaste.ts, tldraw/apps/tldraw-logseq/src/lib/shapes/TweetShape.tsx
- We now try to create a shape on DataTransfer (dnd) or ClipboardItem (paste) based on `text/plain` first. If that fails, we use `text/html` to create a shape. As a last resort, we use `text/plain` again to create a new block with plain text. The reason behind this choice is that when both `text/plain` and `text/html` are available, it probably makes sense to attempt  creating an embed based on a raw url first, The preferred order is debatable, but I think this is a better default. Resolves #8407
- Added a min width to tweet shape.
=> Fix (Whiteboards): paste type order

src/main/frontend/components/whiteboard.cljs
Do not show whiteboards tour on demo graph.
See https://discord.com/channels/725182569297215569/1065425525683785818/1065425525683785818
=> fix (witeboards): disable onboarding tour on demo graph

templates/config.edn
- add :arweave/gateway configuration option
- add :custom-js-url configuration option
- add :feature/enable-whiteboards? configuration option
- add :journal/page-title-format configuration option
I followed the order and wording style of the current configuration options as good as I could.
=> fix: add missing user-config options

.github/ISSUE_TEMPLATE/bug_report.yaml
The short and simple description at `ask-pr` may confuse people, especially the user. They may check this box without any understanding of what a PR is or what actually happens if the box is checked. For example, see https://github.com/logseq/logseq/issues/8438 and https://github.com/logseq/logseq/issues/8371.
=> enhance(issue-template): add description to `ask-pr`

.clj-kondo/config.edn, src/main/frontend/components/content.cljs, src/main/frontend/components/page_menu.cljs, src/main/frontend/handler/common/developer.cljs, src/main/frontend/handler/events.cljs, src/main/frontend/modules/shortcut/config.cljs, src/main/frontend/modules/shortcut/dicts.cljc
This PR adds a couple nice things for developers and a clear all notifications command. The developer improvements:
* Block AST inspector
* Page AST inspector
* Make all dev menu items available as commands
To QA commands, invoke any of the 4 dev commands and it will use the last editing state to invoke the page or block functionality. The new ast menu items can be found off any block or page level menu
=> Enhancement: Add dev ast inspector menu items, dev commands and clear all notifications command

src/main/frontend/components/whiteboard.cljs, tldraw/apps/tldraw-logseq/src/components/ContextBar/ContextBar.tsx, tldraw/apps/tldraw-logseq/src/lib/shapes/LogseqPortalShape.tsx, tldraw/packages/react/src/components/HTMLLayer/HTMLLayer.tsx, tldraw/packages/react/src/components/SVGLayer/SVGLayer.tsx, tldraw/packages/react/src/components/ui/DirectionIndicator/DirectionIndicator.tsx, tldraw/packages/react/src/hooks/useCursor.ts, tldraw/packages/react/src/hooks/useStylesheet.ts
This PR improves the performance and the perceived responsiveness of whiteboards by
- Lazy loading the previews on WB dashboard. Navigating to dashboard should now feel smoother.
- Loading the content of portals after rendering the wrapper. Rendering an empty portal with the correct dimensions once, allows fast loading heavy on portals canvases. The content of portals will be lazily loaded when we are already viewing the whiteboard.
- Improving the performance of panning. It could previously take more than a second to start panning on a complicated canvas, due to calling setProperty to change the cursor.
=> perf(whiteboards): enhance whiteboards performance & responsiveness 🚀

src/main/frontend/components/find_in_page.cljs, src/main/frontend/handler/search.cljs, src/main/frontend/util.cljc
close https://github.com/logseq/logseq/issues/7761
close #7212
The experience isn't great when searching the contents of pages, especially when using a Pinyin IME, but I've finally figured out how to fix it.
A react ref  `*composing?` is created to represent the current IME composing state. The state will be mutated in `on-change-fn`. `on-change-fn` is also registered to `:on-composition-start` and `:on-composition-end` to listen to composition events. For more information about `:on-composition-start` and `:on-composition-end`, check: https://reactjs.org/docs/events.html#composition-events.
If `composition-start`, cancel the pending debounced function callback. This can be prevented from being interrupted by `electron-find-in-page!` when you type some letters and then quickly switch to …
=> fix: searching in page defers while entering Chinese character using a Pinyin IME

docs/develop-logseq-on-mobile.md
This command runs properly on my M1; the one listed before gives the error `arch: posix_spawnp: gem: Bad CPU type in executable`
=> docs: Fix arch/sudo command in instructions

deps/graph-parser/src/logseq/graph_parser/util/db.cljs, src/main/frontend/date.cljs, src/test/frontend/db/query_react_test.cljs
This adds support for `:query-page` as an input for advanced queries. This resolves issues such as #6528 (I'll look up more issues in a moment).
Logseq at the moment provides a `:current-page` and `<% current page %>` input type that resolves to the page open in the current window. Embedding blocks that contain any queries using these inputs causes the results to change depending on where the block is shown. This adds an alternate input `:query-page`, that will resolve to the page of the block of that query originally comes from.
Currently this does not add `<% query page %>` to simple queries, as we are not currently providing the current block id to simple queries which makes it a little tricker, and this is namely to support the journal day queries in advanced queries. That …
=> Adds support for :query-page as an input

src/main/frontend/components/onboarding/setups.cljs, src/main/frontend/components/repo.cljs, src/main/frontend/components/widgets.cljs
The current behavior of clicking `Add new graph` on browsers with no native FS API support is a silent dead.
After this PR the button will bring user to the page with fallback message:
=> enhancement: no native FS API support display for web version

src/main/frontend/components/block.cljs
To reproduce, add 
```markdown
```
the link will be `file:///logseq_local_bingo/assets/https:/cdn.hacklog.sh/vid-2023-01-27_16-13_22.mp4`.
- closes:  #8477
=> fix: assets url wrong path

deps/graph-parser/src/logseq/graph_parser/extract.cljc, deps/graph-parser/src/logseq/graph_parser/test/docs_graph_helper.cljs, deps/graph-parser/test/logseq/graph_parser_test.cljs, src/test/frontend/handler/repo_conversion_test.cljs
This PR fixes property values not showing their full text in query tables. This is the same issue as https://github.com/logseq/logseq/issues/8227 but for page results. See https://linear.app/logseq/issue/LOG-2374/fix-page-property-values-in-query-tables-not-displaying-full-text for more
Before:
After:
To QA the fix:
- Create a page with content
```
desc:: mixing #foo and bar
```
- Then query it with `{{query (page-property :desc)}}` and switch to table view
=> Fix: Page blocks not displaying full property values in query tables

.clj-kondo/config.edn, src/main/frontend/components/page_menu.cljs, src/main/frontend/handler/common/developer.cljs, src/main/frontend/handler/page.cljs, src/main/frontend/util/page.cljs
This PR enhances some of the behavior for file related commands, fixes #8117 and ports those improvements to dev commands in #8450. The file related commands are "Copy current file", "Open file in default app", and "Open file in parent directory". One enhancement is that these file commands will work in journal pages that have been edited after going home (a common workflow in my experience). Previously nothing happened.  Another enhancement is that when a file isn't found, the user is given a warning notification.
To QA:
- file commands display a "No file found" warning: type 'gh', invoke a file command
- file commands work in edited journal contexts: type 'gh', edit a journal page, invoke a file command
- dev page commands work in navigation contexts: type 'gh', navigate to a page by …
=> Enhancement: File and page commands work in more contexts and warn when they don't work

package.json, resources/package.json, src/electron/electron/file_sync_rsapi.cljs, static/yarn.lock, yarn.lock
- Add native logging implementation, 
- now all Logseq Sync logs will be written to:
- `~/Library/Logs/Logseq/main.log`
- `C:\Users\USER_NAME\AppData\Roaming\Logseq\logs\main.log`
- ?? Linux `~/.logseq/...`
- Update age-encryption, try to fix #8497
=> enhance(sync): add native logging for desktop and android

src/main/frontend/mobile/intent.cljs, src/main/frontend/quick_capture.cljs, src/main/frontend/util/text.cljs
- add `[:quick-capture-options :default-page]` config, for default page of quick-capture (other than current-page and today-page)
=> fix(android): share with no url

src/main/frontend/handler/user.cljs, src/main/frontend/state.cljs
See https://discord.com/channels/725182569297215569/1070813646143369268
Logged out users should't be able to visit whiteboards, even if the have previously enabled the feature. The feature should also be off and disabled under Settings->Features.
`frontend.handler.user/feature-available?`  explicitly  checks for the logged-in state and also the feature-matrix, so it should be a better option regardless. The problem is that the previous implementation should also work. The underlying issue seems to be that `user-groups` are not cleared from the local storage upon logout, so I changed that too although it's not required in this case. My only concern that this could affect sync's behavior. A signed out user shouldn't be marked as `beta` or `alpha`, but I might be missing something (see …
=> Fix: Access to features

deps/graph-parser/src/logseq/graph_parser/block.cljs
The `convert-page-if-journal` is repeatly called in building reference.
This PR improve re-index performance by 20%~25% 
* From 25% -> 5%
Remaining time-costing stages in re-index:
* Datomic transact - 30% (bottle-neck)
* Mldoc parsing - 30% (can be off-load to worker?)
* Search index building - 5%
=> enhance: re-index performance

src/main/frontend/handler/editor.cljs, src/test/frontend/handler/editor_test.cljs
This PR fixes command completion triggering too often, especially in the middle of words e.g. typing out a url. It has been annoying enough that [users wanted to remap '/'](https://discuss.logseq.com/t/custom-command-trigger/3081) to get around this. This PR also fixes #5510 to make typing a single '/' easier. By improving command completion, the experience should be great and we can deprecate `:editor/command-trigger`. To QA this PR, try any of the test cases
=> Fix: Command completion triggering too often

src/main/frontend/components/block.cljs
=> fix(pdf): remove prefix(`@`) checking for links of org mode page

src/main/frontend/handler/repo_config.cljs
This PR improves the error experience when a config.edn is invalid while they are trying to use it from the Settings UI. Currently there is silent (js console only) failure so we should let them know something is wrong. This error shouldn't happen much once [config validation](https://github.com/logseq/logseq/pull/8382) has been used by most. Some examples of these errors are https://logseq.sentry.io/issues/3930076858/?project=5311485&referrer=slack and https://logseq.sentry.io/issues/3928852010/?project=5311485&referrer=slack.
=> Fix: Display error when unexpected invalid repo config.edn occurs

src/main/frontend/db/model.cljs, src/main/frontend/handler/editor.cljs, src/test/frontend/db/model_test.cljs, src/test/frontend/handler/editor_test.cljs
This PR builds off #8546. This fixes https://github.com/logseq/logseq/issues/6805 and https://github.com/logseq/logseq/issues/8175 by keeping the tag menu open instead of abruptly closing for multiple tags in a block. This also fixes property values that are references not autocompleting their reference characters. For example, property values like `[[Class]]` complete as `Class` and lose valuable refs. I noticed this with the docs graph. To QA, try the scenarios in tests.
=> Fix: Tag and property value autocompletion cases

tldraw/apps/tldraw-logseq/src/components/ContextBar/contextBarActionFactory.tsx
Introduced here https://github.com/logseq/logseq/pull/8448/files
Use the collapse toggle on a portal element to test this
=> fix (Whiteboards): Toggle collapsed button action

docs/develop-logseq.md
Hi there,
This is LA, I love to use Clojure/Script and reading PDF within Logseq. But when I try to contribute to Logseq I found that it doesn't have a document about how to connect REPL in the docs. Development experience is crucial in Clojure world, missing REPL setup feels like unforgivable. I'm not sure my config is universal correct, but at least it works for me. It would be better core dev team can share their REPL setup to other contributors.
=> docs: add repl setup to development document

resources/css/show-hint.css, src/main/frontend/extensions/code.cljs, src/main/frontend/schema/handler/common_config.cljc, tailwind.all.css
- Add auto-completion for editing `config.edn`
- triggered by "ctrl+space" or ":"
- config key completion
- nested config key completion(max level 2)
- boolean/enum value completion
- rename `cm` to `CodeMirror` in `code.cljs` according to the same naming rule of JavaScript
Known Issues:
- duplicated keys are detected by regexp over the whole document(ugly but works)
- cursor position is at the end of `""`, `{}`, `[]` after completion, should be in the middle of the enclosure
- maili has some bug in fetching the current schema(I can not fetch some info by mu/properties, mu/type-properties, .... )
- enabled by `edn` mode, not depending on config file names/paths
- CSS of Auto-completion UI is copied from codemirror, not changing according to the current theme setting
- syntax errors are …
=> Feat: auto-completion for config editing

src/main/frontend/schema/handler/common_config.cljc, templates/config.edn
This PR fixes #8580. To QA:
- Toggle a favorite on a page with `"mod+shift+f"`
- Add `:command/toggle-favorite false` to :shortcuts in config.edn
- Confirm toggling favorite no longer works
=> Fix: shortcuts can be disabled with `false`

src/electron/electron/core.cljs, src/main/electron/listener.cljs
close https://github.com/logseq/logseq/issues/3549
Some menu items are not fixed because they rely on `Event` object.
=> fix: electron menu handler(Redo, Undo, Copy)

src/main/frontend/components/commit.cljs, src/main/frontend/modules/shortcut/config.cljs
Went to QA the git commit command from https://github.com/logseq/logseq/pull/7808 and noticed that the command only works with the keybinding and not when selected from the command palette:
Removed most of the event handler logic as it was outdated from when it was keydown based - https://github.com/logseq/logseq/commit/5d0ecd68b2d5394db058bf7cdc3d0b359420effa
=> Fix: git commit command not opening

src/main/frontend/components/block.cljs, src/main/frontend/extensions/pdf/pdf.css
=> fix(ui): marker layout of area highlight ref block content

tldraw/packages/core/src/lib/TLViewport.ts, tldraw/packages/core/src/lib/tools/TLSelectTool/states/BrushingState.ts, tldraw/packages/core/src/lib/tools/TLSelectTool/states/ResizingState.ts, tldraw/packages/core/src/lib/tools/TLSelectTool/states/TranslatingState.ts
A common feature on 2D applications is auto panning to pointer position. When we move our mouse out of the visible canvas while dragging, selecting or resizing elements, the viewport should be adjusted so we don't have to stop the action to pan (see demo video).
I don't think we need to document this. It's considered standard behavior on similar applications.
Also see https://discord.com/channels/725182569297215569/1054782990435229806/1054782990435229806
[Screencast from 2023-02-13 21-38-43.webm](https://user-images.githubusercontent.com/10744960/218557729-b403ef19-2449-48db-9f95-9207637daf10.webm)
=> feat (Whiteboards): Auto pan canvas to pointer when out of view

src/electron/electron/core.cljs, src/main/electron/listener.cljs
Reverts logseq/logseq#8466
The original PR breaks Copy&Pasting in the Developer console.
=> Revert "fix: electron menu handler(Redo, Undo, Copy)"

src/main/frontend/components/settings.cljs
This pull request fixes the incorrect version control description in the settings (please see issue: #8665). The original description stated that users can view a page's edit history by clicking on three vertical dots in the top-right corner and selecting "Check page's history". However, the three dots were actually horizontally aligned and the menu item said "View page history" instead of "Check page's history".
Please let me know if there are any concerns or questions about this pull request. Thank you.
=> Fix incorrect version control description in settings

.github/workflows/build-desktop-release.yml, resources/forge.config.js
Apple said they need some workdays to migrate developer certificates from individual to organization.
=> fix: disable macos sign temporarily

deps/graph-parser/src/logseq/graph_parser/block.cljc, deps/graph-parser/src/logseq/graph_parser/block.cljs, deps/graph-parser/test/logseq/graph_parser/block_test.cljs
To reproduce:
1. Create a new file `test.md` in a graph with the content as below:
```
- foo
id:: 63f199bc-c737-459f-983d-84acfcda14fe
- bar
id:: 63f199bc-c737-459f-983d-84acfcda14fe
```
2. Notice that Logseq can't load the blocks in the `test` page
3. Write some content on the page `test`, the file content will be overwritten without any warning
Caveat: this PR will keep the bottom block's id and generate new ids for the above block, it's easier to implement but may not be the user's intention.
The same block ids across different files could happen too, I will address it in another PR.
=> fix: duplicate block ids in same file

src/main/frontend/handler/editor.cljs, src/main/frontend/handler/paste.cljs, src/test/frontend/handler/paste_test.cljs
fix [#8640](https://github.com/logseq/logseq/issues/8640)
Now the logic of pasting from the clipboard after selecting some contents as below:
- If the selected content is part of a link, replace it from the clipboard instead of formatting it to a link
- If the selected content is not part of a link
- If the selected content is a URL, format it to a link and make content from the clipboard as the label of the link
- If the selected content is not a URL, format it to a link and make it the label of the link and content from the clipboard as the URL of the link
- If the selected content and content from the clipboard are both URL, replace it
=> enhance: paste from clipboard

src/main/frontend/extensions/srs.cljs
This is more-or-less also a feature request.  It works, but the design may not be the best.  I'm glad to improve it if you decide this is a worthwhile addition to Logseq.
SRS users usually need some "cues" to restrict possible answers of a cloze.  For example, 
```
#card Apples are {{cloze red}} (color).
```
AFAIC, this approach has two issues:
1. It takes a bit longer time to input.
2. The display in the flashcard interface looks bad.  The cue is not part of the cloze, so it stays there after the cloze is revealed.
Especially consider this example:
Therefore, it's desired that the cue could be directly combined with the cloze itself.
This PR proposes a syntax addition to the `cloze` macro.
- Before: `{{cloze <answer>}}`
- After:  `{{cloze <answer> [\\ <cue>]}}`  ([...] = optional)
I …
=> feat(srs): support cloze cues

deps/graph-parser/src/logseq/graph_parser/block.cljs, deps/graph-parser/test/logseq/graph_parser/block_test.cljs
This PR adds support for block refs in properties to show up as block backlinks. This should bring blocks to parity with pages as far as ability to be referenced
This fixes https://github.com/logseq/logseq/issues/5286, https://github.com/logseq/logseq/issues/8594 and https://github.com/logseq/logseq/issues/5796. Also adds some tests for timestamp blocks as there was nothing to test its functionality
To QA:
create one page with:
```
- A block
id:: 63f528da-284a-45d1-ac9c-5d6a7435f6b4
- Link to  ((63f528da-284a-45d1-ac9c-5d6a7435f6b4))
- B block
author:: ((63f528da-284a-45d1-ac9c-5d6a7435f6b4))
```
Create another page with:
```
ref:: ((63f528da-284a-45d1-ac9c-5d6a7435f6b4))
```
Observe there are 3 references to the first block
=> Enhance: Add support for block refs in properties to backlink to blocks

.clj-kondo/config.edn, .clj-kondo/hooks/path_invalid_construct.clj, src/main/frontend/components/block.cljs, src/main/frontend/components/hierarchy.cljs, src/main/frontend/db/conn.cljs, src/main/frontend/fs/nfs.cljs, src/main/frontend/fs/sync.cljs, src/main/frontend/handler/page.cljs, src/main/frontend/util.cljc, src/main/frontend/util/text.cljs
Lint those exprs that use `string/join` to construct the path:
`(string/join "/" [...])`
@andelf is working on a unified way(for different platforms) to do path-related operations.
=> dev(lint): add :path-invalid-construct/string-join linter

src/electron/electron/utils.cljs
=> fix(electron): global config dir name under windows

src/main/frontend/components/plugins.cljs, src/main/frontend/handler/plugin_config.cljs
Fixes #8726. Not sure what changed but looks like this should be opening as a sub-modal since it's under the plugin modal. To QA, just follow the referenced bug's instructions
=> Fix: Plugins menu item not opening from plugins dashboard

src/main/frontend/handler/common/config_edn.cljs, src/test/frontend/handler/common/config_edn_test.cljs
=> enhance(ui): add better error messages for duplicate key in config.edn

tldraw/apps/tldraw-logseq/src/styles.css, tldraw/packages/react/src/components/ui/SelectionForeground/SelectionForeground.tsx
Allow overflow on portal elements to display autocomplete components. The border radius fixes the background component that is used for coloring.
See https://discord.com/channels/725182569297215569/1080832699255758961/1080832699255758961
and https://github.com/logseq/logseq/pull/8652#issuecomment-1439505679
=> Fix (Whiteboards): Autocomplete on portals

src/main/frontend/components/plugins.css, src/main/frontend/components/plugins_settings.cljs
If there is no `descrition` value in config, header looks not good. I've missed this case 😕
As there is no (in whole file) checks for empty values, will add just CSS solution
update for https://github.com/logseq/logseq/pull/8643
=> fix: hide empty settings description

resources/css/common.css, src/main/frontend/handler/common/config_edn.cljs, src/main/frontend/handler/file.cljs, src/main/frontend/ui.cljs, src/test/frontend/handler/common/config_edn_test.cljs
Per https://linear.app/logseq/issue/LOG-2402/deprecation-warning-for-editorcommand-trigger-config, display a deprecation warning for the :editor/command-trigger config option when it is detected. Deprecation setup is reusable for any config keys in the future should we need to migrate or deprecate future keys
To QA:
- With an unparseable config file - detection is skipped
- With a config file containing :editor/command-trigger - warning displayed
- Any other config file - nothing different happens
=> Chore: Add deprecation for :editor/command-trigger config

src/main/frontend/components/block.cljs
How to reproduce:
1. Create a page `Test` with the content
```
- [[foo]] test
```
2. Click the `[[foo]]` reference
3. In the linked references, a lower-case page `test` is displayed instead of its original name `Test`.
=> fix: display page's original name when possible

deps.edn, src/main/frontend/extensions/pdf/assets.cljs, src/main/frontend/extensions/pdf/core.cljs
related https://github.com/logseq/logseq/issues/8735
For this issue, the main reason is that serializing large highlights data to the file system is so slow with clojure.core internal solution. so this PR is trying to do this work with a three-party library https://github.com/brandonbloom/fipp,  it's about 2 to 3 times faster than the built-in solution. This PR is a quick patch, not a final solution!
=> enhance(pdf): UI lag for the case of large highlights data

e2e-tests/whiteboards.spec.ts, src/main/frontend/extensions/tldraw.cljs, src/main/frontend/handler/whiteboard.cljs, src/main/frontend/modules/editor/undo_redo.cljs, src/main/frontend/modules/outliner/pipeline.cljs, tldraw/apps/tldraw-logseq/src/lib/shapes/LogseqPortalShape.tsx, tldraw/packages/core/src/lib/TLHistory.ts, tldraw/packages/core/src/types/types.ts
Is some cases we had to persist a new state by replacing the last history entry, instead of pushing a new one.
The related block was removed here https://github.com/logseq/logseq/pull/7786/files#diff-f8d520c32e2ccdf12b14a130b819d3ecbc21284ceabab9ac1ed48d2cab65f272L68-L70
As a result, calling `app.persist(true)`, disregards the boolean and always pushes a new entry. For example, if you drag and drop a block into the canvas and then undo the action, you will notice that there are intermediate history entries that shouldn't exist. There is a similar problem with tweet shapes and iframes.
I think we can achieve a similar result by setting `:whiteboard/transact?` to false and by using the existing `:compute-new-refs?` that seems to swap the data of the last undo entry.
Fixed another bug …
=> Fix (Whiteboards): History issues

src/main/frontend/handler/paste.cljs, src/test/frontend/handler/paste_test.cljs, src/test/frontend/handler/plugin_config_test.cljs
fix #8810, #8809
We should not change the data or text in clipboard but keep it unchanged while `raw-pasting?` is true.
=> fix(paste): do not convert url to macro while raw pasting

src/main/frontend/components/editor.cljs, src/main/frontend/components/editor.css
=> fix(ui): incorrect position of absolute modal on some mobile platforms

src/main/frontend/handler/editor.cljs
Previously, undo cycle todos needed multiple steps.
Before:
https://www.loom.com/share/5513dde568d74d3f9bb5c4d0138dfd71
After:
https://www.loom.com/share/c51a82b549294084a3e72529995e03c8
=> fix: undo cycle todos

src/main/frontend/components/block.cljs
This is a temporary fix. To avoid showing empty block content, a fix in parser is required.
To reproduce:
1.  edit
2. render
3. Click a bullet with empty content, the router will nav to a blank page
=> fix(editor): avoid nav to block with empty uuid

e2e-tests/hotkey.spec.ts, e2e-tests/page-rename.spec.ts, e2e-tests/page-search.spec.ts, e2e-tests/utils.ts, src/main/frontend/components/content.cljs, src/main/frontend/handler/editor.cljs, src/main/frontend/state.cljs, src/main/frontend/util.cljc
This PR will select the current block only when the context menu for this specific block has been opened.
It also disables the global shortcuts to prevent any further operations on selected blocks.
Before:
https://www.loom.com/share/2fa708a32c284ae5948083efd99ae7b1
After:
https://www.loom.com/share/0b4dd4be985a46ae91f3760b3ea28445
=> fix: select only the current block when open its context-menu

e2e-tests/whiteboards.spec.ts, src/main/frontend/components/whiteboard.css, src/main/frontend/handler/whiteboard.cljs, tldraw/packages/core/src/lib/TLHistory.ts, tldraw/packages/core/src/lib/TLPage/TLPage.ts
- Fixed persisting and undoing shape index changes. To reproduce the issue, place shapes on top of each other and click `[` or `]` to change their order. After changing their original order, navigate to a different page or undo the action. You will see that the index changes are not persisted, and cannot be undone. Reintroduced the index property of shapes to fix persist. If the current index is different from the shape index, we update its nonce. Also added `update-shapes-index` to update the order on undo/redo. I removed `bump` from page, since it doesn't do anything anymore.
- Fixed an issue with arrow bindings and undo/redo, To reproduce this, create two shapes, connect them with an arrow, delete one of them, undo the delete action and move the previously deleted shape. The arrow …
=> Fix (Whiteboards): Shape index and arrow binding issue

src/main/frontend/components/block.cljs, src/main/frontend/components/query_table.cljs, src/test/frontend/components/query_table_test.cljs
This PR adds a :page column for block results as asked for at https://discuss.logseq.com/t/add-pagename-field-to-the-list-of-table-fields-in-simple-query/15176/2 and https://discuss.logseq.com/t/query-table-view-display-the-page-title-when-block-result-is-a-page-property-block/4716. To QA try the test example. This PR also fixes a query result count in the list view per steps in #8586
=> Enhance: Add page column for query tables with block results

src/main/frontend/components/block.cljs, src/main/frontend/handler/whiteboard.cljs, src/main/frontend/state.cljs, tldraw/apps/tldraw-logseq/src/lib/preview-manager.tsx, tldraw/apps/tldraw-logseq/src/styles.css
- Check if snapshot pages exist (resolves https://github.com/logseq/logseq/issues/8886)
- Fix breadcrumbs without label (resolves https://github.com/logseq/logseq/issues/7087 - not a whiteboards specific issue)
- Maintain original page name when we create a new page within a whiteboard (resolves https://github.com/logseq/logseq/issues/7811)
- Allow scrolling on tools (resolves https://github.com/logseq/logseq/issues/8364). This might not be the perfect solution, but it allows access to the tools that overflow the screen.
- This PR also reverts https://github.com/logseq/logseq/commit/cb2c1f1d6a466c821ae104ff445029e3dee0ef2e that seems to be causing focus issues on inputs. If you click to edit a page title and then click again somewhere in the middle of the input, the focus will be lost. …
=> Fix (Whiteboards): An attempt to fix most of the remaining issues

templates/config.edn
`:ignored-page-references-keywords` should use `#{:author :startup}`.
=> config: update default templete to correct format

src/main/frontend/components/query/builder.cljs, src/main/frontend/components/query/builder.css, src/main/frontend/template.cljs
close #8900
This PR also fixed #8903 that `<% current page %>` resolves to a zoomed block instead of its page.
=> fix: broken simple queries

src/main/frontend/config.cljs, src/main/frontend/handler/editor.cljs
=> fix(fs): asset url calculation

src/main/frontend/components/block.cljs, src/main/frontend/components/block.css, tldraw/apps/tldraw-logseq/src/styles.css
=> fix: query with breadcrumbs show blocks on wrong hierarchy

src/main/frontend/handler/paste.cljs, src/test/frontend/handler/paste_test.cljs
Fixes #8926 . This bug was accidentally introduced in https://github.com/logseq/logseq/pull/8815. To QA, enable the file pasting config, copy an image from html like https://user-images.githubusercontent.com/38045018/228234385-cbbcc6b2-1168-40da-ab3e-1e506edd5fce.png. Paste should create an asset
=> Fix: Pasting a file when file pasting is preferred 

e2e-tests/editor.spec.ts, e2e-tests/logseq-url.spec.ts, src/main/frontend/components/export.cljs, src/main/frontend/extensions/pdf/assets.cljs, src/main/frontend/extensions/pdf/core.cljs, src/main/frontend/extensions/tldraw.cljs, src/main/frontend/handler/common.cljs, src/main/frontend/handler/editor.cljs, src/main/frontend/handler/paste.cljs, src/main/frontend/modules/outliner/core.cljs, src/main/frontend/state.cljs, src/main/frontend/util.cljc, src/main/frontend/utils.js, src/test/frontend/handler/paste_test.cljs
fix #8924
This PR adds a custom `web application/logseq` type for the internal paste item in clipboard, check this [link](https://developer.chrome.com/blog/web-custom-formats-for-the-async-clipboard-api/) for more details on clipboard's web custom formats. 
Test:
=> fix: internal blocks paste

src/main/frontend/components/block.cljs
Fix #8925 and fix #8950. To QA, try a default-query, a simple query and and advanced query. The fix should only show up in a default query e.g.:
=> Fix: Bring back result count for built-in queries

.clj-kondo/config.edn, src/electron/electron/backup_file.cljs, src/electron/electron/configs.cljs, src/electron/electron/core.cljs, src/electron/electron/git.cljs, src/electron/electron/handler.cljs, src/electron/electron/plugin.cljs, src/electron/electron/search.cljs, src/electron/electron/server.cljs, src/electron/electron/updater.cljs, src/electron/electron/utils.cljs, src/electron/electron/window.cljs, src/main/frontend/fs/sync.cljs, src/main/frontend/mobile/intent.cljs, src/main/frontend/util/fs.cljs, src/test/frontend/fs_test.cljs, src/test/frontend/handler/plugin_config_test.cljs, src/test/frontend/test/helper.cljs
This is a follow up to https://github.com/logseq/logseq/pull/8792#discussion_r1145228387 so that the path alias doesn't have conflicting namespaces
=> Chore: Consistent "path" aliases

.clj-kondo/config.edn, .clj-kondo/hooks/path_invalid_construct.clj, .clj-kondo/hooks/regex_checks.clj, src/main/frontend/util/fs.cljs
Following up the fix https://github.com/logseq/logseq/pull/8927
This PR is just introducing a check to the `string/replace`, no actual logic modified.
This PR is to avoid mistakenly escaping special characters with double slashing `\\` and create unexpected results (see https://github.com/logseq/logseq/pull/8927/files)
It's easy to make the mistake. Similar mistake happens in the legacy code (but it doesn't affect the actual result for this line) https://github.com/logseq/logseq/blob/1519e35e0c8308d8db90b2525bfe7a716c4cdf04/src/main/frontend/util.cljc#L892
TODO: introduce the check to other functions accepting regex?
Seems clj-kondo doesn't have a hook to analyze all Regex nodes
=> clj-kondo: check regex error prone double escaping

src/main/frontend/extensions/html_parser.cljs, src/test/frontend/extensions/html_parser_test.cljs
This PR adds missing `\t` to the md/org converted from HTML, it also fixed the converting result for org mode (using `*` instead of `-` for blocks)
To reproduce:
1. Create a page on http://localhost:3001
2. Create a block `a` with a child block `b`
```
- a
- b
```
3. Copy both blocks to the Logseq Electron app, the indentations will be gone.
=> fix: paste html

src/main/frontend/handler/editor.cljs
> BUG: I pick an image from the desktop and drop it into the whiteboard that's possible but nothing happens, just a ring spinning forever (in Win 10). is it a feature not so well implemented yet or a problem of my pc or win 10?
=> fix(fs): whiteboards drop file on win32

src/main/frontend/handler/assets.cljs
Replace #8843 
fixes #4401
fixes #4859
fixes #8533
QAed:
```markdown
- ![local pdf with file:// url + options](file:///path/to/SSD1608%232.pdf#page=2&zoom=200) sss
- ![local pdf](../assets/Tang#Nano.pdf) local pdf
- ![online pdf](https://cursedhardware.github.io/epd-driver-ic/SSD1619A.pdf)
- ![online pdf with encoded chars](https://hy.cnki.net/File/WS/2/1/1%20%E6%96%B0%E6%97%B6%E6%9C%9F%E5%9B%BE%E4%B9%A6%E9%A6%86%E7%9A%84%E8%BD%AC%E5%9E%8B%E4%B8%8E%E5%8F%91%E5%B1%95%20%E2%80%94%EF%BC%88%E7%B4%A2%E4%BC%A0%E5%86%9B%EF%BC%89.pdf)
- ![local pdf with file:// url](file:///path/to/SSD1608%232.pdf) sss
- ![local full path](/path/to/SSD1608#2.pdf)
```
Unimplemented
```markdown
- ![local pdf with file:// url + options](file:///path/to/SSD1608%232.pdf#page=2&zoom=200)
```
Buggy:
- Link to absolute …
=> fix(editor): assets link resolve

src/main/frontend/handler/user.cljs
when users register account with username having non-ascii code, app will throw err like this
`Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.`
fix #8929
=> fix: decode username for jwt

src/main/frontend/handler/editor.cljs
To reproduce:
1. add `- NOW test` in the current journal page
2. put the cursor in the beginning of the first block in the default NOW query
3. press `backspace`
The block will be deleted. 
In most situations, it doesn't make sense to concat two blocks in the query result, so Delete at the end of any block in the query result is disabled too.
=> fix: disable backspace from the start and delete at the end for query

ios/App/App.xcodeproj/project.pbxproj, src/main/frontend/components/file_sync.cljs, src/main/frontend/config.cljs, src/main/frontend/fs/capacitor_fs.cljs, src/main/frontend/handler.cljs, src/main/frontend/handler/events.cljs, src/main/frontend/mobile/core.cljs, src/main/frontend/mobile/graph_picker.cljs, src/main/frontend/mobile/util.cljs
Releated #9002
BUG: `ios-ensure-documents!` is called after `persist_var` loading
Other fixes:
- Graph names with special chars
- Await iOS folder creation, (1s wait)
- Handle exceptional cases for folder selection: top iCloud directory, no permission
Chore:
- iOS version is bumped, allowing for the TestFlight release.
=> Fix: ios path handing

src/main/frontend/components/content.cljs, src/main/frontend/components/page_menu.cljs, src/main/frontend/dicts.cljc
Replace all explicit text with i18n text in the context menu, if missing, add new key to dicts.
Add shortcut key prompts to the context menu, if available.
=> replace all explicit text with i18n text in the context menu

e2e-tests/editor.spec.ts, src/main/frontend/commands.cljs, src/main/frontend/handler/editor.cljs
=> fix: hash tags enclosed in double brackets is broken

src/main/frontend/components/query/builder.cljs, src/main/frontend/components/select.cljs
=> enhance(ux): add an apply button to multiple selects in query builder

docs/develop-logseq-on-windows.md
This PR simplifies the Windows development setup documentation, specifically:
* Uses `winget` for installing pre-requisites.  This is installed by default on modern windows and is now the "standard" package manager.
* Use clj-msi to install clj.exe, rather than the clojure-tools powershell module.  This allows the build to work without modifying package.json
* Remove build instructions that are out of date and now inconsistent with the develop-logseq.md doc.
=> Simplify Windows development docs

README.md
Change the link to shields.io for a cleaner look of the twitter badge.
=> fix: twitter badge in readme

tldraw/apps/tldraw-logseq/src/components/inputs/ColorInput.tsx, tldraw/apps/tldraw-logseq/src/lib/shapes/LogseqPortalShape.tsx, tldraw/apps/tldraw-logseq/src/lib/shapes/style-props.tsx, tldraw/apps/tldraw-logseq/src/styles.css, tldraw/packages/core/src/utils/ColorUtils.ts
See https://discord.com/channels/725182569297215569/1089440090696187994/1089440090696187994
Also reverted the overflow styles of the main toolbar, that introduced a bug on iPhone.
=> Feat (Whiteboards): Support custom colors

tldraw/apps/tldraw-logseq/src/lib/shapes/LogseqPortalShape.tsx, tldraw/packages/core/src/lib/tools/TLBoxTool/states/CreatingState.tsx
Since Whiteboards are used in a note taking context, creating shapes without labels will be rare. Entering edit mode when we create a new shape makes sense. Arrows are not included in this category, which is fine in my opinion.
Also fixed the following
- Portal background color on previews, when we use custom colors
- Portal header background when we switch from a built-in to a custom color
=> Enhance (Whiteboards): Auto enter edit mode when we create shapes

src/main/frontend/components/block.cljs, src/main/frontend/components/block.css
=> fix(ui): breadcrumb fragments overflow in query results container

.gitignore, deps/graph-parser/.gitignore, deps/graph-parser/src/logseq/graph_parser/cli.cljs, deps/graph-parser/src/logseq/graph_parser/test/docs_graph_helper.cljs, deps/graph-parser/test/logseq/graph_parser/cli_test.cljs, deps/graph-parser/test/logseq/graph_parser/mldoc_test.cljs, deps/publishing/src/logseq/publishing/html.cljs, src/main/frontend/handler/common/file.cljs, src/test/frontend/handler/repo_test.cljs
This PR fixes two bugs I encountered while publishing our docs with https://github.com/logseq/publish-spa:
* the :file/name-format option wasn't being used which resulted in namespace bugs
* the older :all-pages-public? config wasn't being picked up by publishing
=> Fix: Two bugs with graph parsing for CLIs

tldraw/apps/tldraw-logseq/package.json, tldraw/apps/tldraw-logseq/src/components/ContextBar/contextBarActionFactory.tsx, tldraw/apps/tldraw-logseq/src/components/PrimaryTools/PrimaryTools.tsx, tldraw/apps/tldraw-logseq/src/components/inputs/ScaleInput.tsx, tldraw/apps/tldraw-logseq/src/components/inputs/SelectInput.tsx, tldraw/apps/tldraw-logseq/src/hooks/usePaste.ts, tldraw/apps/tldraw-logseq/src/lib/shapes/BoxShape.tsx, tldraw/apps/tldraw-logseq/src/lib/shapes/EllipseShape.tsx, tldraw/apps/tldraw-logseq/src/lib/shapes/PolygonShape.tsx, tldraw/apps/tldraw-logseq/src/styles.css, tldraw/packages/core/src/lib/TLApi/TLApi.ts, tldraw/packages/core/src/lib/TLSettings.ts, tldraw/packages/core/src/lib/shapes/TLShape/TLShape.tsx, tldraw/packages/core/src/lib/tools/TLBoxTool/states/CreatingState.tsx, tldraw/packages/core/src/lib/tools/TLDrawTool/states/CreatingState.tsx, tldraw/packages/core/src/lib/tools/TLLineTool/states/CreatingState.tsx, tldraw/packages/core/src/lib/tools/TLTextTool/states/CreatingState.tsx, tldraw/yarn.lock
By popular request, introduced a global scale level option (see https://discord.com/channels/725182569297215569/1001746361303187466/1085263046294913034)
I had to upgrade @radix-ui/react-select to change the position of the select popover.
Shape borders are now also adjusted based on scale level.
[Screencast from 2023-04-13 17-11-45.webm](https://user-images.githubusercontent.com/10744960/231786716-101faac2-0932-450b-a050-3bda1408d9e8.webm)
=> Feat (Whiteboards): Global scale level option

src/main/frontend/components/block.cljs
This tiny code change fixes a minor bug where if you type
```
- TODO
```
(or LATER, DOING, etc; any marker), it will simply show nothing when you exit edit mode. With this fix, it shows the checkbox and the marker now instead.
Before:
After:
The code that actually causes the checkbox to appear is here:
https://github.com/logseq/logseq/blob/89bd707f41dd99b904868ebdf6f1abb632d63198/src/main/frontend/components/block.cljs#L1910-L1912
https://github.com/logseq/logseq/blob/89bd707f41dd99b904868ebdf6f1abb632d63198/src/main/frontend/components/block.cljs#L1974
(discussed briefly on [discord](https://discord.com/channels/725182569297215569/802530020605820949/1096615875005665331))
=> Fix: Show marker when block text is empty

deps/graph-parser/src/logseq/graph_parser.cljs, deps/graph-parser/src/logseq/graph_parser/block.cljs, deps/graph-parser/src/logseq/graph_parser/extract.cljc, deps/graph-parser/test/logseq/graph_parser/block_test.cljs, package.json, src/main/frontend/db/model.cljs, src/main/frontend/fs/diff_merge.cljc, src/main/frontend/fs/diff_merge.cljs, src/main/frontend/fs/watcher_handler.cljs, src/main/frontend/handler/common/file.cljs, src/main/frontend/handler/file.cljs, src/main/frontend/handler/repo.cljs, src/test/frontend/fs/diff_merge_test.cljs, yarn.lock
Refactored ver. of https://github.com/logseq/logseq/pull/8694
> Diff-Merge is actually crossing structured data (DB) & unstructured data (external text editing)
Setting up a directory data_bridge in graph parser for the inter-domain data transferring
What is this PR doing:
In previous version of Logseq, any external editing to a `.md` / `.org` file should "refresh" all blocks' uuids on that page, except those with `id::` provided. 
In this PR, we introduce 2 way diff on the blocks, then the external editing will not "refresh" the blocks' uuids, except the block that was edited externally.
There's a test for checking if the block uuids are persisted upon file parsing:
https://github.com/logseq/logseq/blob/3c0175dfc29899da45e65781f6c88aefbf84a80b/src/test/frontend/fs/diff_merge_test.cljs#L30 …
=> Feat: persist block UUID upon external editing using diff-merge (2)

Dockerfile
Update Nginx image version in `Dockerfile` to solve some vulnerabilities.
Before:
`docker run aquasec/trivy image nginx:1.23.3-alpine`
```
nginx:1.23.3-alpine (alpine 3.17.2)
===================================
Total: 45 (UNKNOWN: 0, LOW: 0, MEDIUM: 30, HIGH: 11, CRITICAL: 4)
```
After:
`docker run aquasec/trivy image nginx:1.24.0-alpine3.17`
```
nginx:1.24.0-alpine3.17 (alpine 3.17.3)
=======================================
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```
=> chore: update nginx version

.clj-kondo/config.edn, src/main/frontend/components/query.cljs, src/main/frontend/components/query/result.cljs, src/test/frontend/components/query/result_test.cljs, templates/config.edn
This PR also adds `:group-by-page?` option for advanced queries to enable grouping even if `result-transform` exists.
Close https://github.com/logseq/logseq/issues/9088
=> fix: disable grouped by page when result-transform exists

src/main/frontend/db/model.cljs
Background: when I were preparing the PR #9154, I found that there is some naming mistake in the fn param in `frontend.db.model`
For example, the second param in `parents-collapsed?` should be `block-uuid`, instead of `block-id`.
https://github.com/logseq/logseq/blob/6771a88781f54d90491719d593d3863c3b796228/src/main/frontend/mobile/action_bar.cljs#L43
=> refactor: rename fn params in `frontend.db.model`

src/main/frontend/utils.js
Introduced: #8968
To reproduce: copy any block which contains a `&`
=> fix(editor): wrong xml prettify implementation

src/main/frontend/components/query_table.cljs, src/test/frontend/components/query_table_test.cljs
This PR fixes two query table issues:
-  #9146 which was caused by #6529. The issue has good instructions to QA
- #9055 which was caused by #8869
=> Fix: Two query table fixes - Comma separated properties display and sorting by page for block queries

deps/db/src/logseq/db/rules.cljc, src/test/frontend/db/query_dsl_test.cljs
To QA, try the old version of `property` from #9119
=> Chore: Add test to prevent regression on property query

tldraw/apps/tldraw-logseq/src/components/ContextMenu/ContextMenu.tsx, tldraw/apps/tldraw-logseq/src/components/ZoomMenu/ZoomMenu.tsx, tldraw/packages/core/src/lib/TLApp/TLApp.ts, tldraw/packages/react/src/components/Shape/Shape.tsx
This fixes exporting selected groups to image (see https://discord.com/channels/725182569297215569/1099184966971166802/1099184966971166802), and also changes the shortcut of `zoom to fit selection`, that is in conflict with the default shortcut that toggles the input command dialog (see https://discord.com/channels/725182569297215569/1099050768977379439/1099050768977379439). I also disable the export option on the context menu, if there are no selected elements.
=> Fix (Whiteboards): Export grouped elements and zoom to fit selection shortcut

deps/graph-parser/src/logseq/graph_parser/property.cljs, src/main/frontend/commands.cljs, src/main/frontend/components/block.cljs, src/main/frontend/components/block.css, src/main/frontend/components/content.cljs, src/main/frontend/handler/block.cljs, src/main/frontend/handler/editor.cljs, src/main/frontend/handler/events.cljs
Reverts logseq/logseq#9141
- Drag & Drop from normal blocks to ordered blocks is broken
- DWIM for list should be disabled
=> Revert "Feat: ordered(number) list blocks"

src/main/frontend/util.cljc, src/main/frontend/utils.js, src/main/logseq/api.cljs
=> enhance(api): restore editing cursor state only for the input element in viewport

src/main/frontend/components/query/result.cljs, src/main/frontend/components/query_table.cljs, src/test/frontend/components/query/result_test.cljs
This PR adds an option to make removing block children optional for a query and fixes bugs #3260 and #9045. The query option `:remove-block-children?` is added because there are times when we want to see block children e.g. when using the :current-block input. I still left children removal as the default as most users probably want the parent block when doing tag/page-ref searches e.g. https://github.com/logseq/logseq/issues/6406.  To QA this option, try:
```
- #+BEGIN_QUERY
{:title "Count under current block"
:inputs [:current-block]
:query [:find (count ?b)
:in $ ?current-block
:where [?b :block/parent ?current-block]]
;; This query only works when this option is added
:remove-block-children? false}
- b1
- b2
#+END_QUERY
```
The second commit removes the removal of template blocks as it …
=> Enhance: Add :remove-block-children? query option for advanced queries and an advanced query :template fix

src/main/frontend/ui.cljs
|Before|After|
|:---:|:---:|
|<img width="250px" src="https://user-images.githubusercontent.com/1984175/234269947-295f9baf-aeed-407c-8c5c-2ca04d520751.png"/>|<img width="250px" src="https://user-images.githubusercontent.com/1984175/234269970-d4f2c31d-9341-4074-bea7-3ab346366dd2.png"/>|
||||
|:---:|:---:|:---:|
|Before|<img width="245px" src="https://user-images.githubusercontent.com/1984175/234272232-293d5e22-c137-45e6-bdfe-de9cf8184c37.png"/>|<img width="100px" src="https://user-images.githubusercontent.com/1984175/234272672-9b648399-9172-4dd0-9073-b4e56d75916d.png"/>|
|After|<img width="245px" src="https://user-images.githubusercontent.com/1984175/234271992-8bafa70d-e8d6-4260-aeea-3783b1201c02.png"/>|<img width="100px" src="https://user-images.githubusercontent.com/1984175/234272827-edb4 …
=> tiny style fix: polish color circles in block context menu

src/electron/electron/search.cljs, src/main/electron/listener.cljs
As #7467 shows that invalid SQLite indexes can lead to extremely slow editing, it seems that failed sql `prepare` statement can block even the input events running in the renderer. We still don't know what caused the error `vtable constructor failed`.
This PR will delete the invalidate db file when `prepare` fails and rebuild the search indices.
A proper solution might be to switch to [sqlite worker threads](https://github.com/WiseLibs/better-sqlite3/blob/master/docs/threads.md) to avoid blocking the renderer.
=> fix: delete sqlite cache when prepare failed

src/main/frontend/components/server.cljs
The api server port range should between 1 and 65535.
It is no possible setting at 65536 and 0.
=> fix: port range should be 1 ~ 65535

src/main/frontend/fs.cljs, src/main/frontend/fs/node.cljs
This PR is an attempt to improve the error handling in the `mkdir-if-not-exists` function by ignoring the "EEXIST" error (which indicates the directory already exists) instead of throwing it. Other errors will continue to be handled as before.
=> fix: Improve error handling in `mkdir` function

src/main/frontend/handler/whiteboard.cljs
See https://discord.com/channels/725182569297215569/1001746361303187466/1101128680664743956
To reproduce this, press mod+K and create a new whiteboard that contains capitalized letters.
=> Fix (Whiteboards): Page name sanitization

src/main/frontend/modules/shortcut/config.cljs
Fix #9253
Root cause: fn with 1 or more args will be called with `[event]` or `[state event]` by shortcut handlers.
- Also checked all the other shortcut handlers for this type of misuse
@logseq-cldwalker Is it possible to check fn type using some lint rules?
=> fix(editor): copy page url with shortcut

src/main/frontend/components/container.css, src/main/frontend/components/header.css, src/main/frontend/ui.cljs, src/main/frontend/util.cljc
Linux users with Intel GPUs have been reporting issues with garbled text
in the sidebar nav and header dropdown menu.
The exact cause is unknown but likely a Electron rendering issue with
Intel GPUs when opacity is set with SVG and text elements.
To workaround the problem we can set the required opacity directly to
the text element.
Added a new `is-linux` ui class to narrow the workaround to Linux only, not strictly required but thought it would be useful to denote an OS specific workaround.
Fixes #7233
=> fix: Garbled text in sidebar and dropdown menus on Linux 

src/main/frontend/components/plugins.cljs
This PR-related issue affects https://github.com/vipzhicheng/logseq-plugin-mark-map not working properly.
=> fix(plugin): incorrect renderer for the pagebar ui items

src/main/frontend/modules/outliner/pipeline.cljs, src/test/frontend/modules/outliner/pipeline_test.cljs
This fixes a longstanding bug where a child block's :block/path-refs holds on to old path-refs when a parent's refs change. Fixes #5759, #5992, #6990, #8430 and #4116. Since this bug allowed stale refs data, this lead to stale data in query results, linked references and maybe other places. To QA, add these blocks:
```
- parent #foo
- child #baz
- grandchild #bing
- {{query (and [[foo]] <% current page %>)}}
```
Observe that changing `#foo` to `#bar` cleanly removes all the blocks from the query results. Another case to QA is toggle task states with children blocks as described in #5992
=> Fix: Stale children block's path-refs when parent's refs change

src/main/frontend/dicts.cljc
Original request [here](https://discord.com/channels/725182569297215569/1093226739024531637/1102875663398084670)
`Показать все ссылки на блок` not correct, as it does not make sense according to feature [itself](https://discord.com/channels/725182569297215569/735747000649252894/1102832326657978440)
Proposal translation make more sense.
Also improved few other words.
`ё` is important letter, it should exist :smile_cat:
=> enhance: `main/frontend/dicts` improve RU translation

src/main/frontend/handler/paste.cljs
- use legacy method on Android
Related #8971 #8980
**UPDATE**:
Android apk build: https://github.com/logseq/logseq/actions/runs/4913425315
=> fix(android): paste with native input device

src/main/frontend/components/file_sync.cljs, src/main/frontend/handler/file_sync.cljs
`fetch-page-file-versions` return nil(expect async chan) when file-id is nil
=> fix: reduce page-history err when page doesn't have file-id yet

src/main/frontend/handler/file_sync.cljs
Follow up for #9310
- :file/path should always be relative
- use path fn to convert URL to path
=> chore: refine #9310

src/main/frontend/dicts.cljc, src/main/frontend/fs/sync.cljs
when localtime is incorrect, aws s3 return "Request is not yet valid" err
=> fix(sync): validate rsapi upload err

deps/graph-parser/.carve/ignore, deps/graph-parser/src/logseq/graph_parser.cljs, deps/graph-parser/src/logseq/graph_parser/block.cljs, deps/graph-parser/src/logseq/graph_parser/cli.cljs, deps/graph-parser/src/logseq/graph_parser/config.cljs, deps/graph-parser/src/logseq/graph_parser/test/docs_graph_helper.cljs, deps/graph-parser/test/logseq/graph_parser_test.cljs, src/main/frontend/format/block.cljs, src/main/frontend/handler/common/file.cljs, src/test/frontend/handler/repo_conversion_test.cljs
This PR fixes #9346 and #5926. It also fixes an issue where relative paths for unsupported formats like `deps/graph-parser/yarn.lock` would result in multiple invalid pages e.g. deps, deps/graph-parser and deps/graph-parser/yarn.lock. To QA, try any of the added test examples and confirm that they do not create any invalid pages
=> Fix: mailto and other protocols creating invalid pages

src/main/frontend/db/model.cljs
Reproduce:
https://github.com/logseq/logseq/assets/479169/b51903d8-d13b-47de-b5e4-ed5ac2957556
=> fix: refresh the page after deleting blocks in a long page

src/main/frontend/components/plugins.css
=> fix(ui): incorrect arrangement of ui items from pagebar

src/main/frontend/components/page.cljs, src/main/frontend/components/page.css
Introduced: 6b94181116dbaec8d72a2fc6dae5dd424f3a5bd1 (Cannot track this commit to any PR)
Related: #9368
CC @tiensonqin, This is a quick fix, no idea of if adding `pointer-events-none` back will break any fixes introduced in 6b94181116dbaec8d72a2fc6dae5dd424f3a5bd1.
=> fix(ui): renaming input edit when on-click

src/main/frontend/handler/whiteboard.cljs, tldraw/packages/core/src/lib/tools/TLSelectTool/states/TranslatingState.ts
Fixed a bug introduced on #8885 that was marking all shapes as updated, slowing down persist on element heavy boards. Also replaced `indexOf` that is slow, and removed an unneeded persist call. 
Related to https://discord.com/channels/725182569297215569/1001746361303187466/1105943246611419197
=> Fix (Whiteboards): Performance of persist

deps/graph-parser/src/logseq/graph_parser/block.cljs, deps/graph-parser/src/logseq/graph_parser/test/docs_graph_helper.cljs, deps/graph-parser/test/logseq/graph_parser_test.cljs, src/test/frontend/handler/repo_conversion_test.cljs
This PR fixes #9367 which was introduced with #9353. #9367 has good QA instructions
=> Fix: Org mode pages in aliased links not creating pages

src/main/frontend/components/block.css
- smaller space for the number list marker with block content
=> Enhance/minor UI tweaks

deps/db/src/logseq/db/schema.cljs, src/test/frontend/handler/editor_test.cljs, src/test/frontend/handler/repo_test.cljs, src/test/frontend/modules/outliner/pipeline_test.cljs, src/test/frontend/test/helper.cljs
This PR fixes #9365 which was introduced in #9254.  ~~This brings back the previous behavior where the current block always has it's :block/path-refs transacted as noticed in https://github.com/logseq/logseq/pull/9254#discussion_r1178247609 . It seems this is needed.~~ This PR fixes this by no longer having :block/path-refs as a retracted attribute. To QA, you can reproduce with the first minute of the video in #9365. You can also QA with:
- Create a block `foo #bar`
- Run `show block data` command on the block and note its :block/path-refs
- Change block to `fooz #bar`
- Rerun `show block data` command on the block and its :block/path-refs should not change
~~I'll see if I can do a test for this on Monday~~
=> Fix: Current block losing path-refs if refs don't change

src/main/frontend/components/settings.cljs
Fix https://github.com/logseq/logseq/issues/9361
The current logic for the version control tab is awful: 
- If a graph has Logseq sync setup, just block the entry to the version control setting. 
- The git auto commit is a global config (stored in electron cfg)
- It can come to a dead case that a user has git auto commit enabled, then activate the Logseq Sync service, thus unable to change the setting anymore.
This PR do:
1. Remove the blocking (allow pro users continue to use Git while having Logseq Sync enabled)
2. Use text box to hint users about the page history feature for Logseq Sync users instead:
Suggestion on logic / wordings are welcome :)
=> Enhance: version control settings description update

e2e-tests/whiteboards.spec.ts, src/main/frontend/extensions/tldraw.cljs, tldraw/apps/tldraw-logseq/src/components/ContextBar/contextBarActionFactory.tsx, tldraw/apps/tldraw-logseq/src/lib/shapes/EllipseShape.tsx, tldraw/packages/core/src/lib/TLApi/TLApi.ts, tldraw/packages/core/src/lib/tools/TLSelectTool/states/ContextMenuState.ts
The PR handles the following issues
- Create a rectangle, convert it to an ellipsis, and try to change its color or set its fill property. Those actions should work without resetting the element selection.
- Create a rectangle, convert it to an ellipsis, move the object and then undo the actions. The conversion should be a separate history action.
- Create multiple elements. Then create a rectangle and convert it to an ellipsis. Select all elements and right click on the converted shape. All elements should remain selected when the context menu should is triggered. 
The main problem was that in order to maintain the same id, a different shape instance with the same ID is created upon conversion.
=> Fix (Whiteboards): Actions on converted shapes

src/main/frontend/handler/editor.cljs, src/main/logseq/api.cljs, src/test/frontend/handler/editor_test.cljs
Update block properties similar to `api-insert-new-block` https://github.com/logseq/logseq/blob/master/src/main/frontend/handler/editor.cljs#L588.
Fixes #5298
=> enhance: logseq.api.update_block can preserve properties

e2e-tests/fixtures.ts
If a link fails to load, the error message "Failed to load resource: net::ERR_CONNECTION_REFUSED." is printed to the console.  This error can occur during testing if Google ad trackers are blocked due to the YouTube video in the demo page.
CC: @cnrpman
=> dev(playwright): Ignore conntection refused errors

android/app/src/main/java/com/logseq/app/FsWatcher.java, deps/common/src/logseq/common/path.cljs, ios/App/App/FsWatcher.swift, src/main/frontend/fs/capacitor_fs.cljs, src/main/frontend/handler/common/file.cljs, src/main/frontend/handler/events.cljs
The file system (fs) watcher on mobile platforms accesses files using native URL or Uri.
Due to this, files with unnormalized Unicode characters such as diacritical letters are not handled correctly when URLs are used as file paths.  BUG: Unicode normalization should be applied after uri-decode.
Upon detecting a file modification event, the watcher treats the file as new due to the unnormalized characters and as such, results in lost history. Additionally, the screen keyboard bounces, causing issues.
In this fix:
- add a `catch-all` style fix to `logseq.common.path`
- Refactor mobile fs-watcher, use relative paths, add path normalization
Fix #9378
=> Fix(fs): add unicode normalization to fs watcher on mobile platforms

src/main/frontend/components/block.cljs
- UI indicator for hidden content
=> fix(editor): show block bullet when a blank block has children

deps/common/src/logseq/common/graph.cljs, deps/graph-parser/src/logseq/graph_parser/cli.cljs, deps/graph-parser/src/logseq/graph_parser/test/docs_graph_helper.cljs, deps/graph-parser/test/logseq/graph_parser/cli_test.cljs, src/test/frontend/handler/repo_conversion_test.cljs, src/test/frontend/handler/repo_test.cljs
This is a bug fix for functionality introduced with #9348. The bug only effect nbb-logseq scripts
=> Fix: graph-parser.cli ignoring incorrectly for relative dir

ios/App/App.xcodeproj/project.pbxproj
At least, the current App cannot run on iOS 13.2, reporting a `ResizeObserver` not defined error.
=> chore(mobile): drop support for ios 13

src/main/frontend/commands.cljs, src/main/frontend/handler/editor.cljs, src/main/frontend/util.cljc
To reproduce, add/edit a block with many lines.
Then press `shift+enter` in the middle of the block content. Thee page will scroll to the bottom of the block.
https://github.com/logseq/logseq/assets/72891/38fc402e-a08a-4ddc-93d5-41d7bb97167e
=> enhance(editor): restore scroll position new adding newline in a block

templates/config.edn
@tiensonqin the default values updated in https://github.com/logseq/logseq/pull/9408/ are incorrect. I provided all source code for default values in PR https://github.com/logseq/logseq/pull/9287
=> fix:  revert #9408 wrong default config.edn values

src/main/frontend/components/block.cljs
=> fix(ios): wrong link when sharing asset link

.github/workflows/build-desktop-release.yml
This avoids #9471
[Demo Run](https://github.com/logseq/logseq/actions/runs/5065081348)
=> Dev:  run e2e tests when releasing binaries

deps/graph-parser/src/logseq/graph_parser/extract.cljc, src/main/frontend/components/block.cljs, src/main/frontend/handler/editor.cljs, src/main/frontend/modules/outliner/core.cljs, src/main/frontend/modules/outliner/datascript.cljc, src/main/frontend/state.cljs
This PR is a refactor followup to https://github.com/logseq/logseq/pull/9406/files. This introduces a keyword ns to make temporary block keys more explicit. I chose :block.temp but we could also :block.tmp if preferred. I only renamed keys with low risk and that were easy to trace with grep
=> Chore: Rename temp :block keys to be explicit about their use

src/main/frontend/components/plugins.cljs
Use non-breaking space to ensure that space within the inline element `open ~/.logseq` is correctly rendered.
|before | After |
| ----- | ------|
|![image](https://github.com/Alistair10123/logseq_p/assets/25513724/9486b519-b1d8-48c2-a6d1-cf38fa2f9451)| ![image](https://github.com/Alistair10123/logseq_p/assets/25513724/7f0caf09-ac61-40b0-a643-a280b9ae82d9)|
@xyhp915, please TAL when you get a chance. It's a minor UI change.
=> Dev(plugins): fix space in overflow menu 

src/main/frontend/mobile/intent.cljs
Previously, sharing media to logseq via an android intent only substituted the url/time. Now it substitutes the date and replaces the text with nothing (which seems like a reasonable default when there is no text).
=> fix: substitute date/text in all quick-capture templates

src/main/frontend/handler/editor.cljs
Closes #3295 
As in common text editors, selected text should be deleted when pressing "enter".
At the moment, Logseq deletes selected text only when a new line is inserted within a block ("shift+enter", if not in document mode).
This PR enhances the insertion of a new block when "enter" is pressed, deleting selected text. If there is no selection (i.e. `util/get-selection-start` and `util/get-selection-end` return the same value), the behavior is as before.
Before:
https://github.com/logseq/logseq/assets/16477970/11c266e8-2d41-4721-8b6b-8f6d361877f7
After:
https://github.com/logseq/logseq/assets/16477970/a58c030f-1d79-44f3-bfd5-2ab47824e8eb
=> enhance(editor): delete selected text when pressing enter

src/main/frontend/components/header.cljs, src/resources/dicts/en.edn
This is an attempt to add a "Toggle theme" item in the options menu for published graphs. 
resolves https://github.com/logseq/logseq/issues/9240
=> Enhance: Menu item for toggling theme mode in published graphs

src/main/frontend/extensions/tldraw.cljs, src/main/frontend/handler/route.cljs, src/main/frontend/handler/whiteboard.cljs
Resolves #9481
I managed to reproduce this without enabling sync
- Make sure you already have created an onboarding whiteboard on your machine. The `ls-onboarding-whiteboard?` local storage key should be set to `true`
- Create a new graph with an empty Whiteboards folder
- Create your first Whiteboard and add some shapes to it (the onboarding whiteboard should not be triggered)
- Manually delete the `ls-onboarding-whiteboard?` local storage key, or clear all local storage data
- Reload the app and open the previously created Whiteboard
The onboarding shapes will be populated on top of the existing whiteboard.
=> Fix (Whiteboards): Onboarding triggered on existing whiteboard

tldraw/apps/tldraw-logseq/src/lib/shapes/TextShape.tsx, tldraw/packages/core/src/lib/TLApp/TLApp.ts
- b80bf088d2204222e982e4d5a74113c96c2286c2 This should fix the long standing `Maximum call stack size exceeded` error that was triggered on mobile devices. To reproduce this, create a text element on iOS, type something and then tap outside to exit the editing mode. The app will hang for some seconds until the stack size error is thrown. 
- 2b227177e535ce2cfe52430484e6a2c1979bc4d5 Remove unneeded persist call. This was triggered multiple times on load and on window resize, on whiteboards with image assets. To reproduce this, open the console log and load a whiteboard with images (like the onboarding).
=> Fix (Whiteboard): Various issues

src/main/frontend/commands.cljs, src/main/frontend/handler/common/config_edn.cljs, src/main/frontend/handler/editor.cljs, src/main/frontend/state.cljs, src/test/frontend/handler/common/config_edn_test.cljs
This PR removes the :editor/command-trigger config option as described in https://linear.app/logseq/issue/LOG-2379/remove-editorcommand-trigger-config-option. This option has been deprecated for a couple months. Didn't know whether to label this is a fix or a chore since it has a minor breaking change so just chose fix
=> Fix: Remove deprecated :editor/command-trigger option [minor change]

e2e-tests/whiteboards.spec.ts, tldraw/packages/core/src/lib/TLViewport.ts, tldraw/packages/core/src/lib/tools/TLSelectTool/states/BrushingState.ts, tldraw/packages/core/src/lib/tools/TLSelectTool/states/ResizingState.ts, tldraw/packages/core/src/lib/tools/TLSelectTool/states/TranslatingState.ts
This is just a minor tweak to auto panning, introduced on https://github.com/logseq/logseq/pull/8611
We won't have to move the pointer out of canvas to trigger the auto pan. Moving it close to the canvas bounds will also pan to the mouse position. That would allow to use this on mobile devices and on certain desktop cases.
[Screencast from 2023-06-02 18-39-51.webm](https://github.com/logseq/logseq/assets/10744960/58a950ab-3970-4f21-91ad-b2b22d6666ec)
=> Enhance (Whiteboards): Auto pan

.github/ISSUE_TEMPLATE/bug_report.yaml
Some users may overlook the "bug only" policy of the issue section. This results in the creation of multiple tickets that lack of description, which can clutter the issues section and divert our attention from addressing legitimate bugs and prioritizing developments.
(Not creating the links toward tickets on purpose. And it's not a single case.)
Example: 9569 9570
Of course, in practice, we should still keep gentle towards the question tickets.
=> chore: Update bug_report.yaml to reassure our policy on questions

e2e-tests/fixtures.ts
When there is no connection available or if Google trackers are blocked, playwright tests fail to work due to the youtube video link in the demo graph page. To address this issue previously, I added an exception for a specific network error.
This PR ignores all network-related errors as they do not affect the E2E tests and will only show up in a restricted environment where Google might be blocked.
Instead of completely ignoring the errors, they are now logged as warnings in the console.
CC: @cnrpman please TAL when you have the time :\)
Example output:
```log
WARN:: Failed to load resource: net::ERR_FILE_NOT_FOUND
WARN:: Error with Permissions-Policy header: Unrecognized feature: 'ch-ua-form-factor'.
WARN:: Failed to load resource: net::ERR_CONNECTION_REFUSED
```
=> dev(e2e): Log and ignore net errors

src/main/frontend/components/page.cljs
This PR fixes https://github.com/logseq/logseq/issues/8678, fixes #2796, fixes #2848 and fixes #6080
Use the `page-cp` component so that the link behaves the same as other page links in the app
**After**
[Screen recording 2023-06-04 1.33.00 PM.webm](https://github.com/logseq/logseq/assets/11085079/394d4963-e586-4368-87d9-3d6045887d4b)
If there's anything I can help provide for this, please let me know. Thanks!
=> Fix: shift clicking on "Pages tagged with" page link doesn't open in sidebar

e2e-tests/hotkey.spec.ts, e2e-tests/page-rename.spec.ts, e2e-tests/util/search-modal.ts, src/main/frontend/search.cljs
fix #9577 
The root cause is that the corresponding title indices were not updated when only `:block/origin-name` was updated (i.e., only the title case changed).
The PR fixes `datoms` filtering logic under `get-direct-blocks-and-pages`. Below are some common renaming cases. The cause of this bug is that it didn't care about the transactions with only `:block/origin-name`.
| Case | Renaming |
| --- | --- |
| Only origin-name is updated | apple -> Apple |
| Both name and origin-name are updated | apple -> banana |
=> Fix: Page search is not updated after changing the capitalization of the page name

resources/package.json, static/yarn.lock
Addresses #9534 related to `warning: Empty last update token` errors being thrown on Mac OS
=> Bump dependency dugite from 1.8.0 to 2.5.0

tldraw/apps/tldraw-logseq/src/components/ContextMenu/ContextMenu.tsx
Fixes a bug introduced on #9567 that doesn't allow us to export images using the whiteboards' context menu.
=> Fix (Whiteboards): Exporting from context menu

deps/publishing/src/logseq/publishing/db.cljs, deps/publishing/test/logseq/publishing/db_test.cljs
This PR fixes #4143. To reproduce:
1. create a public page with an alias
2. create another public page that has two links, one to the page and one to the page alias
3. Be sure logseq/config.edn has `:publishing/all-pages-public? false`
4. Run `bb dev:publishing ...` to build the publishing app per https://github.com/logseq/logseq/blob/master/docs/dev-practices.md#babashka-tasks
5. The aliased link should correctly redirect to the original page
For these first two steps, you can QA the exact pages I used by using the [logseq-export and logseq-import CLIs](https://github.com/logseq/bb-tasks/tree/main#clis) and the following export.edn content:
```
[#:file{:content
"public:: true\n\n- https://github.com/logseq/logseq/issues/5280\n\t- [[page 5280]]\n\t- [[page 5280-alias]]",
:path …
```
=> Fix: Alias pages not included in published subgraph

src/main/frontend/handler/editor.cljs, src/main/frontend/handler/paste.cljs, src/test/frontend/handler/paste_test.cljs
This PR fixes #8981 for any macro-wrapped url e.g. youtube or twitter url. This PR also does some light refactoring and tests another paste scenario. See issue for how to QA
=> Fix: Pasted special urls on selected text don't get wrapped with macros

.clj-kondo/config.edn, bb.edn, deps.edn, deps/common/bb.edn, deps/common/deps.edn, deps/db/bb.edn, deps/db/deps.edn, deps/graph-parser/bb.edn, deps/graph-parser/deps.edn, deps/publishing/bb.edn, deps/publishing/deps.edn, src/main/frontend/components/shortcut.cljs, src/main/frontend/db/react.cljs, src/main/frontend/extensions/pdf/toolbar.cljs, src/main/frontend/modules/outliner/tree.cljs, src/test/frontend/handler/editor_test.cljs, src/test/frontend/modules/outliner/core_test.cljs, src/test/frontend/util/clocktime_test.cljs
This PR updates our clj-kondo and logseq/bb-tasks deps used for linting. Looking [through clj-kondo's changelog](https://github.com/clj-kondo/clj-kondo/blob/master/CHANGELOG.md), there aren't any breaking changes that effect us and there are a few new linters. One new linter catches tests without assertions which is handy and caught a couple of our tests that accidentally didn't test anything
=> Chore: Update lint deps

src/main/frontend/handler/editor.cljs, src/main/frontend/handler/events.cljs, src/main/frontend/state.cljs
This PR returns a promise for `(state/pub-event!)` so we can block waiting for the result and do other things.
It fixed the bug that typing `1. ` sometimes can result in `1. 1.`.
To reproduce it:
1. create a new block and type `1.`
2. wait for two seconds (the block will be saved automatically)
3. press `space`
Notice that the block is ordered now, but its content still has `1.`.
=> enhance: pub-event! returns a promise

deps/graph-parser/src/logseq/graph_parser/block.cljs, deps/graph-parser/src/logseq/graph_parser/mldoc.cljc, deps/graph-parser/test/logseq/graph_parser/mldoc_test.cljs
This PR removes the extra whitespaces when building `block/content`. Also `gp-mldoc/remove-indentation-spaces` is not called on org mode content.
Previously, the extra whitespace in line 2 will not be removed. 
```
- block 1
- block 2
line 1
line 2
line 3
```
Edit: Needed for 3-way merge to work in this situation
=> Fix: trim block whitespace for markdown files for a specific case

src/main/frontend/components/block.css, tldraw/apps/tldraw-logseq/src/styles.css
This PR fixes an annoying bug: clicking to edit a block from the right sidebar or a whiteboard can't jump to the correct position.
The cause is `user-select: none`, I changed it to `text`.
To reproduce, you can open or create a block in either the right sidebar or a whiteboard and click a middle position (end position sometimes works).
=> fix: clicking to edit a block from the right sidebar or a whiteboard can't jump to the correct position

e2e-tests/code-editing.spec.ts
This fixes the intermediate failure of the tests introduced in #9553. This issue and fix are the same as the ones introduced in #9387.
=> fix: test intermediate failure

src/main/frontend/components/block.cljs, src/main/frontend/components/page.cljs
=> fix: disable content selection when blocks have been selected

tldraw/packages/core/src/lib/tools/TLBoxTool/states/CreatingState.tsx, tldraw/packages/core/src/lib/tools/TLSelectTool/states/ResizingState.ts
When we scale shapes with locked aspect ratio (e.g. images, videos), or when we hold the shift key while creating geometric shapes, the aspect ratio needs to be preserved. Combining snapping while resizing with locked aspect ratio is possible. This PR will just skip snapping for now, to avoid messing with existing proportions, until we have a better solution.
=> Fix (Whiteboards): Skip snapping to preserve aspect ratio

deps/graph-parser/src/logseq/graph_parser/util.cljs, deps/graph-parser/test/logseq/graph_parser/cli_test.cljs, ios/App/App.xcodeproj/project.pbxproj, ios/App/App/FsWatcher.swift, package.json, resources/package.json, shadow-cljs.edn, src/electron/electron/file_sync_rsapi.cljs, src/electron/electron/handler.cljs, src/main/frontend/fs.cljs, src/main/frontend/fs/diff_merge.cljs, src/main/frontend/fs/node.cljs, src/main/frontend/fs/sync.cljs, src/main/frontend/handler/common/file.cljs, src/test/frontend/fs/diff_merge_test.cljs, src/test/frontend/fs/sync_test.cljs, static/yarn.lock, yarn.lock
This is a follow-up of @cnrpman 's diff-merge implementation, to use a three-way merge implementation when handling file conflicts.
This should apply to the following scenario:
- Edit before the local files update to newest(currently, any edits before updating to newest is overwritten)
- Quick capture to a non-updated graph(the same as above)
- Edit simultaneously from 2 or more clients, which should reach a final consistent state
=> Enhance Logseq Sync: 2 stage file merge

src/main/frontend/extensions/html_parser.cljs, src/main/frontend/handler/paste.cljs
Also, removes ending `-` when converting html to text
=> fix: disable hiccup export for heading/footer/etc when paste

src/main/frontend/handler/paste.cljs, src/test/frontend/handler/paste_test.cljs
If you paste some text over a link, it should transfer the link to named link. However, if the content of the block does not only contain a link, this process will fail now, this PR fix that.
How to reproduce:
https://www.loom.com/share/3ad28e87363e42238c7b7397a5d6538e
=> Fix paste text to link

package.json, resources/package.json, static/yarn.lock, yarn.lock
- Reinstalled `node-abi` to fix an electron forge issue
-  [Electron 23.0.0 drops Windows 7/8/8.1 Support](https://www.electronjs.org/blog/electron-23-0#dropping-windows-7881-support)
Windows 7/8 support was already problematic, as far as I understand #6868
Also, Windows 7 market share dropped from 13% to <4% within the past year. Both 8 and 8.1 are  <1% currently  https://gs.statcounter.com/os-version-market-share/windows/desktop/worldwide
Resolves #8702, #9304
=> Chore (Deps): Upgrade to Electron 24 [minor change]

ios/App/App.xcodeproj/project.pbxproj, package.json, yarn.lock
- Fix initial base dir creation. 
- update iOS version for TestFlight release
See-also https://github.com/logseq/capacitor-file-sync/commit/7d48bc460a3718544495e723e6bd873f990d0ff5
=> chore(deps): update capacitor-diff-merge; fix initial dir create

resources/forge.config.js, scripts/bump-version.sh
The version number "isn't" displayed twice.  Since Logseq is using the native about dialog, what we see is the version number follow by the build number between parentheses: "Version Number (Build Number)".
By default, Electron Forge will use the same value for the version number and the build number unless we specify otherwise.
In this pull request, I added the required configuration to have a build version in the release.  Since there is already a "Code version" in the codebase, I choose to use the same number to keep thing simple.
Apple Documentation on Version Numbers and Build Numbers : 
https://developer.apple.com/library/archive/technotes/tn2420/_index.html
BONUS: The bump-version.sh script displayed the old Code Version (line 53) instead of the new one.  I fix that as well.
=> fix(ui): Issue#9315 - About dialog shows the version number twice (MacOS)

e2e-tests/editor.spec.ts, src/main/frontend/handler/editor.cljs, src/main/frontend/handler/history.cljs, src/main/frontend/handler/paste.cljs, src/main/frontend/modules/outliner/core.cljs, src/main/frontend/state.cljs
Fixed:
- Cutting or copying multiple blocks in a non-consistent page order with the ID order in the database can result in display errors on the page. 
Related issues (not necessarily fixed by this PR): #4491, #1389, #3929 and #8188
Before
https://user-images.githubusercontent.com/824436/231724312-80f766cf-3df6-4fbd-bc20-7e87933e3da7.mp4
After
https://user-images.githubusercontent.com/824436/231751640-50bf763d-c7bd-45fb-9feb-dee864d0e1bb.mp4
Improve:
- Remove all ref-related values when copying blocks, including :id and exclude-properties in :block/properties-text-values, :block/_refs.
- Preserve the UUID when cutting blocks to avoid ref broken.
- Replace the target block if has no refs and empty content as much as possible when cutting or copying blocks, including target block has no …
=> Enhance cut and copy blocks

src/main/frontend/components/datetime.cljs, src/main/frontend/components/editor.css
As a Logseq user on mobile I noticed that the schedule modal is very scrunched when setting repeater. I was unable to see what was in the inputs.
- Use tailwind classes `flex-col.sm:flex-row`
(uses `flex-direction: column` for small screens, `flex-direction: row` for anything larger)
- Fix small width stying rules in `editor.css`
Thank you for your consideration
=> Use flex-col for schedule modal on smaller screens

src/main/frontend/handler/editor.cljs
=> FIX(editor): Fix delete character which has more than one UTF-16 code unit using `Delete` key. close  the issue #9834

src/main/frontend/fs/sync.cljs, src/main/frontend/mobile/core.cljs
Root Cause: 
On mobile platforms, DB is not persisted if the app goes inactive or gets killed. So DB(datascript transit files) will lose sync with the disk files if the App is closed by system UI or launcher.
This is very different from the Desktop version, where transit files are saved when closing-app/switching-graph.
=> Fix: content overwritten caused by diff merge on mobile platforms

src/main/frontend/components/header.css
When we click on the header buttons around the inner icon, the action should be triggered instead of the window dragging.
See https://discord.com/channels/725182569297215569/802530020605820949/1129383697989251072
=> Fix: Header button drag region

src/main/frontend/mobile/index.css
In the iOS mobile app, the swipe-left action menu would not adjust to the page's vertical scroll. The mobile web view seems to treat `position: absolute` differently than a normal mobile web browser
- Create a page long enough that it needs to scroll the content
- Choose a block toward the bottom of the page (such that the page is scrolled down)
- Swipe left to trigger the mobile action-bar buttons
- At first it appears nothing happened, I cannot see the mobile action-bar
- But if I scroll up I see that it is actually just higher up on the page
- Appears to be positioned where it should be if the page were not scrolled at all.
but the in-app web view seems to treat `position: absolute` different than a mobile browser would  
- The fix for this is pretty simple
- The in-app web view seems …
=> Fix positioning of swipe-left action bar on iOS mobile app

src/main/frontend/components/settings.cljs
fixed https://github.com/logseq/logseq/issues/9875
`state/use-theme-mode!` don't need i18n.
I don't know Clojure, is this the right way to modify the code?
=> fix: unable to change theme mode in theme row for zh-cn lang

package.json, resources/package.json, static/yarn.lock, yarn.lock
The version of Electron 24 used by logseq contains a critical vulnerability. 
- https://security.snyk.io/vuln/SNYK-JS-ELECTRON-5663563
- https://www.cve.org/CVERecord?id=CVE-2023-2931
OS compatibility checks:
Changes:
https://releases.electronjs.org/release/compare/v24.3.1/v24.6.3
=> chore(deps): Fix CVE-2023-2931 in Electron 24 [minor change]

src/main/frontend/handler.cljs
The listeners setup of Electron should be initialized before the render life phase.
=> fix(server): sometimes the API server autostart not working

deps/graph-parser/src/logseq/graph_parser/block.cljs, deps/graph-parser/src/logseq/graph_parser/test/docs_graph_helper.cljs, deps/graph-parser/src/logseq/graph_parser/whiteboard.cljs, deps/graph-parser/test/logseq/graph_parser/block_test.cljs, libs/src/LSPlugin.ts, src/main/frontend/modules/file/core.cljs, src/test/frontend/handler/repo_conversion_test.cljs
This PR deletes the remaining uses of :block/unordered as most of it was deleted in https://github.com/logseq/logseq/pull/3362
=> Chore: Remove remaining :block/unordered that should've been deleted

resources/css/common.css
Those styles were introduced on #1431. The excalidraw version was `0.4.2` and now it's `0.12.0`
There are no `hr` elements and  the `.Island` selector is too vague.
See the resolved issue to reproduce the problem.
Resolves #9940
=> Fix (draw): Remove outdated styles

src/main/frontend/components/container.cljs
Setting default sidebar pages on `config,edn` should work as described [here](https://github.com/logseq/logseq/blob/master/src/resources/templates/config.edn#L121-L135)
The problem was that `state/sidebar-add-block!` expects a `db-id`, not a page name.
Resolves #9950
Also related to #4416 that was automatically closed
=> Fix: Setting default sidebar pages on config

src/main/frontend/extensions/excalidraw.cljs
It looks like `(not= elements->clj @*elements))` returns false when we update an existing shape. To reproduce this, create a rectangle, move it to a different location and reload the page. The new position is not persisted. To make sure that the equality check is now working as intended, open the dev tools and ensure that persist is triggered when we transform existing elements, but not when we change the selected elements.
Resolves #8706
=> Fix (Draw): Persist when updating existing elements

src/main/frontend/extensions/excalidraw.cljs
See-also #9533
`(.-clientWidth el)` is 0 in ref-block.
=> fix(editor): display of embedded drawing

src/main/frontend/extensions/pdf/pdf.css
related #9926 
A reproduced pdf file: 
[Error when pdf annotation and reference · Issue #8304 · logseq_logseq.pdf](https://github.com/logseq/logseq/files/12257232/Error.when.pdf.annotation.and.reference.Issue.8304.logseq_logseq.pdf)
=> fix(pdf): highlights text layer is overlaid by the pdfjs built-in annotation layer

tldraw/packages/core/src/lib/TLApp/TLApp.ts
Hey! My first PR ever here. 
I really wanted to have pen pressure support for the whiteboard, since having an infinitely scrolling canvas is much more convenient than a bunch of excalidraw drawings. I looked around in the tldraw code, and it seems that the onPointer handlers have the pressure hardcoded to 0.5, hence why pressure is simulated even with a pressure-sensitive display tablet.
Changing it to e.pressure seems to do the trick, at least with the development webapp and the Windows electron app. I have zero idea if this quick change would also work on iOS, but maybe!
Here's a quick demo:
https://github.com/logseq/logseq/assets/21244249/01435ead-ff4b-4d49-a089-a8b600bd6904
=> Enhance: Whiteboard Pen Pressure support

src/main/frontend/extensions/pdf/toolbar.cljs
- fixed https://github.com/logseq/logseq/issues/9970
=> enhance(pdf): support `shift + enter` to pick the previous searching results highlight

src/main/frontend/util/property.cljs
I had this error https://github.com/logseq/logseq/issues/9784 and think the problem was trim in the null value. If is not would you guys give some input to fix this
=> fix(whiteboard) page sidebar empty string

packages/amplify/src/LSAuthenticator.tsx, packages/amplify/src/amplify.ts
As requested by @logseqramses, this would allow more users to login without needing support
=> Enhance: Tweak login wording to let users know that email login works

src/main/frontend/handler/route.cljs
Follow up of #10018
The whole app becomes a blank page when navigating to `#/page/`.
Caused by opening the following whiteboard in the right sidebar:
```clojure
{:blocks (
{:block/uuid #uuid "64da1ec9-7b45-47f2-a1e2-c4660c53e0c1"
:block/properties 
{}
:block/updated-at 1692016333246
:block/created-at 1692016333246
:block/format :markdown
:block/content "Test on block"
:block/parent 
{:block/uuid "64da1ebc-d5ea-408b-9986-18ecadfd3f8b"}} 
{:block/properties 
{:ls-type :whiteboard-shape
:logseq.tldraw.shape 
{:blockType "B"
:stroke ""
:collapsed false
:borderRadius 8
:index 0
:scale [1 1]
:pageId "64da1ec9-7b45-47f2-a1e2-c4660c53e0c1"
:scaleLevel "md"
:fill ""
:compact true
:isAutoResizing true
:type "logseq-portal"
:size [400 41]
:strokeType "line"
:strokeWidth 2
:opacity 1
:id …
```
=> fix(editor): avoid nav to empty page name

src/main/frontend/components/page.cljs
I found that when I want to click on a node in the graph view to jump to the corresponding page, but with a slight mouse movement, unexpected behavior occurs: instead of jumping to the corresponding page, the node moves slightly.
Therefore, I added a threshold for nodeClick event handler, to temporarily solve this problem.
=> fix: add drag threshold for graph view

src/main/frontend/handler/editor.cljs
See-also: #8728
This is tricky to fix.
- When second-stage-style auto-completion UI is triggered, say, template expansion
- If the AC popup disappears then re-appears, (caused by an empty search result, then delete some search prefix chars to let search result shown again)
- The component state is cleared. So the default "orig-prefix" calculation in `commands/insert!` is reset, leads to wrong state
- `(insert-command! element-id "" format {})` fails to clear block content.
- Template will be inserted in a new block, current block is not cleared
=> fix(editor): template expansion if auto-completion ui is blurred

src/electron/electron/window.cljs
Quoting https://www.electronjs.org/docs/latest/faq#the-font-looks-blurry-what-is-this-and-what-can-i-do
> Sub-pixel anti-aliasing needs a non-transparent background of the layer containing the font glyphs.
> Even if you don't see a difference, some of your users may. It is best to always set the background this way, unless you have reasons not to do so.
The background of the electron app upon loading is already white, so this change should not affect anything else.
Resolves #2813
=> Fix (UX): Sub-pixel anti-aliasing

src/main/frontend/components/container.cljs, src/main/frontend/handler/route.cljs
Clicking on a recently opened whiteboard on the left sidebar, should not push the whiteboard at the top of the list.
=> Fix: Clicking on recently opened whiteboards

src/main/frontend/db/model.cljs, src/main/frontend/db/persist.cljs, src/main/frontend/fs/watcher_handler.cljs, src/main/frontend/handler/events.cljs, src/main/frontend/idb.cljs
Related #10028 
- Refine app-id change handling:  Since fs refactor, db stores file names as relative paths. Thus make it possible to reuse old db directly, no db migration is needed.
- fs initial watcher's performance is not acceptable(actually it's not a watcher, is a recursive directory scan)
- `:graph/ready` should be after `watcher-handler/load-graph-files!`: trade-off between responsiveness and correctness
Changes in this PR:
- Refine iOS app-id change handling
- Add "homepage-preload": refresh today's journal or homepage as early as possible
- Reorder initial watcher incoming files: journals first, then pages
- Add notification when initial watcher receives a large changeset.
=> Refactor: iOS App start-up

capacitor.config.ts, package.json, src/main/frontend/fs/capacitor_fs.cljs, src/main/frontend/fs/watcher_handler.cljs, src/main/frontend/handler/events.cljs, src/main/frontend/handler/page.cljs, src/main/frontend/handler/repo.cljs, src/main/frontend/mobile/core.cljs, src/main/frontend/search/agency.cljs, yarn.lock
Follow up of #10081
- Fix iOS Logseq Sync download progress notification
- Refactor iOS's initial appOpenUrl handling using `preinit-homepage` introduced in #10081 
- Do not read out all version files when backing up files
- Avoid unnecessary file-reading when calling create-today-journal!
=> Fix: iOS sync download progress; refine iOS share intent

src/main/frontend/handler/editor.cljs
@xyhp915 I am not sure if this is an acceptable solution. I decided to take shot at it, since the issue was introduced by #9926. Feel free to close the PR or make changes to it. 
The problem seems to be this change https://github.com/mozilla/pdf.js/pull/15373 that removed the registration of the keyboard shortcuts and added an event listener for the global `copy` event.
The changes work for non-detached PDFs, and also respect Logseq's keyboard shortcut config. I tried using `document.execCommand("copy")` that didn't work. I also don't know what's the best way to handle the detached window. I think ideally we would want to listen to our custom keyboard shortcuts.
Resolves #10058
=> Fix (PDF): Copy keyboard shortcut

src/main/frontend/common.css
Remove `word-spacing: -0.15em;` CSS rule under `:not(pre) > code` selector, which is causing inline code to be not strictly monospace and can not align between lines:  
Close #10061.
=> fix: remove `word-spacing` css rule for inline code, so they are actually monospace

static/yarn.lock
Package upgraded here https://github.com/logseq/logseq/pull/10079
Should fix failing e2e tests on recent PRs (https://github.com/logseq/logseq/actions/runs/5976530434/job/16215023601?pr=10096).
=> chore (deps): Update static yarn.lock

src/electron/electron/core.cljs
Based on [this comment](https://github.com/logseq/logseq/pull/9735#issuecomment-1607101801), we override the default [Window and File menu](https://www.electronjs.org/docs/latest/api/menu#examples) to disable the close window shortcut on all platforms. This binding seems to annoy a lot of users, and multi-window workflow is not properly supported yet. The menu item itself is preserved. `CmdOrCtrl+Q` will now be the only shortcut that closes the window. `CmdOrCtrl+W` is free to be used by plugins or Logseq to dismiss panes etc.
Resolves #3967
=> Enhance: Disable close window shortcut

docs/develop-logseq-on-windows.md
The scoop `clojure` package being deprecated in favor of `clj-deps` which is already included.
Following up on https://github.com/logseq/logseq/pull/8857:
> - re-add scoop and choco instructions (these are untested)
The choco instructions do not work **for cmd.exe** ; more specifically, the `choco install clojure` command does not provide the `clojure` CLI utility **for cmd.exe**:
```
C:\dev\logseq>yarn watch
yarn run v1.22.19
$ run-p gulp:watch cljs:watch
$ gulp watch
$ clojure -M:cljs watch app electron
'clojure' is not recognized as an internal or external command
```
After running the the scoop install commands, it works OK:
```
C:\dev\logseq>yarn watch
yarn run v1.22.19
$ run-p gulp:watch cljs:watch
$ gulp watch
$ clojure -M:cljs watch app electron
Downloading: …
```
=> Update develop-logseq-on-windows.md to warn about Choco

src/main/frontend/components/reference.cljs, src/main/frontend/handler/editor.cljs, src/main/frontend/state.cljs
https://github.com/logseq/logseq/assets/1779837/77a9ccfc-cad3-4c0b-95c0-ef8ad9a1753f
https://github.com/logseq/logseq/assets/1779837/89488b6b-4219-4e40-8199-07d6ff5fb928
=> fix(ux): make linked references filters reactive when the page properties changed

src/main/frontend/ui.cljs
Fixes #10106
This PR uses the `select` event instead of the `mouseup` event for firing the `input-selection-end` event (`logseq.Editor.onInputSelectionEnd`). This eliminates some unexpected behaviors reported in #10106 and enables keyboard interactions.
Manually tested and it works. And the selection of multiple blocks is not affected.
=> fix: input-selection-end is not firing correctly

libs/src/LSPlugin.core.ts, libs/src/LSPlugin.user.ts, libs/src/postmate/index.ts
Fixes #10107
If there is an error in the child iframe `beforeunload`, the promise will never resolve, making us wait infinitely. Therefore, the `try{}catch{}` block is not working as expected:
https://github.com/logseq/logseq/blob/361d08debe9e0f0b274f8f7ec6c9103be55550dc/libs/src/LSPlugin.core.ts#L920-L928
This PR rejects child promise on error so that the `try{}catch{}` block is catching the error.
To test it, follow #10107 but change `@logseq/libs` to the development one.
One question, should I update `LSPlugin.core.js` in this PR?
=> fix: reject promise on child error

src/main/frontend/extensions/pdf/pdf.css
Resolves https://github.com/logseq/logseq/issues/10108
That seems like a stretch, but judging from the video, the only thing that resulted in this behavior was switching to the dark theme of the PDF viewer and trying to jump on a ref that requires scrolling. Opening the dev tools somehow makes the issue consistently reproducible, although it's not necessary. The filter rule creates a new stacking context that seems to mess with the auto scrolling. Moving the rule to the individual pages seems to fix this. This is not related to different page sizes within the same PDF, so we need to validate that the reported issue is fixed when this is released.
=> fix (pdf): Scroll to ref on dark theme

deps/common/src/logseq/common/path.cljs, src/main/frontend/handler/web/nfs.cljs
For compatibility, loading the graph is not prevented. Only show a warning notification box.
=> enhance(fs): check graph folder for bad name and nested graph

src/main/frontend/components/plugins.cljs, src/main/frontend/fs/sync.cljs
Follow-up of #10134
- Fix green state is not reliable: stop sync when ws-connection is not available
- If the outgoing internet connection is cut(WiFi/wired connection still available), the ws-connection retries forever. The sync icon stays green.
- Close network connectivity warning notification when the network is available
- Add testing URLs to the Proxy Setting dialog
- Fix: Retry sync connection even when app starts without a network connection(sync state is nil)
=> enhance(sync): refine network checking

src/electron/electron/handler.cljs, src/electron/electron/window.cljs, src/main/frontend/components/theme.cljs
Based on the[ electron docs](https://www.electronjs.org/docs/latest/api/browser-window#using-the-ready-to-show-event), we keep the window hidden until the app is loaded to avoid the theme blinking state. The only downside of this approach is that the initial display of the app will be delayed. Although we could show a loading banner until the app is fully loaded, I am not sure if the delay is long enough to justify that. Improving the loading speed might also be possible.
Regarding the event hook, `ready-to-show` fires too soon in our case. I also tried `did-finish-load` with similar results, which is why I decided to use the `theme-loaded` event. If there is a more appropriate event that does the same thing time-wise, I would be happy to try it.
The `manage` call of `windowStateKeeper` …
=> Enhance (UX): Electron loading

src/main/frontend/components/container.css
I am indifferent towards this, so I decided to push a fix since the requested change was trivial. The team can test this and decide to merge or reject it. The action buttons of the sidebar panes will now always be visible to resolve [this discord feedback](https://discord.com/channels/725182569297215569/802530020605820949/1148255023676006440) and also indirectly fix two bugs, because of the visibility change. The buttons were already visible on mobile devices, but that does not include desktops or laptops with touchscreens.
Resolves #10053
Resolves #10051
=> Fix: Close button visibility

src/electron/electron/handler.cljs, src/electron/electron/window.cljs, src/main/frontend/components/theme.cljs
Initial PR https://github.com/logseq/logseq/pull/10049
Introduced bug https://github.com/logseq/logseq/issues/10162
Reverted the [revert](https://github.com/logseq/logseq/pull/10165) and pushed a fix. The issue was that use-effect was triggered on window resize. Added an empty list as a second param to `use-effect!` to ensure that it is only triggered once. 
Tested on Linux and macOS. I am experiencing issues with my Windows VM. It would be nice if we could also test this on Windows before merging, to make sure it's working properly on all platforms.
To QA, open Logseq, maximize the window and close the app. Re-open the application and try to unmaximize and resize the window.
=> Enhance (UX): Electron loading (fixed)

src/main/frontend/extensions/video/youtube.cljs, src/main/frontend/util.cljc
NOTE: I'm not sure if this fixes case 2 (see #9920) where "NN:NN" is interpreted as "hour:min", instead of "min:sec"...  If it does not, I apologize. I'm just recalling my LISP and trying to figure out this ClojureScript thing. It's possible that case 2 is not resolved (I don't see how my modification would change anything if case 2 was already an issue), and if so, would appreciate some guidance or help.
=> youtube.cljs: allow for single-digit minutes and seconds in youtube-timestamp (addresses #9920)

src/electron/electron/configs.cljs, src/electron/electron/handler.cljs
A log from a user without further info.
```
[2023-09-10 19:10:11.581] [debug] :electron.handler/watch-dir {:path "C:/Users/user/Documents/Logseq"}
[2023-09-10 19:10:12.369] [error] IPC error:  {:event #object[Object [object Object]], :args #js ["inflateGraphsInfo" #js [#js {:url "logseq_local_C:/Users/user/Documents/Logseq", :root "C:/Users/user/Documents/Logseq", :nfs? true}]]} Error:                                                                                      is not ISeqable
at $cljs$core$seq$$ (C:\Users\user\AppData\Local\Logseq\app-0.9.17\resources\app\electron.js:1535:9)
at $cljs$core$rest$$ (C:\Users\user\AppData\Local\Logseq\app-0.9.17\resources\app\electron.js:1548:356)
at $cljs$core$next$$ (C:\Users\user\AppData\Local\Logseq\app-0.9.17\resources\app\electron.js:1552:290) …
```
=> chore(electron): use logger instead of console.log

src/main/frontend/components/window_controls.cljs, src/main/frontend/handler/whiteboard.cljs, src/main/frontend/handler/window.cljs, src/main/frontend/modules/shortcut/config.cljs, src/resources/dicts/en.edn
Continuing on #10096. Now that the default keyboard behavior is deactivated, users will be able to remove the introduced binding if they want to.  I moved the window handlers to a dedicated file to clean up the code. The binding was added to `:shortcut.handler/global-non-editing-only` to avoid closing the window while editing, which might be questionable. I can move it to global bindings if that's not what we want. I also suppressed some random infer build warnings here 6d15483051ce3621d31dcdf1f288b1b2c51972a1.
Resolves https://github.com/logseq/logseq/issues/10176
=> Enhance: Introduce customizable close window shortcut

resources/js/preload.js
Fix #10188
Support both percent-encoding and non-percent-encoding.
=> fix(fs): support asset filenames with percent encoding

deps.edn
I've confirmed that #10218 is fixed by this.
=> fix: fix backslash characters unable to be keybound in #10218 with rewrite-edn update

src/main/frontend/handler/web/nfs.cljs
See-also: #10246
Disable this for now. It's actually safe to use.
=> fix(fs): disable graph name warning

package.json, yarn.lock
codemirror v5.65.15 is the last version of codemirror 5. There are no breaking changes between the two releases.
changelog:
https://codemirror.net/5/doc/releases.html
codemirror v6 contains breaking changes (not tested w/ logseq)
https://codemirror.net/docs/migration/
=> chore(deps): bump CodeMirror from 5.58.1 to 5.65.15

src/main/frontend/components/page.cljs, src/main/frontend/handler/dnd.cljs
See-also: #10104, #10262
- Add drop handler to `dummy-page` component
- Add the same style as `dnd-separator`(only top border, since incoming blocks always appear at the top of the page)
To Reproduce:
- Use any calendar plugin, click and nav to a non-exsit page, then `dummy-page` will shown.
- Drag a block from the right side bar to the "Click here to edit..." placeholder
=> fix(editor): drag and drop to dummy page

src/electron/electron/core.cljs
I've modified the source to enable zooming as per this issue: #5637 
It is a longstanding issue from the electron project, found and implemented a workaround as per the [docs](https://github.com/electron/electron/blob/main/docs/tutorial/keyboard-shortcuts.md).
> To configure a local keyboard shortcut, you need to specify an [accelerator](https://github.com/electron/electron/blob/main/docs/api/accelerator.md) property when creating a [MenuItem](https://github.com/electron/electron/blob/main/docs/api/menu-item.md) within the [Menu](https://github.com/electron/electron/blob/main/docs/api/menu.md) module.
=> enhance(electron): ctrl or cmd + = to zoom

src/main/frontend/components/container.css, src/main/frontend/components/whiteboard.css, src/resources/dicts/en.edn, tldraw/apps/tldraw-logseq/src/components/ActionBar/ActionBar.tsx, tldraw/apps/tldraw-logseq/src/styles.css, tldraw/packages/core/src/lib/TLApi/TLApi.ts, tldraw/packages/core/src/lib/TLSettings.ts, tldraw/packages/react/src/components/AppCanvas.tsx, tldraw/packages/react/src/components/Canvas/Canvas.tsx, tldraw/packages/react/src/hooks/useCanvasEvents.ts, tldraw/packages/react/src/hooks/useShapeEvents.ts
A simplified approach to pen mode. When this mode is enabled, non 'pen' type pointer events will be rejected.
Although this feature needs to be explicitly enabled, it would be nice if we could test this on multiple different devices before release. It seems to work fine on my wacom tablet on linux. I also made some minor style adjustments to our bottom toolbars for mobile.
Resolves #9863
Also see
https://discuss.logseq.com/t/whiteboards-could-really-do-with-palm-rejection-for-use-on-tablets/16769
https://discuss.logseq.com/t/whiteboard-ipad-apple-pencil-support/17526
=> Feat (Whiteboards): Pen mode (palm rejection)

libs/src/LSPlugin.ts
The current `BlockEntity` interface does not have a marker prop.
This PR adds the marker prop (optional string) for better typing.
=> chore: add marker prop to BlockEntity interface

resources/js/preload.js
It is currently possible for plugins to access clipboard data from a small set of supported formats, e.g. `text/plain`, `text/html`. However, it is not possible to access custom formats like `application/custom` (for more context, see [here](https://bugs.chromium.org/p/chromium/issues/detail?id=487266)). For a plugin I am currently developing I want to provide interoperability with an application that uses such a custom clipboard data format.
This change adds a function that allows for accessing this data to `preload.js`. It exposes this function to the main world. I believe this change would also be useful for the development of other plugins.
=> dev: Allow plugins to access custom format clipboard data

src/main/frontend/mobile/action_bar.cljs, src/main/frontend/mobile/core.cljs, src/main/frontend/mobile/index.css, src/main/frontend/state.cljs
- back button should close the action bar
- Should not quit when editing
- Should not quit when selection is active
- Avoid vertical scroll bar of action bar
Fix #10341
=> Fix android back button closing order

src/main/frontend/components/block.cljs, src/main/frontend/extensions/tldraw.cljs, src/main/frontend/fs/capacitor_fs.cljs, src/main/frontend/handler/assets.cljs, src/main/frontend/handler/editor.cljs, src/main/frontend/mobile/camera.cljs, src/main/frontend/mobile/intent.cljs, src/main/frontend/mobile/record.cljs
- Refactor: mv get-asset-file-link to assets-handler
- Fix: iOS binary file saving using base64
- Fix: block-drop handler should also accept files
- Fix: Drop assets on non-editing block
Related issues:
- Fix #10338 
- Fix #10248
- Fix #9799
- Fix #5636, by not handling block-drop when editing
- Fix #2508
=> Fix: drag and drop of assets, not being about to save assets sometimes

src/main/frontend/date.cljs, src/main/frontend/modules/file/core.cljs
Wrong date fn usage introduced in #10350.
Error in dev mode:
```
Write file failed, please copy the changes to other editors in case of losing data.
Error: Error: Assert failed: (instance? goog.date.Date dt)
at Object.cljs_time$format$unparse [as unparse] (./js/cljs-runtime/cljs_time.format.js:686:8)
at Object.frontend$date$date__GT_file_name [as date__GT_file_name] (./js/cljs-runtime/frontend.date.js:235:25)
at Object.frontend$modules$file$core$transact_file_tx_if_not_exists_BANG_ [as transact_file_tx_if_not_exists_BANG_] (./js/cljs-runtime/frontend.modules.file.core.js:168:57)
at Object.frontend$modules$file$core$save_tree_BANG_ [as save_tree_BANG_] (./js/cljs-runtime/frontend.modules.file.core.js:245:35)
at Object.frontend$modules$outliner$file$do_write_file_BANG_ [as …
```
=> fix: wrong date fn usage in #10350

src/main/frontend/components/block.cljs, src/main/frontend/components/search.cljs
Fix #10432
This is an old bug. When using non-current journal names in page-ref, it can't navigate.
This is coupled with page-cp logic.
This fix:
- Guard at final click logic(This avoids calculating date formats for all page-refs)
- This original warning text still exists to denote a warning state: `page-inner's page-entity is nil, given page-name:  2023_10_28  page-name-in-block:  2023_10_28`
=> fix(journal): handle non standard journal name page-ref

src/main/frontend/extensions/pdf/core.cljs
Reverts logseq/logseq#10435
Regarding the issue with mouse interaction, a new branch will be created to support this feature.
=> Revert "feat(pdf): add zoom via touchpad"

.github/workflows/build-desktop-release.yml
See-also: https://github.com/actions/runner-images/releases/tag/macOS-11%2F20231030.1
=> fix(ci): lock python version in release build

src/main/frontend/components/block.cljs
NOTE: The purpose of this is to provide the ability of the plug-in to redirect the path of the pdf file by adjusting the value of `data-href`. CC: @sethyuan
=> enhance(pdf): export asset ref link as dataset value for the pdf asset

src/main/frontend/components/query/builder.cljs
Bug was caused by query string updates relying on q-str which is only valid on initial render. Subsequent changes to query caused bugs
Fixes #10263, fixes #10264 and fixes #9159. This is also fixed a bug with deleting a filter e.g. add a property filter, delete it and then observe query string still has property filter
=> fix: multiple bugs with query builder construction

src/main/frontend/components/cmdk.cljs
Previously, a user has to type `/ ` to trigger the filters.
=> enhance: remove the need to add a space to trigger search command

package.json, src/main/frontend/db/restore.cljs, src/main/frontend/db_worker.cljs, src/main/frontend/handler.cljs, src/main/frontend/modules/shortcut/core.cljs, src/main/frontend/persist_db/browser.cljs, src/main/frontend/persist_db/node.cljs, yarn.lock
See-also: https://github.com/logseq/sqlite-db
Changes:
- Use a different file set for each graph (db, journal, wal, shm. This also leaves space for the search index, maybe vector db in the future)
- Split async init and sync loading logic
=> Feat: multi tab db worker

src/main/frontend/components/cmdk.cljs
BUG:
- In CMDK search input: page jumps when ENTER key is pressed while IME composing.
- Expected: handle composing finished event(pass event to system)
https://github.com/logseq/logseq/assets/72891/e0d0ed5d-0fc7-47b2-9de9-3e581275dba9
=> fix(cmdk): enter key while ime composing

src/main/frontend/components/cmdk.cljs, src/main/frontend/mixins.cljs
BUG: 
- when typing in all uppercase with shift, the `shift?` state is not cleared.  The page will be always open in side-bar.
=> fix(cmdk): shift key state handling

src/main/frontend/components/block.cljs, src/main/frontend/components/block.css, src/main/frontend/components/container.css, src/main/frontend/ui.cljs
=> fix(ui): theme details

deps/shui/src/logseq/shui/list_item/v1.cljs, e2e-tests/editor.spec.ts, src/main/frontend/components/cmdk.cljs, src/main/frontend/search/db.cljs
- Fixes #10573 
- Fixes #10574 
- Fixes #10575
- Fixes #10576
- Fixes #10577
=> Fix new search issues

src/main/frontend/extensions/slide.cljs
This fixes https://github.com/logseq/publish-spa/issues/11. To QA the fix locally:
* `bb dev:publishing /path/to/a/graph publish`
* `python3 -m http.server 8080`
* In another tab, open `http://localhost:8080/publish/#/page/home` in a browser
* Click on three dots menu in upper right and select 'View as slides' to see slides load a page's blocks correctly
=> fix: slides don't work on published sites that aren't under '/'

package.json, src/main/frontend/extensions/excalidraw.cljs, src/main/frontend/fs/node.cljs, yarn.lock
- Fix #7321
- Update excalidraw to 0.16.1 (0.17 is not possible due to CLJS compiler does not support the newest JS standard)
- Fix wrong EEXISTS reporting for mkdir
See-also: https://github.com/excalidraw/excalidraw/blob/557add5bf7dd1d682e5802e5a6289cdb895b1593/src/data/json.ts#L42-L65
=> Fix: inline images are not saved in excalidraw

src/main/frontend/handler/paste.cljs
I believe this is a typo in the original logic.
Bug: Only multi-level HTML lists can be pasted. When all items are at the same level, only raw markdown is parsed.
- Fix "Full content is not displayed, Logseq doesn't support multiple unordered lists or headings in a block."
=> fix(editor): incorrect handling of pasting html list

package.json, resources/package.json, static/yarn.lock, yarn.lock
=> chore(deps): upgrade electron v27

deps.edn, deps/db/deps.edn, src/main/frontend/db/utils.cljs
Updating datascript version to derisk our datascript update in feat/db. [Changes since 1.3.8](https://github.com/tonsky/datascript/blob/master/CHANGELOG.md#138) should be backwards compatible except for `d/entity` which I've accounted for by updating `db/entity`
=> chore(deps): Update datascript to latest version before our fork

deps/db/src/logseq/db/sqlite/db.cljs, src/electron/electron/core.cljs, src/electron/electron/db.cljs, src/electron/electron/handler.cljs, src/main/frontend/db_worker.cljs, src/main/frontend/handler.cljs, src/main/frontend/persist_db.cljs, src/main/frontend/persist_db/browser.cljs
This PR writes the transaction data to both the db backed by OPFS and another one on disk, to avoid any data-loss in case the app crashes.
One caveat is that any transaction will be repeated to 3 dbs (memory, OPFS, disk), it doesn't slow down the UI because writing to OPFS and disk is asynchronous, in the future, we'd like to skip writing to the memory db, writes will go directly to OPFS. Chrome doesn't support specifying a folder on disk to use OPFS (in our case `~/logseq/graphs`), so we still need to write to disk, hopefully, this'll be changed soon so that we can write once.
=> Save transactions to disk db to avoid data-loss

src/main/logseq/api.cljs
solution context: https://clojure.org/guides/faq#keyword_number
=> fix(api): safety key string for the simple command key value

src/resources/dicts/fr.edn
Translates to "linked references" when it should be "unlinked references"
=> fix(i18n): Fix french translation typo

src/main/frontend/util/fs.cljs, src/test/frontend/db/name_sanity_test.cljs
Patch for  https://github.com/logseq/logseq/issues/9196
This patch resolves a problem that prevents Logseq from loading pages with titles beginning with a dot.
The solution is to force the percent-encoding of a leading dot.
Other solutions could be considered.  For example, distinguishing between a hidden file (e.g., ".bashrc") and a Logseq page file (e.g., ".NET.md")  might solve the issue, but it appears to impact the overall program significantly.
The good thing about this patch is its simplicity.  
Limitations of this approach:
- It cannot resolve existing files that start with a dot character. It resolves only newly created files.
- Until now, the page titled '.' was saved as '.___.md,' but from now on, it will be '%2E.md'.
- File names starting with '%2E' are somewhat unsightly.
=> Percent encoding of leading dots

src/main/frontend/extensions/pdf/core.cljs
Area highlights don't blink when jumping to it.  
Maybe we sould use the same id naming style for all highlights elements, so area highlights (when in filled style) would blink as text highlights do.
PS: I don't know if disabling the blinking is by design. Let me know if it's not a bug but a feature :)
- [`id` of text highlight](https://github.com/e-zz/logseq/blob/27e3b9d019fc39c875616205f96d234cb307dddc/src/main/frontend/extensions/pdf/core.cljs#L254) 
- [The part for blinking in `pdf/utils.js` ](https://github.com/e-zz/logseq/blob/27e3b9d019fc39c875616205f96d234cb307dddc/src/main/frontend/extensions/pdf/utils.js#L123C5-L130)
``` js
// blink highlight
function blinkHighlight () {
const id = highlight?.id
const el = document.getElementById(`hl_${id}`)
if (!el) return …
```
=> fix(pdf): area highlights don't blink

deps/shui/src/logseq/shui/list_item/v1.cljs, src/main/frontend/components/cmdk.cljs
Fixes #10698 
Page aliases were getting formatted in the `cmdk.cljs` file, so when those results were being rendered as `list_item`, the `text` property wasn't a string. Thus, nothing would get highlighted.
A lot of the search result formatting (of headers for blocks and whatnot) are already taking place in the `list_item/v1.cljs` file so we can just move the alias formatting there so that the highlighting works the same as for non-alias results.
=> fix: Highlight page aliases in search results

src/main/frontend/ui.cljs
close #10635 
Through my investigation, I found that pressing the Enter key while focusing on a button triggers the click event twice, with the second click happening within the `mixins/on-key-down` function of the modal.
https://github.com/logseq/logseq/blob/ab37d30e2d64dfcc889329276dd8ca310d7429ba/src/main/frontend/ui.cljs#L635-L641
The idea to fix issues is to stop the propagation of keydown event in `ui/button` when it is assigned `ui__modal-enter` classname.
=> fix(ui): prevent button in modal from being clicked twice when pressing enter key

resources/package.json, static/yarn.lock
Use zig linker to link against glibc 2.17 (>= CentOS 7)
See-also: #10811
=> fix(rsapi): refine build, supports old glibc

src/main/frontend/components/editor.cljs, src/main/frontend/handler/block.cljs, src/main/frontend/handler/editor.cljs, src/main/frontend/util.cljc, src/main/frontend/util/cursor.cljs, src/test/frontend/util_test.cljs
This PR fixes a series of data errors related to inappropriate handling multiple characters caused by cursor postion changes.
- moving up or down across blocks or inside a block may enter the middle of a character
Case 1: across blocks
* 😀
* a
Case 2: inside a block
* 😀
ba
Both case, put cursor after "a" then click up arrow key then click enter it will separate 😀 to 2 unrecoginzed characters.
- right arrow calculate character length incorrect if the cursor is at the beginning of the block
If the block is beginning with an emoji, like "😀a", click right arrow from 0 should go to 2, current it's 1.
- unable to use 'del' to delete the last character if the cursor is at the beginning of the block
For example, "abcdefg", if the cursor is between a and b then click 'del' it will delete from "b" …
=> Fix wrong cursor posistion

src/main/frontend/handler/export/common.cljs, src/main/frontend/handler/export/html.cljs, src/main/frontend/handler/export/opml.cljs, src/main/frontend/handler/export/text.cljs, src/test/frontend/handler/export_test.cljs
when export with "no-indent" style
export:
```
- 1
2
- 3
4
```
result:
```
1
2
3
4
```
before-fix:
```
1
2  
3
4
```
=> fix(export): remove prefix spaces when no-indent

src/resources/dicts/fr.edn
Handle more plural forms (0, "", nil).
- `""` is used as argument `total` in `unlinked-references/reference-count`
- `nil` is used as argument `filtered-count` in `linked-references/reference-count`
Expressions were tested at `https://tryclojure.org/`.
=> fix: Update French translations

src/main/frontend/components/editor.cljs
Right now, the mock text maybe disordered if it's long enough.
If the block contains a long text, click the block to make it editable will generate a mock span per character to help calc cursor postion, the spans should be ordered as the content.
=> Fix mock text disordered

src/main/frontend/handler/export/text.cljs, src/test/frontend/handler/export_test.cljs
example:
export result:
````
asdf
```clojure
(defn- make-push-assets-update-ops-timeout-ch
[repo never-timeout?]
(if never-timeout?
(chan)
(go
(<! (async/timeout 2000))
;; TODO: get-unpushed-assets-update-count
(pos? (op-mem-layer/get-unpushed-asset-update-count repo)))))
```
```
var d                        = require("../")
, getOwnPropertyDescriptor = Object.getOwnPropertyDescriptor;
module.exports = function (t, a) {
var Foo = function () {}, i = 1, o, o2, desc;
Object.defineProperties(
Foo.prototype,
t({
bar: d(function () { return ++i; }),
bar2: d(function () { return this.bar + 23; }),
bar3: d(function () { return this.bar2 + 34; }, { desc: "ew" }),
bar4: d(function () { return this.bar3 + 12; }, { cacheName: "_bar4_" }),
bar5: d(function () { return this.bar4 + 3; }, { cacheName: …
=> fix(export): remove leading spaces for block-src when no-indent

docs/contributing-to-translations.md, docs/dev-practices.md, src/main/frontend/context/i18n.cljs, src/resources/dicts/fr.edn
This PR reverted overly complex fn translations from #10810 and updates docs to emphasize that fn translations need to remain as simple as possible
=> fix: Simplify fn translations in light of #10868

src/main/frontend/components/export.cljs, src/main/frontend/components/file.cljs, src/main/frontend/db_worker.cljs, src/main/frontend/extensions/zip.cljs, src/main/frontend/handler/export.cljs, src/main/frontend/handler/export/common.cljs, src/main/frontend/handler/export/opml.cljs, src/main/frontend/handler/export/opml.cljs.~3f773ed876c3d1b88bdcae855dbed02d3f2d4c62~, src/main/frontend/handler/export/text.cljs, src/main/frontend/handler/whiteboard.cljs, src/main/frontend/worker/export.cljs, src/main/frontend/worker/file/core.cljs, src/test/frontend/handler/export_test.cljs
The end goal is to separate export to its own dep and move related queries to the worker so we can lazy load data in the main UI thread.
=> refactor(export): move export work to web worker

bb.edn, deps/publishing/src/logseq/publishing.cljs, deps/publishing/src/logseq/publishing/export.cljs, deps/publishing/src/logseq/publishing/html.cljs, docs/dev-practices.md, scripts/src/logseq/tasks/dev.clj, scripts/src/logseq/tasks/dev/publishing.cljs, shadow-cljs.edn
This PR fixes #10893 which stopped working when we changed our React setup with #10694. This PR also improves the publishing frontend dev experience with a watched dev mode e.g. `bb dev:publishing /path/to/graph tmp/publish --dev`
=> fix: publishing app not building

package.json, yarn.lock
See-also: https://github.com/logseq/rsapi/commit/a95f2b79dc72364376b52d2921c87b001e35e4f5
- Close #10916
- Close #10828
=> fix(android): sync crash caused by wrong logging

src/main/frontend/handler/editor.cljs, src/main/frontend/mobile/mobile_bar.cljs
- Close #10879
- Close #8503
- Close #10013
NOTE: This is a behavior change. When clicking the "cycle todo" button, the App will exit editing mode.
This is OK for mobile devices.
=> fix(mobile): commit composing text before cycle todo

src/main/frontend/components/git.cljs, src/main/frontend/components/page_menu.cljs, src/main/frontend/handler/events.cljs, src/main/frontend/handler/shell.cljs
This PR is a quick fix to #9506
Since the version list (which is a notification panel) is currently overlapped with the versioned file content (which is a modal), I think the most straightforward way to fix this problem is to close the notification panel after the user open the file content modal.
=> fix #9506: close history panel after select a version 

src/main/frontend/components/page.cljs, src/main/frontend/extensions/graph.cljs, src/main/frontend/extensions/graph/pixi.cljs, src/main/frontend/schema/handler/common_config.cljc, src/main/frontend/state.cljs, src/resources/templates/config.edn
This MR adds the ability to change graph forces in the graph view, under a new dropdown menu item called "Forces"
This resolves requests for a customisable/better graph algorithm:
- https://discuss.logseq.com/t/extracting-more-understanding-from-graph-view-additional-graph-layout-algorithms/16841
- https://discuss.logseq.com/t/improve-graph-view-relationship-types-link-styling-and-graph-parameters-like-in-cosma/7023
- https://discuss.logseq.com/t/how-the-graph-view-could-improve-creativity/5579
This should also resolve some a number of user issues related to the graph layout being messy/not being very useful:
- https://discuss.logseq.com/t/graph-overlapping-problems/1726
- https://discuss.logseq.com/t/better-graph-make-sure-the-edges-of-graph-do-not-cross-like-obsidian/16862
Users …
=> feat: add ability to change graph forces via UI

android/app/build.gradle, android/app/capacitor.build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/assets/capacitor.plugins.json, android/app/src/main/java/com/logseq/app/FolderPicker.java, android/capacitor.settings.gradle, package.json, src/main/frontend/components/block.cljs, src/main/frontend/mobile/intent.cljs, yarn.lock
Allow users to choose between 'Share' or 'Open Default App'.
This also disables sentry for Android native. Since the UI part uses sentry react.
Close #10976
=> Enhance: Android share/open asset file

src/main/frontend/config.cljs
See-also #11010
This is not a fix, instead, this PR allows sharing and saving an heic file.
Heic file requires some polyfill to be displayed on a webview.
=> fix: add .heic to media type

src/main/frontend/components/encryption.cljs
Minor fix for mobile UI.
Prevent the password input box from overlapping with the keyboard.
=> fix(ui): shorter heading for pwd input box

src/main/frontend/handler/editor.cljs, src/main/frontend/modules/shortcut/config.cljs, src/resources/dicts/en.edn
This PR adds a keyboard shortcut to toggle the expanded/collapsed state of the currently edited or selected block(s), addressing requests made here:
- https://discuss.logseq.com/t/toggle-block-expanded-shortcut/2161
- https://github.com/logseq/logseq/issues/9676
The new keybinding defaults to `mod + ;` by default. It works by checking whether the focused block is currently expanded or collapsed, and invoking `collapse!` or `expand!` respectively. Scenarios where the whiteboard UI is active, or where no block is currently being edited/selected, are left as no-ops for now.
=> feature: new keybinding for "toggle expand/collapse this block"

src/electron/electron/core.cljs, src/electron/electron/git.cljs, src/electron/electron/handler.cljs, src/electron/electron/state.cljs, src/main/frontend/components/commit.cljs, src/main/frontend/handler/shell.cljs
This removes all use of `:graph/current` in the electron state, and fixes the issue where git autocommit will only work on the last opened graph. Fixes #11011.
=> fix: Deprecate :graph/current in the electron state

src/main/frontend/modules/outliner/datascript.cljc, src/main/frontend/modules/outliner/tree.cljs
This is an attempt at a fix. There may be a better way to do this. When cutting + pasting the root node's references are not preserved. The problem is that the root-block returned by `db/pull` misses the `:block/_refs` while blocks returned by `db/get-block-and-children` contain `:block/_refs`. I know too little about the inner workings for Logseq and Datascript to know if this is expected. If someone could let me know whether or not this is expected or whether there is a way to modify `db/pull` to return `:block/_refs` that would be great.
More details can be found in this issue: https://github.com/logseq/logseq/issues/4491
=> Fix: Preserve root node block refs when cutting + pasting.

src/main/frontend/handler/export/text.cljs
In the case of blocks with multiple lines, we should add an extra inline break following the last simple ast.
Related issue: [#10930](https://github.com/logseq/logseq/issues/10930)
=> fix: missing newline after multiline block when exporting a page #10930 

android/app/build.gradle, ios/App/App.xcodeproj/project.pbxproj, resources/forge.config.js, resources/package.json, src/main/frontend/version.cljs
- Fix toggling of task list #11046 [#11079](https://github.com/logseq/logseq/pull/11079)
- fix: missing newline after multiline block when exporting a page #10930  [#10934](https://github.com/logseq/logseq/pull/10934)
- fix(editor): incorrect cursor move for the emoji from the line head [#11112](https://github.com/logseq/logseq/pull/11112)
- fix(sync): logout and clear cognito keys [#11111](https://github.com/logseq/logseq/pull/11111)
- fix(ux): support href prop for the classical ui button component [#11068](https://github.com/logseq/logseq/pull/11068)
- Update rsapi and fix token expiration [#11088](https://github.com/logseq/logseq/pull/11088)
- enhance: display username on Logout button [#11105](https://github.com/logseq/logseq/pull/11105)
- enhance(i18n): Fixed and added some …
=> chore(release): bump version 0.10.8

src/main/frontend/search/db.cljs
See-also: https://www.fusejs.io/api/options.html#ignorelocation
Improve search relevance by finding terms anywhere within the PR title's first 500 characters.
Previously, searches were limited to the first 60 characters of the title.
=> fix(search): fine tune page title search strategy

package.json, tailwind.config.js, yarn.lock
`yarn watch` says:
```
warn - As of Tailwind CSS v3.3, the `@tailwindcss/line-clamp` plugin is now included by default.
warn - Remove it from the `plugins` array in your configuration to eliminate this warning.
```
This modification removes the warning, and avoids a dependency that is no longer useful.
=> dev: remove obsolete "@tailwindcss/line-clamp" dependency

.github/workflows/build-desktop-release.yml, resources/package.json, static/yarn.lock
This PR intoduces [long-awaited](https://github.com/logseq/logseq/issues/6623) linux-arm64 builds!
A few notes on the PR:
1. Dugite was updated from 2.5.0 to 2.5.1. There should be no incompatibilities (see UPD2 below) between this versions but [2.5.1 has linux-arm64 support](https://github.com/logseq/logseq/issues/6623#issuecomment-1731775174). Please kindly check if everything works as expected before merging this upgrade to upstream.
2. Since AppImage [builder has hardcoded x64 architecture](https://github.com/logseq/electron-forge-maker-appimage/blob/master/src/MakerAppimage.ts#L123) specified in build settings, I have commented-out moving AppImage to builds directory. After (if?) it will be fixed it's possible to just uncomment related line and everything should work just fine. …
=> Linux ARM64 build support

deps/graph-parser/src/logseq/graph_parser/block.cljs, src/main/frontend/handler/editor.cljs, src/main/frontend/handler/page.cljs
fix: https://github.com/logseq/logseq/issues/9220
=> fix: missing refs for property text values when creating a page

package.json
This only adds `DEBUG=pw:api` to the environment variables set by `cross-env` for the `e2e-test` script, as mentioned [here](https://github.com/logseq/logseq/issues/11195#issuecomment-2034200367).
=> e2e-test: add "DEBUG=pw:api" to "e2e-test" script in package.json (fix #11195)

docs/develop-logseq.md
This only specifies in `docs/develop-logseq.md` that there are also dependencies in `/static` that need to be `yarn install`'d.
=> docs/develop-logseq.md: specify that dependencies in /static also exist (fix #11192)

src/main/frontend/components/page.cljs, src/main/frontend/components/page.css
Related: #11250
This should be a regression. I remember one day when I could use a keyboard to create new blocks.
The "Skip to main content" is also for keyboard-only operations.
This should be cherry-pick to db branch when merged.
=> fix(editor): new block placeholder should accept tab and enter key

android/app/build.gradle, ios/App/App.xcodeproj/project.pbxproj, resources/forge.config.js, resources/package.json, src/main/frontend/version.cljs
- fix: feature request dead link [#11207](https://github.com/logseq/logseq/pull/11207)
- fix: missing refs for property text values when creating a page [#11208](https://github.com/logseq/logseq/pull/11208)
- fix(editor): incorrect behavior of the delete key for deleting the last char [#11190](https://github.com/logseq/logseq/pull/11190)
- ci(build): refine windows sign [#11215](https://github.com/logseq/logseq/pull/11215)
- Linux ARM64 build support [#11183](https://github.com/logseq/logseq/pull/11183)
@KaMeHb-UA * Linux ARM64 build support by @KaMeHb-UA in [#11183](https://github.com/logseq/logseq/pull/11183)
=> chore(release): bump version 0.10.9

src/main/frontend/util.cljc
https://github.com/logseq/logseq/assets/1779837/3cf0b9b7-9ac2-4102-a38b-b7f71876927b
=> fix(mobile): incorrect theme color for the android status bar

e2e-tests/whiteboards.spec.ts, tldraw/apps/tldraw-logseq/src/hooks/usePaste.ts, tldraw/apps/tldraw-logseq/src/lib/shapes/TweetShape.tsx
After X.com changed their urls to default to x.com instead of twitter.com the code stopped detecting pasted urls
See issue #11319
- Update `TWITTER_REGEX` to `X_OR_TWITTER_REGEX` to now recognize both urls
See Regex debugger
- All add new E2E test for x.com urls based on copy of existing twitter.com test
Given my inexperience with LogSeq PR's and some maintainer might want to take this over.
I thought it would be simple one to fix though and an opportunity to help 😅
Closes #1139
=> Update Tldraw regex to detect both x.com AND twitter.com urls to preserve embed capabilities

src/main/frontend/handler/paste.cljs, src/main/frontend/quick_capture.cljs, src/test/frontend/handler/paste_test.cljs
Fixes wrapping twitter/x links with the `{{twitter }}` macro on paste. This should also fix for quick-add, though I did not test it (I'm not set up for doing so).
Adds a basic test to check that this rule works for """x""" links.
Fixes #11319
=> Fix Twitter's rename breaking macro wrapping

android/app/build.gradle, resources/forge.config.js, resources/package.json, src/main/frontend/version.cljs
Draft of changelog:
- fix(mobile): incorrect theme color for the android status bar [#11272](https://github.com/logseq/logseq/pull/11272)
- fix(sync): cannot delete some nested files [#11280](https://github.com/logseq/logseq/pull/11280)
- enhance(ux): better highlights page name for the search result items [#11271](https://github.com/logseq/logseq/pull/11271)
- Add MSI build for windows [#11301](https://github.com/logseq/logseq/pull/11301)
- Update Electron 28 [#11304](https://github.com/logseq/logseq/pull/11304)
- Update Tldraw regex to detect both x.com AND twitter.com urls to preserve embed capabilities [#11321](https://github.com/logseq/logseq/pull/11321)
@mattmazzola * Update Tldraw regex to detect both x.com AND twitter.com urls to preserve embed capabilities by @mattmazzola in …
=> chore(release): bump version 0.10.10

tldraw/apps/tldraw-logseq/build.mjs
the old domain no longer works
=> fix tsup domain

libs/README.md
Add to this document: https://logseq.github.io/plugins/
I created a simple Logseq plugin kit that does not require React or any other tools.
https://github.com/YU000jp/logseq-plugin-sample-kit-typescript
=> doc: Add a URL to a Logseq plugin kit to Plugin document

src/main/frontend/extensions/fsrs.cljs
I improved the wording about how to choose the answer button based on following guide:
- Again should be pressed if your answer is incorrect. If your answer is partially correct, you should be strict with yourself: if it would count as a fail in real-life context outside of Anki, then it counts as a fail in Anki as well. You'll typically use this button about 5-20% of the time.
- Hard should be pressed if your answer is correct, but you had doubts about it or it took a long time to recall.
- Good should be pressed if your answer is correct, but it took some mental effort to recall it. When Anki is used properly, this should be the most commonly used button. You'll typically use this button about 80-95% of the time.
- Easy should be pressed if your answer is correct and it took no mental …
=> chore: tooltips to choose the answer button when using FSRS

src/dev-cljs/shadow/user.clj, src/main/frontend/components/header.cljs, src/main/frontend/config.cljs, src/main/frontend/handler/assets.cljs, src/main/frontend/handler/worker.cljs, src/main/frontend/persist_db/browser.cljs, src/main/frontend/worker/db_worker.cljs, src/main/frontend/worker/rtc/asset.cljs, src/main/frontend/worker/rtc/asset_db_listener.cljs, src/main/frontend/worker/rtc/client.cljs, src/main/frontend/worker/rtc/client_op.cljs, src/main/frontend/worker/rtc/const.cljs, src/main/frontend/worker/rtc/core.cljs, src/main/frontend/worker/rtc/db_listener.cljs, src/main/frontend/worker/rtc/exception.cljs, src/main/frontend/worker/rtc/full_upload_download_graph.cljs, src/main/frontend/worker/rtc/log_and_state.cljs, src/main/frontend/worker/rtc/remote_update.cljs, src/main/frontend/worker/rtc/ws_util.cljs, src/main/frontend/worker/state.cljs, src/rtc_e2e_test/client_steps.cljs, src/rtc_e2e_test/helper.cljs, src/test/frontend/worker/rtc/db_listener_test.cljs, src/test/frontend/worker/rtc/remote_update_test.cljs
This PR adds asset synchronization to the rtc implementation.
Briefly describe the implementation:
- `frontend.worker.rtc.asset-db-listener`
like `frontend.worker.rtc.db-listener`,
`asset-db-listener` add a new method to `db-listener/listen-db-changes`(`:gen-asset-change-events`),
it will generate asset-update-ops, then store them into client-ops db
- `frontend.worker.rtc.asset`
main namespace for asset-sync, the main fn is `create-assets-sync-loop`.
`frontend.worker.rtc.core/create-rtc-loop` is responsible for blocks-sync
`frontend.worker.rtc.asset/create-assets-sync-loop` is responsible for assets-sync
Some UI components are not reactive when working with asset-sync.
- download-asset-file from s3 won't trigger an ui-refresh.
- adding some highlights in PDF also won't trigger an …
=> feat: asset-sync init impl

deps/db/src/logseq/db.cljs, deps/db/src/logseq/db/frontend/content.cljs, deps/db/src/logseq/db/frontend/delete_blocks.cljs, deps/db/src/logseq/db/frontend/entity_plus.cljc, deps/db/src/logseq/db/frontend/schema.cljs, deps/db/src/logseq/db/sqlite/build.cljs, deps/db/test/logseq/db/frontend/content_test.cljs, deps/graph-parser/src/logseq/graph_parser/exporter.cljs, deps/graph-parser/test/logseq/graph_parser/exporter_test.cljs, deps/outliner/src/logseq/outliner/pipeline.cljs, deps/outliner/test/logseq/outliner/pipeline_test.cljs, docs/dev-practices.md, src/main/frontend/common_keywords.cljs, src/main/frontend/components/block.cljs, src/main/frontend/db/model.cljs, src/main/frontend/handler/common/page.cljs, src/main/frontend/handler/db_based/editor.cljs, src/main/frontend/handler/editor.cljs, src/main/frontend/handler/page.cljs, src/main/frontend/handler/paste.cljs, src/main/frontend/worker/db/migrate.cljs, src/main/frontend/worker/handler/page.cljs, src/main/frontend/worker/search.cljs
This PR replaces both `~^uuid` and `[[~^uuid]]` with `[[uuid]]` for node references in `:block/title`, to simplify the code and fix the following bugs:
1. [[~^uuid]] is shown when referencing a non-page block
2. [[nested [[page]]]] can't be parsed back after editing the block content
3. wrong page named as `~^uuid` created
4. adding an inline tag still shows the tag at the end of the block
5. non-page blocks are displayed with their names instead of `[[uuid]]` in the editor mode, there're two problems:
a. references might share the same name in the same block
b. reference block content might have other references, for example [[this is a block that has other [[reference]]]].
The migration will replace the previous references with the `[[id]]`:
1. `[[~^id]]` -> `[[id]]`
7. `#~^id` -> …
=> refactor: store all node references using `[[uuid]]`

.github/workflows/build-android.yml, .github/workflows/build-demo.yml, .github/workflows/build-desktop-release.yml, .github/workflows/build-ios-release.yml, .github/workflows/build-ios.yml, .github/workflows/build-stage.yml, .github/workflows/build.yml, .github/workflows/db.yml, .github/workflows/deploy-db-pages.yml, .github/workflows/deploy-db-test-pages.yml, .github/workflows/e2e.yml, .github/workflows/graph-parser.yml, .github/workflows/logseq-common.yml, .github/workflows/outliner.yml, .github/workflows/publishing.yml
We should be doing this since we upgraded electron in #11620 - https://github.com/electron/electron/blob/main/docs/tutorial/electron-timelines.md
=> Chore: Update actions to use Node 20

.clj-kondo/config.edn, src/main/frontend/components/block.cljs, src/main/frontend/components/cmdk/core.cljs, src/main/frontend/components/cmdk/list_item.cljs, src/main/frontend/components/container.cljs, src/main/frontend/components/editor.cljs, src/main/frontend/components/icon.cljs, src/main/frontend/components/shortcut.cljs, src/main/frontend/extensions/handbooks/core.cljs, src/main/frontend/extensions/pdf/core.cljs, src/main/frontend/extensions/pdf/toolbar.cljs, src/main/frontend/hooks.cljs, src/main/frontend/mixins.cljs
js/React uses `js/Object.is` to compare the dep-value and its previous value.
Some cljs built-in types(keyword, symbol, uuid) would not be identical, even if they are value-equal
`(identical? :a :a) = false`
=> Refactor: custom react hooks

.clj-kondo/config.edn, deps/graph-parser/src/logseq/graph_parser.cljs, deps/graph-parser/src/logseq/graph_parser/block.cljs, deps/graph-parser/src/logseq/graph_parser/cli.cljs, deps/graph-parser/src/logseq/graph_parser/extract.cljc, deps/graph-parser/src/logseq/graph_parser/property.cljs, deps/graph-parser/src/logseq/graph_parser/text.cljs, src/main/frontend/common/file/core.cljs, src/main/frontend/components/diff.cljs, src/main/frontend/components/file_based/git.cljs, src/main/frontend/components/git.cljs, src/main/frontend/components/imports.cljs, src/main/frontend/fs/sync.cljs, src/main/frontend/fs/watcher_handler.cljs, src/main/frontend/handler.cljs, src/main/frontend/handler/code.cljs, src/main/frontend/handler/config.cljs, src/main/frontend/handler/draw.cljs, src/main/frontend/handler/events.cljs, src/main/frontend/handler/file_based/file.cljs, src/main/frontend/handler/file_based/import.cljs, src/main/frontend/handler/file_based/repo.cljs, src/main/frontend/handler/file_based/reset_file.cljs, src/main/frontend/handler/import.cljs, src/main/frontend/handler/worker.cljs, src/main/frontend/worker/file.cljs, src/test/frontend/fs/diff_merge_test.cljs
Moves a handler namespace and its dependent namespaces to file-based as they are only used by file graphs. Makes maintenance easier as another 1k+ lines are explicitly file based. Merging once green
=> Refactor: mv file handlers

deps/common/src/logseq/common/uuid.cljs, deps/db/src/logseq/db/frontend/property/build.cljs, deps/db/src/logseq/db/sqlite/create_graph.cljs, deps/db/src/logseq/db/sqlite/util.cljs, deps/db/test/logseq/db/sqlite/create_graph_test.cljs, src/main/frontend/components/plugins.cljs
Ensure that the `tx-data` returned by `build-db-initial-data` is idempotent (except for certain attributes such as `:block/created-at`).
This approach can resolve potential issues of multiple duplicate blocks when RTC is enabled. 
For instance, currently, `$$$favorites` and `$$$views` may generate multiple duplicates because their `block/uuid` is randomly assigned (`d/squuid`).
testcase: build-db-initial-data-test
run `build-db-initial-data` 2 times, and compare their result
=> enhance: make build-db-initial-data idempotent

src/main/frontend/worker/db_worker.cljs, src/main/frontend/worker/rtc/client.cljs, src/main/frontend/worker/rtc/client_op.cljs, src/main/frontend/worker/rtc/core.cljs, src/main/frontend/worker/rtc/db_listener.cljs, src/main/frontend/worker/rtc/gen_client_op.cljs, src/main/frontend/worker/rtc/malli_schema.cljs, src/main/frontend/worker/rtc/migrate.cljs, src/main/frontend/worker/rtc/remote_update.cljs, src/main/frontend/worker/rtc/skeleton.cljs, src/test/frontend/worker/rtc/client_test.cljs, src/test/frontend/worker/rtc/fixture.cljs, src/test/frontend/worker/rtc/gen_client_op_test.cljs
This PR compares the client-schema-version and server-schema-version, retrieves the migration-data diff from `frontend.worker.db.migrate/schema-version->updates`, and synchronizes them to the server.
Currently, it only supports adding :properties and :classes, while ignoring :fix.
=> feat: send migrate-data when rtc start

src/electron/electron/fs_watcher.cljs, src/electron/electron/handler.cljs, src/electron/electron/utils.cljs
The reason is that `mtime` and `ctime` are lost in the main thread.
=> fix: graph keep re-index when loading

.github/workflows/build-desktop-release.yml, .github/workflows/e2e.yml
The Github Actions `download-artifact` action is deprecated, causing builds to fail.
This PR updates the `download-artifact` action from v3 to v4, fixing the pipeline builds.
=> Github Actions: update deprecated `download-artifact` workflow actions to v4

src/main/frontend/common/thread_api.cljc, src/main/frontend/handler/assets.cljs, src/main/frontend/persist_db/browser.cljs, src/main/frontend/state.cljs, src/main/frontend/worker/db_worker.cljs, src/main/frontend/worker/rtc/asset.cljs, src/main/frontend/worker/state.cljs
similar to this PR: https://github.com/logseq/logseq/pull/11790
use `#js{"remoteInvoke" remote-function}` to replace `deftype Main` in main-thread.
=> refactor: remove deftype Main

src/main/frontend/commands.cljs, src/main/frontend/components/block.cljs, src/main/frontend/components/editor.cljs, src/main/frontend/handler/editor.cljs, src/test/frontend/handler/editor_test.cljs
- Enhance the `/` input tolerance to allow the current matching content to differ from the most recent successful match by ​up to 1 extra character, if no commands match, display "No matched commands" in the popup. For example:
- ​Scenario 1
- User inputs `he` → successfully matches `help`.
- User adds `x` → input becomes `hex`, which fails to match. Since `hex` is ​1 character longer​ than `he`, the popup remains open.
- User adds another `x` → input becomes `hexx`, which fails and exceeds the tolerance (2 characters longer than `he`). The popup closes.
- ​Scenario 2
- User inputs `he` → successfully matches `help`.
- User presses the ​left arrow key, moving the cursor between `h` and `e`.
- User inputs `x` → input becomes `hx`, which fails to match. Since `hx` is ​1 character shorter​ …
=> enhance:  / command input tolerance

src/main/frontend/commands.cljs, src/main/frontend/components/block.cljs, src/main/frontend/components/block.css, src/main/frontend/components/views.cljs, src/main/frontend/db/query_dsl.cljs, src/main/frontend/db/react.cljs, src/test/frontend/db/query_dsl_test.cljs
1. able to collapse editing either simple or advanced query by clicking the settings icon.
2. more compact view, it shows the block title if it's not empty, or `Untitled query` for advanced query and query builder for simple query.
3. fixes https://github.com/logseq/db-test/issues/237
4. perf: query `:db/id` only because db views don't rely on other properties
=> enhance: query ux

src/main/frontend/components/property/value.cljs, src/main/frontend/components/property/value.css, src/main/frontend/handler/editor.cljs
For :db.cardinality/one number properties, using input instead of select to edit.
=> enhance(ux): number property input

deps/shui/src/logseq/shui/table/core.cljc, src/main/frontend/common.css, src/main/frontend/components/block.cljs, src/main/frontend/components/objects.cljs, src/main/frontend/components/table.css, src/main/frontend/components/views.cljs, src/main/frontend/handler/block.cljs, src/main/frontend/handler/editor.cljs, src/main/frontend/handler/ui.cljs, src/main/frontend/state.cljs, src/main/frontend/util.cljc
Some enhancement:
1. up/down to focus on any table row or outliner block (non-editing mode)
2. `left` to focus on the first cell when a table row has been focused, `right` to choose the last cell for this row
3. up/down/left/right to navigate between cells
4. Enter to edit a cell
5. ESC to quit editing the cell and focus on it, another ESC to focus on the table row
https://www.loom.com/share/e29191b6d7ed4fb2902edbf333e9bc3b
=> enhance(ux): table row/cell navigation

deps/db/src/logseq/db/frontend/property.cljs, deps/db/src/logseq/db/frontend/schema.cljs, deps/db/test/logseq/db/sqlite/create_graph_test.cljs, src/main/frontend/components/property/value.cljs, src/main/frontend/worker/commands.cljs, src/main/frontend/worker/db/migrate.cljs
This PR addresses some [cleanup we'd talked about](https://logseq.slack.com/archives/C04ENNDPDFB/p1736252801748289?thread_ts=1735200320.849879&cid=C04ENNDPDFB). Better to do this before the merge to master. I QAed the migration works for affected properties with deadline, scheduled and custom user repeat use cases
=> refactor: rename repeat properties to reflect use outside of tasks

src/main/frontend/common/graph_view.cljs
Fixes exclude-from-graph-view property for file graphs not working, which I just reported as logseq/db-test#277
=> (fix) excluding nodes from graph view for MD graphs

deps/db/src/logseq/db/frontend/db.cljs, src/main/frontend/components/block.cljs, src/main/frontend/components/objects.cljs, src/main/frontend/components/page.cljs, src/main/frontend/components/property.cljs, src/main/frontend/components/property/value.cljs, src/main/frontend/components/views.cljs, src/main/frontend/db/async.cljs, src/main/frontend/db/model.cljs, src/main/frontend/handler/property.cljs
This PR uses the default `select` component for setting tag properties, this makes the properties UX more consistent, efficient, and it includes some other enhancements:
1. Display `Set icon | Configure` for property page, `Set icon | Add tag property` for tag page
2. Display a collapsed triangle on the left of page title when it's collapsed.
Demo:
https://www.loom.com/share/8005608eb5bd47af83d8781ba3185bb1
=> enhance(ux): use select component for setting tag properties

deps/db/.carve/ignore, deps/db/src/logseq/db/common/sqlite_cli.cljs, deps/db/src/logseq/db/frontend/kv_entity.cljs, deps/db/src/logseq/db/sqlite/debug.cljs, deps/db/src/logseq/db/sqlite/gc.cljs, deps/db/test/logseq/db/sqlite/gc_test.cljs, src/main/frontend/handler/repo.cljs, src/main/frontend/modules/shortcut/config.cljs, src/main/frontend/worker/db_worker.cljs, src/resources/dicts/en.edn
This PR introduces gc to remove unused addresses from the `kvs` table, to reduce disk usage.
Previously, 6051be610f disabled deleting addresses from our forked [persistent-sorted-set](https://github.com/logseq/persistent-sorted-set) [pss] because the nodes using those addresses may still be shared by other nodes. This introduced errors, including missing addresses and invalidated blocks.
Using gc is safer than deleting kvs from pss because we're sure that those deleting addresses are no longer used by other nodes. 
By default, gc will run if the db hasn't been GCed before or the last time was 3 days ago, I also added a command `Garbage collect graph` so that users can run without waiting. 
Other notes:
`gc` takes about 650ms on [4k …
=> fix: gc unused addresses in SQLite kvs table

deps/common/src/logseq/common/uuid.cljs, src/main/frontend/components/views.cljs
Check our lambda rtc.
The fix is to generate persistent id for the first generated view.
=> fix: multiple default views created for linked references

src/main/frontend/components/block.cljs, src/main/frontend/extensions/code.cljs, src/main/frontend/handler/editor.cljs, src/main/frontend/handler/editor/lifecycle.cljs, src/main/frontend/handler/jump.cljs, src/main/frontend/mixins.cljs, src/main/frontend/state.cljs, src/main/frontend/util.cljc, src/main/logseq/api.cljs
Fixes https://github.com/logseq/db-test/issues/284.
This PR uses the exact dom nodes for selected blocks instead of using their blockid because blockid will find the first block in the dom tree that have this id.
This PR also fixes another bug that pressing `arrow down` in the editor can keep creating new blocks.
To reproduce:
1. create a new page `test page`
2. keep pressing `arrow down`
=> fix: delete block in a container moves cursor to another container

src/main/frontend/handler/paste.cljs
Fixes #11935 
Match with existing regex in code to ensure its valid twitter link when pasting.
=> fix: match paste of x.com links for twitter

src/resources/dicts/es.edn
I've realised that the translation for "Rectangle" in `es` is wrong: it is currently translated as "Recargar", which would be the spanish for "Reload"; the correct translation would be "Rectángulo".
After further inspection, I strongly think that this has just been a copy&paste error from a near line:
```
:whiteboard/reload                                 "Recargar"
```
=> fix(translations): "Rectangle" for es in whiteboard

deps/db/bb.edn, deps/db/src/logseq/db/common/view.cljs, deps/db/src/logseq/db/frontend/rules.cljc, src/main/frontend/db/model.cljs, src/main/frontend/db/query_dsl.cljs, src/test/frontend/db/query_dsl_test.cljs
This PR also adds a new :self-ref rule.
Query examples:
1. `[[page]]` will be [:self-ref page]
2. `(or [[page1]] [[page2]])` will be `(or [:self-ref page1] [:self-ref page2]`.
3. `(and [[page1]] [[page2]])` will be `(and [:page-ref page1] [:page-ref page2] (or [:self-ref page1] [:self-ref page2]))` to ensure the query result nodes to have at least one page reference.
Before:
After:
=> fix: :and ref query should return nodes that having at least one ref

deps/db/src/logseq/db/frontend/property.cljs, deps/db/test/logseq/db/frontend/property_test.cljs, src/main/frontend/components/property.cljs
1. When sorting properties, consider cases where values are nil or blocks/orders are identical.
2. If block/order are nil or duplicated in sorted-properties, recalculate and transact them
for example:
```
;; original sorted properties:
({:block/order "a0", :db/ident :user.property/p0}
{:block/order "a0", :db/ident :user.property/p1}
{:block/order "a0", :db/ident :user.property/p2}
{:block/order "a0", :db/ident :user.property/p3}
{:block/order "a0", :db/ident :user.property/p4}
{:block/order "a0", :db/ident :user.property/p5}
{:db/ident :user.property/p6}
{:db/ident :user.property/p7}
{:db/ident :user.property/p8})
;; -----------------------------------------------------
;;   after draging :user.property/p8  to top
;; the result sorted properties are:
({:block/order "Zt", :db/ident …
```
=> fix: properties stable sort, normalize :block/order of properties
