resources/css/common.css

Right now, the global `font-size` variable is only applied to the `#main-content-container` and does not change the `font-size` of the sidebar content.
This fix will make it work on both.

Fix: Apply font size to all divs.

---

resources/css/common.css

This will fix a two minor bugs:
Editing text with a different setting than the default one.
Before:
After:
Better todo marker alignment:
Before:
After:

Fix: Better font rendering and alignement

---

resources/css/common.css

This will fix the colors of the notification area for the dark theme.
Before:
After:

Fix: Dark theme for notification area

---

deps.edn
package.json

After updating to Clojure 1.10.1.727, `yarn watch` prints the following warning messages:
```console
DEPRECATED: Libs must be qualified, change lib => lib/lib (deps.edn)
WARNING: Use of :main-opts with -A is deprecated. Use -M instead.
WARNING: When invoking clojure.main, use -M
```
This PR fixes the warnings.

chore: use qualified lib names

---

src/main/frontend/helper.cljs
src/main/frontend/state.cljs

Sometimes the structure of the `repos` key is broken caused by some unknown reasons, which makes the `get-github-token*` can not get token even after invoking an HTTP request.
This PR provides a more clear error message.

 fix(token): fix token logic

---

src/main/frontend/handler/editor.cljs

fix: quick enter followed by a tab can lead to file corruption

---

src/main/frontend/components/block.cljs
src/main/frontend/components/reference.cljs
src/main/frontend/components/sidebar.cljs
src/main/frontend/ui.cljs

fix warning in `page` URL, including:
`help` element warning
two others react warning

fix(react): fix react warning

---

src/main/frontend/helper.cljs
src/main/frontend/state.cljs

As the user's system time may be inaccurate, this PR uses the expiration interval (60 minutes ) directly. This solution might cause some problems while Github changes the expiration interval.

 fix(token): calculate expiration based on user's system time

---

src/main/frontend/handler/common.cljs
src/main/frontend/handler/draw.cljs
src/main/frontend/handler/editor.cljs
src/main/frontend/handler/file.cljs
src/main/frontend/handler/page.cljs

Due to some concurrency issue, `git/resolve-ref` may fail in `check-changed-files-status` and an error is reported. This is unnecessary.

Do not log error when resolving ref fails in check-changed-files-status

---

src/main/frontend/handler/editor.cljs

A quick fix for https://github.com/logseq/logseq/issues/865.

fix: prevent parent block duplicate

---

src/main/frontend/state.cljs
src/main/frontend/ui/date_picker.cljs

According to https://github.com/logseq/logseq/issues/901
Is your feature request related to a problem? Please describe.
In my country week is started from monday. Now calendar a bit confused.
Describe the solution you'd like
I'm want to able change start day of week in calendar via config.edn
Add new setting :start-of-week in config.edn. 6 - Sunday, 0 - Monday. Default is 6 - Sunday.

Add support for change start of week in calendar

---

resources/css/common.css

The page refs colors got probably changed with the link colors in the recent CSS features, this fix will make it work as intended.

Fix: Page ref colors for custom themes

---

src/main/frontend/diff.cljs
src/main/frontend/handler/editor.cljs

The current implementation of `find-position` cannot handle bi-directional links, e.g., `[foo](page/foo.md)` will print '"diff error: " #object[Error Error: No item 18 in vector of length 18]'.

Fix find-position

---

resources/js/worker.js
src/main/frontend/git.cljs
src/main/frontend/handler/repo.cljs

The current implementation assumes Git's working tree and staging area are exactly the same, however, due to some mysterious concurrency bug, a file might be modified but unstaged, leaving the user in a state where neither pulling nor pushing is possible.
This PR will `git add` all unstaged files before committing and pushing.
- It might fix https://github.com/logseq/logseq/issues/919 and https://github.com/logseq/logseq/issues/958.
-  It should fix https://github.com/logseq/logseq/issues/773.
- Related to https://github.com/logseq/logseq/issues/848.
- Depends on https://github.com/logseq/logseq-backend/pull/16.

fix: git add unstaged files before committing

---

src/main/frontend/components/block.cljs

If query in :default-queries journals from config.edn returns empty result it doesn't hidden.

Fix empty queries in journal

---

src/main/frontend/components/commit.cljs
src/main/frontend/components/repo.cljs
src/main/frontend/fs.cljs
src/main/frontend/git.cljs
src/main/frontend/handler/page.cljs
src/main/frontend/handler/repo.cljs

For unknown reason, the entire repo directory might be missing in some rare cases. If it does happen, we should notify users of the error, and prevent them from further editing as the content will be lost due to sync failure.
This PR
- Makes some operations defensive.
- Always show error notification when manual push/pull fails.

Make sure the code raises error in case repo dir is missing

---

src/main/frontend/fs.cljs

This bug was introduced in https://github.com/logseq/logseq/pull/1018 which makes it unable to delete files from file system.

fix: Stat.isFile is not available

---

src/main/frontend/components/block.cljs

Fixes https://github.com/logseq/logseq/issues/871.

fix: handle empty block embed

---

src/main/frontend/handler/repo.cljs

When switching from a GitHub repo to a local repo, Logseq will try to push the local one and then print the "Cannot find repo dir" error. Also the GitHub repo will be mistakenly marked as with Git push error so the sync dot will turn red.
（这是昨天 @dale502 报的 bug）

fix: do not push local repo when switching repos

---

README.md

Richard Stallman, author of AGPLv3, said:
> I wrote to him:
>   > The word open-source is sometimes associated with the ideals of free
>   > software. So, I'll write "freedom-respecting and open-source" or "(aka open
>   > source)" or "(sometimes known as "open-source", a false flag movement by
>   > Microsoft)."
> 
> Those are subtly misleading.  How about this?
> 
>   freedom-respecting (and open source too)
Let's emphasize the control, customizability, reliability, etc. the user has by rewording the README this way.

Emphasize the user's freedom and their control in README

---

deps.edn
package.json
yarn.lock

My develop env:
- OS: macOS Big Sur version 11.1
- JDK: openjdk version 1.8.0_275
- Node.js: v15.4.0
Currently, run command `yarn watch` throws many error messages like follows:
```
[:failed-to-compare "^16.8.1" "16.13.1" #error {
:cause "Cannot invoke \"Object.getClass()\" because \"target\" is null"
:via
[{:type java.lang.NullPointerException
:message "Cannot invoke \"Object.getClass()\" because \"target\" is null"
:at [clojure.lang.Reflector invokeInstanceMethod "Reflector.java" 97]}]
:trace
[[clojure.lang.Reflector invokeInstanceMethod "Reflector.java" 97]
[shadow.cljs.devtools.server.npm_deps$make_engine invokeStatic "npm_deps.clj" 39]
[shadow.cljs.devtools.server.npm_deps$make_engine invoke "npm_deps.clj" 32]
[shadow.cljs.devtools.server.npm_deps$fn__17468$fn__17469 invoke …
```

feat: upgrade some dependencies

---

externs.js
src/main/frontend/utils.js

Add externs for external JS libs to prevent name been munged when building with release.
**Problem**
The issue happens when calling module `utils.js` from cljs :
```
(utils/openDirectory #js {:recursive true} (fn [] ))
```
But this is a external JS library,  which has been optimized by Google closure compiler in release mode into something like follows:
Which cause weird issue mentioned in c611a7a8e1d70fbc9f7aa969edfb89ed8758884f

fix: add externs for external JS libs to prevent name been munged

---

src/main/frontend/db/model.cljs

Related to https://github.com/logseq/logseq/issues/1096.
The issue had been resolved in https://github.com/logseq/logseq/pull/928 but the changes are lost.

fix: allow no blank line after front matter

---

src/main/frontend/config.cljs

Now sure what's the right way to properly specify domains, but hopefully the comment will at least help people who can't figure out why logseq is making queries to `asset.logseq.com` by searching in code.

add comment with "asset.logseq.com" so it's easier to find where it's hardcoded

---

src/main/frontend/date.cljs

fixing #1182 when /Current Time shows midnight as 24:xx instead of 00:xx

Fixing /Current Time showing midnight as 24:xx

---

src/electron/electron/handler.cljs
src/main/frontend/handler/editor.cljs

fix: miss update properties when marker change

Fix miss update properties when marker change

---

resources/css/common.css

Opacity and color variables were removed from the `a` tags in the last css tweaks, this fix is to put them back on.
It will also fix the background color for the new wide search field.

Fix missing css global variables 

---

src/main/frontend/commands.cljs
src/main/frontend/components/block.cljs

Adds `/vimeo` & `{{vimeo }}`
[Regex](https://regex101.com/r/6jOSWk/1) should match:
```
https://vimeo.com/48510638
https://player.vimeo.com/video/48510638
vimeo.com/48510638
player.vimeo.com/video/48510638
48510638
```
I didn't see a good existing place to add tests, happy to do that with some guidance.

feat: add vimeo video embed block command

---

src/electron/electron/core.cljs
src/electron/electron/utils.cljs

Currently on linux, the app does not have title bar, thus on desktop env, I cannot move the boderless window...
After the fix, it'll look like below on my linux env:

fix: linux title bar not showing

---

src/main/frontend/db/model.cljs
src/main/frontend/format/mldoc.cljs
src/main/frontend/handler/page.cljs

A directive like '#+TITLE: foobar' probably is not the first ast item.
see also https://github.com/logseq/logseq/issues/694

fix: find all directives in ast

---

src/main/frontend/handler/export.cljs

journal page's `:page/name` is not equal to `:page/original-name` , so should take care of it

fix(export): also take :page/original-name into exporting markdown

---

deps.edn

cherry-picked one commit from upstream to deprecate qualified lib warning
everything else is same

use logseq fork of datascript

---

package.json
src/electron/electron/core.cljs
yarn.lock

The application opens with the default width and height every time, resulting in an adjustment every time it is reopened. So this PR uses [electron-window-state](https://github.com/mawie81/electron-window-state) to remember the last window state.

feat: add electron-window-state to remember the window state

---

src/main/frontend/components/block.css

The resize handler of the images was always at the right-bottom of the image block because by default the block level item will take 100% width of the parent container.
After changing the resize block to `display: inline-flex`, the default width will be the contained item size and the little resize handle will be in the right-bottom corner of the image, instead of the whole block. Also, this change makes it possible to have images placed inline, e.g., having two horizontal images in the same row; place image in the texts.

fix: .resize should be inline-flex

---

src/main/frontend/components/block.cljs

similar to previewing PDF files, this PR will use `<video>` to inlining videos into the editor.

feat: support previewing videos in desktop mode

---

src/main/frontend/components/header.cljs
src/main/frontend/components/header.css
src/main/frontend/components/repo.cljs
src/main/frontend/components/sidebar.cljs

fix: truncate repo name in small screen and show repo switch header

---

.github/workflows/build.yml

Otherwise it might cause weird build errors
Sadly, it seems that there is still a version mismatch between `build` and `build-desktop-release` for example....
YAML :vomiting_face:  https://github.community/t/reusing-sharing-inheriting-steps-between-jobs-declarations/16851/23
But hopefully it's a start...

CI: add check for Docker image consistency

---

src/main/frontend/components/block.css

I found an issue when trying to click (or shift+click) a bullet in an embedded block, that the editing mode will be turned on, instead of navigating to that block (or shown in the right panel).
After some investigation, I believe this is because the `link` check failed [in this line of code](https://github.com/logseq/logseq/blob/83eb8278aa908b550e3aa0aead3e969a05c0b2b9/src/main/frontend/components/block.cljs#L1359).
The `event.target` is the bullet span instead of the anchor when the event we used is `mouseown`. But if I change the event to `mouseclick`, the target is what we want (anchor).  
I am not sure why yet, but the current workaround is to give `pointer-events: none` to the `.bullet-container` inside of an anchor.
The bug screenshot:

fix an issue when clicking bullets in embedded block/page

---

src/main/frontend/components/block.cljs
src/main/frontend/components/block.css

fix: block ref should be able to wrap

---

src/main/frontend/components/right_sidebar.cljs
src/main/frontend/components/sidebar.css

.resizer element is inside of a scrolling container so when the right sidebar scroll up, the resizer will also scroll up. As a result, the user may not be able to change the right bar size.
This fix will make sure the resizer is outside of the scrolling container.

fix: resizer should not scroll with the container

---

src/main/frontend/components/block.css

After git bisects, I found the issue is introduced since https://github.com/logseq/logseq/pull/1634.
However, these changes still seem not that quite relevant to this issue.
I spend some time deep-diving into the issue. It looks like the resize handle will disappear when one of the parent containers overflows with scrollbars and the resize container is `position: relative`.
I think this might be a Chrome bug because this is not reproducible on Firefox. See:
https://codepen.io/pengx17/pen/zYNbmJv?editors=1100
Since this is very fragile that the user can easily apply some custom styles to some of the elements in custom.css, I guess the ultimate solution is to render resize handles with real DOM elements, instead of depending on the Browser to render it.

fix: add back missing resize icon in Chrome

---

src/main/frontend/util.cljc

Looks like `re-pos` is defined in the cljs context, thus its caller `add-or-update-marker` should be also defined in cljs context.

fix: fix compiler error

---

src/main/frontend/handler/editor.cljs
src/main/frontend/modules/shortcut/binding.cljc
src/main/frontend/modules/shortcut/core.cljs
src/main/frontend/modules/shortcut/handler.cljs
src/main/frontend/util.cljc

- clear block content
- word move/kill
- line kill
- move cursor start/end

feat: more bash-like basic in block editing shortcuts

---

src/main/frontend/handler/repo.cljs

Regressed by 45533ce77b3488d107d82a7bfc12b105a4a83135, that is why Canary build's decryption wasn't working.

Fix missing argument for input-secret dialog

---

src/main/frontend/handler/editor.cljs

1. move the cursor to the new block when press "Enter" at the
beginning of the parent block
2. new block should be a child when press "Enter" not at the beginning
of the parent block

enhance(editor): insert blocks

---

deps.edn
src/main/frontend/config.cljs
src/main/frontend/dicts.cljs
src/main/frontend/handler/repo.cljs
templates/config.edn
templates/contents.md
templates/contents.org
templates/dummy-notes-en.md
templates/tutorial-en.md

shadow-cljs has this nice inline function for us to extract static resource as part of the compilation
https://clojureverse.org/t/using-none-code-resources-in-cljs-builds/3745
this PR extract large chunk of md file and config.edn to templates for eazy editing, modifying those esacped string in cljs is pain!

feat: extract template files

---

src/main/frontend/components/block.cljs
src/main/frontend/components/page.cljs
src/main/frontend/components/reference.cljs
src/main/frontend/db.cljs
src/main/frontend/db/model.cljs
src/main/frontend/db/query_react.cljs
src/main/frontend/db/react.cljs
src/main/frontend/db_schema.cljs
src/main/frontend/handler/editor.cljs
src/main/frontend/handler/page.cljs
src/test/frontend/db/model_test.cljs

1.  can't edit and enter new blocks in the references 
2. references and source blocks are not synced
3. the existing queries are verbose, it doesn't utilize datascript's recursive queries very well (although we might move to a performant way in the future)
4. to render the blocks tree, no matter it's a page or refs, a query is triggered when encountering a parent block, this not only hurts the performance but also makes the code ugly.
1. make queries simpler and easy to use
2. simplify the rendering code
1. aliases 
2. block-refs data attributes
1. Should we remove blocks->vec-tree? Recursive queries already provide the tree structures, we can also use datascript's raw index API to make it faster. see https://github.com/tonsky/datascript/issues/130#issuecomment-169520434

Refactor queries && fix issues related to references

---

src/main/frontend/format/block.cljs
src/main/frontend/handler/editor.cljs
src/main/frontend/handler/extract.cljs
src/main/frontend/modules/outliner/core.cljs

<del>Prerequisites: current editing block's content is empty(sometimes just want to paste the raw text into the block, e.g copy some codes into a code block) <del>
1. transform md/org text into blocks
2. split normal paragraphs by double newline

Transform text into blocks when pasting text from external

---

libs/src/LSPlugin.d.ts

`this` for `registerSlashCommand` and `registerBlockContextMenu` is useless for the users, and they will also cause TS errors like the following, so I suggest removing them, which should be safe

fix: registerSlashCommand/registerBlockContextMenu do not need to expose this

---

src/electron/electron/core.cljs
src/main/frontend/components/sidebar.cljs
src/main/frontend/components/sidebar.css

When a note reaches the point where a scrollbar is needed the entire application shifts to the left slightly to accommodate the width of the scrollbar.
This uses the `overflow-y: overlay`  css property which was recently [readded to Chrome](https://chromium-review.googlesource.com/c/chromium/src/+/2739606), though it doesn't have compatibility with other browsers and is simply left with `overflow-y: auto` elsewhere.
In the future browsers will implement [scrollbar-gutter](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter) which should be a globally available method of fixing this problem but that is still likely quite far away.
I've attached a before/after video of this patch:
https://user-images.githubusercontent.com/454563/119415702-fbcc5f00-bca6-11eb-92cf-cbf7c0a64266.mp …

improve: Stop scrollbar from causing app content shift

---

src/main/frontend/handler/route.cljs
src/main/frontend/state.cljs
src/main/frontend/util.cljc

Fixes #1614 and adds the following feature,
- If a previously visited page is visited again, it will resume from the last known scroll position.

Remember scroll positions of visited pages

---

deps.edn
src/main/frontend/extensions/calc.cljc
src/main/grammar/calc.bnf
src/test/frontend/extensions/calc_test.cljc

The calculator for [Numi](https://numi.app/) and [Soulver](https://www.acqualia.com/soulver/) are very useful for day to day tasks but not worth having in a separate apps. It’d be possible to add a block type that implements a limited subset of Numi and make it very convenient to use inside Logseq. This feature is being discussed [here](https://discuss.logseq.com/t/calculator-mode-like-numi-or-soulver/1059)
This PR adds a calculator parser and evaluator. You can see the min calculator language in the tests.
On a follow up PR, I will wire this evaluator to code blocks of type `calc`

feat: add calc parsing and evaluation

---

src/main/frontend/handler/editor.cljs

fix: incorrect asset path when create new page that local file not existed

---

libs/src/LSPlugin.d.ts

If given a page id, the `logseq.App.getBlock` API will return PageEntity instead of a normal block.
This fix will let the user to explicitly set the returned block mode
- `logseq.App.getBlock` => `Promise<BlockEntity | PageEntity | null>`
- `logseq.App.getBlock<true>` `Promise<PageEntity | null>`
- `logseq.App.getBlock<false>` `Promise<BlockEntity | null>`

fix: add PageEntity type

---

libs/src/LSPlugin.d.ts
src/main/logseq/api.cljs

My use case is that when querying a page from a block entity, I only have "db/id" but no page name or page uuid.

feat: allow get page by db id

---

src/main/frontend/components/theme.cljs
src/main/logseq/api.cljs

it seems in the DB theme mode for "light" theme is "white", but the LSP developers may always expect `getAppConfigs` or `onThemeModeChanged` returns `light`, which returns `white` for the moment.
The change in this PR is not clean - later there should be an utility adapter function to be used for similar purposes, or maybe change the db theme mode value from "white" to "light."

feat: adapt correct light theme mode for plugins

---

src/main/frontend/handler/editor.cljs
src/main/frontend/util/property.cljs

```
(paste-block-tree-after-target 1762 false [
{
:content "this is a block",
:props {"collapsed" "true" "another-key" "value"},
:children [
{ :content "this is child block" }
]
},
{
:content "this is sibling block"
}
] :markdown)
```

Feat: paste blocks at target

---

src/main/frontend/components/page.cljs
src/main/frontend/components/repo.cljs
src/main/frontend/handler.cljs
src/main/frontend/handler/editor.cljs
src/main/frontend/handler/page.cljs
src/main/frontend/modules/shortcut/core.cljs
src/main/frontend/modules/shortcut/data_helper.cljs
src/main/frontend/state.cljs
src/main/frontend/util.cljc
src/main/frontend/util/cursor.cljs

- refactor and improve shortcut installation
- shortcuts shall reinstall itself correctly
1. when user click the refresh button, force re-install
2. when user switch repo, it will pick up the correct shortcut from the repo config
3. when user create new repo, refresh to default shortcut
- fix two places where enter key shall working when prompted (rename page, delete page)

enhance: shortcut installation improve

---

src/main/frontend/handler/editor.cljs
src/main/frontend/modules/shortcut/config.cljs

Per #701 it would be nice to be able to strike through text with a key binding.
I've added the function for strikethrough (matching how highlight was done), as well as a tentative binding.
Since users can rebind now, hopefully this can be added in, even if you may wish to set a different default binding. :)

feat: add :editor/strike-through binding (fixes #701)

---

src/main/frontend/components/block.cljs
src/main/frontend/components/block.css

Make "IN-PROGRESS" "WAIT" "WAITING" markers have consistent looking to switch markers.
See:

fix: add styles for task-status

---

src/main/frontend/handler/editor.cljs
src/main/frontend/util/cursor.cljs

enhance: select formatted text after changing its formatting for toggle support
fix: place cursor between (pattern)(pattern) pair when selection is empty
---
Hopefully this is in line with behavior you'd like to support!
This PR makes the formatting shortcuts behave more like most editors:
- selection is preserved after applying formatting changes
- if nothing is selected, the next characters that you type after pressing a formatting shortcut are formatted (cursor position)
- if the current text is already formatted, the formatting is toggled off rather than double-wrapping in formatting
You can see the changes applied in this commit in the following GIF:

feat: toggle formatting of selected area instead of double-wrapping

---

README.md

added "cd logseq" line after git clone line, before running yarn

tiny missing step in instructions for compiling

---

src/main/frontend/extensions/calc.cljc
src/main/frontend/extensions/code.cljs
src/main/frontend/extensions/code.css

Adds a UI for the calc interpreter introduced in https://github.com/logseq/logseq/pull/2052
The user must be in `calc` mode to get those results.
* Add documentation to show what is possible in the calculator

feat: add ui for calculator mode in editor

---

src/main/frontend/extensions/calc.cljc
src/main/grammar/calc.bnf
src/test/frontend/extensions/calc_test.cljc

Adds scientific numbers and variables with underscores to calc mode so that the following is possible:
```
foo_bar = 1.45e3
foo_bar / 3.0e-1
```

feat: add scientific numbers and variables with underscores

---

resources/css/common.css
src/main/frontend/components/block.cljs
src/main/frontend/components/block.css
src/main/frontend/components/sidebar.css

There are some issues related to images and code blocks when their width is too big to fit, even their width is 100%, but since they are placed into flex containers we also need to use max-width to trap them to get overflow horizontal scrolling.

fix: some overflow issues

---

src/main/frontend/handler/editor.cljs

When you are moving a block up or down with the keyboard shortcut `ctrl+shift+down`, it is easy for the block to move out of the viewport where you can't see it anymore. This change scrolls the viewport to follow the block as you move it.

fix: scroll to follow the moving block

---

src/main/frontend/handler/editor.cljs
src/main/frontend/modules/shortcut/config.cljs

A shortcut to collapse all top level blocks. It helps in getting
a quick summary of document, especially when there are too many headlines.
This relates to a [feature request to collapse blocks by default](https://discuss.logseq.com/t/outlines-collapsed-by-default/300).
Next steps could be
- toggle it
- recursively collapse children (with toggle?)

Add collapse all key binding

---

resources/css/common.css
src/main/frontend/components/header.cljs
src/main/frontend/components/header.css
src/main/frontend/components/page.cljs
src/main/frontend/components/page.css
src/main/frontend/components/repo.cljs
src/main/frontend/components/right_sidebar.cljs
src/main/frontend/components/search.css
src/main/frontend/state.cljs
src/main/frontend/ui.cljs

1. Makes it so that clicking out of a modal closes it, just as if you clicked the `x` in the top right corner of if you'd hit the `esc` key
2. Fixes a tiny typo ("scollable" → "scrollable")
3. Increases contrast on the icons. Previously, they were very hard to see.
**Before:** ![image](https://user-images.githubusercontent.com/6979755/122305825-728aff80-ced5-11eb-812b-538744d80640.png)
**After:** ![image](https://user-images.githubusercontent.com/6979755/122307580-9c91f100-ced8-11eb-85eb-3ccbcb4b700d.png)
If it makes more sense to just put this in my `custom.css` that's fine too, but since it's an accessibility issue I figured it might be useful to others too.
We may want to boost the contrast even more—the change I made still technically doesn't conform to the [Web Content Accessibility …

Tweak modal + fix typos + boost contrast on icons

---

src/main/frontend/components/block.cljs

Should show the `original-name` of the page when possible.

fix: page title in page-cp should use original-name

---

src/main/frontend/commands.cljs
src/main/frontend/extensions/code.cljs

Adds a /calc command that goes directly into the CodeMirror editor, rather than the raw content editor with the `` ```code `` fence.
The following screen capture shows (1) selecting the /calc slash command with the mouse and then (2) selecting it with the arrow + enter keys.
https://user-images.githubusercontent.com/6979755/122676683-13670c80-d1ad-11eb-89fb-9f87f2aea480.mp4

feat: Add /calc slash command

---

src/electron/electron/core.cljs
src/main/frontend/publishing/html.cljs

Right now `custom.css` content is directly appended to `style.css`. There is an issue with it:
if the user provides an `@import` rule in `custom.css`, this rule will take no effect at all, since `@import` rule should be the first rule than any all other css rules, see https://developer.mozilla.org/en-US/docs/Web/CSS/@import
Alternatively, we could parse the concatenated style content and reorder the rules - which is clearly harder than the current solution in this PR.

fix: output custom.css instead of append to style.css

---

src/main/frontend/components/block.cljs

One potential fix for #2220 
We have two scenarios to handle
1. either the file link is a ml-doc file and we show a page reference, or 
2. it is a file with unknown ext and the system should handle it.
The bug was that we were handling both Complex type with file protocol and File
type the same way. In case of File type it would add extra `file://` and causing
unexpected behavior.
Since we handle search beforehand, the fix can be to simple remove `file:`
prefix, to keep the behavior consistent with markdown syntax

Fix - opening non ml-doc file links in org syntax

---

src/main/frontend/components/page.cljs

When renaming a page often you just want to adjust the existing title. Therefore, default the input field with the current page title.

feat: Use current title as default when renaming page

---

src/main/frontend/components/settings.cljs
src/main/frontend/ui.cljs

When react-tippy is given a theme, the tippy content will get a `${themename}-theme` class. 
There are some issues about it:
- the theme value will not change when user changes theme with `t t`
- some weird ui styling issues
Also, logseq's theme and react-tippy's theme have different meanings and we are not importing react-tippy's theme file, which is another reason why we do not need to pass it down.
---
I also noticed that there is an unused `@tippyjs/react` dep, which is similar to `react-tippy` but is provided by `tippyjs` officially. Is there any plan to migrate to this one in the future?

fix: do not pass theme to react-tippy

---

src/main/frontend/extensions/calc.cljc
src/test/frontend/extensions/calc_test.cljc

Fix for https://github.com/logseq/logseq/issues/2245
Excuse the poor diff! I renamed `eval` to `eval*` (no change) and I added a new `eval` that recognizes parse errors and catches variable not found exceptions. It should be safe to call `eval` and always get a value, `nil`, or an error, but no exceptions thrown.
Consider a better UI than `?` to show errors to users.

fix: don't show calc parse errors to the UI

---

src/main/frontend/handler/editor.cljs
src/main/frontend/modules/shortcut/config.cljs
src/main/frontend/util/thingatpt.cljs

feat: replace block-reference with its content

---

src/main/frontend/format/block.cljs
src/main/frontend/handler/editor.cljs
src/main/frontend/handler/external.cljs

fix for https://github.com/logseq/logseq/issues/2224

fix: entity not found err when import opml with non-existed block-ref-id

---

src/main/frontend/components/block.cljs

block ref is often very short and its meaning depends on its page context or breadcrumbs. Having breadcrumbs in the block ref preview will make it more useful.

feat: show block breadcrumbs in preview

---

src/main/frontend/components/block.cljs
src/main/frontend/handler/editor/lifecycle.cljs

markdown:
- `![label](url)`
- pdf preview (desktop app)
- image inline display
- `[label](url)` only display as clickable label
org:
- `[[url][label]]{:show true}`
- pdf preview (desktop app)
- image inline display
- `[[url][label]]{:show false}` just display as clickable label
- `[[url][label]]`   
- keep same behaviors as before: inline images if its suffix included in #{:gif :svg :jpeg :ico :png :jpg :bmp}

fix: link syntax behavior

---

src/main/frontend/handler/editor.cljs
src/main/frontend/modules/shortcut/config.cljs

Normal paste (mod+v) will split paragraphs into multi blocks.
And `paste-text-in-one-block-at-point` (mod+shift+v) just paste text in clipboard into one block at point

feat: add paste-text-in-one-block-at-point (mod+shift+v)

---

src/main/grammar/calc.bnf
src/test/frontend/extensions/calc_test.cljc

Makes the calc parser more careful not to match `*` or other symbols.
Fixes https://github.com/logseq/logseq/issues/2234

fix: stricter parsing for variables

---

src/main/frontend/extensions/code.cljs

When you click on a Codemirror, the state isn't updated with the right block being edited. When you type `*`, the `autopair` function inserts the double `*` in the block returned by `(state/get-edit-input)`, which is the last block that was selected before clicking in the Codemirror editor.
This PR sets the Codemirror editor's block as the block being edited.
Fixes https://github.com/logseq/logseq/issues/2278
Please review closely given that I am not entirely familiar with the state model of the app and this may have other repercussions that I am not aware of.

fix: set the codemirror block as the edited block when it is clicked

---

src/main/frontend/components/block.cljs
src/main/frontend/components/diff.cljs
src/main/frontend/components/hierarchy.cljs
src/main/frontend/components/page.cljs
src/main/frontend/db.cljs
src/main/frontend/db/model.cljs
src/main/frontend/db_schema.cljs
src/main/frontend/format/block.cljs
src/main/frontend/handler/external.cljs
src/main/frontend/handler/page.cljs
src/main/frontend/util.cljc

If there're there three pages:
1. a
2. a/b
3. a/b/c
Rename page `a` to `d` will cause:
1. page `a` -> page `d`
2. page `a/b` -> page `d/b`
3. page `a/b/c` -> page `d/b/c`
4. corresponding files rename
The renaming part as below is using files instead of pages, which will be changed by another PR.
https://github.com/logseq/logseq/pull/2283/files#diff-ffded5a00bdaff768972d58b680c9c85a2912243029bd6323e064da6c474d964R272

feat: rename a page will rename corresponding namespace pages and files

---

src/main/frontend/components/block.cljs
src/main/frontend/components/block.css
src/main/frontend/ui.cljs

I personally wanted to make the block control visible at all times, even though the current behavior is for it to be hidden in doc-mode until you hover over a block.
This PR changes the code so that this behavior is controlled via CSS selectors rather than removing the content entirely so that people like me can have the behavior I want without imposing it on everyone else.
---
This PR also refactors a few small bits of code I stumbled upon to make it a little more readable, nothing major.

Make block control available via CSS selectors so it can be customized

---

src/electron/electron/core.cljs
src/main/frontend/components/header.cljs
src/main/frontend/components/header.css
src/main/frontend/components/svg.cljs
src/main/frontend/state.cljs

This PR is similar to #2335 with some minor differences:
1. it uses `titleBarStyle` which only works on Mac
2. the traffic lights are still there
3. some UI polish
cc @devonzuegel

feat: frameless desktop app on Mac

---

src/main/frontend/handler/editor.cljs

Changes the behavior of #2187 to fix #2275
It now only scrolls when the block is moving out of the viewport but there is no scrolling in most cases.

fix: use better option for scrolling into moving blocks

---

src/main/frontend/components/block.cljs

There is an issue that makes embed block/page UX not ideal: the user will easily get into the host block editing mode when interacting with the embedded block/page.
This pr fixes this issue by
- the embed container will swallow the bubbling `mousedown` event
- the user still can edit the host block when the user double clicks the embed element, unless he is already in editing mode
This pr also fixes an issue that the user cannot fold a block in an embedded context.

feat: enhance embed block/page ux

---

src/main/frontend/components/block.cljs
src/main/frontend/components/block.css
src/main/frontend/components/journal.cljs
src/main/frontend/components/page.cljs
src/main/frontend/components/page.css
src/main/frontend/components/right_sidebar.cljs
src/main/frontend/page.cljs
src/main/frontend/ui.cljs

This PR enhanced a UX that when the user mouse hovering a `page-ref` or `block-ref` with `shift-key` pressed, which changes the cursor to `e-resize`, which looks like a right arrow.
The solution is:
- attach keydown/keyup events for each keystroke, keep track all active keystrokes and write them to `body[data-active-keystroke]`
- add a css selector over `[data-active-keystroke*="Shift" i]` and change corresponding element's cursors

feat(cursor): allow cursor change to another style based on context

---

src/main/frontend/components/block.cljs
src/main/frontend/components/editor.cljs
src/main/frontend/components/editor.css
src/main/frontend/components/page.cljs
src/main/frontend/db/model.cljs
src/main/frontend/ui.cljs

Inspired by Innos Note, this PR enables page previewing within block auto-complete of page-search.
Some details:
- The preview will be debounced for 1s on open and active selected item's name
- Will be closed immediately without debouncing
- Will change the active selected item on mouseenter

feat: page autocomplete preview

---

src/main/frontend/components/search.cljs
src/main/frontend/handler/ui.cljs
src/main/frontend/modules/shortcut/config.cljs

Per request from [discord server](https://discord.com/channels/725182569297215569/725182570131751005/860797035888115732):
> Is it somehow possible to hit shift+enter to open a page on the sidebar while in the search box? (instead of having to shift left click on it)
Should fix https://github.com/logseq/logseq/issues/2271

feat(shortcut): add shift+enter to open auto complete item

---

src/main/frontend/components/onboarding.cljs

I could not open the given links in the sidebar of the app. With the added hash routes it works again.

fix: FAQ and Changelog urls.

---

src/main/frontend/commands.cljs

Affected apis:
- `registerBlockContextMenu: (tag: string, action: BlockCommandCallback) => boolean`

fix(plugin): editor hook payload

---

src/main/frontend/handler/export.cljs

add ttl for get-embed-and-refs-blocks-pages,  related to https://github.com/logseq/logseq/issues/2464

fix: get-embed-and-refs-blocks-pages slow

---

src/main/frontend/extensions/calc.cljc

Fix for https://github.com/logseq/logseq/issues/2454

fix(calc): don't show errors for empty lines

---

src/main/frontend/handler/editor.cljs

remove '\r'  when comparing pasted-text and copied-text

fix: copy&paste err on win

---

src/main/frontend/db_schema.cljs
src/main/frontend/handler/page.cljs

reproduce steps:
1. create page "page1", and add "alias: page2"
2. click [[page2]] will redirect to [[page1]], which is good
3. goto [[page2]], input some text
4. click [[page2]] will goto [[page2]], good
5. delete page "page2"
6. click [[page2]] will goto an empty [[page2]], BAD, it should goto [[page1]]

fix: delete alias page cause wrong alias relations

---

src/main/frontend/config.cljs
src/main/frontend/util/property.cljs
templates/config.edn

Hide properties specified in `config.edn`
Reference:
- https://discuss.logseq.com/t/control-which-block-properties-are-hidden-in-view-mode/884

feat: hide specific block properties

---

src/main/frontend/components/export.cljs
src/main/frontend/util.cljc
src/main/frontend/utils.js

when “Copy as” Html，set 'text/html' option on copied text.
|Copy as HTML| Google Doc |
|---|---|
| ![image](https://user-images.githubusercontent.com/5608710/128472520-a62e6315-c497-4a65-b314-d16eea025b30.png) |![image](https://user-images.githubusercontent.com/5608710/128472743-6c175b33-a014-4073-bcf9-831f57736b1c.png)|

feat: set text/html when copy html text

---

src/main/frontend/components/block.cljs
src/main/frontend/util/property.cljs

So that if a row only contains hr, the bullet is also hidden

feat: also honor hr when check if block content is empty

---

src/main/frontend/components/block.cljs
src/main/frontend/extensions/pdf/assets.cljs

`![sample.pdf](http://www.africau.edu/images/default/sample.pdf)` will open Logseq pdf annotation as file.

enhance: support web pdf link

---

src/main/frontend/handler/editor.cljs

Timestamp log started with "`*`" in org-mode got rendered as a
first-level headline. This patch fixes it.

fix: incorrect timestamp log in org-mode

---

src/main/frontend/format/block.cljs

a user reported issue on discord:
sample page with the first block:
```
type:: feature
head:: [[redacted]] 
communication_poc:: [[test]]
```
sample query doesn't work in 0.3.3:
```
{{query (and (property communication_poc [[test]]) (or (property type feature) (property type internal_feature)))}}
```
found out that page property value for collection was treated as list, not sure which commit introduced this regression.
`:head '("redacted"), :communication_poc '("test")`
this caused the `(contains? ?v "test")` cause always return false.
Added a safeguard to always convert coll v to set would fix the issue. Maybe a little hacky..

fix: some contains query doesn't work

---

src/main/frontend/extensions/zotero/extractor.cljs

This patch fixes the attachment links in orgmode. Currently, logseq
creates markdown-only attachment links even in orgmode.

fix(zotero): attachment links in orgmode

---

src/main/frontend/ui.css

Prevents settings window from jumping up and down when switching between submenus. 
Note there is still slight horizontal jumping once a scrollbar appears. This has been left unchanged.

enhance: keep settings window from jumping

---

src/main/frontend/handler/editor.cljs
src/main/frontend/util/property.cljs

As the gif shows, logseq always add extra empty lines in orgmode. These two patches offer a solution to fix this. There might be some edge cases that the patches do not cover, but they work pretty well in most conditions as I tested. Please give them a review. Thanks.

fix(org): remove extra lines

---

src/main/frontend/extensions/pdf/assets.cljs

This issue maybe cause the illusion of highlights data loss!

fix(pdf): incorrect joined full url path of pdf asset

---

src/main/frontend/commands.cljs

this whitespace doesn't seem to be markdown compliant. Some editors won't syntax highlight correctly (e.g. Markor)

enhance: remove extra whitespace in src-block-command for better compatibility with other markdown editors

---

src/main/frontend/components/command_palette.cljs
src/main/frontend/components/command_palette.css
src/main/frontend/components/sidebar.cljs
src/main/frontend/handler.cljs
src/main/frontend/handler/command_palette.cljs
src/main/frontend/modules/shortcut/config.cljs
src/main/frontend/modules/shortcut/data_helper.cljs
src/main/frontend/state.cljs
src/main/frontend/ui.cljs

`cmd+shift+p` to toggle.
Currently, all commands are taken from global scope shortcuts.
A command looks like:
{:id uniqte namespaced id
:desc description
:action (fn [] do...)
:shortcut optional shortcut description}
Users can register custom commands by providing the above map.
Basic functionality is there. The UI may need a little tweak help from charlie. Eg, I'm not sure how to make the outside modal to a fixed width and height?

feat: command palette

---

src/main/frontend/commands.cljs

This pull request is for fixing the typo error in the tool-tip for the 'Block reference' option. A screenshot of the issue is added below.
I have raised bug #2774  on this issue previously. Today, I got an opportunity to fix it. 
As this is a small fix. It would be great if this can be reviewed quickly so that this issue is resolved and deployed.

Fixing typo  for the tooltip 'Block reference'

---

src/main/frontend/handler/editor.cljs
src/main/frontend/handler/repeated.cljs
src/main/frontend/text.cljs

When using `date-picker` to update the SCHEDULED/DEADLINE timestamp by clicking the existing one, logseq will add a new timestamp. This patch tries to remove the old timestamp before adding it.

fix(timestamp): remove old SCHEDULED/DEADLINE timestamp

---

src/main/frontend/ui.cljs

Even if the switch/toggle was on, the `aria-checked` property stays "false". This PR fix this behavior.

Set aria-checked to "true" if toggle is on

---

src/main/frontend/components/editor.cljs

The enter animation was delayed by 100ms (it was a bit annoying), while the exit timeout was
100ms: the css transition is 150ms and the exit timeout should be the
same.

Fix animated modals timing

---

src/main/frontend/modules/shortcut/config.cljs

This is not documented in the default key descriptions:
When in edit mode but no text selected, copy current block ref (/src/main/frontend/handler/editor.cljs)

Document mod-c/copy current block ref

---

src/main/frontend/commands.cljs
src/main/frontend/handler/editor.cljs

Hello!
Currently the "Image link" slash command emits a markdown HTML link rather than embedding an image.
This patch changes the Image link command emitting a markdown link for an embedded image rather than a link to an image.

Emit image links as image embeds rather than as html links

---

src/main/frontend/handler/dnd.cljs

fix `Cannot read property 'altKey' of null`

fix: plugin api moveBlock not working

---

resources/css/common.css
src/main/frontend/components/header.cljs
src/main/frontend/components/onboarding.cljs
src/main/frontend/components/shortcut.cljs
src/main/frontend/dicts.cljs
src/main/frontend/modules/shortcut/config.cljs
src/main/frontend/modules/shortcut/data_helper.cljs
src/main/frontend/ui.cljs

This PR polishes the user experience of viewing and customizing keyboard shortcuts. In particular, the documentation for keyboard shortcuts and Markdown/Org Mode was duplicated across the sidebar and the Keyboard Shortcuts page, which was a confusing user experience. This PR...:
- consolidates that documentation into the Keyboard Shortcuts page and removes them from the sidebar. (It is reachable from the sidebar from the Keyboard Shortcuts link.)
- organizes the Help links into categories, to make them easier to find.
- adds the new hotkey <kbd>g</kbd><kbd>s</kbd> to go to keyboard shortcuts, which is also available from the command palette.
- adds a small button to the header to go to the keyboard shortcuts page. (This may not be important to warrant usage of that prime real estate; very …

Consolidate shortcut docs

---

src/main/frontend/extensions/code.css

Simple fix on wide mode toggle for code block. `max-width` should be controlled by its root content.  
Before:
After:

Fix code block wide mode toggle

---

src/main/frontend/commands.cljs
src/main/frontend/util/marker.cljs

Fixes #3036 
-  minimum value of `pos-delta` is now 0
-  rm leading `^` in marker-pattern
- Is it better to use `#*\s*[TODO|...]\s*`?
- remove additional space in `replace-marker`, when cycling to nil marker in header line

fix: pos and space when cycling marker in header

---

src/main/frontend/components/page_menu.cljs
src/main/frontend/handler/page.cljs
src/main/frontend/modules/shortcut/config.cljs

This PR adds the following hotkeys:
- <kbd>o</kbd><kbd>f</kbd> to open current file with the default app
- <kbd>o</kbd><kbd>d</kbd> to open file the parent directory
~It also removes these same commands from the dropdown at the top. These commands aren't super commonly used, so I think it's best to declutter that dropdown. However I'm happy to remove this change if the maintainers disagree!~

enhance: add hotkeys for open file in directory / default app

---

src/main/frontend/components/block.cljs
src/main/frontend/text.cljs
src/main/frontend/util/thingatpt.cljs

Logseq indirects to a wrong page if org-styled page-reference or embed link (like `[[file:./demo.org][other name]]`, `{{embed [[file:./demo.org][other name]]}}`) has different page-name and label. This PR fixes this.

enhance(org): page-ref embeding allows different page-name and label

---

src/main/frontend/commands.cljs
src/main/frontend/components/editor.cljs
src/main/frontend/handler/editor.cljs
src/main/frontend/state.cljs

This PR makes it possible to customize the character that triggers the editor command palette. [Here is the discussion in Discuss.](https://discuss.logseq.com/t/custom-command-trigger/3081) The default trigger will remain `"/"` as it's always been, but if a user wants to customize it (e.g. to `"\"` as shown below), then they can do that. 
In a future PR, we could consider adding an input on the Settings panel to make this changeable from the GUI, rather than requiring the user to go into `config.edn` to change it (which makes it unlikely that they'll find it).
Note that updating the custom trigger config requires a full refresh of the app.
---
This PR also introduces a few smaller changes, which are not directly related to the primary change but came up while I was poking around the code: …

enhance: custom editor command trigger

---

src/main/frontend/components/page.cljs

1. Clicking the page title clears its content. `page-title` function introduced a new emoji argument as its second argument, so the default value of title should be the third one of the state instead of the second one.
2. Enter key can rename page now.  
3. Add a confirm window before renaming page.

enhance page rename

---

src/main/frontend/handler/editor.cljs
src/main/frontend/handler/page.cljs
src/main/frontend/util/page_property.cljs
src/test/frontend/util/page_property_test.cljs

Creating or renaming a page with namespace will add block-styled title
property, which is not proper. This PR fixed this issue.
Before: 
After:

fix: insert page attributes instead of block property when creating and renaming page

---

src/main/frontend/components/block.cljs
src/main/frontend/text.cljs
src/main/frontend/utils.js

- Fix https://github.com/logseq/logseq/issues/3085
- Fix issue: https://discord.com/channels/725182569297215569/735747000649252894/906585990108414033

Fix(rename): get the right page name if namespace exists in the path 

---

src/main/frontend/components/block.cljs
src/main/frontend/extensions/srs.cljs

I wanted to be able to add custom CSS styles to change the way **timestamps** and **custom queries** are rendered, but they didn't have classes that made it easy to change those styles.
This tiny PR adds classnames so users can add custom CSS on those elements.

enhance: add CSS classes to enable custom styles

---

src/main/frontend/text.cljs
src/test/frontend/text_test.cljs

This solves some issues when renaming page.
1. The embeded references will be updated which was not supported before.
2. query supports orgmode link now.

enhance page-ref-un-bracket!

---

src/main/frontend/handler/link.cljs
src/main/frontend/util/property.cljs
src/test/frontend/handler/test_link.cljs

Fix link display in properties drawer in Org-Mode
Before:
After:

enhance(properties): display various links well

---

src/main/frontend/components/page.cljs

- Cancel to reset the page name to its old one
- If new page already exists, popup notification instead of confirm window

enhance: page rename confirm window

---

src/main/frontend/db.cljs
src/main/frontend/db/model.cljs
src/main/frontend/handler/page.cljs
src/main/frontend/util.cljc

1. Renaming namespace page will update all its children's links
fix https://github.com/logseq/logseq/issues/3023
2. Update corresponding pages when renaming a page which referenced by other pages in title.
fix https://github.com/logseq/logseq/issues/1489

enhance: renaming namespace page will update all its children's links

---

src/main/frontend/components/editor.cljs

- Adds a `.page-properties` class to textarea so that user can style the editor differently when editing properties on a page vs other blocks.
- Fixes the `.multiline-block` class so that it applies **in addition to** the `h1`, `h2`, etc classes rather than **instead of** them.

Add more content-aware classes to textarea for a more WYSIWYG experience

---

src/electron/electron/state.cljs

Fixes #3157
The option in the setting menu is "enable git auto commit".
While the option in code is "disable-auto-commit".

fix: disable-auto-commit should default to true

---

Dockerfile

To keep it in sync with .github pipelines.

chore: bump nodejs version in Dockerfile

---

resources/css/tooltip.css
src/main/frontend/components/header.cljs
src/main/frontend/components/right_sidebar.cljs
src/main/frontend/components/search.cljs
src/main/frontend/components/settings.cljs
src/main/frontend/components/shortcut.cljs
src/main/frontend/components/sidebar.cljs
src/main/frontend/extensions/srs.cljs
src/main/frontend/handler.cljs
src/main/frontend/modules/shortcut/config.cljs
src/main/frontend/modules/shortcut/data_helper.cljs
src/main/frontend/ui.cljs
src/main/frontend/util.cljc
yarn.lock

- Now pulls the keyboard shortcut binding from config if the user has defined it, otherwise pulls the default binding. (Previously, it was hard-coded and didn't talk to config at all, which meant that the tooltips were wrong if (a) you'd defined a custom tooltip or (b) the tooltip had the wrong binding hard-coded.)
- Tooltips have slightly higher contrast + `<kbd>` styles, making them easier to read.
- Creates a `monospace` theme for tooltips, meant for shortcut bindings
- Refactors `shortcuts.config` so that the default bindings are easier to read. 
- Note: This part of the PR has a very large diff, but it's not actually a substantial change (i.e. functionality didn't change), it was just for readability.
- By restructuring it in this way, it'll allow for more use in the future (e.g. …

enhance shortcut tooltips

---

src/main/frontend/handler/editor.cljs

Fixes #3178
Introduced in https://github.com/logseq/logseq/commit/8323d0a2d2da8764bdd995bc0c076e0d0cf2f6f3 #2357
Does this break #2357 fix?

fix: do not triml while saving block

---

cypress/integration/app/basic.cljs
cypress/integration/app/template.cljs
cypress/integration/app/util.cljs

- wait for loading before starts
- no header logo now, click the modal overlay to go home
- multiline block requires `{enter}` twice to finish editing?

fix(test): update cypress tests according to new ui

---

.clj-kondo/config.edn
deps.edn
package.json
src/electron/electron/utils.cljs
src/main/frontend/components/repo.cljs
src/main/frontend/components/sidebar.cljs
src/main/frontend/db/model.cljs
src/main/frontend/debug.cljs
src/main/frontend/extensions/graph.cljs
src/main/frontend/format/block.cljs
src/main/frontend/fs/protocol.cljs
src/main/frontend/handler/git.cljs
src/main/frontend/handler/plugin.cljs
src/main/frontend/handler/ui.cljs
src/main/frontend/spec.cljs
src/main/frontend/state.cljs
src/main/frontend/util.cljc
src/main/frontend/util/property.cljs
src/test/frontend/handler/export_test.cljs
src/test/frontend/handler/page_test.cljs
src/test/frontend/react_test.cljs

* Can lint via `yarn cljs:lint` (not included in any other script yet)
* Resolved some macros for clj-kondo to work
* Fix some simple errors in 426a93a (e.g. duplicated `require`, private call)
* 10+ error and 700+ warnings to fix (or suppress)
* Suppress some linting using [namespace local config](https://github.com/clj-kondo/clj-kondo/blob/master/doc/config.md#introduction) (most cases are in `/src/test/`)

Introduce clj-kondo for linting

---

src/main/frontend/components/block.cljs
src/main/frontend/state.cljs

Adds ar://<tx> URL support for both links and images. The Arweave gateway used can be configured with the :arweave/gateway config key. It defaults to "https://arweave.net" if not configured.
I think this is reasonably tidy, but I'm happy to restructure it if desired (move code, rename functions, etc.). Also, it wasn't completely clear if or where I should add tests. Just let me know if you want any changes and I'll update the PR.

feat: support Arweave URLs for links and images

---

libs/src/LSPlugin.ts

Currently, using the isPageBlock property when using insertBlock allows you to insert a block on an empty page. However, there will be a TS error as shown below:
```
Argument of type '{ isPageBlock: boolean; }' is not assignable to parameter of type 'Partial<{ before: boolean; sibling: boolean; properties: {}; }>'.
Object literal may only specify known properties, and 'isPageBlock' does not exist in type 'Partial<{ before: boolean; sibling: boolean; properties: {}; }>'.
```
This PR attempts to remove this lint error.

Include isPageBlock property in insertBlock

---

src/main/frontend/handler/editor.cljs

See-also: https://developer.mozilla.org/en-US/docs/Web/API/Document/keydown_event#ignoring_keydown_during_ime_composition
Fixes #1821
Reproduce this bug on macOS:
- add system Japanese Hiragana Input Method, switch to it
- press `[` key
- the IME begins composition,  and Logseq shows `[「]` with an underline, which is annoying

Fix: Ignoring keydown during IME composition

---

src/main/frontend/handler/metadata.cljs

This avoids diff caused by hashmap order rearrangement, also minimizing diff when new pages are added.

enhance: sort by block name before save page metadata

---

src/main/frontend/db.cljs
src/main/frontend/db/model.cljs
src/main/frontend/handler/page.cljs
src/main/frontend/util.cljc
src/main/frontend/util/page_property.cljs
src/test/frontend/handler/page_test.cljs

- fix #3221.
- The nested_page will also be updated if the namespace in the name got renamed.  
Renaming a page will be more stable after this PR and PR https://github.com/logseq/logseq/pull/3228 got merged.
Demo: https://www.loom.com/share/8f78a816257449c5b42a888ef44a7621

fix rename issues if special chars like (), + exists in page name

---

src/main/frontend/components/hierarchy.cljs
src/main/frontend/format/block.cljs
src/main/frontend/text.cljs

1. Fix: create wrong pages if nested_link exists in the graph.
If `[[[[A/B]] is page]] got referenced` exists as a link in the graph, a `[[A` page will be created. This PR fixes this issue.
2. Fix: create wrong namespace if nested_link exists in the graph.
Before:
After:

Fix wrong namespace if nested link exists in the graph

---

.github/workflows/build.yml
README.md
deps.edn
src/test/frontend/external/roam_test.cljs

Hi logseq team. I noticed the clj tests run with `clj -Mtest-clj` fail with `Exception in thread "main" Syntax error compiling at (frontend/external/roam.cljc:1:1)`. It seems that roam.clj is no longer clj compatible so I moved the roam test to be cljs. I also added the clj tests to CI so they continue to pass going forward. I could make roam.clj to be cljs specific as well or take this PR in a different direction e.g. remove clj testing.
Thanks for this amazing editor :) Cheers.

Fix clj test invocation

---

resources/package.json

Fixes:
`cd static && DEBUG=electron-rebuild yarn rebuild:better-sqlite3`
```
✖ Rebuild Failed
An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '***/Repos/logseq/static/node_modules/better-sqlite3'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".
Error: Invalid version number: 15
```

fix(build): electron-rebuild version

---

src/main/frontend/components/plugins.cljs

Clicking a custom macro may invoke the block content itself's `mouse-down` handler. https://github.com/logseq/logseq/blob/master/src/main/frontend/components/block.cljs#L1794
Alternatively, we can stop event propagation here: https://github.com/logseq/logseq/blob/master/libs/src/helpers.ts#L358. Not sure which one is the desired solution?

fix: custom macro click issue

---

src/main/frontend/handler.cljs

Hi logseq team.
I thought it'd be fun if logseq had support for https://github.com/homebaseio/datalog-console like athens does. Here's what it looks like: 
I've confirmed this works in Chrome. This may work in electron but that will require more investigation. I've only enabled this in dev but perhaps it could be useful in prod at some point. I could add transact support from their [example integration](https://github.com/homebaseio/datalog-console/blob/main/src/main/datalog_console/integrations/datascript.cljs) if you'd like. To try this extension, follow steps 2-5 from https://github.com/homebaseio/datalog-console . For step 3, `yarn watch` and open logseq in Chrome.
Thanks for your hard work. Cheers

Add datalog console extension in dev

---

src/main/frontend/commands.cljs

When using `\` to open `Template` popup, extra space will be inserted after `\`.
Rationale: A `\` is not like other prefix+postfix style inserting commands, it is only the first stage of the template command.
To reproduce the behavior:
- `\Tem`
- Click Template or press Enter
- A popup will appear, and the current line becomes `\ |` (`|` indicates text cursor)
Triggering template popup:
Original
This fix:

fix: rm space when showing template popup

---

src/main/frontend/handler/editor.cljs

When pressing enter key at an empty page-ref `[[|]]` (`|` indicates text cursor), Logseq app will get stuck showing an empty page.
To reproduce:
- type `[[]]` in any block
- discard the search popup, and move text cursor to the middle of the square brackets
- type `Enter` on the keyboard
- App gets stunk, no responding

Fix app stuck when pressing enter at empty page-ref

---

src/main/frontend/format/block.cljs

**Issue to solve:**
https://github.com/logseq/logseq/issues/3224
**What's happening:**
* Refs are counted into pages.
* 538b0d8ad6c78c6e2d8ed51a151fc9bf9b186c94 removed the quote check (`[[]]`) when retrieving refs of "Links" with `:url` of "Search", and triggers the bug. (Haven't checked why the image file is categorized as this)
* Bug happens if a user has such links, and apply a re-index within the bad commits.
**The fix:**
* Add back the quote check
**For users suffered from the bug:**
* Refresh and re-index after the commit

fix: All Pages view lists all of the images

---

.github/workflows/build.yml

Ref: [Git libs are downloaded by default to the ~/.gitlibs directory](https://clojure.org/reference/deps_and_cli#_git)

ci: add ~/.gitlibs to build cache

---

src/main/frontend/components/page.cljs

Fixes #3273
https://github.com/logseq/logseq/blob/5b2ae552ae171c75633f08a0af27fe55dbaea6a1/src/main/frontend/components/page.cljs#L749-L755

fix: search input in All pages requires 2 chars

---

src/main/frontend/components/block.css
src/main/frontend/components/editor.cljs
src/main/frontend/state.cljs
src/main/frontend/util/keycode.cljs

**Motivation**:
* For users who write multiple lines in heading block, the current WYSIWYG is very annoying, as it enlarges the non-heading part of the block.
* The process of "typing '#'s then changing style" is laggy
**Improvements**:
* refactor: remove duplicated class-name
* enhance: remove change of style for multiline headings in editing
* enhance: to make heading css more responsive, bind editor's heading class to editor content
* fix: adapt textarea to changable font-size
* fix: remove the markdown style WYSIWYG headline in org-mode editing
**Trade-offs**:
* Every change of content would trigger the heading class check
* ~~Every typing would trigger the textarea's row-height measurement~~
* Every pressing of `enter` would trigger textarea's row-height measurement
* Since the …

Enhance WYSIWYG experience of multiline heading

---

src/main/frontend/modules/shortcut/config.cljs

Refers to https://github.com/logseq/logseq/issues/3278
Fix the cmd+l for inserting `[blablabla]()` ability.
To further improve the functionality, we could split it into an individual insert-link handler function in future.

fix: insert-link doesn't work

---

README.md

Updated the instructions for E2E testing
- Cypress was removed and replaced with playwright (https://github.com/logseq/logseq/pull/3241)
- Instructions are based on @andelf comment (https://github.com/logseq/logseq/pull/3241#issuecomment-976201958)

chore: Update README E2E Testing Instructions

---

src/main/frontend/handler/editor.cljs
src/main/frontend/util/cursor.cljs

* Fix the bug that some DWIM features don't work on the first line of block
* https://github.com/logseq/logseq/issues/3294 Limit the list item's DWIM to the case that user press `enter` at the end of line

Enhance DWIM feature of list item

---

e2e-tests/basic.spec.ts
e2e-tests/fixtures.ts
e2e-tests/hotkey.spec.ts
e2e-tests/utils.ts
playwright.config.ts

- Refactor using hijacked fixtures, now the spec files are more like a normal playwright test
- Add hotkey tests, See-also: https://github.com/logseq/logseq/issues/3278
*Edit*: Refactor e2e tests

test(e2e): Refactor and add test cases for hotkey

---

.github/workflows/build-desktop-release.yml
package.json
scripts/get-pkg-version.js

- Reduce build steps
- Add nightly build
- Merge macOS x64 and arm64 build into one job
- To trigger a beta release:
- Bump `version` config in `src/main/frontend/version.cljs`
- In Github Actions page, choose Build-Desktop-Release workflow
- Make build target a `beta`
- Run the workflow
- Go to the Release page and fill the release notes
- Publish the Release🚀
**Update:**
**Edit**
Use version in `src/main/frontend/version.cljs`.
Fix #3128, now the version in Release Page will always match App version in Settings menu

ci: refactor desktop app release workflow, add nightly build

---

src/main/frontend/components/settings.cljs

Added a warning under "Clear cache" in advanced settings. I noticed that some users like in (#3309) might not realize that clearing the cache will discard open graphs. 
<table><tbody><tr><td>Before</td><td>After</td></tr><tr><td><figure class="image"><img src="https://user-images.githubusercontent.com/25513724/143990370-33d8d725-df9c-4839-b955-ba6336fc4a23.png"></figure></td><td><figure class="image"><img src="https://user-images.githubusercontent.com/25513724/143990932-e8fe268e-7578-4d04-9182-839bc33b41a2.png"></figure></td></tr></tbody></table>
The warning is based on the warnings for "Refreshing" and "Re-Indexing" the graph  
 
<table><tbody><tr><td>Refresh</td><td>Re-index</td></tr><tr><td><figure class="image"><img src="https://user-images.githubusercontent.com/25513724/143916911-8dc2 …

enhance: add warning for clear cache

---

src/main/frontend/components/settings.cljs

There is a grammatical error (663c86d#commitcomment-61122338) in my last pull request (#3316)
<table><tbody><tr><td>Current</td><td>Fix</td></tr><tr><td><figure class="image"><img src="https://user-images.githubusercontent.com/25513724/144099330-9d98b427-c51a-4c41-8beb-c90f7caf92de.png"></figure></td><td><figure class="image"><img src="https://user-images.githubusercontent.com/25513724/143990932-e8fe268e-7578-4d04-9182-839bc33b41a2.png" alt="https://user-images.githubusercontent.com/25513724/143990932-e8fe268e-7578-4d04-9182-839bc33b41a2.png"></figure></td></tr></tbody></table>
Any feedback on the warning phrasing would be appreciated

fix: typo in warning for clear cache

---

.github/workflows/build-desktop-release.yml
scripts/get-pkg-version.js

Fix missing variables in `schedule` builds.
~For a temporary solution, users can download nightly build from Artifacts list from Github Actions:~
**EDIT:**
- Only fixes missing variables and disable nightly scheduled build for now
- Planning to use a customized github action to manage nightly release

fix(ci): missing variables in release build

---

src/electron/electron/utils.cljs

Fixes #3310
TODO:
**EDIT**:
Tested on Windows.

fix: do not ignore patterns in parent dir

---

src/main/frontend/handler/web/nfs.cljs

BUG:
You cannot enable encryption on a local graph with the Encryption setting on.
[The doc](https://logseq.github.io/#/page/Encryption) says `re-index` the graph should work, but actually nothing happens when re-indexing.
Fix:

fix: local graph should popup encryption dialog when re-index

---

src/main/frontend/components/block.cljs

By fixing the href value, the following links should work well as external links in orgmode.
`[[file:/Users/ll/Downloads/test.pdf]]`
`[[file:/Users/ll/Downloads/test.pdf][a pdf]]`

fix(org): get right link href for file links

---

src/main/frontend/components/repo.cljs

fix(ui): missing span in repo-name dropdown

---

src/main/frontend/components/block.cljs
src/main/frontend/components/query_table.cljs
src/main/frontend/components/sidebar.cljs
src/main/frontend/db/model.cljs
src/main/frontend/db_schema.cljs
src/main/frontend/format/block.cljs
src/main/frontend/handler/block.cljs
src/main/frontend/handler/editor.cljs
src/main/frontend/handler/export.cljs
src/main/frontend/handler/extract.cljs
src/main/frontend/handler/page.cljs
src/main/frontend/modules/file/core.cljs
src/main/frontend/modules/outliner/core.cljs
src/main/frontend/tools/html_export.cljs
src/main/frontend/util/drawer.cljs
src/main/frontend/util/page_property.cljs
src/test/frontend/handler/block_test.cljs
src/test/frontend/modules/outliner/ds_test.cljs

For two reasons:
1. Reducing memory usage, both block/title and block/body are AST parsed
by Mldoc. After removing, logseq is able to handle 10k notes.
2. Simplify the db schema

chore: remove :block/title, :block/body and :block/unordered

---

src/main/frontend/extensions/srs.cljs

(screenshot taken while hovering over the middle button)

enhance: color code SRS buttons & extract shortcut to tippy

---

src/main/frontend/components/repo.cljs

fix: graph name in all graphs page

---

src/main/frontend/util/drawer.cljs

Once a Task Block got embedded, its logbook drawer disappears when toggling the state from TODO to DOING.  This PR fixed this issue.
https://www.loom.com/share/fbe905f794294c6eb3088252e473530f

fix(logbook): logbook disappears when block got embedded

---

e2e-tests/basic.spec.ts
e2e-tests/utils.ts

New left sidebar is handled by `is-open` class.

fix: e2e tests for new left sidebar

---

src/main/frontend/text.cljs

This PR fixes:
- Indention is wrongly calculated from the first line of code, causing #3130 
- `string/split-lines` returns empty vec, following `re-find` call will fail
FYI:
`clojure.string/split-lines` is not empty-line friendly:
```clojure
user=> (clojure.string/split-lines "\n\n\n\n \n\n\n\n")
["" "" "" "" " "]
user=> (clojure.string/split-lines "\n\n")
[]
```
`(string/split text #"\r?\n" -1)` is OK.

fix(editor): wrong indent removal fn

---

src/main/frontend/components/lazy_editor.cljs

See-also: #3410
This is a little tricky. Since the original implementation of code editor requires the buggy behavior of `text/remove-indentations`.
Will add e2e test cases for code-editing.

fix(editor): extra newline in code editor

---

e2e-tests/basic.spec.ts
e2e-tests/code-editing.spec.ts
e2e-tests/hotkey.spec.ts
e2e-tests/utils.ts
src/main/frontend/components/lazy_editor.cljs
src/main/frontend/extensions/code.cljs
src/main/frontend/text.cljs

- won't `remove-indentations` before and after code editor
- underlying CodeMirror status is buggy, the original implementation forgets to modify block just before entering code editor,
- I can confirm this is the main cause of failing to save code to block
- empty spaces matter, what if a user write code in [whitespace](https://en.wikipedia.org/wiki/Whitespace_(programming_language)) 🤣 
- rewrite saving handler of code editor
- use pos-meta to handle block updates(both markdown and org-mode)
- Now multiple code snippets can be in the same block
- debounce ESC event against blur
- original debounce logic is lagging
- Add e2e test cases
- simple edit, switch between code editor and raw editor
- indentations, whitespaces
- code snippets surrounded by texts
- multiple code snippets in the …

Refactor: refine saving process of code editing, with e2e test cases

---

package.json

Fixes #3421
~~Haven't got any idea of how this was introduced.~~
**EDIT:**
2e2e8f23aae62d0ae0f71c3b9f577dd5beba331b changes excalidraw semver from `^0.4.2` to `0.4.2`.
While in the codebase's `resources/js/excalidraw-assets/vendor-3525c448906ddcdcb701.js` is the asset file of `0.4.3`( semver rule matters).
So when building a release desktop app with no-cache, excalidraw vendor assets will be missing(wrong file path).

fix(build): wrong vendor assets of excalidraw

---

.github/workflows/build.yml

It seemed that 32eba7ab7a1e500033be6f7c039be7574e1b01d0 breaks e2e tests.
Since this repo doesn't reject push to master.
e2e tests should be enabled in any case.
Related #3433

fix(ci): enable e2e test on push

---

e2e-tests/code-editing.spec.ts
src/main/frontend/extensions/code.cljs

Affects code block with non-latin1 chars in the heading line.

fix(editor): handle code block with non-latin1 chars

---

.github/workflows/build-desktop-release.yml

Nightly build must be a non-draft. It is due to the nightly tag is already existed, a draft release can not create a tag.

fix: nightly build with draft=false

---

src/main/frontend/handler/editor.cljs

Close #3459
Note: the key change is to remove this Enter key checking:
https://github.com/logseq/logseq/blob/d7b1ce51e368a8ea7ae2020070144b7e0441abcf/src/main/frontend/handler/editor.cljs#L2877
I read the whole logic and didn't find it's usage. But I'm still concerning if it breaks any other case.
The Enter key checking is introduced in https://github.com/logseq/logseq/commit/efbcb792997a11af67d0a5b1cee51e833aaa11eb (to solve https://github.com/logseq/logseq/issues/3251). I tested MS pinyin and the `【【` completion works correctly.

fix: Chinese IMEs doesn't trigger slash command

---

src/main/frontend/components/editor.cljs
src/main/frontend/components/search.cljs

Fix #3199 #3084 
Close #1561  (Seems it is fixed for a while)

fix: unable to type with IME in search modal

---

e2e-tests/code-editing.spec.ts
src/main/frontend/components/block.cljs

- use new-content when entering edit mode
- add e2e test cases for #3463

Fix: code save when blur

---

src/main/frontend/components/datetime.cljs

If editing state is on in other block, submitting the timestamp to current block will also add a timestamp to that block.

fix(timestamp): clear editing state before setting timestamp

---

src/main/frontend/components/search.cljs
src/main/frontend/handler/editor.cljs
src/main/frontend/util.cljc

Fix #3440
#3440 #3459  #3283 #3251 #3218 #3199
* Chinese IME would trigger markdown heading 1 style when type in `#中文标签`

fix: IME check refactor

---

src/main/frontend/extensions/graph/pixi.cljs

Fix #3331
Add a try-catch block to avoid the hang-up.

fix: graph view hang if duplicated links exist

---

e2e-tests/code-editing.spec.ts
src/main/frontend/extensions/code.cljs
src/main/frontend/format/block.cljs

When properties and code snippets are in the same block, offset calculation will interfere with property-stripped content.
- Fix pre-block offset
- Fix multiple properties with code snippet
- Fix #3472 
- Add e2e test case

Fix: code offset is wrong when code and multi properties in the same block

---

src/main/frontend/handler/graph.cljs

This slightly improves the cubic-root-based node-size scaling in the graph view. 
Diff looks bigger than it is (only functional change is b2fff04887a48396ba9d2ef571773dabdd34afae) because I also removed some redundant code. That may (slightly) improve performance on large graphs.

More fluid Graph scaling on lower-end

---

e2e-tests/basic.spec.ts
src/main/frontend/handler/editor.cljs
src/main/frontend/util/keycode.cljs

Fix #3444
Close #3292 
**Observations**
* Same KeyCode represents different Keys on different keyboard layouts;
* Should avoid checking `:keyCode` or `:code` of Events for non-functional keys;
* Assuming the `:keyCode` check is introduced for recognizing full-width chars like `【` `（` (Mainly caused by CJK IMEs)
**Actions**
**Notes**
* Playwright's IME / Keyboard support is non-exist. 
* Playwright's typing of non-US keys are not sending keyup / keydown event.

fix: unexpected behaviour caused by abuse of keycode

---

src/main/frontend/components/query_table.cljs

Original query table has the following structure:
```html
<table>
<th />
<tr> 
<td>
```
Fixed:
```html
<table>
<thead>
<tr>
<th>
<tbody>
<tr>
<td>
```

fix(ui): missing tr/thead/tbody in query-table

---

src/main/frontend/modules/shortcut/config.cljs

Changes:
- The recommended key for `Escape editing` is `Ctrl` + `[`. This is a default binding in Logseq for going `Backwards` and should not be recommended.
- the goto shortcuts such as: `g` `h` are used for navigating logseq.

fix: Formatting keyboard shortcuts

---

src/main/frontend/components/block.cljs
src/main/frontend/components/file.cljs
src/main/frontend/extensions/code.cljs

- use `CodeMirror.findModeByName`
- remove redudent clojure mime type for CodeMirror
- fix wrong highlight.js language mode(since .language-* is not set, it was always a guess)

Optimize the language selection logic, fix the wrong highlight.js language selection

---

src/main/frontend/handler/link.cljs

Fix #3519
**EDIT:**
Use a simpler regexp.

fix: use simpler regexp to parse links in properties

---

src/main/frontend/components/file.cljs
src/main/frontend/extensions/code.cljs
src/main/frontend/fs/nfs.cljs
src/main/frontend/fs/node.cljs

fix(editor): more stable file edit
- update element state when switching files #3415
- notification when saved
- minor style change
- refine editor element id gen, use UUID
- add trailing newline to the saved file
Fix #3415

Refine file editing experience, fix file switching bug

---

e2e-tests/page-alias.spec.ts
e2e-tests/utils.ts
src/main/frontend/extensions/graph.cljs
src/main/frontend/handler/editor.cljs
src/main/frontend/handler/route.cljs

- Should call `get-redirect-page-name` to check if a `page-name` is an alias of another page before redirect
- Partly related to #3511
**Fixed `redirect-to-page` invokes that alias is NOT working**
Checked `redirect-to-page` invokes that alias is working
- On click `shift + mod + o`:  (db name only)
- On mouse click:  `page-cp` (calling `get-redirect-page-name`)
- On create page: `create!` if `re-direction` is `true` (happens when create new page in search modal)
- On zoom-in: `zoom-in!` (uuid only)
- On zoom-out: `zoom-out!` (db name only)
- On opening `default-home`: `main-content` (db name only)
- On search (db name only)
**E2E Tests**
- Add argument `inner_only` to functions `lastBlock` and `newBlock` (see comments)

fix: alias is not considered from shortcut / graph / press enter visit

---

src/main/frontend/components/datetime.cljs

revert https://github.com/logseq/logseq/pull/3481, it broke the workflow that insert a new timestamp in a block.

fix: failed to insert a new timestamp in a block

---

src/main/frontend/components/sidebar.css

https://user-images.githubusercontent.com/72891/146886912-14ec75d1-1b71-4a33-b9ac-3a6457f2e337.mov
This left sidebar's animation is divided into header and body parts, which is not in sync.
Caused by `:before` pseudo-element.

fix(style): refine shift-in animation of left-sidebar

---

src/main/frontend/modules/shortcut/config.cljs

- set to false to disable silently

fix: shortcut warning at startup

---

.github/workflows/build-mobile-release.yml

NOTE: Because the release process for the mobile version of the application has not yet been determined, no release operations are currently being performed. The apk can be downloaded from the Github Actions page.
This workflow requires two secrets for signing apk:
- ANDROID_KEYSTORE: base64 encoded of keystore.jks
- ANDROID_KEYSTORE_PASSWORD: the password of keystore.jks, with no special chars for now

ci: add android apk build

---

.github/workflows/build-android.yml
.github/workflows/build-desktop-release.yml
android/app/build.gradle

- reuse build-android.yml in nightly/beta release workflow
- bump Android app version to 0.5.4
#3541 will add Android version to bump-version script later.

Ci: add android build to nightly

---

src/main/frontend/state.cljs
src/main/frontend/util.cljc

Move the editor into the center of the viewport if it's near the top.
It can be triggered by deleting a block near the top.

enhance: move the editor into the center of the viewport

---

.github/workflows/build-desktop-release.yml

"non-release" for a build-only workflow

ci: non release for non-beta

---

e2e-tests/basic.spec.ts
e2e-tests/fixtures.ts

This should avoid something like #3563.

test(e2e): monitor error logs

---

ios/App/App/FileContainer.swift

add an empty .logseq file at the container root to reveal the logseq folder.

fix(ios): unhide logseq folder in iCloud Drive

---

src/electron/electron/handler.cljs

Fix #3568 #3563
Require cache to be cleaned.
Or manually delete `~/.logseq/graphs/` directory.

fix(electron): windows path escape with colon

---

package.json

fix(build): lock pixi.js v6.2.0 for pixi-graph-fork

---

src/main/frontend/components/block.cljs
src/main/frontend/components/block.css
src/main/frontend/components/content.cljs
src/main/frontend/components/page.cljs
src/main/frontend/handler/editor.cljs

There are several improvements list below:
* fix `t o` doesn't collapse all blocks 
* add `Exppand all` and `Collapse all` menu item for toggling block 
*  auto expand children of the top block if collapse(fix #3222) 
* basic support for toggling by clicking the left bar of the block (see https://discuss.logseq.com/t/collapse-all-child-bullets-by-clicking-the-alignment-line/1937/3)
For the structure below:
if we collapse `b` block
and use `t o` to collpase all block, and manually expand `b` block again, we will find `c` is not collapsed.
**wrong behavior after expand b block**
**expected behavior**
Now we can toggle in the block level.
When we jump to the block page, if the top block is collapse, expand its next level children.
fix #3222
see …

Enhance block toggle feature

---

src/main/frontend/components/block.cljs
src/main/frontend/components/block.css

In https://github.com/logseq/logseq/pull/3559, block children are wrapped into a `flex` container, but it previously took all available width, after the change it only takes its children width. This issue will make the width of block children smaller. For empty block children, they are not clickable.

fix empty block children is not clickable issue

---

src/main/frontend/components/block.cljs
src/main/frontend/components/block.css
src/main/frontend/components/content.cljs
src/main/frontend/components/page.cljs
src/main/frontend/handler/editor.cljs

Some improvements based on #3559
1. Display `Expand all` where there're already collapsed blocks. This applies to `Collapse all` too.
2. Make the guideline bold when hovering on it.
3. Simplify some logic
It also resolves #2190

enhance: block expand/collapse toggle

---

resources/icons.edn
src/main/frontend/components/block.cljs
src/main/frontend/components/hierarchy.cljs
src/main/frontend/db/model.cljs
src/main/frontend/handler/file.cljs
src/main/frontend/handler/page.cljs
src/main/frontend/handler/route.cljs
src/main/frontend/util.cljc

`{{namespace [[Book 1]]}}` can be rendered as:

feat: add {{namespace [[page]]}} macro which can be used as a toc

---

src/main/frontend/components/header.css

Fix the right padding of header:

fix(mobile): weird header padding on mobile

---

resources/css/common.css

Addresses #3659, fixes both the case of a two-word search string matching a one word string, and having the space inserted, as well as a two word search string leading to a space at the end when highlighting.
I feel it looks much more aesthetic now.
Before:
Now:

Removing padding on mark

---

libs/src/helpers.ts

Without `target="_blank"` attribution, the plugin cannot render an external link (or this link will always be opened in current window).

fix(plugin): allow target attribution in provideUI

---

src/main/frontend/db/query_dsl.cljs
src/test/frontend/db/query_dsl_test.cljs

Related to #3630.
Full text search example in a nested query:
`(and [[page]] "query")`

fix: nested and query issues and full-text search in nested queries

---

.github/ISSUE_TEMPLATE/feature_request.md

Updating the phrasing of the feature request template
```diff
- Please go to [Logseq forum](https://discuss.logseq.com/c/feature-requests/7) to create a feature request so that people can vote there.
+ Thank you for the feature request.
+ Please note that GitHub is only used to track issues/bugs.
+ Feature requests are available on the [Logseq forum](https://discuss.logseq.com/c/feature-requests/7) to allow users to engage in the discussion and vote on it.
+ All feature requests on GitHub will be closed.
```

enhancement: update feature request template

---

src/main/frontend/components/repo.cljs

Fixes the following BUG:
`multiple-windows?` will always be true if set.
To reproduce:
- Open Window A with Graph A
- Open Window B(will also be Graph A)
- Click re-index(then cancel)
- Close Window B
- Now you cannot re-index Graph A

fix(electron): multi window check in re-index

---

src/main/frontend/handler/editor.cljs

Clipboard data with newlines will be inserted as raw text in source block or admonition.
fix https://github.com/logseq/logseq/issues/3685

enhance(dwim): dwim on paste in source block or admonition

---

src/main/frontend/extensions/graph/pixi.cljs

Fix #3755
Further fix #3498
- I think it's better to merge the error catching first.

fix: graph view hang due to node / edge duplication

---

android/app/capacitor.build.gradle
android/app/src/main/assets/capacitor.plugins.json
android/capacitor.settings.gradle
src/main/frontend/fs/capacitor_fs.cljs

- Don't encode path on android
- Allow reading and parsing file with # and % in its filename. 
fix https://github.com/logseq/logseq/issues/3707

Fix filename encode and special chars

---

src/main/frontend/debug.clj
src/main/frontend/debug.cljs

we can replace `clojure.core/defn` with `frontend.debug/defn` when profiling , this `defn` will print elapsed time of all funcs

feat(debug): add debug func `defn`

---

src/main/frontend/components/block.cljs
src/main/frontend/components/editor.cljs
src/main/frontend/components/journal.cljs
src/main/frontend/components/page.cljs
src/main/frontend/components/sidebar.cljs
src/main/frontend/components/sidebar.css
src/main/frontend/modules/outliner/tree.cljs
src/main/frontend/ui.cljs
src/main/frontend/util.cljc

This PR addresses the bad performance when loading long pages, 20k blocks will make logseq stuck and not respond at all.
Previously, there's already pagination and lazy loading but it's only for the top-level blocks, this PR enabled the lazy loading for blocks in nested levels too.
In the future, we should investigate virtual trees to improve both UX and reduce memory usage.
https://www.loom.com/share/296118d8a50e4fba90d5c4398f9cae30

enhance: improve long page loading performance

---

package.json

The current version 1.2.1 was released 3 years ago. Updating it to the latest version may solve some issues, typically unloading issue that iOS users keep reporting.

bump react-tweet-embed

---

src/main/frontend/db/model.cljs

Safari doesn't support lookbehind pattern `?<!`.
Reference: https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group
Fix #3645

fix(iOS): clicking unlinked reference blanks out

---

src/electron/electron/window.cljs

- `Add to dictionary` is used for spelling check
- The condition in `when-let` of menu item is wrong, since `""` is considered boolean true in Clojure
Fix #3657

fix(electron): only show add to dictionary when misspelling

---

.github/workflows/build.yml

The `test(ubuntu-latest)` is renamed. No clue why it says "wait for status to be reported".

Fix ci(build): rename job

---

src/electron/electron/handler.cljs

Clear cache then close the app will save a `local.transit` in `~/.logseq/graphs`.
Next time opening logseq, there will be a "path empty" error in the main thread.
Fix #3850

fix(electron): do not save cache for demo graph

---

gulpfile.js

Solve gulp high cpu usage by explicitly setting `usePolling`
Before:
After:
An internal bug of Gulp / chokidar ? The default value for `usePolling` was `false`.
https://gulpjs.com/docs/en/api/watch/

dev: fix gulp-watch cpu usage

---

resources/marketplace.html

The marketplace page, in the readme page of plugin,the close button has a wrong position ,Also,the end of this page has no padding.
windows 10  
0.5.8 nightly 20220113
marketplace: link preview plugin

enhance(marketplace): plugin readme page ui position

---

src/main/frontend/components/block.cljs
src/main/frontend/handler/extract.cljs
src/main/frontend/handler/file.cljs

A temporary Fix #3804
Need discussion about how to refine this part of code.
Can locate the issue is caused by
https://github.com/logseq/logseq/blob/3ded9ee1ff9dc7c15ce8aaf072d8de7deeb2ba9e/src/main/frontend/handler/file.cljs#L163-L180
which requires the filtering logic from
https://github.com/logseq/logseq/blob/3ded9ee1ff9dc7c15ce8aaf072d8de7deeb2ba9e/src/main/frontend/handler/extract.cljs#L250-L255
Should we merge this two functions or at least extract some helper functions? As they have so many overlapping logics

fix: datascript error blocks file watching

---

src/main/frontend/components/editor.cljs
src/main/frontend/components/search.cljs
src/main/frontend/components/sidebar.cljs
src/main/frontend/handler/editor.cljs
src/main/frontend/search.cljs
src/main/frontend/search/db.cljs
src/main/frontend/util.cljc

Make search index normalized & case-insensitive.
**Motivations**
* `fuse.js` and `SQLite3 + fst5` have different behaviors toward tokenization, especially the default tokenizers in `fst5` handles Cyrillic upper case characters badly (Fix #3352);
* It's confusing that index text is case-sensitive, while query text is case-insensitive;
**To activate the update**
* `mod+c mod+s` to rebuild search index

Enhance full text search index

---

src/main/frontend/components/header.cljs

This fixes the wrong precondition for top-right `+ Open` button.
Avoid buggy UI conditions like:( neither repo-switch nor open button is shown. CANNOT open new graphs)
The button's shown condition should be coordinated with repo-switch of left-sidebar.
https://github.com/logseq/logseq/blob/557b67925fc2025facd039ed184be063f5110b27/src/main/frontend/components/repo.cljs#L215
https://github.com/logseq/logseq/blob/557b67925fc2025facd039ed184be063f5110b27/src/main/frontend/components/repo.cljs#L296-L305
Fix #3781
Fix #3637

fix(ui): wrong precondition for open button

---

e2e-tests/basic.spec.ts
src/main/frontend/format/mldoc.cljs

Introduced in 2401ce9. it might change some processing orders. A commit just before it works.
Fixes #3944

Fix invalid boolean props

---

src/main/frontend/mobile/core.cljs

Since left-sidebar layout mess-up when editing has been fixed, collapse is not needed anymore.

don't collapse left sidebar when editing

---

src/main/frontend/components/editor.cljs

fix(editor): reorder auto-complete items

---

src/main/frontend/handler/page.cljs
src/main/frontend/util.cljc

Fix #3971
NOTE: whitespace changes introduced
Diff without whitespace: https://github.com/logseq/logseq/pull/3977/files?diff=split&w=1

fix: add title property when necessary

---

src/main/frontend/handler.cljs
src/main/frontend/handler/page.cljs
src/main/frontend/mobile/util.cljs

Logseq iOS app now fully downloads iCloud files every 5 seconds (called in `create-today-journal`),  which is too frequent and may leads to some performance issues (The device gets hot slightly).
This PR increases the interval to 5 minutes.

Increase iCloud background sync interval

---

src/main/frontend/components/command_palette.css
src/main/frontend/components/editor.cljs
src/main/frontend/components/repo.cljs
src/main/frontend/components/select.cljs
src/main/frontend/components/sidebar.cljs
src/main/frontend/components/widgets.cljs
src/main/frontend/config.cljs
src/main/frontend/dicts.cljs
src/main/frontend/handler/events.cljs
src/main/frontend/modules/shortcut/config.cljs
src/main/frontend/state.cljs
src/main/frontend/ui.cljs

This PR adds a command for switching graphs easily via keyboard. I'd like to be using 2-4 graphs in one window but the friction of using a mouse discourages it. This PR also provides a reusable select component for future commands that have the same selection needs. I chose to split select from command palette because the goals of the two components are different enough as is the logic and styling needs. Command palette is focused primarily on great command selection ux whereas the select component just quickly picks a value from a list.

Add a command to switch graphs

---

src/main/frontend/handler/editor.cljs

This is a fix for #4045. As noted in the first comment, this bug effects all collapse/expand actions. I found that this bug was introduced in https://github.com/logseq/logseq/pull/3855#discussion_r792101354. The fix just adds back the behavior before of saving the collapse state to the file. Calling `set-block-property!` directly is maybe a little inefficient since now two calls to `db/refresh!` and `outliner-core/save-node` occur. I didn't know if I should refactor more but at least this fixes the issue

Fix block collapse state not being saved

---

src/main/frontend/handler/extract.cljs
src/main/frontend/text.cljs

Revert "fix: title prop with double quotes"

---

src/main/frontend/fs.cljs
src/main/frontend/fs/capacitor_fs.cljs
src/main/frontend/handler/page.cljs

The PR fixes page rename issue on mobile.
* Reuse new function from PR https://github.com/logseq/logseq/pull/4010.

fix page rename on mobile

---

ios/App/App/DownloadiCloudFiles.m
ios/App/App/DownloadiCloudFiles.swift
src/main/frontend/fs/capacitor_fs.cljs
src/main/frontend/handler/page.cljs
src/main/frontend/handler/repo.cljs
src/main/frontend/mobile/core.cljs
src/main/frontend/mobile/util.cljs

- Rename `downloadFilesFromiCloud` to `iCloudSync` (swift)
- Add a new function `syncGraph` which takes a graph url parameter (swift)
`iCloudSync` syncs all unsynchronized files in all graphs, including files in `bak`, `.git`, `.Trash`, `.recycle`, while `syncGraph` only syncs a single graph with those auxiliary folders excluded to reduce downloading time.
Now iOS app syncs iCloud files as follows:
- Sync selected graph only when adding a new graph
- Sync current graph only when re-indexing
- Sync current graph only when switching from other apps
- Fully sync all graphs every 5 minutes in background (implemented in PR https://github.com/logseq/logseq/pull/4014) to avoid any potential sync issues, eg. sync block.

enhance iCloud sync

---

src/main/frontend/components/block.css

First PR! 🎉
Fix issue with bullet lines not being shown, closes #3663

fix(document-mode): bullet lines not fully hidden

---

src/main/frontend/db/query_dsl.cljs
src/main/frontend/handler/link.cljs
src/main/frontend/text.cljs
src/test/frontend/db/query_dsl_test.cljs
src/test/frontend/handler/link_test.cljs
src/test/frontend/text_test.cljs

This PR fixes three bugs:
- It starts running the `link-test` ns which wasn't running because it was named `test-link`. Most clj(s) test runners look for namespaces ending in `-test`.
- It fixes #4088 as evidenced by the text-test assertion change. Bug was introduced in #3520 but we didn't catch it because the link tests weren't running . This bug was also effecting querying as described in https://github.com/logseq/logseq/issues/4007#issuecomment-1021245310 and the [visual look of the link](https://github.com/logseq/logseq/issues/4007#issuecomment-1021245310)
- It fixes #4007 which was due to integers needing to match as strings or integers depending on whether they are links in a property value. I made the smallest change possible
While fixing this bug, I observed that the plain urls …

Fix property page links in #4088

---

.clj-kondo/config.edn
deps.edn
src/main/frontend/components/block.cljs
src/main/frontend/components/file.cljs

In preparation for being able to automate [clj(s) dependency checks](https://quire.io/w/Logseq-_team_dedicated_to_sport_of_knowledge/107/Upgrade_clj_cljs_dependencies?filter=all), I noticed we use a forked version of datascript. I looked into the [built-ins we added](https://github.com/tiensonqin/datascript/commits/fork) and the only we use is `get`. I [contributed this back to datascript](https://github.com/tonsky/datascript/pull/423) so we can now depend on the latest datascript. I looked at [the changelog](https://github.com/tonsky/datascript/blob/master/CHANGELOG.md) and didn't see any breaking changes since 1.3.2. Another advantage to being on standard datascript is that we'll be able to use a datascript version of bb. This could be _very_ useful for scripting, both for us logseq …

Use standard datascript

---

src/main/frontend/fs/capacitor_fs.cljs
src/test/frontend/fs/capacitor_fs_test.cljs

These are some tests for #4010 and thus are based off that branch. [The CI job](https://github.com/logseq/logseq/runs/5009975975?check_suite_focus=true) shows that the nil case failed unexpectedly and that the relative case returned url encoded path instead of url decoded path. Fixed these with the followup commit.
EDIT: The last commit doesn't trigger CI tests. I did confirm locally that `yarn test` runs. It looks like it's because of [this configuration](https://github.com/logseq/logseq/blob/86122245af90a793a39673e9e9283dd3a9ff1130/.github/workflows/build.yml#L9). I can change it to any branch if @tiensonqin is ok with it

Tests for #4010

---

.github/ISSUE_TEMPLATE/bug_report.yaml

Replace `value` with `placeholder` for reproduce step and platform information, because this can leave **less interference information** for unfilled fields like: 
Also simplified platform information 
```
- OS: [e.g. iOS]
- Browser [e.g. chrome, safari]
- Version [e.g. 22]
```
into a single `MacOS 12.2 Logseq Desktop v0.5.9`, because the old version doesn't include desktop version and thus may make users confused.
By the way, another choice is something like this (move example into description and keep empty value fields):
```
description: |
Would you mind to tell us the system information about your desktop platform?
example:
- OS: MacOS 12.2
- Browser: Chrome 22 (leave it empty if you are using desktop app)
- Desktop App: v0.5.9 (leave it empty if you are using browser)
value: |
- OS: …
```

Improve issue template

---

src/main/frontend/components/editor.cljs
src/main/frontend/handler/editor.cljs

Demo: https://www.loom.com/share/59251a285045480e8dd50d4f02e40015
close https://github.com/logseq/logseq/issues/378

fix: text goes beneath toolbar in large block on iOS

---

src/main/frontend/components/editor.cljs
src/main/frontend/handler/editor.cljs
src/main/frontend/handler/page.cljs

- Fix #4178, handle `[[]]` with `#` in the same line
- Refine page search item order
- blank input -> placeholder for search or type
- matches -> case insensitive match
- no match -> New Page: ...
- wrong `set-last-pos!` in keydown handler

Fix page search autocompletion

---

ios/App/App/DownloadiCloudFiles.swift

This PR checks whether some important files (`.md`, `.org`, `.css`, `.edn`) are downloaded successfully before refreshing to database.

enhance(iOS): ensure important files to be downloaded from iCloud

---

package.json
src/main/frontend/components/editor.cljs
src/main/frontend/handler/editor.cljs
src/main/frontend/handler/editor/lifecycle.cljs
src/main/frontend/handler/events.cljs
src/main/frontend/handler/ui.cljs
src/main/frontend/util.cljc

This PR improves various editing operations in large block.
- Cursor row goes to center of screen when texts overflow the viewport no matter inputting in the middle or at the end of block.
- Cursor position goes to center of screen when clicking to edit a block
- Calling commands/page reference/block references, etc. will move the autocomplete window to center of screen
Additionally, l updated `react-textarea-autosize` since it added { rowHeight: number } as a second parameter to the onHeightChange callback from [8.2.0](https://github.com/Andarist/react-textarea-autosize/blob/main/CHANGELOG.md#820), which is used in this PR.

enhance(mobile): editing in large block

---

src/electron/electron/search.cljs

On Windows, since `:` was not sanitized, search cache of different graphs in the same drive would be pointed to the same location, then FTS would be failed
TODO: close related issues

fix: search cache contamination on windows cuz missing sanitization

---

src/main/frontend/components/page.cljs
src/main/frontend/components/sidebar.cljs

Adding data-ref for items in the left sidebar and page titles, so we can target it with custom CSS.
My specific use case is making a few pages look extra pretty with emoji, without needing to include the emoji in the actual name. Pictured here is my seedling styling (any pages that start with `S: `)

enhance(ui): add data-ref for items in left sidebar

---

package.json

Latest logseq release doesn't include the fix of https://github.com/logseq/logseq/issues/3343
Current version of `mldoc` is 1.3.0, which does not include the fix (8 days ago)... Btw, the tags of `mldoc` are not pushed to github.
https://github.com/logseq/logseq/blame/5111d59f7a6d71421f7b985d3f702c92603bee4b/package.json#L99

bump mldoc to 1.3.1

---

src/main/frontend/fs/watcher_handler.cljs

Fix #4277
For dev:
All paths should be normalized via `util/path-normalize` when read into main process

fix: missing normalized for file watcher ipc

---

src/main/frontend/modules/file/core.cljs
src/main/frontend/util/property.cljs

Fix: #4311
Move `content-with-collapsed-state` before applying indentation to content

fix: #4311 collapsed state not persisted for blocks with properties

---

src/main/frontend/handler/events.cljs
src/main/frontend/modules/shortcut/config.cljs

This PR adds a command to save the current graph to `~/.logseq/graphs`. This is useful for power users as it allows them to develop and use applications directly against the datascript db. I'm writing a personal CLI to use an updated datascript db. I added this command because the only other way I saw to persist the db was to quit the app which isn't user friendly

Add command to save graph to disk

---

src/main/frontend/db/react.cljs
src/main/frontend/handler.cljs
src/main/frontend/state.cljs

Previously, all the custom queries including both queries and advanced queries will be executed synchronously when there's any editor update, which can hurt the editing experience a lot if there were too many blocks.

enhancement: only run custom queries when not typing

---

src/electron/electron/core.cljs
src/electron/electron/handler.cljs
src/electron/electron/search.cljs
src/main/frontend/db.cljs
src/main/frontend/handler.cljs
src/main/frontend/handler/events.cljs
src/main/frontend/handler/search.cljs
src/main/frontend/search.cljs
src/main/frontend/search/browser.cljs
src/main/frontend/search/db.cljs
src/main/frontend/search/node.cljs
src/main/frontend/search/protocol.cljs

* Happens when a graph is ready to show

enhance: add :graph/ready event; check search version of each repo

---

.carve/ignore
deps.edn
docs/dev-practices.md
shadow-cljs.edn
src/test/frontend/test_runner.cljs

This adds a feature rich test runner as described in https://quire.io/w/Logseq-_team_dedicated_to_sport_of_knowledge/186/Add_a_more_featureful_test_runner. This runner provides most of the options that https://github.com/cognitect-labs/test-runner#invoke-with-clojure--m-clojuremain provides. Card contains more details on other options that were considered and ruled out. One day we should contribute this test runner to shadow so everyone can benefit

Add shadow test runner that provides most test-runner like options

---

src/main/frontend/components/right_sidebar.cljs
src/main/frontend/handler/ui.cljs

Persist right sidebar width into store just before sidebar is closed;
Restore right sidebar width from local store when sidebar is about to open

feat: remember right sidebar width after resizing

---

src/main/frontend/fs/capacitor_fs.cljs

As reported in https://github.com/logseq/logseq/issues/4399, annoying `invalid path` alert window consistently popups. This PR changes `read-file` error-catch to `log` to avoid this popup.

Avoid annoying javascript alert window for error debug

---

.carve/ignore
deps.edn
docs/dev-practices.md
package.json
shadow-cljs.edn
src/test/frontend/node_test_runner.cljs
src/test/frontend/test_runner.cljs
yarn.lock

This is a followup to #4364 to provide `--exclude` and fixes a bug which is currently effecting some tests from being run on master. We can now start writing tests like performance tests that only run at certain times :) This PR also bumps shadow-cljs. I did not see any breaking changes with [shadow's changelog](https://github.com/thheller/shadow-cljs/blob/master/CHANGELOG.md) and there are a number of bug fixes. There is a new Runtime tab under shadow builds which allow for some namespace exploration

Add --exclude to node test runner and fix testing staleness issue

---

src/main/frontend/components/search.cljs
src/main/frontend/handler/ui.cljs
src/main/frontend/modules/shortcut/config.cljs

Most of us have a number of links in our notes. It would be helpful to quickly visit them. This PR adds a keystroke `mod+o` (same keybinding for same functionality when we're editing) to open urls from the current search item. It also does some minor cleanup of the search component in the 2nd commit. I QAed refactored changes
[Demo of opening links for block and page](https://www.loom.com/share/4d89fdd1cf79409cb108e6ec092e84ac)

Feature: Open links in search with keybinding

---

src/main/frontend/handler/editor.cljs

a workaround fix for https://github.com/logseq/logseq/issues/4430

fix(android): backspace can't delete empty block

---

shadow-cljs.edn
src/test/frontend/handler/editor_test.cljs
src/test/frontend/util/marker_test.cljs

This follows up on https://github.com/logseq/logseq/pull/4382/files/c250ca7f4076280afce3ae7613a2754b4c26e04e#r815154731 to convert the tests to use `with-redefs` /cc @llcc. I also moved tests since the tested fn is in `editor-handler`.
In general, `with-redefs` is pretty useful for mocking and stubbing. If we have more complex testing scenarios, we can use something like https://github.com/circleci/bond . One caveat with `with-redefs` in cljs is that async is not supported - https://clojure.atlassian.net/browse/CLJS-884

Dev: Rewrite tests from #4382 to use with-redefs

---

src/main/frontend/components/sidebar.cljs
src/main/frontend/modules/shortcut/data_helper.cljs

Fix some UI warnings
- `Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.`
- Command register validation under mobile & browser platforms(nil vals of commands)

Fix some UI warnings

---

src/main/frontend/db/query_dsl.cljs
src/main/frontend/db/query_react.cljs

While investigating #4101, I found that the generated query is invalid and causes datascript to throw an exception. I was surprised to see that the user saw a blank table, as if nothing was wrong. This PR makes dsl query failures more explicit by displaying the "Block render error" e.g.
I think this is an improvement as the user is aware something went wrong. When they report the issue, we are able to fix the bug quicker because we know it's an unexpected failure

Fix: Display error if dsl query fails hard

---

src/main/frontend/handler/editor.cljs

fix https://github.com/logseq/logseq/issues/4397

fix(android): unable to display asset image

---

ios/App/App/FsWatcher.swift

When loading large graphs, tick function might be running for a long time. Meanwhile, the timer is already deinited.

fix(ios): nil timer in fs watcher

---

src/main/frontend/ui.cljs

`logseq.App.showMsg`notifications-content support `\n`
before:
after:

feat: ✨ notifications-content support \n

---

src/main/frontend/format/block.cljs
src/main/frontend/text.cljs

As described by @w1ndy in https://github.com/logseq/logseq/issues/4462, using `set` for properties causes the parsed pages out of order, so I removed the set function and used `instinct` to remove duplicates.
Close https://github.com/logseq/logseq/issues/4462

fix: List properties out of order when contain more than 8 elements

---

src/main/frontend/format/block.cljs
src/main/frontend/text.cljs

Reverts logseq/logseq#4470
Since it breaks query test cases. Final changes will be included in https://github.com/logseq/logseq/pull/4477

Revert "fix: List properties out of order when contain more than 8 elements"

---

package.json
resources/package.json
src/electron/electron/handler.cljs
src/main/frontend/fs/watcher_handler.cljs
static/yarn.lock
yarn.lock

Previously, files are stored to logseq/bak when logseq detects
there're differences between the db and disk. But it has two problems:
1. Only a few users know `logseq/bak`, other users think that their
data has been lost.
2. Files in the logseq/bak folder are never truncated.
This PR backups old files in DB with timestamp suffixes instead of
logesq/bak, and only keep the latest 10 versions of any changed file.

enhance: backup files when there're differences between db and disk

---

src/main/frontend/db/model.cljs
src/main/frontend/db/rules.cljs

Fix: https://github.com/logseq/logseq/issues/4362
According to [This Stackoverflow answer](https://stackoverflow.com/a/42470020), it's better to bind the child of the ancestor if we want to find the descendants of some node.
Intuitively, it's to avoid the case that both variables in a rule are unresolved. E.g, when `?p` is given, we should use `[?t :block/parent ?p]` instead of `[?c :block/parent ?t]`
[REFERENCE: Clause order](https://docs.datomic.com/on-prem/query/query-executing.html#clause-order)
Should double confirm the internal detail of datascript? Should overhaul and re-order all queries?

Optimizing nested query rules for graph traversal

---

src/main/frontend/components/block.cljs

close https://github.com/logseq/logseq/issues/3281

fix: id link in orgmode format

---

src/main/frontend/format/block.cljs
src/main/frontend/handler/page.cljs

When creating a `demo` Excalidraw file from commands, two pages `Draws` and `Draws/demo.Excalidraw` are created unexpectedly. `Draws` page should not be created, and both of them should not appear in `All Pages` and `Graph View`.  Also, when uploading an PDF asset, similar problem exists. 
This PR fixed the above issue.

fix: remove assets/draws from All Pages

---

src/main/frontend/components/block.cljs

This PR implements block-embed alias in OrgMode, which is already supported in markdown format.
The syntax is `[[((6225c04c-1d8f-47a2-9a5c-76be21fe8fd2))][label]]`.
Close https://github.com/logseq/logseq/issues/4111

feat: support block-embed alias in OrgMode

---

libs/src/LSPlugin.core.ts

I spent a good amount of time trying to trace functions things like `provideStyle()`, and I didn't figure out how to trace the event until today, since its listener is added using string concatenation. This PR adds a few comments with the full event name, so it's easier to trace in the code for future programmers.
Until we have comprehensive documentation for plugin developers, this will help out the people who don't mind looking at the code itself.

Add comments near plugin event listeners to make events more searchable

---

src/main/frontend/db/query_dsl.cljs
src/main/frontend/db/rules.cljs
src/test/frontend/db/query_dsl_test.cljs

This PR is a follow up to https://github.com/logseq/logseq/pull/4420 that fixes https://github.com/logseq/logseq/issues/4101. This PR also converts all search operators to use rules, tests were added for 5+ operators that weren't tested before and the query dsl namespace and tests are easier to read and maintain as they are split into smaller logical chunks. Unless I've noted otherwise, I strived to not change any logic that would effect existing behavior

Fix: task and priority query bug

---

src/main/frontend/db/query_react.cljs

Fix #4520
`(t/yesterday)` is a DateTime object.

fix(query): yesterday should be a date

---

.carve/ignore
.clj-kondo/config.edn
scripts/src/logseq/tasks/dev.clj
shadow-cljs.edn
src/main/frontend/db/query_custom.cljs
src/main/frontend/db/query_dsl.cljs
src/main/frontend/db_mixins.cljs
src/main/frontend/extensions/srs.cljs
src/main/frontend/handler.cljs
src/main/frontend/util/datalog.cljc
src/test/frontend/db/config.cljs
src/test/frontend/db/model_test.cljs
src/test/frontend/db/outliner_test.cljs
src/test/frontend/db/query_custom_test.cljs
src/test/frontend/db/query_dsl_test.cljs
src/test/frontend/modules/outliner/core_test.cljs
src/test/frontend/modules/outliner/ds_test.cljs
src/test/frontend/react_test.cljs
src/test/frontend/test/fixtures.cljs
src/test/frontend/test/helper.cljs
src/test/frontend/test/node_test_runner.cljs
src/test/frontend/util/datalog_test.cljs

Following up on https://github.com/logseq/logseq/pull/4420#discussion_r817182905, this PR allows a user to use any of the [query-dsl-rules](https://github.com/logseq/logseq/blob/d8bc074be17d3e4c1b780f9ce08e15f2f45193a6/src/main/frontend/db/rules.cljc#L61) in advanced queries and it will seamlessly work e.g. https://github.com/logseq/logseq/blob/ed6a02c6921f6605d6c2482ca013f81de9c16b01/src/test/frontend/db/query_custom_test.cljs#L26-L29 . The ability to pull in rules dynamically will make advanced queries much easier to read and should allow for interesting and powerful query composition. There are other powerful features we could enable with this ability e.g. allow users to define rules in their config and pull them in as they would like. I'll see if I can get some feedback from users. …

Feature: Use query-dsl rules from advanced query

---

android/app/build.gradle
resources/package.json
src/main/frontend/version.cljs

This is the preparation for the v0.6.3 release.

chore: bump version 0.6.3

---

src/main/frontend/components/block.css

During the development of the theme, I found that the selector of `cloze` didn't correspond to the actual tag.

fix: cloze selector

---

deps.edn

SCI has moved to a new organization: `org.babashka/sci {:mvn/version "0.3.2"}`.
Having both `borkdude/sci` and `org.babashka/sci` on the classpath can cause problems.

Upgrade SCI

---

src/main/frontend/components/block.cljs
src/main/frontend/components/page.cljs
src/main/frontend/db/query_react.cljs
src/main/frontend/ui.cljs

This fixes #4539 where two users had shared default-queries that were causing their home screen to crash. This PR also improves the error handling of default-queries so that any future errors render an inline error instead of blanking the screen like:
This PR also introduces a reusable block-error component and uses it when advanced queries fail to parse correctly. Before it looked like:
and now the error looks like:
If we like this block-error component, I could use it in a couple more places where we render blocks errors with `div.warning ...`

Fix blank screen on home page

---

docs/dev-practices.md
src/test/frontend/test/node_test_runner.cljs

This PR adds some node test runner improvements after working with #4540. The test runner now prints stack traces on a failure and we can compose multiple test options as seen in the dev-practices doc. This PR also adds some docs on datalog linting I forgot to add for #4503

Dev: Node test runner improvements

---

src/main/frontend/components/block.cljs
src/main/frontend/format/mldoc.cljs
src/main/frontend/text.cljs
templates/config.edn

Demo: https://www.loom.com/share/d08f355e2a964ffe87c40f1aea26a325

fix #+keyword issues in orgmode

---

src/main/frontend/util/marker.cljs
src/test/frontend/util/marker_test.cljs

This PR changes the regex of a markdown header to `#+\s+`, it's more accurate than `#*\s*` because a markdown header should always have at least one `#` and one space.
So it can close #4588 due to `#xxx` won't being matched anymore.

fix: cycle marker will remove `#` unexpectedly

---

src/main/frontend/components/block.cljs
src/main/frontend/db/model.cljs
src/main/frontend/handler/editor.cljs
templates/config.edn

This PR introduces a new option `:outliner/block-title-collapse-enabled?` to bring back the old collapse behavior.
**Notice**: it's disabled by default.
Fix https://github.com/logseq/logseq/issues/4583
https://www.loom.com/share/eea40ca4853142e9b95050c83aa64db4

Add a configuration option to support the previous collapse behavior

---

src/main/frontend/db/query_dsl.cljs
src/main/frontend/db/rules.cljc
src/main/frontend/extensions/srs.cljs
src/main/frontend/ui.cljs
src/test/frontend/db/query_custom_test.cljs
src/test/frontend/db/query_dsl_test.cljs

This PR fixes a couple bugs caused by our use of lookup refs in queries and rules which is [not recommended by datomic](https://docs.datomic.com/on-prem/schema/identity.html#:~:text=You%20can%20use%20lookup%20refs%20to%20retrieve%20entities%20using%20the%20entity%20and%20datoms%20using%20the%20datoms%20and%20seek%2Ddatoms%20APIs.%20You%20cannot%20use%20them%20in%20the%20body%20of%20a%20query%2C%20use%20datalog%20clauses%20instead.):
- page-ref (and page) rules were unable to bind to args as reported in https://github.com/logseq/logseq/pull/4518#issuecomment-1068743086
- For nonexistent lookups, queries failed hard of instead gracefully returning empty. This caused the following issues
- srs query reported `"Nothing found for entity id [:block/name \"card\"]"` as can be seen in #4576 
- …

Fix: Query fixes related to use of lookup refs

---

e2e-tests/editor.spec.ts
src/main/frontend/handler/editor.cljs

The shortcut for "mod+shitf+c" no longer works after https://github.com/logseq/logseq/pull/2889.
Also tried to add a test for this case, but failed to find out the reason why ClipboardItem is not defined when running with playwright 😅

fix: replace-block-reference-with-content-at-point not working

---

src/main/frontend/components/repo.cljs

Replace `repos` with `repo-links`.
After the change, the `<hr />` will not be displayed if there is only one repo.

fix: use the correct variable in (seq coll)

---

.github/workflows/build.yml
src/main/frontend/db/query_custom.cljs
src/test/frontend/db/query_custom_test.cljs
static/yarn.lock

This PR fixes advanced queries that take rules and have rules that are provided by logseq. This scenario fails hard currently. I found this while I was about to give the author of #4555 a way to use their rules as desired. There is low risk with this change as the query-custom ns is well tested
I also found that our static/yarn.lock was outdated so I put in a CI check which catches the error as [this job demonstrates](https://github.com/logseq/logseq/runs/5602407221?check_suite_focus=true)

Fix: rules to advanced query and outdated yarn.lock

---

src/main/frontend/modules/instrumentation/sentry.cljs

I was QAing #4618 and noticed that platform was not showing up as a sentry tag. Docs don't mention a platform option but they do mention an [initialScope](https://docs.sentry.io/platforms/javascript/guides/react/configuration/options/#initial-scope) option which sets [tags](https://docs.sentry.io/platforms/javascript/guides/react/enriching-events/tags/). Here are examples of the issues [before the PR](https://sentry.io/organizations/logseq/issues/3114529645/?environment=development&project=5311485&query=is%3Aunresolved+OOPS&statsPeriod=14d) and [after the PR](https://sentry.io/organizations/logseq/issues/3114531129/?environment=development&project=5311485&query=is%3Aunresolved+OOPS&statsPeriod=14d). I also added mobile to platform and added publishing as another tag to allow for more …

Fix sentry platform not showing up on issues

---

android/app/build.gradle
resources/package.json
src/main/frontend/version.cljs

Prepare for the v0.6.4 release.
- ~~[ ] https://github.com/logseq/logseq/pull/4580~~
**UPDATE**
#4580 will be excluded from 0.6.4.

Chore: bump version 0.6.4

---

src/main/frontend/components/block.cljs
src/main/frontend/components/journal.cljs
src/main/frontend/components/page.cljs
src/main/frontend/components/reference.cljs
src/main/frontend/ui.cljs

In #4576, a user's screen went blank due to the references component failing in irreproducible way and then went on to experience secondary and tertiary errors that were strange. A failing references component now looks like:
This PR adds a `ui/catch-error` to at least give the user a degraded but graceful error. We should consider using more of these for at least the journals/home view so that small errors result in blank startup experiences.
This PR also introduced component-error and fixed `custom-query` not catching its error

Enhance: Gracefully fail references component and other small error improvements

---

src/main/frontend/components/block.cljs
src/main/frontend/components/editor.cljs
src/main/frontend/handler/editor.cljs
src/main/frontend/util/marker.cljs
src/test/frontend/handler/editor_test.cljs

This PR is a follow-up to #4589.
Originally I wanted to add some tests to `replace-marker`, but I found that `replace-marker` and `add-or-update-marker` actually have a logical overlap, so I tried to simplify `cycle-marker` with `add-or-update-marker` because it is more obviously a more generic processing function.
And this PR also fixes a mistake...in #4589, I was in a hurry to fix the test but missed that it actually defied the final application logic. This causes the non-header block to fail to change from `LATER` to `NOW` during the cycle.

refactor: rearrange cycle-marker

---

src/main/frontend/extensions/code.cljs

fix(code): avoid calling .focus when editor close

---

.gitignore
src/electron/electron/git.cljs

Related to #4620, partially fixed (the `.git` file got removed every time)

fix: always trigger removing  file of separate git dir

---

src/main/frontend/components/page.cljs

This minimal change sorts the 'Pages tagged with' list on each tag page alphabetically.

Sort 'Pages tagged with' list alphabetically

---

src/main/frontend/handler/editor.cljs

Resolve #4688.
The old implementation has a condition `(util/uuid-string? page)`, which will always return `nil` because `page` is the name of a page.
But I'm not sure if I need to change anything else, if so please let me know. 😃

fix: detect the first block in a page

---

.github/workflows/build-android.yml
.github/workflows/build-desktop-release.yml
src/main/frontend/modules/instrumentation/sentry.cljs

Fix #4613
- hijack sentry report, hide path, replace with mock URL
- fix sourcemap lineno offset(no idea of why there's a 2-line offset)
to review: https://sentry.io/organizations/logseq/issues/3127186378/?project=5311485&query=release%3Alogseq%400.6.4-local+platform%3Aelectron&statsPeriod=14d

fix(build): sourcemap in release

---

android/app/build.gradle
resources/package.json
src/main/frontend/version.cljs

Prepare for 0.6.5 release. This will be a release focusing on bug fixes.

chore: bump version 0.6.5

---

src/main/frontend/extensions/srs.cljs

I confirmed the A button works for all cards and for a card query

Fix clicking on all in srs cards - close #4687

---

.github/workflows/build-desktop-release.yml

`npm_config_arch=arm64` also afffects electron-forge. so dugite should be fixed additionally.
`--ignore-platform` is added to allow future development on node napi.

fix(build): deps for macos arm64 build

---

src/main/frontend/components/block.cljs
src/main/logseq/api.cljs

Should also pass in the `config`, which contains block/uuid context.
When rendering plugin-provided content (`{{renderer xxx}}` macros) via `onMacroRendererSlotted` API, there will be the arguments and the current blocks' `uuid` . i.e., the following is the type.
```ts
onMacroRendererSlotted: IUserSlotHook<{
payload: {
arguments: Array<string>;
uuid: string;
[key: string]: any;
};
}>;
```
Internally, the `onMacroRendererSlotted` hook will register a render callback to let the core get the custom content provided by plugins. Reference: https://github.com/logseq/logseq/blob/1987d7dc79dcb78453cfcd49b1f9d8c7b3656001/src/main/frontend/components/block.cljs#L1269-L1270
For renderer macros, they will be rendered with `inline-text` fn:
https://github.com/logseq/logseq/blob/1987d7dc79dcb78453cfcd49 …

fix: renderer not rendering in page/block property properly

---

src/main/frontend/components/page.cljs

Reorder `ui/catch-error` and `rum/with-key` 
To fix the following:
Never mind, this is a dev-only warning.

fix(dev): missing today queries key

---

src/main/frontend/components/header.cljs
src/main/frontend/components/sidebar.cljs
src/main/frontend/extensions/code.cljs
src/main/frontend/state.cljs

Disable the following functionalities for the published graph
- settings
- import
- recent
- code editor will be read only

fix: disable some functions for published graph

---

deps.edn
src/main/frontend/components/block.cljs
src/main/frontend/components/settings.cljs
src/main/frontend/ui.cljs

During local development, there are some "Each child in a list should have a unique "key" prop." errors popping up in the console log.
It seems that the main issue is that the adapted components via `rum/adapt-class` will always treat the passed children as an element in an array. This is the reason why they are appended with the key prop for tippy/resize etc.
Also, upgrade Rum version to the latest to support React fragements.

fix: some unique "key" prop issues

---

src/main/frontend/page.cljs
src/main/frontend/ui.css

This PR adds a root error screen for when the app fails unexpectedly, as described and mocked up in https://quire.io/w/Logseq-_team_dedicated_to_sport_of_knowledge/614/UI_Error_Screen?sublist=Cycle2&view=board . Instead of a blank screen when our app fails, we now see this:

Enhance: Add error screen for root component

---

.github/workflows/build.yml
e2e-tests/editor.spec.ts
e2e-tests/util/keyboard-event-cap.html
e2e-tests/util/keyboard-events.ts

Addressing complicated IME / locale / layout related issues like #3741 #3760
Previous PR addressing such cases: https://github.com/logseq/logseq/pull/3478
- Expect: Show `【` at first then autocomplete to `[[]]` at the second type-in
* `clojure -M:cljs compile app`
- Expect: Can type and search Chinese
- Expect: Can search pages
- Expect: Can search commands
- Expect: No autocomplete happens
- Expect: Show `「` only, instead of `[「]`
- Expect: Show `99`

test(e2e): add keyboard event simulation

---

src/main/frontend/util.cljc

fix https://github.com/logseq/logseq/issues/4685

fix: preview image file with capitalized extension

---

src/main/frontend/handler/page.cljs

occurs when creating a new page in autocomplete menu if `org-mode/insert-file-link?` non-nils.
fix https://github.com/logseq/logseq/issues/4732

fix redundant relative path when inserting orgmode page reference

---

src/main/frontend/components/block.cljs
src/main/frontend/handler/editor.cljs

demo: https://www.loom.com/share/1cbe9d386b9f4b13950a66494b088aa6
limitation: The toggle item should be distinct in a block 
partially fixed https://github.com/logseq/logseq/issues/3617.

feat(list): enable checkbox toggle

---

src/main/frontend/components/onboarding.cljs
src/main/frontend/mobile/intent.cljs
src/main/frontend/page.cljs
src/main/frontend/ui.cljs

I saw this change in our discord channels and think it'd be useful to have this in app as well. Currently users don't see any helpful template when reporting from the app

Enhance: Better issue links

---

e2e-tests/basic.spec.ts
e2e-tests/code-editing.spec.ts
e2e-tests/editor.spec.ts
e2e-tests/fixtures.ts

In this PR:
- Add `block` fixture to e2e test suite
- Refactor some `basic` tests with the `block` fixture
- Fix some occasional failures
New-style e2e testing:
```typescript
test('example', async ({ page, block }) => { // introduce the block fixture
await createRandomPage(page)
// add 3 blocks
await block.mustFill('line 1') // fill a block and assure text is really there
await block.enterNext() // press Enter and go to next block
await block.mustType('line 2') // type some text into a block, with default 100ms delay(simulates user typing)
await block.enterNext()
expect(await block.indent()).toBe(true) // indent block, and check block is indented
expect(await block.indent()).toBe(false) // can not indent more
await block.clickNext() // use click methd to create a new block
await …
```

refactor(e2e): add block fixture helpers

---

src/main/frontend/components/block.cljs

Fix #4843
The original bug affects Level 1 and Level 2 headings.
This is a temporary fix. The root cause is 
When expanding from a template, `:block/type` property is missing.
Logseq allows a text block to become a heading, so the condition should use `or`.

fix(ui): wrong condition for rendering heading

---

src/main/frontend/handler/events.cljs

Fix #4877
Introduced in c37b5bd62248fa7a0e05f2ebcbb94e09311fdfea
Fixed by adding restoring to graph-switch.

fix(mobile): page blank when switching graph

---

src/main/frontend/components/editor.cljs

This PR enables dynamically adjusting the commands icons of mobile toolbar. 
demo: https://www.loom.com/share/288b357f586c46cbba86e8c03a43f79c
The first five icons are fixed, while others are dynamically reordered based on the usage frequency. Also, the counts are saved in config file.

feat(mobile): dynamically reorder toolbar commands by click counts

---

src/main/frontend/extensions/srs.cljs

Hi, I find a problem with the flashcard feature. I have used flashcards for a while. When I have 500+ cards, I cannot review all the cards one day, so I have to review part of it. The problem is that the cards at the bottom of the review card set which I left for tomorrow, still seem to be at the bottom of the card set tomorrow. If I cannot review all the cards once, it seems that the bottom part of the card will never be reviewed.
So I check the source code and find that I can easily solve this problem by modifying the 'query-scheduled' function in the 'src/main/frontend/extensions/srs.cljs' path.
I have tested it. It seems to be OK. So I post this PR.
I also posted a discussion in the forum, please check https://discuss.logseq.com/t/sort-the-flashcards/6540
Signed-off-by: FelixGibson …

Feature: sort the flashcard by the ':card-next-schedule' property

---

src/main/frontend/components/page.cljs

As shown in the following screenshot:

fix: increase `td` width to prevent content overflow

---

src/main/frontend/components/block.cljs

This PR fixes `show-brackets` setting toggle for Org-mode page reference, e.g. [[file:./pages/demo.org][demo]].

enable show-brackets? toggle for Org-mode page reference

---

src/electron/electron/core.cljs
src/electron/electron/fs_watcher.cljs
src/electron/electron/handler.cljs
src/electron/electron/state.cljs
src/electron/electron/url.cljs
src/electron/electron/utils.cljs
src/main/electron/listener.cljs
src/main/frontend/components/content.cljs
src/main/frontend/components/page_menu.cljs
src/main/frontend/components/repo.cljs
src/main/frontend/db.cljs
src/main/frontend/db/conn.cljs
src/main/frontend/db/model.cljs
src/main/frontend/dicts.cljc
src/main/frontend/handler/events.cljs
src/main/frontend/handler/repo.cljs
src/main/frontend/handler/ui.cljs
src/main/frontend/util/url.cljs

The `open` action of logseq protocol would open the target in a new logseq window. For example:
logseq://local/open?graph=lambda will open graph `lambda`.
This PR only covers local graphs
- Open block with uuid:
- `logseq://graph/<graph name>?block-id=<block uuid>`
- Open graph:
- `logseq://graph/<graph name>`
- Open page:
- `logseq://graph/<graph name>?page=<page name>`
* Works on Desktop (Electron) only for now. Logseq should be OPEN, and the target graph should be LINKED before-hand.
* Parameter `graph` would match graph name from the existing graphs. Full graph path is not required.
* Parameter `page` receives page name. You may need to use [URL Encode](https://www.google.com/search?q=URL+encode) if your page name contains spaces or special characters.
* Parameter `block-id` receives …

Feat: open action for logseq protocol 

---

src/main/frontend/handler/repo.cljs

Logseq creates a new contents file when users try to change the preferred format, which causes files duplication error.
fix https://github.com/logseq/logseq/issues/4763

don't create new contents file when changing format

---

src/main/frontend/handler/editor.cljs

close https://github.com/logseq/logseq/issues/4914

fix pasting in src block not working on iOS

---

src/main/frontend/components/editor.cljs

fix https://github.com/logseq/logseq/issues/4912
This also solved the toolbar state sync across devices.

fix mobile toolbar order not persisting after restart

---

.github/workflows/build.yml
e2e-tests/basic.spec.ts
e2e-tests/editor.spec.ts
e2e-tests/fixtures.ts
e2e-tests/hotkey.spec.ts
e2e-tests/utils.ts

- add cursor position to `block` test fixture
- a minor enhancement to `mustType` helper fn
- fix `waitForBlocks` helper
- enhance CI, one pass build
- add a test for backspace and check cursor pos (Fails, which is a bug for now)
**NOTE**: disable tests for #4897

test(e2e): add test for backspace and cursor pos

---

src/main/frontend/components/settings.cljs

fix(ui): warn about illegal git commit interval

---

src/main/frontend/components/shell.cljs
src/main/frontend/modules/shortcut/config.cljs

- git command should be available globally
- use mono-font

enhance(editor): allow global git cmd shortcut

---

src/main/frontend/components/block.cljs

Fix #4959
Introduced in #4766
Affects 0.6.6

fix(editor): missing variable in macro expansion

---

src/main/frontend/extensions/code.cljs

Related to https://github.com/logseq/logseq/pull/4776
Referred to https://github.com/codemirror/CodeMirror/issues/2568

fix: code block in published graph is not copyable

---

src/main/frontend/components/block.cljs

This will allow users to put custom macros etc into the title. e.g.,
```
#+BEGIN_QUERY
{:title "{{poem 123}}"
:query ...}
#+END_QUERY
```
will render as

feat: custom query title may also render rich texts

---

ios/App/App.xcodeproj/project.pbxproj
src/main/frontend/components/settings.cljs

Since iOS app is already on AppStore now, better to add version info back in the settings panel. 
BTW, iOS version will follow the desktop's from now on.

display version info on mobile

---

src/main/frontend/util.cljc

try to resolved https://github.com/logseq/logseq/issues/4967

fix(utils): classname utils for string input

---

src/electron/electron/core.cljs
src/electron/electron/url.cljs
src/electron/electron/window.cljs
src/main/electron/listener.cljs

Now the `graph` action of Logseq protocol will try to open the target in a running window on that graph if exists;
The `new-window` action always open the target in a new window.

feat: logseq protocol non-darwin OS support; open in running window if exist by default

---

src/main/frontend/handler/editor.cljs
src/main/frontend/modules/shortcut/config.cljs
src/main/frontend/modules/shortcut/dicts.cljc
src/main/frontend/util.cljc
src/main/frontend/util/cursor.cljs

Relate to #4346.
The new smooth-select action will select lines until you hit the top/bottom of the block, and then it starts selecting whole blocks.
I feel that it is risky to change the default keymap, so I just leave these new actions **unbound**.

enhance(edit): add smooth-select action

---

src/main/frontend/components/block.cljs
src/main/frontend/db/query_react.cljs
src/main/logseq/api.cljs

1. allow plugins to pass in `:today` etc in `logseq.DB.datascriptQuery`
```js
logseq.DB.datascriptQuery(
`[:find (pull ?h [*])
:in $ ?start ?next
:where
[?h :block/marker ?marker]
[?h :block/refs ?p]
[?p :block/journal? true]
[?p :block/journal-day ?d]
[(> ?d ?start)]
[(< ?d ?next)]]`,
":today",
":7d-after"
);
```
2. fix a display issue of query DSLs

feat: resolve datascript query inputs with Logseq DSL for plugins

---

src/main/frontend/modules/shortcut/config.cljs

This PR makes it possible to add shortcuts to open current file in directory or to open file in default app. 
The shortcuts used are
`mod+d` open file in default app
`mod+shift+d` open file in directory
It appears as if this functionality used to be there but was removed. 
The shortcuts were previously: 
`o d` open file in default app
`o f` open file in directory
This is another option. Curious as to the reasoning for removal of tihs shortcut. Was there a bug that necessitated the removal?

add shortcuts for opening file in default app and directory

---

src/main/frontend/extensions/pdf/highlights.cljs
src/main/frontend/page.cljs
src/main/frontend/ui.cljs

* To help users to locate errors, prompt up error notification when error caught by `helpful-default-error-screen`, instead of printing to console only.
* Add error notification for `InvalidPDFException`
Close #4986
* The CI looks broken. Fixed it by switching the jdk distribution

ui: capture invalid pdf error

---

src/main/frontend/util/clock.cljs

Current implementation doesn't calculate hours correctly. E.g., for logbook records `0:30:30` and `0:29:30`, it would return `00:00:00`.

Fix logbook clock-summary

---

src/main/frontend/components/block.cljs

Update block.cljs. Fix mailto link wrong.
See [Issue 5080](https://github.com/logseq/logseq/issues/5080)

fix error in mailto Link

---

e2e-tests/page-rename.spec.ts
e2e-tests/utils.ts
src/main/frontend/db/model.cljs
src/main/frontend/handler/editor.cljs
src/main/frontend/util/thingatpt.cljs

Fix https://github.com/logseq/logseq/issues/4695
Known issue: doesn't support front-matter or using org style properties in markdown

fix: auto save on editing properties

---

src/main/frontend/util/clock.cljs

Ref: https://discuss.logseq.com/t/logbook-clock-can-be-measured-in-days-automatically/7021.
Now it looks like:
In addition to rendering `days`. This PR also reduces the calculation and uses `seq` to fix the check if clock-lines is empty.

perf: optimize the calculation of clock-summary

---

src/main/frontend/modules/shortcut/config.cljs
src/main/frontend/modules/shortcut/dicts.cljc

enhance(ux): support idiomatic shortcut `ctrl+n` for auto-complete navigation

---

src/main/frontend/modules/shortcut/config.cljs

Follow up to #5202 which adds the same keybindings to datepicker and editor so that logseq consistently provides emacs keybindings

Enhance: Adds emacs keybindings to other up/down movements

---

src/main/frontend/handler/editor.cljs
src/main/frontend/mobile/footer.cljs
src/main/frontend/mobile/intent.cljs
src/main/frontend/mobile/record.cljs

Also, set `edit-block?` to false for some functions.

fix: editing empty last block if `:replace-empty-target?` non-nils

---

src/main/frontend/extensions/excalidraw.cljs

Normally occurs when a markdown/org file is imported.

fix(draw): invalid dom element

---

src/test/frontend/modules/outliner/core_test.cljs

Disabled two tests until they pass more consistently. Recent failures:
* random-move-up-down
* https://github.com/logseq/logseq/runs/6325507011?check_suite_focus=true
* https://github.com/logseq/logseq/runs/6322301680?check_suite_focus=true
* random-indent-outdent
* https://github.com/logseq/logseq/runs/6296408756?check_suite_focus=true
* https://github.com/logseq/logseq/runs/6296698299?check_suite_focus=true

Disable two outliner tests which fail intermittently the most

---

resources/package.json
src/electron/electron/file_sync_rsapi.cljs
yarn.lock

This update includes the following:
- avoid refreshing temp credential
- downgrade build platform
- do not link to libssl, fix error on some Linux platforms

fix(sync): update rsapi to 0.0.9

---

src/main/frontend/components/command_palette.css
src/main/frontend/ui.cljs

Close #3773.
This is a bare fix because 
- The style changed in a minimal modified-code way instead of proper CSS adjustment.
- The original need was to fix the command-palette instead of all `auto-complete`.
The idea here is to **split** *hover* and *focus* status handling. After some searches, I figured out that changing the focus item via mouse needs some ugly [workarounds](https://stackoverflow.com/questions/16529807/mousemove-event-is-triggered-onscroll-even-when-mouse-was-not-moved-on-chrome?rq=1), and the behavior may not be a common need. We could just style the hovered item and leave the active item unchanged, e.g. [vuetify](https://vuetifyjs.com/en/components/autocompletes/).
Feel free to modify/reject it.

enhance(ui/auto-complete): split hover and focus status

---

src/main/frontend/components/block.cljs
src/main/frontend/format/block.cljs
src/main/frontend/handler/editor.cljs
src/main/frontend/handler/extract.cljs
src/main/frontend/handler/page.cljs
src/main/frontend/modules/file/core.cljs
src/main/frontend/util.cljc
src/test/frontend/handler/repo_test.cljs

We shouldn't convert reserved chars for page names, those rules are only limited to file paths.
Now page names will be url-encoded when creating a new file, which means in theory we don't need to save a namespace page `a/b` as an `a.b.md` file. But removing the `.` hack now could result in namespace pages not being recognized if there's no title property in the markdown/org file. In the future, we might need to provide a way to allow users to convert those `.` files to the `url-encoded` version.
Fix #5171

fix: missing title properties when page name contains `/` or reserved chars

---

resources/package.json

Fix Windows crash.
Fix Linux crash warning on libssl missing.
- revert to old napi-rs
- rm native-tls
See-also: https://github.com/napi-rs/napi-rs/issues/1175
Fix #5263
Close #5154
Close #4956

fix(build): update rsapi to resolve windows crash

---

package.json
resources/css/common.css
src/main/frontend/components/block.cljs
src/main/frontend/components/journal.cljs
src/main/frontend/components/page.cljs
src/main/frontend/components/reference.cljs
src/main/frontend/db/model.cljs
src/main/frontend/db/react.cljs
src/main/frontend/handler/editor.cljs
src/main/frontend/ui.cljs
yarn.lock

https://github.com/joshwnj/react-visibility-sensor is used to render components only when they go in the window viewport.
So we can use it to only render components (including both block list and even blocks themselves) if needed.
https://www.loom.com/share/38194babccc54430a138b37c9406e3f0

Performance improvements for pages with many linked references

---

android/app/capacitor.build.gradle
android/app/src/main/assets/capacitor.plugins.json
android/capacitor.settings.gradle
ios/App/Podfile
package.json
src/main/frontend/components/block.cljs
yarn.lock

Since PDF support on mobile still needs some work to do, I added a feature that allow users to open their pdf assets with external PDF viewers. 
Also, fixed the bug that PDF link is displayed as empty text.
Tested on iOS and Android.
demo: https://www.loom.com/share/c7b7a5395d7d44b4bc5b5b8f4935d775

open PDF with external app on mobile

---

resources/package.json

chore: update electron-deeplink to 1.0.10 to fix deeplink on Linux

---

src/main/frontend/components/editor.cljs

fixes #5162
Getting the width of editor from textarea element is not reliable sometimes, especially when there are code blocks in it.
This pr tries to fix the position by getting the width from `.editor-wrapper`. iirc, the element with this class represent the current active block area and it seems to be unique which should be safe to get the editor width(I Hope).

fix: modals positions once again

---

src/main/frontend/components/block.cljs
src/main/frontend/components/block.css
src/main/frontend/config.cljs
src/main/frontend/mobile/intent.cljs
src/main/frontend/ui.cljs

Following up to PR https://github.com/logseq/logseq/pull/5283, this PR allows users to share office files (word, excel, ppt, etc.) into Logseq assets directory on mobile. 
Also, users can open those file links by using their favorite external app.

allow sharing office files into Logseq on mobile

---

src/main/frontend/components/block.cljs

fix(ui): wrong position of page preview tip

---

src/main/frontend/components/block.css

closes #5273 
closes #5198 
Before: 
After
Also prevents minor clipping of code block background in some cases

fix(blocks): scrollbar appearing with code block and some latex 

---

src/main/frontend/components/sidebar.cljs
src/main/frontend/fs/sync.cljs
src/main/frontend/handler/file_sync.cljs
src/main/frontend/state.cljs

when "switch to" a remote graph: 
show a download progress bar, just like current parsing-progress-bar

enhance(sync): add progress-bar when init-download remote graph

---

src/main/frontend/ui.cljs

This PR fixes an error due to the introduction of #4741. After the fix, in the first rendering, the old theme that has been set will not be replaced by the new rendering mechanism.

fix: load legacy theme

---

src/main/frontend/mobile/intent.cljs

If the shared filename contains special chars (e.g. `.`, `#`, etc), the page is inserted or not loaded correctly by Logseq, this PR fixes this issue.
Close https://github.com/logseq/logseq/issues/5351

fix: file share issue if the filename contains special chars

---

android/app/src/main/java/com/logseq/app/FsWatcher.java
ios/App/App/FileSync/Extensions.swift
ios/App/App/FileSync/FileSync.swift
ios/App/App/FsWatcher.swift
src/electron/electron/fs_watcher.cljs
src/electron/electron/utils.cljs
src/main/frontend/handler/web/nfs.cljs
src/main/frontend/util/fs.cljs

This PR is to fix the following:
- changes in assets directory are not notified

fix(fs-watcher): notify all graph files, skip reading non-text

---

src/main/frontend/commands.cljs
src/main/frontend/components/block.cljs
src/main/frontend/handler/editor.cljs
src/main/frontend/mobile/intent.cljs
src/main/frontend/util.cljc
src/main/logseq/graph_parser/text.cljs

This PR adds a `{{video url}}` macro to allow Logseq to embed more video URLs.
Use `Mod+Shift+V` to wrap clipboard URL as `{{video url}}`.
This macro replaces `youtube`, `vimeo` and `bilibili` macros.
Users can still use above macros in logseq for backward compatibility, 
but they can't access those commands from the commands menu anymore.

feat: add macro `video` to embed various video URLs

---

shadow-cljs.edn
src/main/frontend/components/block.cljs
src/main/frontend/components/sidebar.cljs
src/main/frontend/db/model.cljs
src/main/frontend/modules/outliner/core.cljs
src/main/frontend/util.cljc

This PR fixed data loss when moving or cutting non-consecutive blocks from linked references or queries.
Close #5267
It also introduces a new feature:
Cmd+click to select multiple non-consecutive blocks.
Demo:
https://www.loom.com/share/b993678f5f8f477b97b4ffa78e9383c6

Fix moving or cutting non consecutive blocks

---

android/app/build.gradle
resources/package.json
src/main/frontend/version.cljs

NOTE:
0.6.10 is abandoned and skipped, since it has a serious data-loss bug.

chore(release): bump version 0.7.0

---

src/main/frontend/components/block.cljs
src/main/frontend/components/theme.css

As the title.
Use `inline-flex.items-center` to prevent the hard code styles.

style: optimize block alignment

---

package.json
src/main/frontend/extensions/calc.cljc
src/test/frontend/extensions/calc_test.cljc
yarn.lock

This PR should improve the output of float numbers:
Old behavior: `3.3 - 1.1` --> 2.1999999999999997
New behavior: `3.3 - 1.1` --> 2.2
This is my first attempt at Clojure, so any feedback welcome!

Calculator: improved output of float numbers

---

src/main/frontend/extensions/html_parser.cljs
src/main/frontend/extensions/zotero/extractor.cljs
src/main/frontend/handler/common.cljs
src/main/frontend/handler/editor.cljs
src/main/frontend/modules/shortcut/config.cljs
src/main/frontend/modules/shortcut/dicts.cljc

This makes it easier to copy && paste content from Logseq and other tools like Google Docs.
Demo:
https://www.loom.com/share/22ea6a3c1d964b68b726da5f0ac3fcb8

Feat: copy && paste with rich-text formats

---

src/electron/electron/core.cljs

- Add Documentation link to the Help menu (previous an "(empty)")
- Better handling of "About" (only macOS have a native about dialog)
Fix #5438

feat(electron): refine app menu

---

src/main/frontend/components/export.cljs
src/main/frontend/handler/common.cljs
src/main/frontend/util.cljc
src/main/frontend/utils.js

Allow using "Paste and match style" outside Logseq App.
Avoid setting HTML as plain text, which will be recognized wrongly by an external editor.

fix(editor): copy with both plain and rich text

---

resources/package.json

This fixes startup runtime errors under specific Windows platforms (lacking VC++ 2015 runtime, ARM Windows machines)
Fix #5467
Fix #5167 
static link to vcruntime, remove `vcruntime140.dll` dependency:
```console
> rabin2 -l rsapi.win32-x64-msvc.node
[Linked libraries]
advapi32.dll
bcrypt.dll
ntdll.dll
kernel32.dll
ws2_32.dll
shell32.dll
ole32.dll
api-ms-win-crt-runtime-l1-1-0.dll
api-ms-win-crt-string-l1-1-0.dll
api-ms-win-crt-stdio-l1-1-0.dll
api-ms-win-crt-convert-l1-1-0.dll
api-ms-win-crt-heap-l1-1-0.dll
```

fix(deps): link static vcruntime under windows

---

src/main/frontend/components/block.cljs
src/main/frontend/components/right_sidebar.cljs

- Why are big shadows bad for cards? #card  
- They take too much user attention. Cards don't need that much attention.  
- Big shadow => floating thing. Cards shouldn't float over the page. They should *lie* on the page => only a slight shadow is needed 
Same reasoning applies to the right sidebar
Previous:
Next:

Reduce shadows on sidebar and inline cards

---

src/main/frontend/components/block.cljs
src/main/frontend/components/block.css
src/main/frontend/handler/block.cljs
src/main/frontend/mobile/mobile_bar.cljs

1. Switch outdent and more buttons to make swipe more natural.
2. disable the swipe action-bar when editing. Only allow indent/outdent when editing
3. resolve conflicts between selection and swipe when editing
4. Remove the indent/outdent button on the mobile toolbar

enhance gestures

---

deps/graph-parser/src/logseq/graph_parser/block.cljs
deps/graph-parser/test/logseq/graph_parser/nbb_test_runner.cljs
deps/graph-parser/test/logseq/graph_parser_test.cljs
src/main/frontend/format/block.cljs
src/main/frontend/modules/instrumentation/sentry.cljs

This PR adds tests for the bug I introduced that was fixed in #5553 (Thanks @andelf!). This PR prevents also future exceptions in `gp-block/extract-blocks` from deleting pages, as reported in #5548 . The cause of this behavior was the try catch in `gp-block/extract-blocks` which causes `:delete-blocks-fn` to receive a page that it deletes. This behavior can be confirmed with the last test in `graph-parser-test`. Note that removing this try/catch does effect paste and import fns by failing fast, which I think is a better user experience than pretending the action behaved correctly. If we need a try/catch for one of these user actions they should be moved up to the specific action that needs it. As a rule of thumb, I would encourage not having try/catch's far from where the user initiates …

Fix: Add test for graph-parser bug and prevent future data deletion

---

src/main/frontend/dicts.cljc

This commit fixes the typo from "일므" to "이름".

Fix Typo in Korean Translation

---

resources/css/common.css
src/main/frontend/components/header.cljs
src/main/frontend/components/header.css
src/main/frontend/components/onboarding/index.css
src/main/frontend/components/right_sidebar.cljs
src/main/frontend/components/sidebar.cljs
src/main/frontend/components/sidebar.css

Fixes #5652 and #5646.
- Header buttons now all have the same height (yes, some had a different height)  
- On the right sidebar, the clickable labels at the top ("Content", "Page graph", "Help") are now buttons with consistent styling (before, they weren't even links)  
- Header button, which were `a` tags, are now `button` tags (it's semantically more correct)  
- Buttons style now use more tailwindcss classes and less custom css, to improve consistency  
- I've replaced many margins and paddings with flex gaps, and I've reused the same gap size where possible, to make things consistent
I haven't been able to test the interface with some header buttons (the ones for previous and next page and some other ones...) because I don't exactly know how to show them. Please have a look at the UI …

Icon alignment + various little UI changes

---

src/electron/electron/fs_watcher.cljs
src/electron/electron/handler.cljs
src/electron/electron/state.cljs
src/main/frontend/fs.cljs
src/main/frontend/fs/bfs.cljs
src/main/frontend/fs/capacitor_fs.cljs
src/main/frontend/fs/node.cljs
src/main/frontend/fs/protocol.cljs
src/main/frontend/fs/watcher_handler.cljs
src/main/frontend/handler/events.cljs
src/main/frontend/handler/file.cljs
src/main/frontend/handler/metadata.cljs
src/main/frontend/handler/repo.cljs
src/main/frontend/handler/web/nfs.cljs
src/main/frontend/state.cljs
yarn.lock

Also, disabled both re-index and refresh when logseq detects that a graph's dir doesn't exist anymore.
Related to https://github.com/logseq/logseq/issues/5549#issuecomment-1151000104
Demo:
https://www.loom.com/share/03a0ee11328d4d7c99966a6c1d8ec449

fix: notify graph dir is gone when starting or running the apps

---

src/main/frontend/handler/paste.cljs

See-also #5723 
On Windows, \r\n is used when copying & cutting.
Known Issue: Close Logseq App then Re-open, this method fails.

fix(editor): handle windows crlf in clipboard

---

deps/graph-parser/.clj-kondo/config.edn
deps/graph-parser/src/logseq/graph_parser.cljs
deps/graph-parser/src/logseq/graph_parser/cli.cljs
deps/graph-parser/src/logseq/graph_parser/extract.cljc
deps/graph-parser/test/logseq/graph_parser/cli_test.cljs
deps/graph-parser/test/logseq/graph_parser/extract_test.cljs
src/main/frontend/handler/file.cljs

This PR is for [the example CI job task](https://quire.io/w/Logseq-_team_dedicated_to_sport_of_knowledge/753/Example_CI_job_that_parses_and_queries). I'm creating [some tests](https://github.com/logseq/docs/tree/add-tests) for the docs graph that use the mldoc ast. Currently, the frontend app doesn't use the ast after parsing but it would be helpful to pass it down to scripts

Enhance: Allow graph-parser to also return ast data

---

src/main/frontend/extensions/html_parser.cljs

- according to how browsers render HTML, unrecognized(illegal) tags are treated as plain inline text.
- merge continuous line breaks into 2 line breaks

fix(editor): use denied tags in html to md conversion

---

e2e-tests/basic.spec.ts

`fill` bypasses events. Might fail under deferred rendering from React. 
Let's see if it works.

fix(test): add delay to e2e testing

---

src/electron/electron/window.cljs

Fix #5771
When a window is destroyed, any property access will fail.

fix(electron): check destroyed window before access property

---

deps/graph-parser/src/logseq/graph_parser/block.cljs
src/main/frontend/components/external.cljs
src/main/frontend/components/onboarding/setups.cljs
src/main/frontend/db.cljs
src/main/frontend/db/model.cljs
src/main/frontend/handler/editor.cljs
src/main/frontend/handler/external.cljs
src/main/frontend/handler/graph.cljs
src/main/frontend/handler/page.cljs

Can be accessed in the onboarding import UI
Recover information from exported `edn` / `json` in the best effort.
- no FS required
- add options toward `handler/page/create!` and `handler/editor/insert-block-tree` to maintain uuid during reconstruction
- uuids are persisted on demand
- basic error capturing - skip pages with errors (e.g. missing block ref) and prompt
Known issue of the current export format:
- assets are dropped
- title properties are duplicated in dupilcated (won't fix since title properties are going to be deprecated)

Feat: import edn / json export of Logseq

---

src/main/frontend/components/block.cljs

close https://github.com/logseq/logseq/issues/5820
修改b站视频进度条显示问题

fix bilibili video progress bar display

---

ios/App/App/capacitor.config.json
src/main/frontend/handler/block.cljs
templates/config.edn

1. Disabled gestures on query table, logbook, excalidraw . fix #5783, #5837
2. Disable gestures on blocks with customized tags in `config.edn` 
```
:mobile
{:gestures/disabled-in-block-with-tags ["kanban"]}
```
3. Increase the threshold to activate gestures to avoid conflicts with scroll.

Disable gesture on query table and logbook

---

resources/css/common.css
src/main/frontend/components/block.css

This reduces a flickery appearance I was noticing when moving between blocks with the up/down arrow keys, by changing the ease function to be a fast ease-out bezier (specifically, easeOutQart from here: https://easings.net/ for easing the color out, and the stiffer https://cubic-bezier.com/?#0,1,0,1 for easing the new color in, so that the new color is transitioned in before the old one is coming out)
It's most pronounced when navigating nested blocks.
I'm not sure why matching eases don't result in the backgrounds adding up to 100% when a child is easing out and a parent is easing in or vice-versa, but I found these curves have the best result from testing. Maybe the removing of one class and adding of the other class happen asynchronously / not in the same JS frame? Or backgrounds don't …

Reduce flicker when moving between blocks with keyboard

---

deps/graph-parser/src/logseq/graph_parser/config.cljs
src/main/frontend/components/block.cljs

On mobile, it's hard to open plaintext assets by external viewers, since not all users have those viewers installed. 
This PR made Logseq open those asset links internally by CodeMirror, which makes external viewers no needed anymore.

feat: open plaintext assets in logseq

---

libs/src/LSPlugin.ts

I noticed this response was `any`, when it could be a more specific array of `PageEntity`'s. I added `| null` since some other types have that, and figured its safe to assume that's what logseq returns if it can't get the pages for whatever reason.
This is my first logseq PR so let me know if I need to add anything

(chore): Update getAllPages typescript

---

src/main/frontend/components/search.cljs

fix(ui) trailing space of search-auto-complete

---

src/main/frontend/handler/page.cljs

Fix issue that changing page `[[work]]` to `[[1work]]` will change `[[work/worklog]]` to `[[1work/1worklog]]` instead of `[[1work/worklog]]`

fix: rename namespace also rename substring in sub-namespace pages

---

docs/develop-logseq.md

Removed a reference in run instructions that pointed to a directory that no longer exists.

Update desktop app run instructions

---

src/test/frontend/extensions/calc_test.cljc

Just some tests for the new behavior of https://github.com/logseq/logseq/pull/5374.

Adding tests for rounding errors

---

src/main/frontend/components/block.cljs
src/main/frontend/handler/events.cljs

1. width of query table in blocks of unlinked reference is larger than the parent node
2. click query table view toggle enters editing mode
3. fix #4273, #5858

Fix some query table issues

---

.github/workflows/build.yml
deps/graph-parser/src/logseq/graph_parser/block.cljs
deps/graph-parser/src/logseq/graph_parser/test/docs_graph_helper.cljs
deps/graph-parser/test/logseq/graph_parser/block_test.cljs
e2e-tests/basic.spec.ts
e2e-tests/page-search.spec.ts
src/main/frontend/commands.cljs
src/main/frontend/components/block.cljs
src/main/frontend/components/block.css
src/main/frontend/components/datetime.cljs
src/main/frontend/components/editor.cljs
src/main/frontend/db/model.cljs
src/main/frontend/extensions/zotero/handler.cljs
src/main/frontend/handler/editor.cljs
src/main/frontend/handler/page.cljs
src/main/frontend/search.cljs
src/main/frontend/state.cljs
src/main/frontend/ui.cljs
src/main/frontend/util.cljc
src/main/frontend/util/cursor.cljs
src/main/frontend/util/text.cljs
src/test/frontend/db/query_dsl_test.cljs
src/test/frontend/util/text_test.cljs

This PR addressed several parts:
1. Simplify states for the editor modal, including the current `:editor/action` and its corresponding data (e.g. slash position, input options, etc.)
2. Adds auto-complete support for block properties
3. Adds auto-complete support for block property values
4. Each property will be treated as a "block" too, which enables property blocks in the linked references
Demo:
https://www.loom.com/share/27804e1bcd7b4e4bbf71ec14956c42fe

Feat: auto-complete support for both block properties and their values

---

ios/App/App/FileContainer.swift

or the app fails to launch if iCloud is disabled (such as on simulator)

only validate documents url when it non-nils

---

libs/src/LSPlugin.ts
src/main/frontend/components/plugins.css
src/main/frontend/components/plugins_settings.cljs

For plugins with a lot of settings would be good to have "visual splitting" into sections.
Added new settings type - `heading`
```js
{
key: "bannerHeading",
title: "Banner settings",
type: "heading"
},
```

Add heading in plugin settings

---

src/electron/electron/core.cljs
src/electron/electron/url.cljs
src/electron/electron/utils.cljs

Fix https://github.com/logseq/logseq/issues/5959
In multiple desktop case, there will be no `focused window` exists for sometime.
No much idea about how to define a "focus window" in macOS for Electron, but should have a fallback window assigned.
Thus, add function `send-to-focused-renderer`
https://github.com/cnrpman/logseq/blob/70f7bd53bd876f5508262a6b2d8e3ad50649f661/src/electron/electron/utils.cljs#L124-L125

fix: quick capture across desktops

---

src/main/frontend/components/block.cljs
src/main/frontend/components/journal.cljs
src/main/frontend/components/reference.cljs
src/main/frontend/ui.cljs

The root cause of page bouncing on the journals page is because of lazy rendered empty linked references.
The fix is to not render empty references at all.
Also, the last time when in-view's state changes will be recorded to prevent loop switching between the lazy loading placeholder and the real content.
related to #5972

Another fix for page bouncing for lazy loading

---

resources/css/common.css
src/main/frontend/config.cljs
src/main/frontend/extensions/html_parser.cljs

- support marked code, bold code, italic code
- better handling of HTML inline markup element
- fix wrong markup symbols for markdown
CSS tested against:

Refactor inline html markup element conversion

---

src/main/frontend/components/block.cljs

tiny fix for query table on mobile: don't enter editing state when clicking it.

don't enter editing when click query table

---

src/main/frontend/util/page_property.cljs
src/test/frontend/util/page_property_test.cljs

Always insert a lower-cased key, and replace the uppercased key with a lower-cased one.
fix #5826

fix key duplicates caused by key case when insert page property

---

ios/App/App/FsWatcher.swift
src/electron/electron/fs_watcher.cljs

This resolves compatibility with both syncthing and git auto commit enabled.
Fix #6005 
Fix #5841 
Fix #5999

fix(watcher): avoid calling delete too early

---

src/main/frontend/extensions/srs.cljs

fix #6013. Introduced in https://github.com/logseq/logseq/commit/71727845043dbccf5a23a5463b3ef159d126ab2b

fix click not working on cards preview mode

---

.github/workflows/graph-parser.yml
deps/graph-parser/.carve/ignore
deps/graph-parser/README.md
deps/graph-parser/package.json
deps/graph-parser/src/logseq/graph_parser/block.cljs
deps/graph-parser/src/logseq/graph_parser/property.cljs
deps/graph-parser/src/logseq/graph_parser/test/docs_graph_helper.cljs
deps/graph-parser/test/logseq/graph_parser/block_test.cljs
deps/graph-parser/test/logseq/graph_parser/cli_test.cljs
e2e-tests/page-search.spec.ts
src/main/frontend/components/block.cljs
src/main/frontend/config.cljs
src/main/frontend/extensions/srs.cljs
src/main/frontend/util/property.cljs
templates/config.edn

As a follow up to https://github.com/logseq/logseq/pull/5922, this does the following:
* Ignores logseq properties to fix #5963
*  Provides a config option to enable/disable property pages
* Provides a config option to exclude certain property names from having pages created
This PR is an alternative PR to #6009 and #6022. I tested this by removing all page properties from `logseq/pages-metadata.edn` and then re-indexing

Enhance: Property page enhancements

---

src/main/frontend/components/plugins_settings.cljs

Add `data-key` attribute to plugin settings item.
**Use case:**
Plugin settings (for ex. colors/bgs) for different modes (dark & light) should have **2x** sets of items for each mode 😒
To hide unneeded via CSS, they should have some identifier.
For ex.  plugin JS and CSS:
```js
const settingsArray: SettingSchemaDesc[] = [
{
key: "lightModeHeading",
title: "Light mode settings",
type: "heading"
},
{
key: "lightDefaultlBgColor",
title: "Default bg color",
type: "string",
description: "",
default: "",
},
...
... lot of "light" related settings
...
{
key: "darkModelHeading",
title: "Dark mode settings",
type: "heading"
},
...
... lot of SAME settings, but for "dark"
...
```
```css
/* User in dark mode - hiding "light" mode items */
.dark-theme .cp__plugins-settings :is(.heading-item, …
```

Plugin settings add data-key

---

android/app/build.gradle
ios/App/App.xcodeproj/project.pbxproj
resources/package.json
src/main/frontend/version.cljs

This is the preparation for the v0.7.7 release.
Pending fixes:
- This might be annoying since it creates many built-in meaningless pages.

Bump version 0.7.7

---

deps/graph-parser/src/logseq/graph_parser/property.cljs
src/main/frontend/components/page.cljs
src/main/frontend/handler/graph.cljs

- Like this thread [#1312](https://discuss.logseq.com/t/option-to-ignore-certain-nodes-in-the-graph/1312), I added the ability to exclude a page in "global graph" by adding the property exclude-in-graph:: true
- added property exclude-in-graph
- added settings paramenter :excluded-pages
- added "Excluded pages" toggle in in graph filters
EDIT: for the moment the display of the "page graph"  remains unchanged

feat: added property exclude-in-graph

---

deps/db/package.json
deps/db/yarn.lock
deps/graph-parser/package.json
deps/graph-parser/src/logseq/graph_parser/block.cljs
deps/graph-parser/src/logseq/graph_parser/extract.cljc
deps/graph-parser/test/logseq/graph_parser/extract_test.cljs
deps/graph-parser/yarn.lock
src/main/frontend/handler/editor.cljs
src/main/frontend/handler/page.cljs

This PR fixes #6124 from which I was able to confirm that page property pages (not block property pages) weren't being deleted when the property-pages config was turned off. This PR also bumps to the latest nbb-logseq. The source of the bug was [what I was worried about from the last PR](https://github.com/logseq/logseq/pull/6024#discussion_r921582161). With this fix, I am now able to delete all property pages with `:property-pages/enable? false` and then re-indexing my graph twice

Fix: page properties not reading property-pages config

---

src/main/frontend/components/right_sidebar.cljs

fix #4983. make the title clickable.

fix: make the title of sidebar item clickable. #4983

---

deps/graph-parser/src/logseq/graph_parser/block.cljs
deps/graph-parser/test/logseq/graph_parser_test.cljs
src/main/frontend/components/block.cljs
src/main/frontend/components/editor.cljs
src/main/frontend/db/model.cljs
src/main/frontend/handler/editor.cljs
src/main/frontend/search.cljs

This PR fixes #6192 and fixes #4907 , two property issues. #4907 was caused by accidental clobbering of the sorted properties map before a block is saved

Fix: Property completion for hidden properties and property ordering

---

src/main/frontend/components/header.css

As the title. The `cursor: pointer !important` in the `.restart` class won't work because there still has another CSS rule to limit all buttons or links in the header to be `cursor: default`.
https://github.com/logseq/logseq/blob/808215dda84587578bd5c601e9049274747faad4/src/main/frontend/components/header.css#L213

fix(style): cursor of restart text

---

src/main/frontend/components/plugins.cljs

Currently, users only are able to open the README page by clicking the plugin icon, which is counterintuitive and is not consistent with many existing tools. I didn't find the feature even after using Logseq for one year and I kept clicking the GitHub icon on the right side to open the website to see the README.
This commit moves the on-click function to the title instead of the plugin icon to improve the user experience.

improve UX design: click the plugin title to open README

---

src/main/frontend/handler/editor.cljs

Fix #5448
At the moment, after selecting multiple blocks:
- `up`/`down` navigation highlights the block at the top/bottom of the page. This behavior, particularly on long page, is very annoying
- `left`/`right` navigation does nothing
This PR solves the "problem" in the following way:
- If `up`/`ctrl+p` is pressed, the previous block of the first selected block is highlighted
- If `down`/`ctrl+n` is pressed, the next block of the last selected block is highlighted
- If `left` is pressed, cursor is placed at the beginning of the first selected block
- If `right` is pressed, cursor is placed at the end of the last selected block
In this way, the behavior of single and multiple block selection is similar.

fix: navigation with multiple selected blocks

---

android/app/src/main/java/com/logseq/app/FileUtil.java

fix(android): handle home uri when picking folder

---

src/main/frontend/handler/editor.cljs

fix: cursor position cannot be moved when editing a page title

---

src/main/frontend/components/sidebar.cljs

Hi @cnrpman , keep the `config/publishing?` is true as we discussed. Sorry for introducing some bugs for this project.

fix: keep the favorites item when publishing

---

src/main/frontend/external/roam_export.cljs

Fix #4502 
Fix Issue: export graph to roam json is broken
reported in https://discord.com/channels/725182569297215569/735747000649252894/1008418884459708459

fix: roam export error caused by typo

---

e2e-tests/editor.spec.ts
src/main/frontend/components/editor.cljs
src/main/frontend/handler/editor.cljs
src/main/frontend/handler/editor/keyboards.cljs

This fixes #6265.
Changes made:
- Adds automated test; I had to add a data class to the modal to be able to check for it with the tests.
- When inside `[[]]`, don't re-open the prompt if the key pressed was Escape (in addition to arrow keys, which were already there).
- When pressing escape, close the action modal instead of calling `on-hide` in keyboards.cljs. This is arguably a little bit hacky because it "should" live in handler/editor.cljs, but I didn't find any cleaner way to intercept the escape handler inside handler/editor.cljs instead, because this keydown handler fires first. I think the jank factor is relatively low, and I don't know of anything it breaks (but please, let me know if you do).

Feat: Press escape to close action menu

---

src/main/frontend/config.cljs
src/main/frontend/handler/ui.cljs

Use case in `custom.css`
```css
@font-face {
font-family: 'Rubik Distressed';
font-style: normal;
/* relative path from current custom.css file */
src: url("../assets/RubikDistressed-Regular.ttf") format('truetype');
}
h1 {
font-family: 'Rubik Distressed' !important;
}
```
Mentioned thread:  
https://discord.com/channels/806040386614853642/840147756487540777/986075938112565299

improve(custom.css): support import current graph assets file

---

src/main/frontend/components/plugins.cljs
src/main/frontend/components/plugins_settings.cljs
src/main/frontend/components/settings.cljs

Add `data-id` to settings items, plugins items and plugin settings panel to target and rule own plugin for features and needs: styles, event listeners, etc...

feat(settings): add plugin id to buttons and panel

---

tldraw/packages/core/src/lib/TLApp/TLApp.ts
tldraw/packages/core/src/lib/TLViewport.ts

As discussed, this PR branches some fixes from #6346 with Zoom and keyboard shortcuts into a new PR.

enhance(whiteboards): Small quick fixes

---

src/main/frontend/handler/editor.cljs

Avoid cycle todo of empty block:
The original BUG:
https://user-images.githubusercontent.com/72891/185789719-974cd786-0534-4afe-83cf-1c858a2b4874.mov
Fixed:
https://user-images.githubusercontent.com/72891/185789726-59755655-a035-4b39-9c6b-679b8069d7e4.mov

fix(editor): skip empty block when cycle todo

---

src/main/frontend/components/block.cljs
src/main/frontend/components/journal.cljs
src/main/frontend/components/page.cljs
src/main/frontend/components/query_table.cljs
src/main/frontend/components/reference.cljs
src/main/frontend/components/reference.css
src/main/frontend/db/model.cljs
src/main/frontend/db/react.cljs
src/main/frontend/handler/block.cljs
src/main/frontend/modules/outliner/pipeline.cljs
src/main/frontend/modules/outliner/tree.cljs
src/main/frontend/ui.cljs

This PR does:
1. fix wrong page refs count in filters
2. fix children's `block/path-refs` are cleared when updating their parent
3. improve performance for linked references
4. remove reactive query ::refs-count
5. add includes and excludes to filters
6. fix #6406 https://github.com/logseq/logseq/pull/6423/commits/cf3a2a668523c0bd3812e19db02396783597321f
7. fix the issue that lazy components are not rendered sometimes

fix missing references and filters ux enhancements

---

src/electron/electron/find_in_page.cljs
src/electron/electron/handler.cljs
src/electron/electron/window.cljs
src/main/electron/listener.cljs
src/main/frontend/components/find_in_page.cljs
src/main/frontend/components/find_in_page.css
src/main/frontend/components/search.cljs
src/main/frontend/components/sidebar.cljs
src/main/frontend/handler/editor.cljs
src/main/frontend/handler/search.cljs
src/main/frontend/modules/shortcut/config.cljs
src/main/frontend/modules/shortcut/dicts.cljc
src/main/frontend/state.cljs
src/main/frontend/ui.cljs
src/main/frontend/ui.css

Demo: https://www.loom.com/share/036276f228f74db2b5b6c0a19365a076
Some caveats:
1. Electron findInPage will cause focus loss, it doesn't provide a way to [ignore inputs or specified elements](https://github.com/electron/electron/issues/11444).
2. The input element itself is counted in the search result too.
3. Can't focus after clearing the search input.
Fixes #4605

feat: find in page on electron

---

src/main/frontend/modules/shortcut/config.cljs

Follow up to #6443 so that electron-only commands don't show up or trigger in mobile or browser. Forgot to mention `:inactive` exists in my code review

Fix: Electron only commands should only show up in electron

---

android/app/src/main/java/com/logseq/app/FolderPicker.java
android/app/src/main/java/com/logseq/app/FsWatcher.java
src/main/frontend/fs/capacitor_fs.cljs

Bug report from Discord.
For graphs which contain spaces in path, urlencoding should be added.

fix(android): handle path with spaces

---

src/main/frontend/components/block.cljs

When a image link is a data-url. The delete button icon fails with `false is not ISeq` error.

fix(editor): handle delete image with no actual file

---

deps/db/package.json
deps/db/yarn.lock
deps/graph-parser/package.json
deps/graph-parser/src/logseq/graph_parser/block.cljs
deps/graph-parser/src/logseq/graph_parser/extract.cljc
deps/graph-parser/src/logseq/graph_parser/property.cljs
deps/graph-parser/src/logseq/graph_parser/util.cljs
deps/graph-parser/test/logseq/graph_parser/nbb_test_runner.cljs
deps/graph-parser/test/logseq/graph_parser/util_test.cljs
deps/graph-parser/test/logseq/graph_parser_test.cljs
deps/graph-parser/yarn.lock
src/main/frontend/components/block.cljs
src/main/frontend/handler/export.cljs

This is a follow up to #6477 that fixes and tweaks the following:
- Invalid properties were identified as valid properties e.g. "foo bar" or "4"
- Page properties were saving :invalid-properties as valid :properties. This would've effected queries since page properties are normally queried by page blocks
- Renamed "Property key" to "property name" since users don't know what keys are. Confirmed that our docs don't refer to keys anywhere
Also bumped to latest nbb-logseq

fix: invalid property fixes

---

src/main/frontend/handler/editor.cljs
src/main/frontend/util/text.cljs

Currently, if you type a backtick and then some text and then another backtick, the last backtick is autopaired and more backticks spawn. It looks like this:
That's annoying because to close the backtick, you can't type a backtick. You need to use the mouse or the arrow keys or jump to the end of the line with a shortcut.
With these code changes, it looks like this:
But we also need to keep in mind that 3 backticks in a row have a special meaning so autopairing makes sense if you're typing several backticks in a row. So that behavior is unchanged and looks like this:
#4380 #4516

Improve backtick autopairing

---

package.json
resources/package.json
yarn.lock

This electron minor version release fixed a bug in wayland rendering for Linux desktops.
Fixes #5010

chore(deps): update electron 19.0.12

---

src/main/frontend/handler/page.cljs

Adds an option to `Editor.renamePage` to allow developers to skip the redirect when a page is renamed

Add an option to skip redirect on page rename

---

tldraw/packages/core/src/lib/tools/TLSelectTool/states/ContextMenuState.ts
tldraw/packages/core/src/lib/tools/TLSelectTool/states/IdleState.ts

When we right click on an element to trigger the context menu, we should also select the hovered element.
Holding `Shift` when we right click, enables multi-selection as a bonus.

feat: select element on context menu

---

src/main/frontend/components/sidebar.cljs
src/main/frontend/handler/route.cljs

I requested this about a year ago: https://discuss.logseq.com/t/shift-click-on-journals-should-open-latest-in-the-sidebar/3631 . Seems like a pretty straightforward new minor feature, but very useful.
This is my first logseq PR so be gentle please.

Shift click on “Journals” opens latest in the right sidebar

---

e2e-tests/editor.spec.ts

The bug reported in #5074 has been fixed but not by this PR. I tried to find the commit that fixed the bug but I couldn't find it.
This PR just adds an E2E test to cover that scenario, as @cnrpman requested in [this comment](https://github.com/logseq/logseq/issues/5074#issuecomment-1220774009). The new E2E test looks like this:
The test is slowed down in the gif so that we can see what it does. The real test will run much faster.
I have no idea what I'm doing. I just started using Logseq a few days ago and I've never written TypeScript before so this PR probably has a bunch of mistakes.
Resolves #5074

Adding E2E test for scenario with text after a soft return

---

src/main/frontend/components/block.cljs
src/main/frontend/search/db.cljs
src/main/frontend/search/node.cljs
src/main/frontend/state.cljs
src/main/frontend/util.cljc
templates/config.edn

This PR fixed the issue that searching and editing could be frozen because the block's content is too large.
It adds a new option `:block/content-max-length` which defaults to 5000 chars. Blocks larger than this max length will not be searchable or editable.

fix: search or editor frozen caused by large text

---

src/main/frontend/config.cljs

In the landing page. `current-graph` is `nil`

fix: do not loading persist vars when nil graph

---

tldraw/apps/tldraw-logseq/build.mjs
tldraw/apps/tldraw-logseq/src/components/ContextBar/ContextBar.tsx
tldraw/apps/tldraw-logseq/src/components/ContextMenu/ContextMenu.tsx
tldraw/apps/tldraw-logseq/src/components/ZoomMenu/ZoomMenu.tsx
tldraw/packages/core/src/lib/TLApp/TLApp.ts
tldraw/packages/react/src/components/ContextBarContainer/ContextBarContainer.tsx

- Replace `ls` with `fs.linkSync` to allow running the build script on windows
- Introduce cut command
- Fix zoom to fit and zoom to selection shortcuts (1->zoom to fit, Shift+1 -> zoom to selection)
- Update zoom menu labels (it looks like prettier added some empty string)
- Fix state management of context menu
- Hide context bar when the context menu is active (`useDebouncedValue` introduced [here](https://github.com/logseq/logseq/pull/5341/commits/a4979c495bb35097fe981d4934716502914779f6) delays the visibility switch)
- Fix context menu labels
- Block zooming and panning when the context menu is active

Enhance: Whiteboards

---

src/main/frontend/fs/capacitor_fs.cljs
src/main/frontend/handler.cljs

Introduced by merging loss of https://github.com/logseq/logseq/pull/5355
Original fix is at https://github.com/logseq/logseq/pull/6389/files#diff-a703d4b245bd7b97105989d39844255a799a03c88c573289cf5bc7b3e100fc5cR161-R183

fix(android): crash at start, accessing illegal path

---

android/app/build.gradle
resources/package.json
src/main/frontend/version.cljs

This release is to fix android platforms.
iOS App version is still pending at 0.8.3.

chore: bump version 0.8.4

---

tldraw/apps/tldraw-logseq/src/components/ActionBar/ActionBar.tsx
tldraw/apps/tldraw-logseq/src/components/ContextBar/ContextBar.tsx
tldraw/apps/tldraw-logseq/src/components/ZoomMenu/ZoomMenu.tsx
tldraw/apps/tldraw-logseq/src/styles.css

- Add zoom buttons and group them with zoom menu
- Fix some styles
- Add titles to buttons
- Remove unneeded `DropdownMenuPrimitive`

feat: zoom buttons

---

src/electron/electron/url.cljs

fix: url param double decoded

---

src/main/frontend/commands.cljs
src/main/frontend/fs/sync.cljs
src/main/frontend/state.cljs

Previously, sync will be started when user is not logged in or the current graph is not a remote graph.

fix: don't start sync if not logged in or it's not a remote graph

---

tldraw/apps/tldraw-logseq/src/lib/tools/LogseqPortalTool/LogseqPortalTool.tsx
tldraw/packages/core/src/lib/TLViewport.ts
tldraw/packages/core/src/lib/tools/TLMoveTool/states/PinchingState.ts
tldraw/packages/core/src/lib/tools/TLSelectTool/states/PinchingState.ts

This PR introduces a normalization method for the [mouse wheel event](https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent),  in order to achieve a consistent behavior across multiple devices/operating systems/browsers (related [stackoverflow issue](https://stackoverflow.com/questions/5527601/normalizing-mousewheel-speed-across-browsers/)). For now, the normalization is applied on `pinch`, on the raw value of [deltaZ](https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent/deltaZ). Ideally, this should be applied to all related events on `useGestureEvents`, since this is a common problem that affects the behavior of multiple gestures.
I also refactored the zooming/pinching functions in order to remove duplicated calculations, and use a common api that always validates the zoom …

Fix: Whiteboards scroll zoom event

---

src/main/frontend/handler/page.cljs
src/main/frontend/modules/file/core.cljs

Fix #5996 
We can't find `:collapsed` in properties. The original condition `(and (:collapsed properties) (false? collapsed?))` is always unreachable.
So it always goes through the `:else` condition when `collapsed? == false`
Before re-index, `collapsed:: true` doesn't show up in `:block/content`, so the result is correct.
After re-index, `collapsed:: true` shows up in `:block/content`, so the result is incorrect.
Fix #6544 
In the legacy design, the `"` wrapper happens when a title contain `,`, but the current title extraction code doesn't handled the `"` wrapper. Then data loss happens.
Now we drop the `"` wrapper as `,` is supported as property value already.

Some fixes related to re-index

---

src/main/frontend/components/block.cljs

It should work like this:
- Before
- After

fix(ui): dsl-query style

---

src/main/frontend/components/block.cljs

Quick display fix for #6589. Linkable built in properties, alias and tags, are meant to be backwards compatible with `:rich-property-values` as they are special properties that have lots of pre-existing usage. Having `tags` not be backwards compatible would also break org-mode tags property

Fix: Linkable built in properties should not display as rich properties

---

src/main/frontend/components/file_sync.cljs
src/main/frontend/fs/capacitor_fs.cljs
src/main/frontend/fs/sync.cljs
src/main/frontend/handler/web/nfs.cljs
src/main/frontend/util/fs.cljs
src/main/frontend/util/persist_var.cljs

- more robust mobile backup path calculating
- rename graph-txid to graphs-txid, avoid misleading
- do not backup persist_var when save

Fix mobile backup path

---

src/main/frontend/search.cljs

When re-index, Electron main process error:
```
RangeError: Too many parameter values were provided
at /Users/..../Repos/logseq/.shadow-cljs/builds/electron/dev/out/cljs-runtime/electron/search.cljs:150:39
at insert-many (/Users/...../Repos/logseq/static/node_modules/better-sqlite3/lib/methods/transaction.js:65:24)
```
The incoming blocks-to-add has a nil in coll.
Introduced in https://github.com/logseq/logseq/pull/6455
`block->index` now becomes nil-able. should filter out all nil values.
Caused by diff of:
https://github.com/logseq/logseq/pull/6455/files#diff-e7fd16ab702eff86ec25cb18638b6fe514d4d527d80bba84f9af4918319dfa01R16-R22

fix(search): cannot batch insert to search db

---

src/main/frontend/fs/sync.cljs
src/main/frontend/handler.cljs
src/main/frontend/handler/events.cljs
src/main/frontend/handler/user.cljs

- set :network/online? in state when init
- won't sync-start if network offline
- if auth-refresh-token failed, won't clear id-token&access-token (if they aren't expired)

fix(sync): api calls fail when network offline

---

.clj-kondo/config.edn
deps.edn
deps/db/deps.edn
deps/graph-parser/deps.edn
src/electron/electron/handler.cljs
src/main/electron/listener.cljs
src/main/frontend/components/block.cljs
src/main/frontend/components/encryption.cljs
src/main/frontend/components/file_sync.cljs
src/main/frontend/components/plugins_settings.cljs
src/main/frontend/fs/sync.cljs
src/main/frontend/handler/events.cljs
src/main/frontend/handler/ui.cljs
src/main/frontend/ui.cljs
src/main/frontend/util/cursor.cljs
src/main/logseq/api.cljs

This enables two clj-kondo linters that are disabled by default but are useful:
- `:used-underscored-binding` - We rely on `_` to communicate unused bindings. This ensures this is true for all bindings. This is helpful for code review where we don't always have the full context and for large PRs like file-sync
- `:namespace-name-mismatch` - catches typos with namespaces. I encountered a typo-ed test ns a couple months ago which should've been caught by this

Dev: Enable two disabled kondo linters and bump kondo deps

---

src/main/frontend/handler/file.cljs
src/main/frontend/handler/global_config.cljs
src/main/frontend/handler/repo.cljs
src/main/frontend/handler/web/nfs.cljs

This fixes 3 user actions which were buggy or failing with mobile or web, which I introduced in #6531. I have tested these fixes work on android. If someone can test iOS that would be helpful. The user actions that were buggy were re-indexing graph, switching graphs and editing config.edn

Fix: 3 user actions broken by global-config in mobile or web

---

ios/App/App/FileSync/FileSync.m
ios/App/App/FileSync/FileSync.swift
src/main/frontend/encrypt.cljs

Use native age-encrypt, and run in the background.

fix(ios): file-sync reload when running

---

ios/App/App/FileSync/FileSync.swift

Since all user actions are blocked by the password prompt, we can use `.default` qos instead of `.backgroud` qos to speed up encryption and decryption.

fix(ios): use .default qos for encription
